CREATE OR REPLACE FUNCTION VMSCMS.FN_ACCT_STAT (ACCT_STAT IN NUMBER)
   RETURN VARCHAR2
AS
   STAT   VARCHAR2 (9);
BEGIN
   STAT := 'UNKNOWN';

   IF (ACCT_STAT >= 1) AND (ACCT_STAT <= 15) AND (ACCT_STAT <> 2)
   THEN
      STAT := 'OPEN';
   END IF;

   IF ( (ACCT_STAT >= 15) AND (ACCT_STAT <= 19)) OR (ACCT_STAT = 2)
   THEN
      STAT := 'CLOSED';
   END IF;

   RETURN STAT;
END;
/

SHOW ERROR