CREATE OR REPLACE FUNCTION VMSCMS.FN_CALC_CHARGE(part_code NUMBER,ic_code CHAR,tran_code VARCHAR2,acqiss_code CHAR)
RETURN NUMBER AS CHARGE NUMBER(15,2) ;

v_RPM_PLAN_CODE VARCHAR2(5);

BEGIN


  BEGIN
   SELECT RPM_PLAN_CODE INTO v_RPM_PLAN_CODE
   FROM REC_PARTNERCRDPLANCODE_MAST
   WHERE RPM_PART_CODE=part_code
   AND RPM_IC_CODE=ic_code;

   EXCEPTION
   WHEN NO_DATA_FOUND THEN
  CHARGE :=0;
  RETURN CHARGE;
   WHEN OTHERS THEN
  CHARGE := -1;
  RETURN CHARGE;

   END;


  BEGIN
   SELECT RPM_CHARGE
   INTO CHARGE
   FROM REC_PLANTRANS_MAST
   WHERE RPM_PLAN_CODE=v_RPM_PLAN_CODE
   AND RPM_TRANS_CODE=tran_code
   AND RPM_ACQISS_CODE=acqiss_code;
      EXCEPTION
   WHEN NO_DATA_FOUND THEN
  CHARGE :=0;
  RETURN CHARGE;
   WHEN OTHERS THEN
  CHARGE := -1;
  RETURN CHARGE;

  END;

  RETURN CHARGE;

END ;
/


