CREATE OR REPLACE FUNCTION VMSCMS.FN_DELI_DEPLOYMENT_FLAG (
   P_INST_CODE          IN NUMBER,
   P_DELIVERY_CHANNEL   IN VARCHAR2)
   RETURN NUMBER
IS
   V_DEPLOYMENT_FLAG   CMS_DELCHANNEL_MAST.CDM_DEPLOYMENT_FLAG%TYPE := 0;
BEGIN
   SELECT CDM_DEPLOYMENT_FLAG
     INTO V_DEPLOYMENT_FLAG
     FROM CMS_DELCHANNEL_MAST
    WHERE CDM_CHANNEL_CODE = P_DELIVERY_CHANNEL
          AND CDM_INST_CODE = P_INST_CODE;

   RETURN V_DEPLOYMENT_FLAG;
EXCEPTION
   WHEN OTHERS
   THEN
      V_DEPLOYMENT_FLAG := 0;
      RETURN V_DEPLOYMENT_FLAG;
END;
/

SHOW ERROR