CREATE OR REPLACE FUNCTION VMSCMS.fn_encr (user_pswd  IN varchar2)
RETURN NUMBER
AS

l_passwd NUMBER(5) ;
passwd  varchar2(20) ;

BEGIN
passwd := user_pswd ;

IF     NVL(LENGTH(PASSWD), 0) = 4 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3) +
              	(ASCII(SUBSTR(PASSWD,3,1))*5)  	+ (ASCII(SUBSTR(PASSWD,4,1))*7));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 5 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3) +
               	(ASCII(SUBSTR(PASSWD,3,1))*5)  	+ (ASCII(SUBSTR(PASSWD,4,1))*7) +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 6 THEN
L_PASSWD := ((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3) +
               (ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7) +
               (ASCII(SUBSTR(PASSWD,5,1))* 11) 	+ (ASCII(SUBSTR(PASSWD,6,1))*13));
END IF;


IF     NVL(LENGTH(PASSWD), 0) = 7 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 8 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17) +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 9 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17) +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23));
END IF;


IF     NVL(LENGTH(PASSWD), 0) = 10 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17) +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23) + (ASCII(SUBSTR(PASSWD,10,1))*29));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 11 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23) + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 12 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23) + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31));
END IF;


IF     NVL(LENGTH(PASSWD), 0) = 13 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23) + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31) +(ASCII(SUBSTR(PASSWD,13,1))*37));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 14 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23) + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31) +(ASCII(SUBSTR(PASSWD,13,1))*37) +
		(ASCII(SUBSTR(PASSWD,14,1))*41));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 15 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)  +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)  +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13) + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23) + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31) +(ASCII(SUBSTR(PASSWD,13,1))*37) +
		(ASCII(SUBSTR(PASSWD,14,1))*41)	+ (ASCII(SUBSTR(PASSWD,15,1))*43));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 16 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)    +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)    +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13)   + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23)   + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31)  + (ASCII(SUBSTR(PASSWD,13,1))*37) +
		(ASCII(SUBSTR(PASSWD,14,1))*41)	+ (ASCII(SUBSTR(PASSWD,15,1))*43)  + (ASCII(SUBSTR(PASSWD,16,1))*47));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 17 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)    +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)    +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13)   + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23)   + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31)  + (ASCII(SUBSTR(PASSWD,13,1))*37) +
		(ASCII(SUBSTR(PASSWD,14,1))*41)	+ (ASCII(SUBSTR(PASSWD,15,1))*43)  + (ASCII(SUBSTR(PASSWD,16,1))*47) +
		(ASCII(SUBSTR(PASSWD,17,1))*53)) ;
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 18 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)    +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)    +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13)   + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23)   + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31)  + (ASCII(SUBSTR(PASSWD,13,1))*37) +
		(ASCII(SUBSTR(PASSWD,14,1))*41)	+ (ASCII(SUBSTR(PASSWD,15,1))*43)  + (ASCII(SUBSTR(PASSWD,16,1))*47) +
		(ASCII(SUBSTR(PASSWD,17,1))*53) + (ASCII(SUBSTR(PASSWD,17,1))*59)) ;
END IF;


IF     NVL(LENGTH(PASSWD), 0) = 19 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)    +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)    +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13)   + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23)   + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31)  + (ASCII(SUBSTR(PASSWD,13,1))*37) +
		(ASCII(SUBSTR(PASSWD,14,1))*41)	+ (ASCII(SUBSTR(PASSWD,15,1))*43)  + (ASCII(SUBSTR(PASSWD,16,1))*47) +
		(ASCII(SUBSTR(PASSWD,17,1))*53) + (ASCII(SUBSTR(PASSWD,18,1))*59)  + (ASCII(SUBSTR(PASSWD,19,1))*61));
END IF;

IF     NVL(LENGTH(PASSWD), 0) = 20 THEN
L_PASSWD := 	((ASCII(SUBSTR(PASSWD,1,1))*2) 	+ (ASCII(SUBSTR(PASSWD,2,1))*3)    +
               	(ASCII(SUBSTR(PASSWD,3,1))*5) 	+ (ASCII(SUBSTR(PASSWD,4,1))*7)    +
               	(ASCII(SUBSTR(PASSWD,5,1))* 11) + (ASCII(SUBSTR(PASSWD,6,1))*13)   + (ASCII(SUBSTR(PASSWD,7,1))*17)  +
       	       	(ASCII(SUBSTR(PASSWD,8,1))*19) 	+ (ASCII(SUBSTR(PASSWD,9,1))*23)   + (ASCII(SUBSTR(PASSWD,10,1))*29) +
               	(ASCII(SUBSTR(PASSWD,11,1))*29)	+ (ASCII(SUBSTR(PASSWD,12,1))*31)  + (ASCII(SUBSTR(PASSWD,13,1))*37) +
		(ASCII(SUBSTR(PASSWD,14,1))*41)	+ (ASCII(SUBSTR(PASSWD,15,1))*43)  + (ASCII(SUBSTR(PASSWD,16,1))*47) +
		(ASCII(SUBSTR(PASSWD,17,1))*53) + (ASCII(SUBSTR(PASSWD,18,1))*59)  + (ASCII(SUBSTR(PASSWD,19,1))*61) +
		(ASCII(SUBSTR(PASSWD,20,1))*59));
END IF;

--dbms_output.put_line('my_pass:'||L_PASSWD);
return L_PASSWD;
END ;
/
show error