CREATE OR REPLACE FUNCTION VMSCMS.FN_ISNUMERIC (AMT VARCHAR2)
   RETURN NUMBER
AS
   F_AMT   NUMBER (10, 2);
BEGIN
   F_AMT := TO_NUMBER (AMT);
   RETURN 1;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN 0;
END;
/

SHOW ERROR