CREATE OR REPLACE FUNCTION VMSCMS.FN_my_number(pData VARCHAR2) RETURN NUMBER
AS
 pRet  NUMBER(15);
BEGIN
 pRet := TO_NUMBER(pData);
 RETURN pRet;
EXCEPTION
 WHEN OTHERS THEN
 RETURN 0;
END;
/


show error