CREATE OR REPLACE FUNCTION VMSCMS.FN_PRECOMP(uniq_id IN NUMBER,action_no IN NUMBER)
RETURN DATE
AS
PRECOMP DATE ;
v_ACTION_DATE DATE ;
v_FUNCREQ_INTCODE CHG_ACTION_DETAILS.CAD_FUNCREQ_INTCODE%TYPE;
v_ACTIONTYPE_INTCODE  CHG_ACTION_DETAILS.CAD_ACTIONTYPE_INTCODE%TYPE;
BEGIN
 begin
     PRECOMP := null;
   SELECT  CAD_ACTION_DATE, CAD_FUNCREQ_INTCODE,CAD_ACTIONTYPE_INTCODE
   INTO    v_ACTION_DATE, v_FUNCREQ_INTCODE,v_ACTIONTYPE_INTCODE
   FROM    CHG_ACTION_DETAILS
   WHERE   cad_uniq_id  = uniq_id
   AND     cad_action_no = action_no;
   IF v_FUNCREQ_INTCODE = 1 AND v_ACTIONTYPE_INTCODE = 3 THEN
   if v_ACTION_DATE is not null THEN
     PRECOMP := v_ACTION_DATE + 30;
    END IF;
   END IF;
 EXCEPTION
 when others then
  PRECOMP := null;
  end;
 RETURN PRECOMP;
END ;
/


