CREATE OR REPLACE FUNCTION VMSCMS.FN_TAB_ROW_SIZE(tab_name IN VARCHAR2)
RETURN NUMBER AS row_size NUMBER(9); 
BEGIN
 row_size := 0;
 SELECT SUM(DATA_LENGTH) INTO row_size FROM ALL_TAB_COLUMNS WHERE TABLE_NAME=tab_name;
 RETURN row_size;
END ;
/


show error