CREATE OR REPLACE FUNCTION VMSCMS.fn_valid_date(datechk VARCHAR2) RETURN NUMBER
AS
CON_DT DATE ;
BEGIN
	CON_DT := TO_DATE(datechk,'yyyymmddhh24miss');
	RETURN 1;
EXCEPTION
	WHEN OTHERS THEN
	RETURN 0;
END;
/


