CREATE OR REPLACE TRIGGER VMSCMS.TRANSACTION_UPDATE_DUPLICATE
AFTER UPDATE ON VMSCMS.TRANSACTIONLOG FOR EACH ROW
DISABLE
BEGIN
  UPDATE TRANSACTION_HISTORY
	SET TXN_STATUS = :NEW.TXN_STATUS
   WHERE RRN = :NEW.RRN AND BUSINESS_DATE = :NEW.BUSINESS_DATE AND
	    BUSINESS_TIME = :NEW.BUSINESS_TIME;
END;
/


