CREATE OR REPLACE TRIGGER VMSCMS.TRG_GRP_TOPUP_INS
 BEFORE INSERT
 ON VMSCMS.CMS_GROUP_TOPUP  FOR EACH ROW
DECLARE
 tmpVar NUMBER;
 BEGIN
    :NEW.CGT_INS_DATE := SYSDATE;
EXCEPTION
      WHEN OTHERS THEN
        -- Consider logging the error and then re-raise
        RAISE;
  END;
/


