CREATE OR REPLACE TRIGGER VMSCMS.TRG_GROUPDEBLOCK_STD  BEFORE INSERT on CMS_GROUP_DEBLOCK  FOR EACH ROW
BEGIN --Trigger body begins
 IF INSERTING THEN
  :new.cgd_ins_date := sysdate ;
 END IF;
END; --Trigger body ends
/


