CREATE OR REPLACE TRIGGER VMSCMS.TRG_MONEYBACK_MAST_STD
BEFORE INSERT OR UPDATE
ON VMSCMS.CMS_MONEYBACK_MAST REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN --Trigger body begins
   IF INSERTING THEN
     :new.CMM_INS_DATE := sysdate;
     :new.CMM_LUPD_DATE := sysdate;
   ELSIF UPDATING THEN
    :new.CMM_LUPD_DATE := sysdate;
   END IF;
END; --Trigger body ends
/


