CREATE OR REPLACE TRIGGER VMSCMS.TRG_VERSION_LOG_HIST
   AFTER DELETE
   ON VMSCMS.CMS_INCOMM_VERSION    REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
BEGIN
   INSERT INTO CMS_INCOMM_VERSION_HIST
               (CIV_BASE_VERS , CIV_VERS_RELS, CIV_VERS_BULD ,CIV_VERS_DATE ,CIS_VERS_USER ,CIV_VERS_INS_DATE)
        VALUES (:OLD.CIV_BASE_VERS, :OLD.CIV_VERS_RELS,:OLD.CIV_VERS_BULD , :OLD.CIV_VERS_DATE, :OLD.CIV_VERS_USER,SYSDATE);
END;
/


