CREATE OR REPLACE TRIGGER VMSCMS.TRG_VMS_TOKEN_TXNLOG BEFORE
  INSERT OR
  UPDATE ON vmscms.VMS_TOKEN_TRANSACTIONLOG FOR EACH ROW 
  BEGIN 
  IF INSERTING THEN 
  :NEW.VTT_INS_DATE := SYSTIMESTAMP;
  :NEW.VTT_LUPD_DATE := SYSTIMESTAMP;
  ELSIF UPDATING THEN
  :NEW.VTT_LUPD_DATE := SYSTIMESTAMP;
END IF;
END;
/