CREATE OR REPLACE TRIGGER VMSCMS."TRG_REISSCLOSE_STD" BEFORE
INSERT ON  "CMS_REISSUE_CLOSE" FOR EACH ROW
BEGIN --Trigger body begins
 IF INSERTING THEN
  :NEW.CRC_INS_DATE   := SYSDATE;
 END IF;
END;
/


