CREATE OR REPLACE TRIGGER VMSCMS.trg_cardstathist_std
 BEFORE INSERT OR UPDATE ON VMSCMS.CMS_CARDISSUE_STATCHANGE_HIST   FOR EACH ROW
BEGIN 
IF INSERTING THEN
 :new.CCH_INS_DATE := sysdate;
 :new.CCH_LUPD_DATE := sysdate;
ELSIF UPDATING THEN
 :new.CCH_LUPD_DATE := sysdate;
END IF;
end;
/


