CREATE OR REPLACE TRIGGER VMSCMS."TRG_GROUPCLOSE_STD" BEFORE
INSERT ON VMSCMS.CMS_GROUP_CLOSE FOR EACH ROW
BEGIN --Trigger body begins
 IF INSERTING THEN
  :NEW.cgc_ins_date := SYSDATE;
 END IF;
END; --Trigger body ends;
/


