CREATE OR REPLACE TRIGGER VMSCMS.TRIG_CMS_RATE_DEFINITION_TEMP
 BEFORE INSERT  ON VMSCMS.CMS_RATE_DEFINITIONTEMP 
  FOR EACH ROW
DECLARE
v_seqno      NUMBER;
BEGIN --Trigger body begins
 IF INSERTING THEN
                SELECT SEQ_CMS_RATE_DEFINITIONTEMP.NEXTVAL
                INTO   v_seqno
                FROM dual;
  :NEW.CRD_UNIQUE_ID:= v_seqno;
 END IF;
END;
/


