INSERT
INTO vmscms.CMS_PRM_MSGQUEUE_SPEC
  (
    CPM_FIELD_NAME,
    CPM_FIELD_LENGTH,
    CPM_FIELD_DEFAULT,
    CPM_FIELD_STARTPOSTION,
    CPM_DELIVERY_CHANNEL,
    CPM_PRM_TYPE,
    CPM_TRANSACTION_CODE,
    CPM_TXN_FIELDNAME,
    CPM_INS_DATE,
    CPM_LUPD_DATE,
    CPM_INST_CODE,
    CPM_PADDING_VALUE,
    CPM_PAD_POS
  )
  (SELECT CPM_FIELD_NAME,
      CPM_FIELD_LENGTH,
      CPM_FIELD_DEFAULT,
      CPM_FIELD_STARTPOSTION,
      CPM_DELIVERY_CHANNEL,
      CPM_PRM_TYPE,
      '13',
      CPM_TXN_FIELDNAME,
      SYSDATE,
      SYSDATE,
      CPM_INST_CODE,
      CPM_PADDING_VALUE,
      CPM_PAD_POS
    FROM vmscms.CMS_PRM_MSGQUEUE_SPEC
    WHERE CPM_DELIVERY_CHANNEL='16'
    AND CPM_PRM_TYPE          ='MRIF'
    AND CPM_TRANSACTION_CODE  ='11'
  );
  
  
INSERT
INTO vmscms.CMS_PRM_MSGQUEUE_SPEC
  (
    CPM_FIELD_NAME,
    CPM_FIELD_LENGTH,
    CPM_FIELD_DEFAULT,
    CPM_FIELD_STARTPOSTION,
    CPM_DELIVERY_CHANNEL,
    CPM_PRM_TYPE,
    CPM_TRANSACTION_CODE,
    CPM_TXN_FIELDNAME,
    CPM_INS_DATE,
    CPM_LUPD_DATE,
    CPM_INST_CODE,
    CPM_PADDING_VALUE,
    CPM_PAD_POS
  )
  (SELECT CPM_FIELD_NAME,
      CPM_FIELD_LENGTH,
      CPM_FIELD_DEFAULT,
      CPM_FIELD_STARTPOSTION,
      CPM_DELIVERY_CHANNEL,
      CPM_PRM_TYPE,
      '14',
      CPM_TXN_FIELDNAME,
      SYSDATE,
      SYSDATE,
      CPM_INST_CODE,
      CPM_PADDING_VALUE,
      CPM_PAD_POS
    FROM vmscms.CMS_PRM_MSGQUEUE_SPEC
    WHERE CPM_DELIVERY_CHANNEL='16'
    AND CPM_PRM_TYPE          ='MRIF'
    AND CPM_TRANSACTION_CODE  ='11'
  );
  
  
  
INSERT
INTO vmscms.CMS_PRM_MSGQUEUE_SPEC
  (
    CPM_FIELD_NAME,
    CPM_FIELD_LENGTH,
    CPM_FIELD_DEFAULT,
    CPM_FIELD_STARTPOSTION,
    CPM_DELIVERY_CHANNEL,
    CPM_PRM_TYPE,
    CPM_TRANSACTION_CODE,
    CPM_TXN_FIELDNAME,
    CPM_INS_DATE,
    CPM_LUPD_DATE,
    CPM_INST_CODE,
    CPM_PADDING_VALUE,
    CPM_PAD_POS
  )
  (SELECT CPM_FIELD_NAME,
      CPM_FIELD_LENGTH,
      CPM_FIELD_DEFAULT,
      CPM_FIELD_STARTPOSTION,
      CPM_DELIVERY_CHANNEL,
      CPM_PRM_TYPE,
      '15',
      CPM_TXN_FIELDNAME,
      SYSDATE,
      SYSDATE,
      CPM_INST_CODE,
      CPM_PADDING_VALUE,
      CPM_PAD_POS
    FROM vmscms.cms_prm_msgqueue_spec
    WHERE cpm_delivery_channel='16'
    AND CPM_PRM_TYPE          ='MRIF'
    AND CPM_TRANSACTION_CODE  ='11'
  );