UPDATE vmscms.CMS_CARD_STAT SET CCS_TOKEN_STAT='A' WHERE CCS_STAT_CODE IN('1','5','8','14'); 

UPDATE vmscms.CMS_CARD_STAT SET CCS_TOKEN_STAT='S' WHERE CCS_STAT_CODE IN('0','2','3','4','6','7','11','12','15','16');   

UPDATE vmscms.CMS_CARD_STAT SET CCS_TOKEN_STAT='D' WHERE CCS_STAT_CODE = '9';

UPDATE vmscms.CMS_CARD_STAT SET CCS_TOKEN_STAT='NA' WHERE CCS_STAT_CODE = '13';