--VMS_FSAPI_TRANS_MAST

INSERT INTO vmscms.VMS_FSAPI_TRANS_MAST(VFT_CHANNEL_DESC,VFT_REQUEST_TYPE,VFT_CHANNEL_CODE,VFT_TRAN_CODE,VFT_INS_DATE,VFT_INST_USER)
VALUES('IVR','ACTIVATION','07','35',SYSDATE,1);
INSERT INTO vmscms.VMS_FSAPI_TRANS_MAST(VFT_CHANNEL_DESC,VFT_REQUEST_TYPE,VFT_CHANNEL_CODE,VFT_TRAN_CODE,VFT_INS_DATE,VFT_INST_USER)
VALUES('WEB','ACTIVATION','17','01',SYSDATE,1);

INSERT INTO vmscms.VMS_FSAPI_TRANS_MAST(VFT_CHANNEL_DESC,VFT_REQUEST_TYPE,VFT_CHANNEL_CODE,VFT_TRAN_CODE,VFT_INS_DATE,VFT_INST_USER)
VALUES('MOBILE','VCVALIDATION','13','59',SYSDATE,1);
INSERT INTO vmscms.VMS_FSAPI_TRANS_MAST(VFT_CHANNEL_DESC,VFT_REQUEST_TYPE,VFT_CHANNEL_CODE,VFT_TRAN_CODE,VFT_INS_DATE,VFT_INST_USER)
VALUES('WEB','VCVALIDATION','17','02',SYSDATE,1);

INSERT INTO vmscms.VMS_FSAPI_TRANS_MAST(VFT_CHANNEL_DESC,VFT_REQUEST_TYPE,VFT_CHANNEL_CODE,VFT_TRAN_CODE,VFT_INS_DATE,VFT_INST_USER)
VALUES('IVR','RELOAD','07','36',SYSDATE,1);
INSERT INTO vmscms.VMS_FSAPI_TRANS_MAST(VFT_CHANNEL_DESC,VFT_REQUEST_TYPE,VFT_CHANNEL_CODE,VFT_TRAN_CODE,VFT_INS_DATE,VFT_INST_USER)
VALUES('WEB','RELOAD','17','03',SYSDATE,1);

insert into vmscms.VMS_FSAPI_TRANS_MAST(VFT_CHANNEL_DESC,VFT_REQUEST_TYPE,VFT_CHANNEL_CODE,VFT_TRAN_CODE,VFT_INS_DATE,VFT_INST_USER)
values('IVR','INITIAL LOAD','07','37',sysdate,1);

insert into vmscms.VMS_FSAPI_TRANS_MAST(VFT_CHANNEL_DESC,VFT_REQUEST_TYPE,VFT_CHANNEL_CODE,VFT_TRAN_CODE,VFT_INS_DATE,VFT_INST_USER)
values('WEB','INITIAL LOAD','17','04',SYSDATE,1);