CREATE OR REPLACE FORCE VIEW VMSCMS.DMRV_TRANSFORMATIONS
(TRANSFORMATION_ID, TRANSFORMATION_OVID, TRANSFORMATION_NAME, TRANSFORMATION_TASK_ID, TRANSFORMATION_TASK_OVID, 
 TRANSFORMATION_TASK_NAME, FILTER_CONDITION, JOIN_CONDITION, PRIMARY, DESIGN_OVID)
AS 
select  Transformation_ID, Transformation_OVID, Transformation_Name, Transformation_Task_ID, Transformation_Task_OVID, Transformation_Task_Name, Filter_Condition, Join_Condition, Primary, Design_OVID from DMRS_TRANSFORMATIONS;


