/* Formatted on 2012/07/02 15:17 (Formatter Plus v4.8.8) */
CREATE OR REPLACE FORCE VIEW vmscms.dmrv_tables (table_name,
                                                 abbreviation,
                                                 object_id,
                                                 ovid,
                                                 import_id,
                                                 model_id,
                                                 model_ovid,
                                                 structured_type_id,
                                                 structured_type_ovid,
                                                 structured_type_name,
                                                 number_data_elements,
                                                 classification_type_id,
                                                 classification_type_ovid,
                                                 classification_type_name,
                                                 allow_type_substitution,
                                                 min_volume,
                                                 expected_volume,
                                                 max_volume,
                                                 growth_rate_percents,
                                                 growth_rate_interval,
                                                 normal_form,
                                                 temporary_object_scope,
                                                 adequately_normalized,
                                                 substitution_parent,
                                                 substitution_parent_ovid,
                                                 engineer,
                                                 spatial_table,
                                                 oid_is_pk,
                                                 oid_is_user_defined,
                                                 include_scripts_into_ddl,
                                                 model_name,
                                                 substitution_parent_name,
                                                 source_info_ovid,
                                                 source_datadict_schema_name,
                                                 source_datadict_object_name,
                                                 design_ovid
                                                )
AS
   SELECT table_name, abbreviation, object_id, ovid, import_id, model_id,
          model_ovid, structured_type_id, structured_type_ovid,
          structured_type_name, number_data_elements, classification_type_id,
          classification_type_ovid, classification_type_name,
          allow_type_substitution, min_volume, expected_volume, max_volume,
          growth_rate_percents, growth_rate_interval, normal_form,
          temporary_object_scope, adequately_normalized, substitution_parent,
          substitution_parent_ovid, engineer, spatial_table, oid_is_pk,
          oid_is_user_defined, include_scripts_into_ddl, model_name,
          substitution_parent_name, source_info_ovid,
          source_datadict_schema_name, source_datadict_object_name,
          design_ovid
     FROM dmrs_tables;


