/* Formatted on 2012/07/02 15:13 (Formatter Plus v4.8.8) */
CREATE OR REPLACE FORCE VIEW vmscms.dmrv_attributes (attribute_name,
                                                     object_id,
                                                     ovid,
                                                     import_id,
                                                     container_id,
                                                     container_ovid,
                                                     mandatory,
                                                     datatype_kind,
                                                     value_type,
                                                     formula,
                                                     scopeentity_id,
                                                     scopeentity_ovid,
                                                     domain_id,
                                                     domain_ovid,
                                                     logical_type_id,
                                                     logical_type_ovid,
                                                     distinct_type_id,
                                                     distinct_type_ovid,
                                                     structured_type_id,
                                                     structured_type_ovid,
                                                     collection_type_id,
                                                     collection_type_ovid,
                                                     check_constraint_name,
                                                     DEFAULT_VALUE,
                                                     use_domain_constraint,
                                                     domain_name,
                                                     logical_type_name,
                                                     structured_type_name,
                                                     distinct_type_name,
                                                     collection_type_name,
                                                     synonyms,
                                                     preferred_abbreviation,
                                                     relationship_id,
                                                     relationship_ovid,
                                                     entity_name,
                                                     pk_flag,
                                                     fk_flag,
                                                     relationship_name,
                                                     SEQUENCE,
                                                     t_size,
                                                     t_precision,
                                                     char_units,
                                                     native_type,
                                                     t_scale,
                                                     data_source,
                                                     scopeentity_name,
                                                     design_ovid
                                                    )
AS
   SELECT attribute_name, object_id, ovid, import_id, container_id,
          container_ovid, mandatory, datatype_kind, value_type, formula,
          scopeentity_id, scopeentity_ovid, domain_id, domain_ovid,
          logical_type_id, logical_type_ovid, distinct_type_id,
          distinct_type_ovid, structured_type_id, structured_type_ovid,
          collection_type_id, collection_type_ovid, check_constraint_name,
          DEFAULT_VALUE, use_domain_constraint, domain_name,
          logical_type_name, structured_type_name, distinct_type_name,
          collection_type_name, synonyms, preferred_abbreviation,
          relationship_id, relationship_ovid, entity_name, pk_flag, fk_flag,
          relationship_name, SEQUENCE, t_size, t_precision, char_units,
          native_type, t_scale, data_source, scopeentity_name, design_ovid
     FROM dmrs_attributes;


