/* Formatted on 2012/07/02 15:13 (Formatter Plus v4.8.8) */
CREATE OR REPLACE FORCE VIEW vmscms.dmrv_columns (column_name,
                                                  abbreviation,
                                                  object_id,
                                                  ovid,
                                                  import_id,
                                                  container_id,
                                                  container_ovid,
                                                  mandatory,
                                                  datatype_kind,
                                                  value_type,
                                                  computed,
                                                  formula,
                                                  scopeentity_id,
                                                  scopeentity_ovid,
                                                  domain_id,
                                                  domain_ovid,
                                                  logical_type_id,
                                                  logical_type_ovid,
                                                  distinct_type_id,
                                                  distinct_type_ovid,
                                                  structured_type_id,
                                                  structured_type_ovid,
                                                  collection_type_id,
                                                  collection_type_ovid,
                                                  check_constraint_name,
                                                  DEFAULT_VALUE,
                                                  use_domain_constraint,
                                                  domain_name,
                                                  logical_type_name,
                                                  structured_type_name,
                                                  distinct_type_name,
                                                  collection_type_name,
                                                  uses_default,
                                                  engineer,
                                                  table_name,
                                                  pk_flag,
                                                  fk_flag,
                                                  native_type,
                                                  SEQUENCE,
                                                  model_id,
                                                  model_ovid,
                                                  model_name,
                                                  t_size,
                                                  t_precision,
                                                  t_scale,
                                                  char_units,
                                                  personally_id_information,
                                                  sensitive_information,
                                                  mask_for_none_production,
                                                  scopeentity_name,
                                                  auto_increment_column,
                                                  identity_column,
                                                  auto_increment_generate_always,
                                                  auto_increment_start_with,
                                                  auto_increment_increment_by,
                                                  auto_increment_min_value,
                                                  auto_increment_max_value,
                                                  auto_increment_cycle,
                                                  auto_increment_disable_cache,
                                                  auto_increment_cache,
                                                  auto_increment_order,
                                                  auto_increment_sequence_name,
                                                  auto_increment_trigger_name,
                                                  design_ovid
                                                 )
AS
   SELECT column_name, abbreviation, object_id, ovid, import_id, container_id,
          container_ovid, mandatory, datatype_kind, value_type, computed,
          formula, scopeentity_id, scopeentity_ovid, domain_id, domain_ovid,
          logical_type_id, logical_type_ovid, distinct_type_id,
          distinct_type_ovid, structured_type_id, structured_type_ovid,
          collection_type_id, collection_type_ovid, check_constraint_name,
          DEFAULT_VALUE, use_domain_constraint, domain_name,
          logical_type_name, structured_type_name, distinct_type_name,
          collection_type_name, uses_default, engineer, table_name, pk_flag,
          fk_flag, native_type, SEQUENCE, model_id, model_ovid, model_name,
          t_size, t_precision, t_scale, char_units, personally_id_information,
          sensitive_information, mask_for_none_production, scopeentity_name,
          auto_increment_column, identity_column,
          auto_increment_generate_always, auto_increment_start_with,
          auto_increment_increment_by, auto_increment_min_value,
          auto_increment_max_value, auto_increment_cycle,
          auto_increment_disable_cache, auto_increment_cache,
          auto_increment_order, auto_increment_sequence_name,
          auto_increment_trigger_name, design_ovid
     FROM dmrs_columns;


