/* Formatted on 2012/07/02 15:17 (Formatter Plus v4.8.8) */
CREATE OR REPLACE FORCE VIEW vmscms.prepaid_card_info (cap_appl_code,
                                                       cap_inst_code,
                                                       cap_asso_code,
                                                       cap_inst_type,
                                                       cap_prod_code,
                                                       cap_prod_catg,
                                                       cap_card_type,
                                                       cap_cust_catg,
                                                       cap_pan_code,
                                                       cap_mbr_numb,
                                                       cap_card_stat,
                                                       cap_pin_off,
                                                       cap_limit_ind,
                                                       cap_cust_code,
                                                       cap_disp_name,
                                                       cap_limit_amt,
                                                       cap_use_limit,
                                                       cap_appl_bran,
                                                       cap_active_date,
                                                       cap_expry_date,
                                                       cap_addon_stat,
                                                       cap_addon_link,
                                                       cap_mbr_link,
                                                       cap_acct_id,
                                                       cap_acct_no,
                                                       cap_tot_acct,
                                                       cap_bill_addr,
                                                       cap_chnl_code,
                                                       cap_pangen_date,
                                                       cap_pangen_user,
                                                       cap_cafgen_flag,
                                                       cap_caf_fname,
                                                       cap_cafgen_date,
                                                       cap_cafgen_user,
                                                       cap_pbfgen_flag,
                                                       cap_pbf_fname,
                                                       cap_pbfgen_date,
                                                       cap_pbfgen_user,
                                                       cap_pin_flag,
                                                       cap_pingen_date,
                                                       cap_pingen_user,
                                                       cap_embos_flag,
                                                       cap_emb_fname,
                                                       cap_embos_date,
                                                       cap_embos_user,
                                                       cap_phy_embos,
                                                       cap_disp_ref,
                                                       cap_join_feecalc,
                                                       cap_next_bill_date,
                                                       cap_lastpos_trandate,
                                                       cap_ins_user,
                                                       cap_ins_date,
                                                       cap_lupd_user,
                                                       cap_lupd_date,
                                                       cap_sync_flag,
                                                       cap_atm_offline_limit,
                                                       cap_atm_online_limit,
                                                       cap_pos_offline_limit,
                                                       cap_pos_online_limit,
                                                       cap_offline_aggr_limit,
                                                       cap_online_aggr_limit,
                                                       flag,
                                                       cap_billdate_flag,
                                                       cap_next_mb_date,
                                                       cap_fee_calc,
                                                       cap_issue_flag,
                                                       cap_request_id,
                                                       cap_rule_indicator,
                                                       cap_rulegroup_code
                                                      )
AS
   SELECT "CAP_APPL_CODE", "CAP_INST_CODE", "CAP_ASSO_CODE", "CAP_INST_TYPE",
          "CAP_PROD_CODE", "CAP_PROD_CATG", "CAP_CARD_TYPE", "CAP_CUST_CATG",
          "CAP_PAN_CODE", "CAP_MBR_NUMB", "CAP_CARD_STAT", "CAP_PIN_OFF",
          "CAP_LIMIT_IND", "CAP_CUST_CODE", "CAP_DISP_NAME", "CAP_LIMIT_AMT",
          "CAP_USE_LIMIT", "CAP_APPL_BRAN", "CAP_ACTIVE_DATE",
          "CAP_EXPRY_DATE", "CAP_ADDON_STAT", "CAP_ADDON_LINK",
          "CAP_MBR_LINK", "CAP_ACCT_ID", "CAP_ACCT_NO", "CAP_TOT_ACCT",
          "CAP_BILL_ADDR", "CAP_CHNL_CODE", "CAP_PANGEN_DATE",
          "CAP_PANGEN_USER", "CAP_CAFGEN_FLAG", "CAP_CAF_FNAME",
          "CAP_CAFGEN_DATE", "CAP_CAFGEN_USER", "CAP_PBFGEN_FLAG",
          "CAP_PBF_FNAME", "CAP_PBFGEN_DATE", "CAP_PBFGEN_USER",
          "CAP_PIN_FLAG", "CAP_PINGEN_DATE", "CAP_PINGEN_USER",
          "CAP_EMBOS_FLAG", "CAP_EMB_FNAME", "CAP_EMBOS_DATE",
          "CAP_EMBOS_USER", "CAP_PHY_EMBOS", "CAP_DISP_REF",
          "CAP_JOIN_FEECALC", "CAP_NEXT_BILL_DATE", "CAP_LASTPOS_TRANDATE",
          "CAP_INS_USER", "CAP_INS_DATE", "CAP_LUPD_USER", "CAP_LUPD_DATE",
          "CAP_SYNC_FLAG", "CAP_ATM_OFFLINE_LIMIT", "CAP_ATM_ONLINE_LIMIT",
          "CAP_POS_OFFLINE_LIMIT", "CAP_POS_ONLINE_LIMIT",
          "CAP_OFFLINE_AGGR_LIMIT", "CAP_ONLINE_AGGR_LIMIT", "FLAG",
          "CAP_BILLDATE_FLAG", "CAP_NEXT_MB_DATE", "CAP_FEE_CALC",
          "CAP_ISSUE_FLAG", "CAP_REQUEST_ID", "CAP_RULE_INDICATOR",
          "CAP_RULEGROUP_CODE"
     FROM cms_appl_pan;


