CREATE OR REPLACE PROCEDURE VMSCMS.SP_BICPART_SPLIT(ERRMSG	OUT		VARCHAR2)
AS

	CURSOR CUR1 IS SELECT ROWID,RPT_AMT2 FROM REC_BICPART_TEMP;
	V_AMT2 NUMBER(20):=0;
BEGIN		--MAIN BEGIN

--Imran 14 Jan 2004
--Imran 11 Feb 2004
-- UPDATE REC_BICPART_TEMP set Rpt_ISSBANK_CODE=fn_getIssBankCode(Rpt_PAN),Rpt_ACQBANK_CODE=fn_getAcqBankCode(Rpt_ACQ_INST_ID_NUM);
 UPDATE REC_BICPART_TEMP SET Rpt_ISSBANK_CODE=fn_getIssBankCode(Rpt_PAN),Rpt_ACQBANK_CODE=fn_getAcqBankCode(Rpt_ACQ_INST_ID_NUM),rpt_card_type=fn_getIssBankCardType(Rpt_PAN);
--Imran 14 Jan 2004

	--ADDED BY SUBHASHINI 4 DEC 2003
	FOR C IN CUR1 LOOP
		BEGIN
			V_AMT2:=TO_NUMBER(C.RPT_AMT2);
		EXCEPTION
			WHEN VALUE_ERROR THEN
				UPDATE REC_BICPART_TEMP
				SET RPT_AMT2=0
				WHERE ROWID=C.ROWID;
		END;
	END LOOP;


	--REQUIRED TO UPDATE ALL REVERSALS TO 420

	UPDATE REC_BICPART_TEMP
	SET RPT_TRAN_TYP='0420'
	WHERE RPT_RVSL_CDE<>'00' AND SUBSTR(RPT_TRAN_TYP,1,2)<>'04';


	-- RQD TO SET MSG TYPE AS 220 FOR PARTIAL REV AND AMT1=AMT2(FINAL AMT)
	UPDATE REC_BICPART_TEMP
	SET RPT_TRAN_TYP='0220',RPT_AMT1=RPT_AMT2,RPT_AMT2=0
	WHERE SUBSTR(RPT_TRAN_TYP,1,2)='04'
	AND TO_NUMBER(RPT_AMT2)<>0
	AND TO_NUMBER(RPT_AMT1)<>TO_NUMBER(RPT_AMT2);


	--AMT2 IS MEANINGFUL IN CASE OF REVERSAL
	UPDATE REC_BICPART_TEMP
	SET RPT_AMT2=0
	WHERE SUBSTR(RPT_TRAN_TYP,1,2)<>'04' AND RPT_TRAN_TYP<>'0220';

--Imran 27th Jan 2004, moving down
/*	--Set all normal msg type as 0210, (0200,0100,0110 to 0210)
	UPDATE REC_BICPART_TEMP
	SET RPT_TRAN_TYP = '0210'
	WHERE RPT_TRAN_TYP = '0200' OR
	SUBSTR(RPT_TRAN_TYP,1,2) = '01';*/
--Imran 27th Jan 2004, moving down

	--END OF ADDN BY SUBHASHINI 4 DEC 2003

ERRMSG := 'OK';
			INSERT INTO REC_BICPART_REJECT (
				RPR_FILE_NAME,          RPR_REC_TYP,	RPR_TRAN_TYP,
				RPR_RESP_CDE,		RPR_RVSL_CDE,	RPR_POST_DAT,
				RPR_ACQ_INST_ID_NUM,	RPR_TERM_ID,	RPR_TERM_NAME_LOC,
				RPR_TERM_OWNER_NAME,	RPR_TERM_CITY,	RPR_TERM_ST_X,
				RPR_TERM_CNTRY_X,	RPR_SEQ_NUM,	RPR_INVOICE_NUM,
				RPR_RETL_ID,		RPR_TRAN_CDE,	RPR_RESPONDER,
				RPR_PAN,		RPR_MBR_NUM,	RPR_TRACE_NUMB,
				RPR_AMT1,		RPR_AMT2,	RPR_SETL_CRNCY_CDE,
				RPR_SETL_CONV_RATE,	RPR_TRAN_DAT,	RPR_TRAN_TIM,
				RPR_PT_SRV_COND_CDE,	RPR_PT_SRV_ENTRY_MDE,
				RPR_FROM_ACCT_TYP,	RPR_FROM_ACCT,	RPR_TO_ACCT_TYP,
				RPR_TO_ACCT,		RPR_ORIG_CRNCY_CDE,	RPR_RESP,
				RPR_MAT_CAT_CODE,	RPR_AUTH_CRNCY_CDE,	RPR_FILE_HEADER,
				RPR_PRODUCT_TYPE,	RPR_PROCESSOR,		RPR_PROCESSING_CODE,
				RPR_ISO_RESPONSE_CODE,	RPR_SAVE_AREA_AMT,	RPR_ACQ_ICHG_SETL_DAT,
				RPR_ISS_ICHG_SETL_DAT,	RPR_EXTERNAL_DUMP_AMT,	RPR_RECON_FLAG
--Imran 14 Jan 2004
        ,Rpr_ISSBANK_CODE,Rpr_ACQBANK_CODE
--Imran 14 Jan 2004
--Imran 11 Feb 2004
        ,Rpr_card_type
--Imran 11 Feb 2004
        )
			SELECT	RPT_FILE_NAME,          RPT_REC_TYP,	RPT_TRAN_TYP,
				RPT_RESP_CDE,		RPT_RVSL_CDE,	RPT_POST_DAT,
				RPT_ACQ_INST_ID_NUM,	RPT_TERM_ID,	RPT_TERM_NAME_LOC,
				RPT_TERM_OWNER_NAME,	RPT_TERM_CITY,	RPT_TERM_ST_X,
				RPT_TERM_CNTRY_X,	RPT_SEQ_NUM,	RPT_INVOICE_NUM,
				RPT_RETL_ID,		RPT_TRAN_CDE,	RPT_RESPONDER,
				RPT_PAN,		RPT_MBR_NUM,	RPT_TRACE_NUMB,
				RPT_AMT1,		RPT_AMT2,	RPT_SETL_CRNCY_CDE,
				RPT_SETL_CONV_RATE,	RPT_TRAN_DAT,	RPT_TRAN_TIM,
				RPT_PT_SRV_COND_CDE,	RPT_PT_SRV_ENTRY_MDE,
				RPT_FROM_ACCT_TYP,	RPT_FROM_ACCT,	RPT_TO_ACCT_TYP,
				RPT_TO_ACCT,		RPT_ORIG_CRNCY_CDE,	RPT_RESP,
				RPT_MAT_CAT_CODE,	RPT_AUTH_CRNCY_CDE,	RPT_FILE_HEADER,
				RPT_PRODUCT_TYPE,	RPT_PROCESSOR,		RPT_PROCESSING_CODE,
				RPT_ISO_RESPONSE_CODE,	RPT_SAVE_AREA_AMT,	RPT_ACQ_ICHG_SETL_DAT,
				RPT_ISS_ICHG_SETL_DAT,	RPT_EXTERNAL_DUMP_AMT,	RPT_RECON_FLAG
--Imran 14 Jan 2004
        ,Rpt_ISSBANK_CODE,Rpt_ACQBANK_CODE
--Imran 14 Jan 2004
--Imran 11 Feb 2004
        ,Rpt_card_type
--Imran 11 Feb 2004
				FROM REC_BICPART_TEMP
--Imran 27th Jan 2004, 0200 to be treated as rejected, as it is a request without response
--        WHERE RPT_RESP NOT IN ('000','001');
        WHERE RPT_RESP NOT IN ('000','001') OR RPT_TRAN_TYP='0200';
--Imran 27th Jan 2004, 0200 to be treated as rejected, as it is a request without response

--Imran 27th Jan 2004, 0200 to be treated as rejected, as it is a request without response
--			DELETE FROM REC_BICPART_TEMP WHERE RPT_RESP NOT IN ('000','001');
			DELETE FROM REC_BICPART_TEMP WHERE RPT_RESP NOT IN ('000','001') OR RPT_TRAN_TYP='0200';
--Imran 27th Jan 2004, 0200 to be treated as rejected, as it is a request without response

--Imran 27th Jan 2004
	--Set all normal msg type as 0210, (0200,0100,0110 to 0210)
	UPDATE REC_BICPART_TEMP
	SET RPT_TRAN_TYP = '0210'
	WHERE RPT_TRAN_TYP = '0200' OR
	SUBSTR(RPT_TRAN_TYP,1,2) = '01';
--Imran 27th Jan 2004

      INSERT INTO REC_BICPART_UNRECON(
        RPU_FILE_NAME,          RPU_REC_TYP,	RPU_TRAN_TYP,
				RPU_RESP_CDE,		RPU_RVSL_CDE,	RPU_POST_DAT,
				RPU_ACQ_INST_ID_NUM,	RPU_TERM_ID,	RPU_TERM_NAME_LOC,
				RPU_TERM_OWNER_NAME,	RPU_TERM_CITY,	RPU_TERM_ST_X,
				RPU_TERM_CNTRY_X,	RPU_SEQ_NUM,	RPU_INVOICE_NUM,
				RPU_RETL_ID,		RPU_TRAN_CDE,	RPU_RESPONDER,
				RPU_PAN,		RPU_MBR_NUM,	RPU_TRACE_NUMB,
				RPU_AMT1,		RPU_AMT2,	RPU_SETL_CRNCY_CDE,
				RPU_SETL_CONV_RATE,	RPU_TRAN_DAT,	RPU_TRAN_TIM,
				RPU_PT_SRV_COND_CDE,	RPU_PT_SRV_ENTRY_MDE,
				RPU_FROM_ACCT_TYP,	RPU_FROM_ACCT,	RPU_TO_ACCT_TYP,
				RPU_TO_ACCT,		RPU_ORIG_CRNCY_CDE,	RPU_RESP,
				RPU_MAT_CAT_CODE,	RPU_AUTH_CRNCY_CDE,	RPU_FILE_HEADER,
				RPU_PRODUCT_TYPE,	RPU_PROCESSOR,		RPU_PROCESSING_CODE,
				RPU_ISO_RESPONSE_CODE,	RPU_SAVE_AREA_AMT,	RPU_ACQ_ICHG_SETL_DAT,
				RPU_ISS_ICHG_SETL_DAT,	RPU_EXTERNAL_DUMP_AMT,	RPU_RECON_FLAG
--Imran 14 Jan 2004
        ,Rpu_ISSBANK_CODE,Rpu_ACQBANK_CODE
--Imran 14 Jan 2004
--Imran 11 Feb 2004
        ,Rpu_card_type
--Imran 11 Feb 2004
        )
			SELECT	RPT_FILE_NAME,          RPT_REC_TYP,	RPT_TRAN_TYP,
				RPT_RESP_CDE,		RPT_RVSL_CDE,	RPT_POST_DAT,
				RPT_ACQ_INST_ID_NUM,	RPT_TERM_ID,	RPT_TERM_NAME_LOC,
				RPT_TERM_OWNER_NAME,	RPT_TERM_CITY,	RPT_TERM_ST_X,
				RPT_TERM_CNTRY_X,	RPT_SEQ_NUM,	RPT_INVOICE_NUM,
				RPT_RETL_ID,		RPT_TRAN_CDE,	RPT_RESPONDER,
				RPT_PAN,		RPT_MBR_NUM,	RPT_TRACE_NUMB,
				RPT_AMT1,		RPT_AMT2,	RPT_SETL_CRNCY_CDE,
				RPT_SETL_CONV_RATE,	RPT_TRAN_DAT,	RPT_TRAN_TIM,
				RPT_PT_SRV_COND_CDE,	RPT_PT_SRV_ENTRY_MDE,
				RPT_FROM_ACCT_TYP,	RPT_FROM_ACCT,	RPT_TO_ACCT_TYP,
				RPT_TO_ACCT,		RPT_ORIG_CRNCY_CDE,	RPT_RESP,
				RPT_MAT_CAT_CODE,	RPT_AUTH_CRNCY_CDE,	RPT_FILE_HEADER,
				RPT_PRODUCT_TYPE,	RPT_PROCESSOR,		RPT_PROCESSING_CODE,
				RPT_ISO_RESPONSE_CODE,	RPT_SAVE_AREA_AMT,	RPT_ACQ_ICHG_SETL_DAT,
				RPT_ISS_ICHG_SETL_DAT,	RPT_EXTERNAL_DUMP_AMT,	RPT_RECON_FLAG
--Imran 14 Jan 2004
        ,Rpt_ISSBANK_CODE,Rpt_ACQBANK_CODE
--Imran 14 Jan 2004
--Imran 11 Feb 2004
        ,Rpt_card_type
--Imran 11 Feb 2004
				FROM REC_BICPART_TEMP ;

EXCEPTION	--EXCP OF MAIN
WHEN OTHERS THEN
ERRMSG := 'MAIN EXCP --'||SQLERRM;
END;		--END OF MAIN
/


