CREATE OR REPLACE PROCEDURE VMSCMS.SP_BIC_SPLIT(ERRMSG	OUT		VARCHAR2)
AS
	CURSOR CUR1 IS SELECT ROWID,RBT_AMT2 FROM REC_BIC_TEMP;
	V_AMT2 NUMBER(20):=0;
BEGIN		--MAIN BEGIN
	--BY SUBHASHINI 4 DEC 2003

--Imran 14 Jan 2004
--Imran 11 Feb 2004
-- UPDATE REC_BIC_TEMP set Rbt_ISSBANK_CODE=fn_getIssBankCode(RBt_PAN),RBt_ACQBANK_CODE=fn_getAcqBankCode(RBt_ACQ_INST_ID_NUM);
 UPDATE REC_BIC_TEMP SET Rbt_ISSBANK_CODE=fn_getIssBankCode(RBt_PAN),RBt_ACQBANK_CODE=fn_getAcqBankCode(RBt_ACQ_INST_ID_NUM),rbt_card_type=fn_getIssBankCardType(RBt_PAN);
--Imran 14 Jan 2004

	FOR C IN CUR1 LOOP
		BEGIN
			V_AMT2:=TO_NUMBER(C.RBT_AMT2);
		EXCEPTION
			WHEN VALUE_ERROR THEN
				UPDATE REC_BIC_TEMP
				SET RBT_AMT2=0
				WHERE ROWID=C.ROWID;
		END;
	END LOOP;

	--REQUIRED TO UPDATE ALL REVERSALS TO 420

	UPDATE REC_BIC_TEMP
	SET RBT_TRAN_TYP='0420'
	WHERE RBT_RVSL_CDE<>'00' AND SUBSTR(RBT_TRAN_TYP,1,2)<>'04';

	-- RQD TO SET MSG TYPE AS 220 FOR PARTIAL REV AND AMT1=AMT2(FINAL AMT)

	UPDATE REC_BIC_TEMP
	SET RBT_TRAN_TYP='0220',RBT_AMT1=RBT_AMT2,RBT_AMT2=0
	WHERE SUBSTR(RBT_TRAN_TYP,1,2)='04'
	AND TO_NUMBER(RBT_AMT2)<>0
	AND TO_NUMBER(RBT_AMT1)<>TO_NUMBER(RBT_AMT2);


	--AMT2 IS MEANINGFUL IN CASE OF REVERSAL
	UPDATE REC_BIC_TEMP
	SET RBT_AMT2=0
	WHERE SUBSTR(RBT_TRAN_TYP,1,2)<>'04' AND RBT_TRAN_TYP<>'0220';

--Imran 27th Jan 2004, moving down
/*	--Set all normal msg type as 0210, (0200,0100,0110 to 0210)
	UPDATE REC_BIC_TEMP
	SET RBT_TRAN_TYP = '0210'
	WHERE RBT_TRAN_TYP = '0200' OR
	SUBSTR(RBT_TRAN_TYP,1,2) = '01';*/
--Imran 27th Jan 2004, moving down


	--END OF ADDN BY SUBHASHINI 4 DEC 2003

ERRMSG := 'OK';
			INSERT INTO REC_BIC_REJECT (
				RBR_FILE_NAME,          RBR_REC_TYP,	RBR_TRAN_TYP,
				RBR_RESP_CDE,		RBR_RVSL_CDE,	RBR_POST_DAT,
				RBR_ACQ_INST_ID_NUM,	RBR_TERM_ID,	RBR_TERM_NAME_LOC,
				RBR_TERM_OWNER_NAME,	RBR_TERM_CITY,	RBR_TERM_ST_X,
				RBR_TERM_CNTRY_X,	RBR_SEQ_NUM,	RBR_INVOICE_NUM,
				RBR_RETL_ID,		RBR_TRAN_CDE,	RBR_RESPONDER,
				RBR_PAN,		RBR_MBR_NUM,	RBR_TRACE_NUMB,
				RBR_AMT1,		RBR_AMT2,	RBR_SETL_CRNCY_CDE,
				RBR_SETL_CONV_RATE,	RBR_TRAN_DAT,	RBR_TRAN_TIM,
				RBR_PT_SRV_COND_CDE,	RBR_PT_SRV_ENTRY_MDE,
				RBR_FROM_ACCT_TYP,	RBR_FROM_ACCT,	RBR_TO_ACCT_TYP,
				RBR_TO_ACCT,		RBR_ORIG_CRNCY_CDE,	RBR_RESP,
				RBR_MAT_CAT_CODE,	RBR_AUTH_CRNCY_CDE,	RBR_FILE_HEADER,
				RBR_PRODUCT_TYPE,	RBR_PROCESSOR,		RBR_PROCESSING_CODE,
				RBR_ISO_RESPONSE_CODE,	RBR_SAVE_AREA_AMT,	RBR_ACQ_ICHG_SETL_DAT,
				RBR_ISS_ICHG_SETL_DAT,	RBR_EXTERNAL_DUMP_AMT,	RBR_RECON_FLAG
--Imran 14 Jan 2004
        ,Rbr_ISSBANK_CODE,RBr_ACQBANK_CODE
--Imran 14 Jan 2004
--Imran 11 Feb 2004
        ,Rbr_card_type
--Imran 11 Feb 2004
        )
			SELECT	RBT_FILE_NAME,          RBT_REC_TYP,	RBT_TRAN_TYP,
				RBT_RESP_CDE,		RBT_RVSL_CDE,	RBT_POST_DAT,
				RBT_ACQ_INST_ID_NUM,	RBT_TERM_ID,	RBT_TERM_NAME_LOC,
				RBT_TERM_OWNER_NAME,	RBT_TERM_CITY,	RBT_TERM_ST_X,
				RBT_TERM_CNTRY_X,	RBT_SEQ_NUM,	RBT_INVOICE_NUM,
				RBT_RETL_ID,		RBT_TRAN_CDE,	RBT_RESPONDER,
				RBT_PAN,		RBT_MBR_NUM,	RBT_TRACE_NUMB,
				RBT_AMT1,		RBT_AMT2,	RBT_SETL_CRNCY_CDE,
				RBT_SETL_CONV_RATE,	RBT_TRAN_DAT,	RBT_TRAN_TIM,
				RBT_PT_SRV_COND_CDE,	RBT_PT_SRV_ENTRY_MDE,
				RBT_FROM_ACCT_TYP,	RBT_FROM_ACCT,	RBT_TO_ACCT_TYP,
				RBT_TO_ACCT,		RBT_ORIG_CRNCY_CDE,	RBT_RESP,
				RBT_MAT_CAT_CODE,	RBT_AUTH_CRNCY_CDE,	RBT_FILE_HEADER,
				RBT_PRODUCT_TYPE,	RBT_PROCESSOR,		RBT_PROCESSING_CODE,
				RBT_ISO_RESPONSE_CODE,	RBT_SAVE_AREA_AMT,	RBT_ACQ_ICHG_SETL_DAT,
				RBT_ISS_ICHG_SETL_DAT,	RBT_EXTERNAL_DUMP_AMT,	RBT_RECON_FLAG
--Imran 14 Jan 2004
        ,Rbt_ISSBANK_CODE,RBt_ACQBANK_CODE
--Imran 14 Jan 2004
--Imran 11 Feb 2004
        ,Rbt_card_type
--Imran 11 Feb 2004
				FROM REC_BIC_TEMP
--Imran 27th Jan 2004, 0200 to be treated as rejected, as it is a request without response
--        WHERE RBT_RESP NOT IN ('000','001');
        WHERE RBT_RESP NOT IN ('000','001') OR RBT_TRAN_TYP='0200';

--Imran 27th Jan 2004, 0200 to be treated as rejected, as it is a request without response
--			DELETE FROM REC_BIC_TEMP WHERE RBT_RESP NOT IN ('000','001');
			DELETE FROM REC_BIC_TEMP WHERE RBT_RESP NOT IN ('000','001') OR RBT_TRAN_TYP='0200';

--Imran 27th Jan 2004
	--Set all normal msg type as 0210, (0200,0100,0110 to 0210)
	UPDATE REC_BIC_TEMP
	SET RBT_TRAN_TYP = '0210'
	WHERE RBT_TRAN_TYP = '0200' OR
	SUBSTR(RBT_TRAN_TYP,1,2) = '01';
--Imran 27th Jan 2004

			INSERT INTO REC_BIC_UNRECON(
      	RBU_FILE_NAME,          RBU_REC_TYP,	RBU_TRAN_TYP,
				RBU_RESP_CDE,		RBU_RVSL_CDE,	RBU_POST_DAT,
				RBU_ACQ_INST_ID_NUM,	RBU_TERM_ID,	RBU_TERM_NAME_LOC,
				RBU_TERM_OWNER_NAME,	RBU_TERM_CITY,	RBU_TERM_ST_X,
				RBU_TERM_CNTRY_X,	RBU_SEQ_NUM,	RBU_INVOICE_NUM,
				RBU_RETL_ID,		RBU_TRAN_CDE,	RBU_RESPONDER,
				RBU_PAN,		RBU_MBR_NUM,	RBU_TRACE_NUMB,
				RBU_AMT1,		RBU_AMT2,	RBU_SETL_CRNCY_CDE,
				RBU_SETL_CONV_RATE,	RBU_TRAN_DAT,	RBU_TRAN_TIM,
				RBU_PT_SRV_COND_CDE,	RBU_PT_SRV_ENTRY_MDE,
				RBU_FROM_ACCT_TYP,	RBU_FROM_ACCT,	RBU_TO_ACCT_TYP,
				RBU_TO_ACCT,		RBU_ORIG_CRNCY_CDE,	RBU_RESP,
				RBU_MAT_CAT_CODE,	RBU_AUTH_CRNCY_CDE,	RBU_FILE_HEADER,
				RBU_PRODUCT_TYPE,	RBU_PROCESSOR,		RBU_PROCESSING_CODE,
				RBU_ISO_RESPONSE_CODE,	RBU_SAVE_AREA_AMT,	RBU_ACQ_ICHG_SETL_DAT,
				RBU_ISS_ICHG_SETL_DAT,	RBU_EXTERNAL_DUMP_AMT,	RBU_RECON_FLAG
--Imran 14 Jan 2004
        ,Rbu_ISSBANK_CODE,RBu_ACQBANK_CODE
--Imran 14 Jan 2004
--Imran 11 Feb 2004
        ,Rbu_card_type
--Imran 11 Feb 2004
        )
      SELECT
      	RBT_FILE_NAME,          RBT_REC_TYP,	RBT_TRAN_TYP,
				RBT_RESP_CDE,		RBT_RVSL_CDE,	RBT_POST_DAT,
				RBT_ACQ_INST_ID_NUM,	RBT_TERM_ID,	RBT_TERM_NAME_LOC,
				RBT_TERM_OWNER_NAME,	RBT_TERM_CITY,	RBT_TERM_ST_X,
				RBT_TERM_CNTRY_X,	RBT_SEQ_NUM,	RBT_INVOICE_NUM,
				RBT_RETL_ID,		RBT_TRAN_CDE,	RBT_RESPONDER,
				RBT_PAN,		RBT_MBR_NUM,	RBT_TRACE_NUMB,
				RBT_AMT1,		RBT_AMT2,	RBT_SETL_CRNCY_CDE,
				RBT_SETL_CONV_RATE,	RBT_TRAN_DAT,	RBT_TRAN_TIM,
				RBT_PT_SRV_COND_CDE,	RBT_PT_SRV_ENTRY_MDE,
				RBT_FROM_ACCT_TYP,	RBT_FROM_ACCT,	RBT_TO_ACCT_TYP,
				RBT_TO_ACCT,		RBT_ORIG_CRNCY_CDE,	RBT_RESP,
				RBT_MAT_CAT_CODE,	RBT_AUTH_CRNCY_CDE,	RBT_FILE_HEADER,
				RBT_PRODUCT_TYPE,	RBT_PROCESSOR,		RBT_PROCESSING_CODE,
				RBT_ISO_RESPONSE_CODE,	RBT_SAVE_AREA_AMT,	RBT_ACQ_ICHG_SETL_DAT,
				RBT_ISS_ICHG_SETL_DAT,	RBT_EXTERNAL_DUMP_AMT,	RBT_RECON_FLAG
--Imran 14 Jan 2004
        ,Rbt_ISSBANK_CODE,RBt_ACQBANK_CODE
--Imran 14 Jan 2004
--Imran 11 Feb 2004
        ,Rbt_card_type
--Imran 11 Feb 2004
			FROM REC_BIC_TEMP;

EXCEPTION	--EXCP OF MAIN
WHEN OTHERS THEN
ERRMSG := 'MAIN EXCP --'||SQLERRM;
END;		--END OF MAIN
/


