CREATE OR REPLACE PROCEDURE VMSCMS.SP_DAILY_BIN_BAL (
   PRM_CARD_NO             VARCHAR2,
   PRM_TRAN_DATE    IN     DATE,
   PRM_TRAN_AMT     IN     VARCHAR2,
   PRM_DR_CR_FLAG   IN     VARCHAR2,
   PRM_INST_CODE    IN     VARCHAR2,
   PRM_INS_USER     IN     VARCHAR2,
   PRM_ERR_MSG         OUT VARCHAR2)
IS
   V_CHECK_BIN_DATE     NUMBER;
   V_MAX_CARD_BAL_BIN   NUMBER;
BEGIN
   PRM_ERR_MSG := 'OK';
END;
/

SHOW ERROR