CREATE OR REPLACE PROCEDURE VMSCMS.SP_GEN_GEFU_IBR
    (errmsg	OUT		 VARCHAR2) AS
BEGIN
	ERRMSG := 'OK';
	INSERT INTO REC_GEFU_BASE2ONUS_IBR (SELECT * FROM REC_GEFU_BASE2ONUS_IBR_TEMP);
	DELETE FROM REC_GEFU_BASE2ONUS_IBR_TEMP;
EXCEPTION
WHEN OTHERS THEN
	errmsg := 'Main Excp --'||SQLERRM;
END SP_GEN_GEFU_IBR;
/


