CREATE OR REPLACE PROCEDURE VMSCMS.SP_GEN_MINI_STMT(PRM_INSTCODE IN NUMBER,
									PRM_CARDNO   IN VARCHAR2,
									PRM_TOTREC   OUT NUMBER,
									PRM_STMTDTL  OUT VARCHAR2,
									PRM_ERRMSG   OUT VARCHAR2) IS
  V_TOTREC    NUMBER(2) DEFAULT 0;
  V_RESULTSET VARCHAR2(1000);
  V_HASH_PAN  CMS_APPL_PAN.CAP_PAN_CODE%TYPE;

  CURSOR C IS
    SELECT A.*, ROWNUM
	 FROM (SELECT CSL_PAN_NO,
			    CSL_TRANS_AMOUNT,
			    CSL_TRANS_TYPE,
			    CSL_TRANS_DATE
		    FROM VMSCMS.CMS_STATEMENTS_LOG_VW		--Added for VMS-5733/FSP-991	
		   WHERE CSL_INST_CODE = PRM_INSTCODE AND CSL_PAN_NO = V_HASH_PAN --prm_cardno
		   ORDER BY CSL_TRANS_DATE DESC) A
	WHERE ROWNUM < 11;
BEGIN
  --<<MAIN BEGIN>>
  PRM_ERRMSG := 'OK';
  --SN CREATE HASH PAN 
  BEGIN
    V_HASH_PAN := GETHASH(PRM_CARDNO);
  EXCEPTION
    WHEN OTHERS THEN
	 PRM_ERRMSG := 'Error while converting pan ' ||
				SUBSTR(SQLERRM, 1, 200);
	 RETURN;
  END;
  --EN CREATE HASH PAN

  FOR I IN C LOOP
    V_RESULTSET := V_RESULTSET || TO_CHAR(I.CSL_TRANS_DATE, 'DD/MM') || ' ' ||
			    TO_CHAR(I.CSL_TRANS_DATE, 'HH24:MI') || ' ' ||
			    TO_CHAR(I.CSL_TRANS_AMOUNT, '99999999999999999.99') || ' ' ||
			    I.CSL_TRANS_TYPE || ',';
    V_TOTREC    := V_TOTREC + 1;
  END LOOP;
  PRM_TOTREC  := V_TOTREC;
  PRM_STMTDTL := V_RESULTSET;
EXCEPTION
  --<MAIN EXCEPTION >>
  WHEN OTHERS THEN
    PRM_TOTREC  := 0;
    PRM_STMTDTL := NULL;
    PRM_ERRMSG  := 'Error while generating mini statement ' ||
			    SUBSTR(SQLERRM, 1, 200);
END; --<<MAIN END>>
/
SHOW ERROR;

