CREATE OR REPLACE PROCEDURE VMSCMS.SP_KEY_ROLLBACK(PRM_RESULT OUT VARCHAR2) IS

  /*************************************************
      * Created Date     :  20/03/2012
      * Created By       :  T.Narayanaswamy
      * PURPOSE          :  For Key Rotation - Migration Rollback
      * Reviewer         :  Saravanakumar
      * Reviewed Date    :  20-Apr-2012
      * Build Number     :  CMS3.5.1_RI0008_B00022
  *************************************************/

  V_TABLE_NAME   VARCHAR2(100);
  V_ENCR_COLUMN  VARCHAR2(100);
  V_HASH_COLUMN  VARCHAR2(100);
  V_CURSOR_QUERY VARCHAR2(400);
  V_QUERY        VARCHAR2(400);
  TYPE RC_TAB_1_BY_1_QRY IS REF CURSOR;
  C_TAB_1_BY_1_QRY RC_TAB_1_BY_1_QRY;
  V_ENCR_OLD_VALUE RAW(2000);
  V_COUNT          NUMBER;
  V_ERR_MSG        VARCHAR2(400);
  V_ENCR_NEW_DATA  VARCHAR2(100);
  V_HASH_DATA      VARCHAR2(90);

  CURSOR C_SELECT_TABLE IS
    SELECT CKR_TABLE_NAME, CKR_HASH_COLUMN, CKR_ENCR_COLUMN
	 FROM CMS_KEY_ROTATE_TABLE
	WHERE CKR_ROTATE_FLAG = 'Y';

BEGIN
  PRM_RESULT := 'OK';
  V_ERR_MSG  := 'OK';

  BEGIN
    OPEN C_SELECT_TABLE;
    LOOP
	 FETCH C_SELECT_TABLE
	   INTO V_TABLE_NAME, V_HASH_COLUMN, V_ENCR_COLUMN;
	 EXIT WHEN C_SELECT_TABLE%NOTFOUND;

	 -- V_CURSOR_QUERY := 'SELECT /*+RULE*/ DISTINCT ' || V_ENCR_COLUMN ||
	 /*          ' , ' || V_HASH_COLUMN || ' FROM ' || V_TABLE_NAME ||
      ' WHERE ' || V_ENCR_COLUMN || ' IS NOT NULL' ||
      ' AND  ' || V_HASH_COLUMN || ' IS NOT NULL';*/

	 V_CURSOR_QUERY := 'SELECT DISTINCT ' || V_ENCR_COLUMN || ' , ' ||
				    V_HASH_COLUMN || ' FROM ' || V_TABLE_NAME ||
				    ' WHERE ' || V_ENCR_COLUMN || ' IS NOT NULL' ||
				    ' AND  ' || V_HASH_COLUMN || ' IS NOT NULL';
	 OPEN C_TAB_1_BY_1_QRY FOR V_CURSOR_QUERY;
	 BEGIN
	   LOOP
		FETCH C_TAB_1_BY_1_QRY
		  INTO V_ENCR_NEW_DATA, V_HASH_DATA;
		EXIT WHEN C_TAB_1_BY_1_QRY%NOTFOUND;
		SELECT COUNT(*)
		  INTO V_COUNT
		  FROM CMS_KEY_ROTATE_LOG
		 WHERE CKR_HASH_DATA = V_HASH_DATA;
		IF V_COUNT > 0 THEN

		  -- SELECT /*+RULE*/
		  /* CKR_OLD_DATA
             INTO V_ENCR_OLD_VALUE
             FROM CMS_KEY_ROTATE_LOG
            WHERE CKR_HASH_DATA = V_HASH_DATA;*/

		  SELECT CKR_OLD_DATA
		    INTO V_ENCR_OLD_VALUE
		    FROM CMS_KEY_ROTATE_LOG
		   WHERE CKR_HASH_DATA = V_HASH_DATA;
		  IF (V_ENCR_OLD_VALUE IS NOT NULL) THEN
		    V_QUERY := 'UPDATE ' || V_TABLE_NAME || ' SET ' ||
					V_ENCR_COLUMN || '=''' || V_ENCR_OLD_VALUE ||
					''' WHERE ' || V_HASH_COLUMN || ' IN (''' ||
					V_HASH_DATA || ''')';
		    EXECUTE IMMEDIATE V_QUERY;
		  END IF;
		END IF;
	   END LOOP;
	   V_QUERY := 'UPDATE  CMS_KEY_ROTATE_TABLE SET CKR_ROTATE_FLAG=''N'',CKR_REMARKS=''KEY REVERTED'',CKR_LUPD_USER=1,CKR_LUPD_DATE=:1' ||
			    '  WHERE CKR_TABLE_NAME = ''' || V_TABLE_NAME ||
			    ''' AND CKR_ENCR_COLUMN=''' || V_ENCR_COLUMN || '''';
	   EXECUTE IMMEDIATE V_QUERY
		USING SYSDATE;
	   COMMIT;
	 END;
	 CLOSE C_TAB_1_BY_1_QRY;
    END LOOP;
    CLOSE C_SELECT_TABLE;

  EXCEPTION
    WHEN OTHERS THEN
	 V_ERR_MSG  := 'EXCEPTION WHEN KEY ROLLBACK PROCESS :' || SQLERRM;
	 PRM_RESULT := V_ERR_MSG;
	 ROLLBACK;
  END;
  PRM_RESULT := V_ERR_MSG;
END;
/


