CREATE OR REPLACE PROCEDURE VMSCMS.SP_MANUAL_LOYL_UPDATION_SCRIPT(ERRMSG OUT VARCHAR2)
AS
	CURSOR C1 IS
	SELECT CPC_CUST_CATG ,CPC_PROD_CODE,CPC_CARD_TYPE
	FROM  CMS_PROD_CCC
	WHERE
	--CPC_PROD_CODE = 'VD03'
	CPC_PROD_CODE = 'NA77'
	AND  CPC_CARD_TYPE = 1
	MINUS
	SELECT CPL_CUST_CATG,CPL_PROD_CODE,CPL_CARD_TYPE
	FROM CMS_PRODCCC_LOYL ;
	BEGIN  --Main Begin
	ERRMSG := 'OK' ;
			        UPDATE CMS_PROD_LOYL
				SET CPL_VALID_TO = TO_DATE('31-MAR-2099','DD-MON-YYYY')
				WHERE CPL_PROD_CODE = 'NA77' ;
				UPDATE CMS_PRODCATTYPE_LOYL
				SET CPL_VALID_TO = TO_DATE('31-MAR-2099','DD-MON-YYYY')
				WHERE CPL_PROD_CODE = 'NA77'  AND
				CPL_CARD_TYPE = 1  ;
				UPDATE CMS_PRODCCC_LOYL
				SET CPL_VALID_TO = TO_DATE('31-MAR-2099','DD-MON-YYYY')
				WHERE CPL_PROD_CODE = 'NA77'  AND
				CPL_CARD_TYPE = 1  ;
				FOR Y IN C1
				LOOP
				   INSERT INTO
				   CMS_PRODCCC_LOYL
				   (	CPL_INST_CODE,CPL_CUST_CATG,CPL_CARD_TYPE,CPL_PROD_CODE,CPL_LOYL_CODE,CPL_VALID_FROM,
					CPL_VALID_TO,CPL_FLOW_SOURCE,CPL_INS_USER,CPL_INS_DATE,CPL_LUPD_USER,CPL_LUPD_DATE     )
				   VALUES
				   (
					1,Y.CPC_CUST_CATG,Y.CPC_CARD_TYPE,Y.CPC_PROD_CODE,1,TO_DATE('01-JAN-2003','DD-MON-YYYY'),
					TO_DATE('31-MAR-2099','DD-MON-YYYY'),'P',1,SYSDATE,1,SYSDATE) ;
				END LOOP ;
				UPDATE CMS_PAN_TRANS
				SET CPT_LOYL_CALC='N'
				WHERE
				      --CPT_PROD_CODE = 'VD03' and
				      CPT_PROD_CODE = 'NA77' AND
				      CPT_CARD_TYPE = 1 AND
				      TRUNC(CPT_TRANS_DATE) > TRUNC(TO_DATE('30-JUN-2004','DD-MON-YYYY')) AND
				      CPT_LOYL_CALC = 'E'  ;
	EXCEPTION
	WHEN OTHERS THEN
	ERRMSG := 'ERROR : '||SQLERRM ;
	END ;
/
SHOW ERRORS

