CREATE OR REPLACE PROCEDURE VMSCMS.Sp_Ptlf_Split(INS_USER IN NUMBER,    ERRMSG    OUT        VARCHAR2)
AS
V_RPT_MER_FIID VARCHAR2(4) := 'ECOM' ;
CURSOR C1 IS SELECT RPT_AMT_1 ,RPT_AMT_2,ROWID FROM REC_PTLF_TEMP ;
C_AMT_CHK    NUMBER(15);

	--Imran cursor for reversal
	CURSOR c_Rev IS SELECT RPT_SEQ_NUM,rpt_CRD_NUM,RPT_AMT_1, RPT_REC_TYP,RPT_RVSL_FLAG,ROWID FROM REC_PTLF_TEMP WHERE RPT_RVRL_CDE <> '00'
	AND rpt_RESP_CDE IN ('000','001');

	--Sivakaminathan cursor for balance amount updatation
	CURSOR C_Bal_Amt_Upt IS SELECT RPT_CRD_NUM,decode(rpT_TYP,'0210',RPT_AMT_1,(-1)*rpt_amt_1)RPT_AMT_1,ROWID
  FROM REC_PTLF_TEMP where RPT_RESP_CDE IN ('000','001');

	c_Rowid ROWID;
	c_No_trans NUMBER(5);

BEGIN        --MAIN BEGIN
ERRMSG := 'OK';
/*
	UPDATE REC_PTLF_TEMP
	SET RPT_CRD_FIID=SUBSTR(RPT_ACCT,1,4)
	WHERE RPT_CRD_FIID IN (SELECT DISTINCT RBM_BRAN_FIID FROM REC_HOST_BRAN_MAST
	WHERE RBM_HOST_CODE='1');


	--UPDATING TERM_FIID FOR IFLEX BRANCHES
	UPDATE REC_PTLF_TEMP
	SET RPT_TERM_FIID=SUBSTR(RPT_TERM_ID,6,4)
	WHERE SUBSTR(TO_NUMBER(RPT_ACQ_INST_ID_NUM),1,6) IN (SELECT DISTINCT TO_CHAR
	(CBM_INST_BIN) FROM CMS_BIN_MAST);
  */


	FOR C IN C1 LOOP
	BEGIN
	--            C_AMT_CHK    :=  TO_NUMBER(C.RTT_AMT2_ACTUAL);
	C_AMT_CHK    :=  TO_NUMBER(C.RPT_AMT_2);
	EXCEPTION
	WHEN VALUE_ERROR THEN
		UPDATE REC_PTLF_TEMP
		--                SET RTT_AMT2_ACTUAL=0
		SET RPT_AMT_2=0
		WHERE ROWID=C.ROWID;
		END;
		BEGIN

		C_AMT_CHK    :=  TO_NUMBER(C.RPT_AMT_1);
		EXCEPTION
		WHEN VALUE_ERROR THEN
			UPDATE REC_PTLF_TEMP
			SET RPT_AMT_1=0
			WHERE ROWID=C.ROWID;
		END;


	--- This is done, bcos ARN needs to be updated into cms_pan_trans
	--- table, which is done by an update qry in sp_base2_recon_process
	UPDATE REC_PTLF_TEMP
	SET rpt_id_col = TO_CHAR(SYSDATE,'YYYY')||LPAD(seq_pan_trans.NEXTVAL,10,0) WHERE ROWID=C.ROWID;
	--- END - T.Karthikeyan on 9th Feb 04 for KVB - Dispute module
END LOOP;

--DELETING TRAN OTHER THAN CASH WDL AND BAL ENQ

DELETE FROM REC_PTLF_TEMP
WHERE RPT_TC NOT IN ('10','15');

--AMT2 IS MEANINGFUL IN CASE OF REVERSAL
UPDATE REC_PTLF_TEMP
SET RPT_AMT_2=0
WHERE RPT_RVRL_CDE  = '00';

--Set all normal msg type as 0210, (0200,0100,0110 to 0210)
UPDATE REC_PTLF_TEMP
SET RPT_TYP = '0210'

WHERE RPT_TYP = '0200' OR
SUBSTR(RPT_TYP,1,2) = '01';
--END ..SUBHASHINI 20 JAN 2004

UPDATE    REC_PTLF_TEMP SET RPT_TYP = '0420',RPT_RVSL_FLAG='F'
WHERE    RPT_RVRL_CDE  <> '00' AND RPT_RESP_CDE IN ('000','001');

UPDATE REC_PTLF_TEMP SET RPT_RVSL_FLAG='P',RPT_AMT_1=TO_NUMBER(RPT_AMT_1)-TO_NUMBER(RPT_AMT_2)
WHERE TO_NUMBER(RPT_AMT_1)!=TO_NUMBER(RPT_AMT_2) AND RPT_RVRL_CDE!='00' AND TO_NUMBER(RPT_AMT_2)>0 AND RPT_RESP_CDE IN ('000','001');

dbms_output.put_line('chk pt 8 '||errmsg);

FOR C IN c_Rev LOOP
BEGIN
SELECT MAX(ROWID), COUNT(*)  INTO c_Rowid , c_No_trans FROM REC_PTLF_TEMP
WHERE RPT_SEQ_NUM  = C.RPT_SEQ_NUM AND RPT_TYP = '0210'
AND RPT_REC_TYP  = C.RPT_REC_TYP AND RPT_CRD_NUM = C.RPT_CRD_NUM AND RPT_RESP_CDE IN ('000','001');

IF c_No_trans >= 1 THEN

UPDATE REC_PTLF_TEMP SET RPT_RVSL_FLAG = C.RPT_RVSL_FLAG WHERE ROWID = c_Rowid;

ELSE
UPDATE REC_PTLF_TEMP SET RPT_RVSL_FLAG = 'O' WHERE ROWID = c.ROWID;
END IF;

END;
END LOOP;

FOR C IN C_Bal_Amt_Upt LOOP
BEGIN
UPDATE CMS_ACCT_MAST
SET CAM_ACCT_BAL = (CAM_ACCT_BAL - C.RPT_AMT_1)
WHERE CAM_ACCT_NO =C.RPT_CRD_NUM;

IF SQL%ROWCOUNT = 1
THEN
UPDATE REC_PTLF_TEMP
SET RPT_ERR_FLAG='Y'
WHERE ROWID=C.ROWID;
ELSE
UPDATE REC_PTLF_TEMP
SET RPT_ERR_FLAG='E'
WHERE ROWID=C.ROWID;
END IF;
EXCEPTION
WHEN OTHERS
THEN
UPDATE REC_PTLF_TEMP
SET RPT_ERR_FLAG='E'
WHERE ROWID=C.ROWID;

END;

END LOOP;

INSERT INTO CMS_PAN_TRANS(
CPT_INST_CODE        ,CPT_ID_COL         ,CPT_AUTH_CODE        ,CPT_ARN_CODE   ,
CPT_MESG_TYPE        ,CPT_TRANS_TYPE        ,CPT_TRANS_CODE        ,CPT_REC_TYP    ,
CPT_TRANS_DATE      ,CPT_TRANS_TIME        ,CPT_TRANS_AMT        ,CPT_ACQ_BANK   ,
CPT_TERM_ID            ,CPT_MCC_CODE        ,CPT_MERC_ID        ,CPT_MBR_NUMB    ,
CPT_ACCT_NO            ,CPT_PAN_CODE        ,CPT_LOYL_CALC      ,CPT_LOYL_CALCDATE    ,
CPT_INS_USER        ,CPT_LUPD_USER        ,CPT_INS_DATE       ,CPT_LUPD_DATE        ,
CPT_ADDON_LINK        ,CPT_MBR_LINK        ,CPT_ADDON_STAT        ,CPT_PROD_CODE,

CPT_CARD_TYPE        ,CPT_CUST_CODE        ,CPT_CUST_CATG
)
SELECT
1                                ,RPT_ID_COL                                ,RPT_APPRV_CDE            ,NULL            ,
RPT_TYP                            ,DECODE(RPT_TERM_LN,'ELEC','1','0')        ,RPT_TC
,'02'            ,

TO_DATE(RPT_TRAN_DAT ,'YYMMDD') ,Fn_Conv_Char_To_Date(RPT_TRAN_DAT,RPT_TRAN_TIM  )    ,

TO_NUMBER(RPT_AMT_1)/100        , ' '                                    ,SUBSTR(RPT_TERM_ID,1,12),' '        ,



' '                                , RPT_MBR_NUM    ,RPT_ACCT    ,TRIM(RPT_CRD_NUM)        ,'N'            ,
NULL        ,'1'        ,'1'    ,SYSDATE        ,
SYSDATE         ,
--CAP_ADDON_LINK        ,CAP_MBR_LINK     ,CAP_ADDON_STAT    ,CAP_PROD_CODE,
--CAP_CARD_TYPE        ,CAP_CUST_CODE     ,CAP_CUST_CATG
NULL,NULL,NULL,'UPD_ME','99',NULL,NULL
FROM REC_PTLF_TEMP  --, CMS_APPL_PAN  --** commented to avoid delay over db link
WHERE
SUBSTR(RPT_CRD_NUM,1,6) IN (SELECT TO_CHAR(CBM_INST_BIN) FROM CMS_BIN_MAST)

--      AND RPT_TYP='0210'
AND RPT_RESP_CDE IN ('000','001')
AND RPT_TC  IN( '10','15');

--AND CAP_PAN_CODE=RPT_CRD_NUM ;
--END OF INSERTION BY SUBHASHINI

insert into CMS_PTLF_EXTRACTION (SELECT * FROM REC_PTLF_TEMP);

insert into CMS_PTLF_TIP_TRANS (SELECT RPT_CRD_NUM,RPT_AMT_1,RPT_TERM_ID, RPT_TERM_OWNER_NAME,RPT_SEQ_NUM, RPT_TRAN_DAT,RPT_ACQ_INST_ID_NUM,RPT_RESP_CDE,RPT_TRAN_TIM,'N',INS_USER,SYSDATE,INS_USER,sysdate  FROM REC_PTLF_TEMP);

EXCEPTION    --EXCP OF MAIN
WHEN OTHERS THEN
ERRMSG := 'MAIN EXCP --'||SQLERRM;
END;        --END OF MAIN
/


