CREATE OR REPLACE PROCEDURE VMSCMS.SP_UPDATE_RESPONSE
(
MSGTRACEID IN NUMBER,
RESPONSECODE IN VARCHAR2,
RESPMSGID IN NUMBER,
ERRORCODE OUT NUMBER,
ERRORDESC OUT VARCHAR2
)
AS
BEGIN
	BEGIN
		UPDATE FHM_RESP_TMP SET FRT_TRACE_ID= MSGTRACEID,FRT_RESP_CODE=RESPONSECODE WHERE FRT_MSG_ID=RESPMSGID;
	EXCEPTION
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-20001,'ERROR IN UPDATING THE RESPONSE TEMPORARY TABLE');
	END;
	BEGIN
		INSERT INTO FHM_MSG_LOG(FML_MSG_ID, FML_TRACE_ID, FML_CARD_NO, FML_REQ_MSG, FML_REQ_DATE_TIME, FML_REQ_ATTMPT,FML_RES_MSG, FML_RES_DATE_TIME,  FML_MSG_TYPE, FML_FUNC_CODE, FML_RESP_CODE)
		(SELECT FSM_MSG_ID, FSM_TRACE_ID, FSM_CARD_NO, FSM_ISO_MSG, FSM_REQ_DATE_TIME, FSM_REQ_ATTMPT,
	FRT_ISO_MSG, FRT_UPD_DATE, FRT_MSG_TYPE, FRT_FUNC_CODE, FRT_RESP_CODE
	FROM FHM_SENT_MSGS SENT, FHM_RESP_TMP RESP
	WHERE SENT.FSM_TRACE_ID = RESP.FRT_TRACE_ID
	AND  FRT_TRACE_ID = MSGTRACEID);
	EXCEPTION
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-20001,'ERROR IN LOGGING THE TRANSACTION');
	END;
	BEGIN
	     DELETE FROM FHM_SENT_MSGS WHERE FSM_TRACE_ID  = MSGTRACEID;
	     DELETE FROM FHM_RESP_TMP WHERE FRT_TRACE_ID  = MSGTRACEID;
        EXCEPTION
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-20001,'ERROR CLEANUP OF TEMPORARY TABLES');
	END;
EXCEPTION
WHEN OTHERS THEN
ERRORCODE:=SQLCODE;
ERRORDESC:=SQLERRM;
END;
/


SHOW ERRORS