CREATE OR REPLACE PROCEDURE VMSCMS.SP_UPDATE_CARDPOSN(ACCT_ID VARCHAR2,PAN VARCHAR2,ERRMSG OUT VARCHAR2)
AS
	C_CATG_CDE VARCHAR2(1);
	C_ID VARCHAR2(25);
	C_POSITION  NUMBER(5);
BEGIN
	ERRMSG:= 'OK';

	-- FIND  CATAGARY OF INSERTED ROW
	SELECT CAP_CATG_CODE ,CMS_PAN_ACCT.ROWID INTO C_CATG_CDE , C_ID FROM CMS_APPL_PAN,CMS_PAN_ACCT
	WHERE CAP_MBR_NUMB = CPA_MBR_NUMB AND CAP_PAN_CODE = CPA_PAN_CODE
	AND CAP_CUST_CODE = CPA_CUST_CODE AND CAP_ACCT_ID = CPA_ACCT_ID
	AND CPA_ACCT_ID= ACCT_ID AND CPA_PAN_CODE = PAN
	AND CPA_CARD_POSN = 0;

	IF C_CATG_CDE = 'D' THEN
		-- FIND MAX POSTION FOR DEBIT CARD
		SELECT NVL(MAX(CPA_CARD_POSN),0) +1 INTO C_POSITION FROM CMS_PAN_ACCT
		WHERE ROWID IN
		(SELECT CMS_PAN_ACCT.ROWID FROM CMS_APPL_PAN,CMS_PAN_ACCT
		WHERE CAP_MBR_NUMB = CPA_MBR_NUMB AND CAP_CUST_CODE = CPA_CUST_CODE
		AND CAP_ACCT_ID = CPA_ACCT_ID AND CPA_ACCT_ID= ACCT_ID  AND CAP_CATG_CODE = 'D');

		-- SET POSITION FOR DEBIT CARD
		UPDATE CMS_PAN_ACCT SET CPA_CARD_POSN = C_POSITION WHERE ROWID = TRIM(C_ID);

		-- SET POSITON FOR ATM CARD
		UPDATE CMS_PAN_ACCT SET CPA_CARD_POSN = CPA_CARD_POSN +1
		WHERE CPA_CARD_POSN >= C_POSITION AND ROWID <> C_ID
		AND CPA_ACCT_ID = ACCT_ID ;

	ELSE
		-- SELECT MAX OF CARD POSITION AND  UPDATE SAME VALUE FOR NEW INSERTED ROW
		SELECT NVL(MAX(CPA_CARD_POSN),0) +1 INTO C_POSITION FROM CMS_PAN_ACCT WHERE CPA_ACCT_ID = ACCT_ID ;
		UPDATE CMS_PAN_ACCT SET CPA_CARD_POSN = C_POSITION WHERE ROWID = TRIM(C_ID);
	END IF;

EXCEPTION
WHEN OTHERS THEN
	ERRMSG:= 'Main Exc........'|| SQLERRM;
END;
/


