CREATE INDEX VMSCMS.AGGR_FUNC_LEVELS_FK_IDX ON VMSCMS.DMRS_AGGR_FUNC_LEVELS
(AGGREGATE_FUNCTION_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


