CREATE INDEX VMSCMS.CHANGE_REQUESTS_PK_IDX ON VMSCMS.DMRS_CHANGE_REQUESTS
(CHANGE_REQUEST_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


