CREATE UNIQUE INDEX VMSCMS.CMS_CALLID_MAST_PK ON VMSCMS.CMS_CALLLOG_MAST
(CCM_INST_CODE, CCM_PAN_CODE, CCM_CALL_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


