CREATE UNIQUE INDEX VMSCMS.CMS_PROD_CATSEC_U01 ON VMSCMS.CMS_PROD_CATSEC
(CPC_INST_CODE, CPC_PROD_CODE, CPC_SEC_CODE, CPC_CARD_TYPE, CPC_TRAN_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


