CREATE UNIQUE INDEX VMSCMS.CMS_EMV_PARAM_TEMP_PK ON VMSCMS.CMS_EMV_PARAM_TEMP
(CEP_INST_CODE, CEP_ROWID, CEP_INST_BIN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


