CREATE INDEX VMSCMS.CONTACT_RES_LOCATORS_FK1_IDX ON VMSCMS.DMRS_CONTACT_RES_LOCATORS
(CONTACT_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


