CREATE INDEX VMSCMS.DFD_INFOS_FK1_IDX ON VMSCMS.DMRS_DATA_FLOW_DIAGRAM_INFOS
(DIAGRAM_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


