CREATE INDEX VMSCMS.DIAGRAM_ELEMENTS_FK_IDX ON VMSCMS.DMRS_DIAGRAM_ELEMENTS
(DIAGRAM_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


