CREATE INDEX VMSCMS.DIMENSION_CALC_ATTRS_FK_IDX ON VMSCMS.DMRS_DIMENSION_CALC_ATTRS
(DIMENSION_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


