CREATE INDEX VMSCMS.DMRS_COLL_TYPES_PK_IDX ON VMSCMS.DMRS_COLLECTION_TYPES
(COLLECTION_TYPE_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


