CREATE INDEX VMSCMS.DOCUMENT_ELEMENTS_FK2_IDX ON VMSCMS.DMRS_DOCUMENT_ELEMENTS
(ELEMENT_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


