CREATE INDEX VMSCMS.EVENTS_FK_MODEL_IDX ON VMSCMS.DMRS_EVENTS
(MODEL_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


