CREATE INDEX VMSCMS.EXT_DATAS_PK_IDX ON VMSCMS.DMRS_EXTERNAL_DATAS
(EXTERNAL_DATA_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


