CREATE UNIQUE INDEX VMSCMS.FHM_MSG_DE_UNIQ ON VMSCMS.FHM_MSG_DE
(FMD_MSG_TYPE, FMD_FUNC_CODE, FMD_DE_CODE, FMD_SUB_DE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


