CREATE INDEX VMSCMS.FLOWS_FK_DIAGRAM_IDX ON VMSCMS.DMRS_FLOWS
(DIAGRAM_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


