CREATE UNIQUE INDEX VMSCMS.FML_MSG_ID_PK ON VMSCMS.FHM_MSG_LOG
(FML_MSG_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


