CREATE UNIQUE INDEX VMSCMS.FPM_PRM_ID_PK ON VMSCMS.FHM_PRM_MAST
(FPM_PRM_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


