CREATE UNIQUE INDEX VMSCMS.FRI_MSG_ID_PK ON VMSCMS.FHM_RES_INFO
(FRI_MSG_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


