CREATE UNIQUE INDEX VMSCMS.FRM_FUNC_ID_PK ON VMSCMS.FHM_REQ_MAST
(FRM_FUNC_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


