CREATE UNIQUE INDEX VMSCMS.FSM_MSG_ID_PK ON VMSCMS.FHM_SENT_MSGS
(FSM_MSG_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


