CREATE UNIQUE INDEX VMSCMS.FTP_TEMP_ID_PK ON VMSCMS.FHM_TEMP_PRM_MAST
(FTP_TEMP_ID, FTP_FIELD_POS, FTP_SUB_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


