CREATE INDEX VMSCMS.GWD_DAY_NAME_IDX ON VMSCMS.GEN_WEEK_DAYS
(GWD_DAY_NAME)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


