CREATE UNIQUE INDEX VMSCMS.HCM_NUMBER_UQ ON VMSCMS.HSM_CONFIG_MASTER
(HCM_INST_CODE, HCM_NUMBER, HSM_PROCESS)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


