CREATE INDEX VMSCMS.HIERARCHY_ROLLUP_LINKS_FK2_IDX ON VMSCMS.DMRS_HIERARCHY_ROLLUP_LINKS
(ROLLUP_LINK_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


