CREATE INDEX VMSCMS.IDX_INST_FTYP_REFNUM ON VMSCMS.CMS_FILEUPLOAD_DETL
(CFU_INST_CODE, CFU_FILE_TYPE, CFU_REF_NUMBER)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


