CREATE INDEX VMSCMS.IDX_CPS_SPPRT_KEY ON VMSCMS.CMS_PAN_SPPRT
(CPS_SPPRT_KEY)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


