CREATE INDEX VMSCMS.IND_PCC_PAN_NO_MER ON VMSCMS.CMS_MERCHANT_CARDS
(PCC_PAN_NO)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


