CREATE INDEX VMSCMS.IND_TRANVERIFY ON VMSCMS.CMS_TRANSACTION_VERIFICATIONS
(CTV_TXN_CODE, CTV_MSG_TYPE, CTV_SHORT_NAME, CTV_REVERSAL_CODE, CTV_INST_CODE, 
CTV_INST_BIN, CTV_DELIVERY_CHANEL)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          896K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


