CREATE INDEX VMSCMS.IND_BINAUTHPRC_INSTCDBIN ON VMSCMS.CMS_BINAUTH_PROCESS
(CBP_INST_CODE, CBP_BIN)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


