CREATE INDEX VMSCMS.IND_CPT_PAN_CODE_ATM ON VMSCMS.CMS_PAN_TRANS_ATM
(CPT_PAN_CODE)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


