CREATE INDEX VMSCMS.IND_PREAUTH ON VMSCMS.CMS_PREAUTH_TRANSACTION
(CPT_CARD_NO, CPT_EXPIRY_FLAG, CPT_INST_CODE, CPT_EXPIRY_DATE, CPT_TOTALHOLD_AMT)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


