CREATE INDEX VMSCMS.IND_CGA_CARD_NO ON VMSCMS.CMS_GROUP_ACCTLINK_TEMP
(CGA_CARD_NO)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


