CREATE INDEX VMSCMS.IND_CFM_PAN_CODE ON VMSCMS.CMS_FUNDTRANSFER_MAST
(CFM_PAN_CODE)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


