CREATE INDEX VMSCMS.IND_TRANPROP ON VMSCMS.CMS_TXN_PROPERTIES
(CTP_TXN_CODE, CTP_INST_CODE, CTP_REVERSAL_CODE, CTP_MSG_TYPE, CTP_DELIVERY_CHANNEL)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


