CREATE INDEX VMSCMS.IND_CMW_PAN_NO ON VMSCMS.CMS_MERC_WALLET
(CMW_PAN_NO)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


