CREATE INDEX VMSCMS.IND_TXNLOG_DELCHNL ON VMSCMS.TRANSACTIONLOG
(DELIVERY_CHANNEL)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


