CREATE INDEX VMSCMS.IND_PAN_EMB ON VMSCMS.CMS_APPL_PAN
(CAP_PROD_CODE, CAP_APPL_BRAN)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


