CREATE INDEX VMSCMS.IND_CLA_PAN_CODE_LOYL ON VMSCMS.CMS_LOYL_AUDIT
(CLA_PAN_CODE)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


