CREATE INDEX VMSCMS.IND_CCC_FROM_CARD ON VMSCMS.CMS_CARDFNDSTRANS_COUNTER
(CCC_FROM_CARD)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


