CREATE INDEX VMSCMS.IND_BRCNT_CD ON VMSCMS.BRANCH_CNT
(CAP_APPL_BRAN)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


