CREATE INDEX VMSCMS.IND_RRNBDATETIME ON VMSCMS.TRANSACTIONLOG
(RRN, BUSINESS_DATE, MSGTYPE, BUSINESS_TIME, TXN_CODE, 
DELIVERY_CHANNEL)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          14M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


