CREATE INDEX VMSCMS.IND_CGT_CARD_NO_GRP_TEMP ON VMSCMS.CMS_GROUP_REGENPIN_TEMP
(CGT_CARD_NO)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


