CREATE INDEX VMSCMS.IND_AUDITRIAL_OBJNAME ON VMSCMS.CMS_AUDIT_TRAIL
(CAT_OBJECT_NAME)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          6M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


