CREATE INDEX VMSCMS.IND_CKR_HASH_DATA ON VMSCMS.CMS_KEY_ROTATE_LOG
(CKR_HASH_DATA)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


