CREATE INDEX VMSCMS.IND_CTD_CUSTOMER_CARD_NO ON VMSCMS.CMS_TRANSACTION_LOG_DTL
(CTD_CUSTOMER_CARD_NO)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          20M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


