CREATE INDEX VMSCMS.IND_CSL_PAN_NO_LOG ON VMSCMS.CMS_STATEMENT_LOG
(CSL_PAN_NO)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


