CREATE INDEX VMSCMS.IND_KYC_SEARCH ON VMSCMS.CMS_CAF_INFO_ENTRY
(CCI_KYC_FLAG, CCI_SEG12_NAME_LINE1, CCI_SEG12_NAME_LINE2, CCI_SSN, CCI_PAN_CODE, 
CCI_UPLD_STAT, CCI_APPROVED)
TABLESPACE CMS_BIG_IDX
/


