CREATE INDEX VMSCMS.IND_CCI_PAN_CODE_ERROR ON VMSCMS.CMS_CARDBASE_PERM_ERRORS
(CCI_PAN_CODE)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


