CREATE INDEX VMSCMS.IND_CKR_TABLE_NAME ON VMSCMS.CMS_KEY_ROTATE_TABLE
(CKR_TABLE_NAME)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


