CREATE INDEX VMSCMS.IND_CRD_CARD_NO_RENEW ON VMSCMS.CMS_RENEW_DETAIL
(CRD_CARD_NO)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


