CREATE INDEX VMSCMS.IND_PAL_NEW_CARD ON VMSCMS.PROCESS_AUDIT_LOG
(PAL_NEW_CARD)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


