CREATE INDEX VMSCMS.IND_CCI_CARD_NUMBER ON VMSCMS.CMS_CAF_INFO_AUDIT
(CCI_CARD_NUMBER)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


