CREATE INDEX VMSCMS.IND_CLD_ADDON_PAN ON VMSCMS.CMS_LOYL_DTL
(CLD_ADDON_PAN)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


