CREATE INDEX VMSCMS.IND_CEL_PAN_CODE_ERR ON VMSCMS.CMS_PERM_ERR_CARDBASE
(CEL_PAN_CODE)
LOGGING
TABLESPACE CMS_BIG_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


