CREATE INDEX VMSCMS.INDEX_MONTHWISELOYL_ACCTNO ON VMSCMS.CMS_MONTHWISE_LOYL
(CML_ACCT_NO)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


