CREATE INDEX VMSCMS.INDX_PANACCT_INSTACCT ON VMSCMS.CMS_PAN_ACCT
(CPA_INST_CODE, CPA_ACCT_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


