CREATE INDEX VMSCMS.INDX_CAFINFO_INSTFILEGEN ON VMSCMS.CMS_CAF_INFO
(CCI_INST_CODE, CCI_FILE_GEN)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


