CREATE INDEX VMSCMS.INDX_GRPHOTREISSUEPIN ON VMSCMS.CMS_GROUP_HOTREISSUE
(CGH_PIN_HOTREISSUE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


