CREATE INDEX VMSCMS.INDX_CAFINFO_TEMP ON VMSCMS.CMS_CAF_INFO_TEMP
(CCI_FILE_NAME, CCI_ROW_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


