CREATE INDEX VMSCMS.INDX_APPLPAN_PANGENDATE ON VMSCMS.CMS_APPL_PAN
(CAP_INST_CODE, CAP_PANGEN_DATE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


