CREATE INDEX VMSCMS.INDX_CBA_USERPIN ON VMSCMS.CMS_BULK_ACTIVITY_REPORT
(CBA_USER_PIN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


