CREATE INDEX VMSCMS.INDX_PRODCCC_SHORTNAME ON VMSCMS.CMS_PROD_CCC
(CPC_PROD_SNAME)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


