CREATE INDEX VMSCMS.INDX_GRPREISSUEPIN ON VMSCMS.CMS_GROUP_REISSUE
(CGR_PIN_REISSUE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


