CREATE INDEX VMSCMS.INDX_PURGEREC_PURGEFLAG ON VMSCMS.CMS_PURGE_REC
(CPR_PURGE_FLAG)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


