CREATE INDEX VMSCMS.INDX_PANTRANS_INSTPAN ON VMSCMS.CMS_PAN_TRANS
(CPT_INST_CODE, CPT_PAN_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


