CREATE INDEX VMSCMS.INDX_CUSTMAST_FIRSTNAME ON VMSCMS.CMS_CUST_MAST
(CCM_INST_CODE, CCM_FIRST_NAME)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


