CREATE INDEX VMSCMS.INDX_PRODCCCFEES_COMBINED ON VMSCMS.CMS_PRODCCC_FEES
(CPF_INST_CODE, CPF_PROD_CODE, CPF_CARD_TYPE, CPF_CUST_CATG)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


