CREATE INDEX VMSCMS.INDX_CARD_DENOMINATION ON VMSCMS.CMS_REQUEST_INVENTORY
(CRI_CARD_DENIOMINATION)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


