CREATE INDEX VMSCMS.INDX_CAFINFOTEMP_FIID ON VMSCMS.CMS_CAF_INFO_TEMP
(CCI_FIID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


