CREATE INDEX VMSCMS.INDX_APPLPAN_INSTACCTNO ON VMSCMS.CMS_APPL_PAN
(CAP_INST_CODE, CAP_ACCT_NO)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          384K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


