CREATE INDEX VMSCMS.INDX_PANSPPRT_PANCODE ON VMSCMS.CMS_PAN_SPPRT
(CPS_PAN_CODE)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          704K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


