CREATE INDEX VMSCMS.INFO_STORES_PK_IDX ON VMSCMS.DMRS_INFO_STORES
(INFO_STORE_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


