CREATE INDEX VMSCMS.LEVEL_ATTRS_FK_IDX ON VMSCMS.DMRS_LEVEL_ATTRS
(LEVEL_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


