CREATE INDEX VMSCMS.LOGICAL_TO_NATIVE_FK_IDXV1 ON VMSCMS.DMRS_LOGICAL_TO_NATIVE
(LOGICAL_TYPE_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


