CREATE UNIQUE INDEX VMSCMS.MCCODEGROUP ON VMSCMS.MCCODE_GROUP
(MCCODE, MCCODEGROUPID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


