CREATE INDEX VMSCMS.MEASURES_PK_IDX ON VMSCMS.DMRS_MEASURES
(MEASURE_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


