CREATE INDEX VMSCMS.MODEL_NAMING_OPTIONS_FK_IDX ON VMSCMS.DMRS_MODEL_NAMING_OPTIONS
(MODEL_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


