CREATE INDEX VMSCMS.MODEL_DISPLAYS_PK_IDX ON VMSCMS.DMRS_MODEL_DISPLAYS
(DISPLAY_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


