CREATE UNIQUE INDEX VMSCMS.P_BATCH_ID ON VMSCMS.CMS_EMBOSS_BATCH_STATUS
(EBS_BATCH_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


