CREATE UNIQUE INDEX VMSCMS.PK1 ON VMSCMS.CMS_RESPONSE_MAST
(CMS_INST_CODE, CMS_DELIVERY_CHANNEL, CMS_RESPONSE_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


