CREATE UNIQUE INDEX VMSCMS.PK__CONV_CURRPAIR_MA__316EE0E7 ON VMSCMS.CONV_CURRPAIR_MAST
(CCM_INST_CODE, CCM_UNIQUE_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


