CREATE UNIQUE INDEX VMSCMS.PK_APPL_NO ON VMSCMS.CMS_GIROAPPL_FORMAT
(CAD_APPL_NUM)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


