CREATE UNIQUE INDEX VMSCMS.PK_ACCT_STAT ON VMSCMS.CMS_ACCT_STAT
(CAS_INST_CODE, CAS_STAT_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


