CREATE UNIQUE INDEX VMSCMS.PK_AGENCY_MAST ON VMSCMS.CMS_AGENCY_MAST
(CAM_AGENCY_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


