CREATE UNIQUE INDEX VMSCMS.PK_ACCT_TYPE ON VMSCMS.CMS_ACCT_TYPE
(CAT_INST_CODE, CAT_TYPE_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


