CREATE UNIQUE INDEX VMSCMS.PK_ASSO_MAST ON VMSCMS.CMS_ASSO_MAST
(CAM_INST_CODE, CAM_ASSO_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


