CREATE UNIQUE INDEX VMSCMS.PK_ADDR_MERCMAST ON VMSCMS.CMS_MERC_ADDR_MAST
(CAM_INST_CODE, CAM_ADDR_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


