CREATE UNIQUE INDEX VMSCMS.PK_BATCHUPLOAD_PARAM ON VMSCMS.CMS_BATCHUPLOAD_PARAM
(CBP_INST_CODE, CBP_PARAM_KEY, CBP_PARAM_VALUE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


