CREATE UNIQUE INDEX VMSCMS.PK_BRANCHTYPE_MAST ON VMSCMS.CMS_BRANCH_TYPE
(CBT_INST_CODE, CBT_TYPE_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


