CREATE UNIQUE INDEX VMSCMS.PK_BIN_SCHEME ON VMSCMS.CMS_BIN_SCHEME
(CBS_INST_CODE, CBS_INST_BIN)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


