CREATE UNIQUE INDEX VMSCMS.PK_BATCH_PIN ON VMSCMS.CMS_BATCH_PIN
(CBP_FILE_NAME, CBP_PAN_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


