CREATE UNIQUE INDEX VMSCMS.PK_BIN_LEVEL_CONFIG ON VMSCMS.CMS_BIN_LEVEL_CONFIG
(CBL_INST_CODE, CBL_INST_BIN)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


