CREATE UNIQUE INDEX VMSCMS.PK_BIN_MAST ON VMSCMS.CMS_BIN_MAST
(CBM_INST_CODE, CBM_INST_BIN)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


