CREATE UNIQUE INDEX VMSCMS.PK_CFD_FILE_ID ON VMSCMS.CMS_FILE_DEFIN_MAST
(CFD_FILE_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


