CREATE UNIQUE INDEX VMSCMS.PK_CUST_MAST ON VMSCMS.CMS_CUST_MAST
(CCM_INST_CODE, CCM_CUST_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


