CREATE UNIQUE INDEX VMSCMS.PK_CUST_GROUP ON VMSCMS.CMS_CUST_GROUP
(CCG_INST_CODE, CCG_GROUP_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


