CREATE UNIQUE INDEX VMSCMS.PK_CRP_INST_PROG_ROLE ON VMSCMS.CMS_ROLE_PROG
(CRP_INST_CODE, CRP_PROG_CODE, CRP_ROLE_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


