CREATE UNIQUE INDEX VMSCMS.PK_CSG_GL_CODE ON VMSCMS.CMS_SUB_GL_MAST
(CSM_GL_CODE, CSM_GLCATG_CODE, CSM_SUBGL_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


