CREATE UNIQUE INDEX VMSCMS.PK_CMS_MERINV_LOCATION ON VMSCMS.CMS_MERINV_LOCATION
(CML_INST_CODE, CML_MER_ID, CML_LOCATION_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


