CREATE UNIQUE INDEX VMSCMS.PK_CNTRYCODE_RULEGROUP ON VMSCMS.CMS_CNTRYCODE_RULEGRP
(CCR_CNTRY_GRPCODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


