CREATE UNIQUE INDEX VMSCMS.PK_CBD_REL ON VMSCMS.CMS_CBD_REL
(CCR_INST_CODE, CCR_ASSO_CODE, CCR_INST_TYPE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


