CREATE UNIQUE INDEX VMSCMS.PK_CNTRYCDE_CNTRYGRP ON VMSCMS.CMS_CNTRYGRP_CNTRYCODE
(CCC_CNTRY_GRPCODE, CCC_CNTRY_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


