CREATE UNIQUE INDEX VMSCMS.PK_CGR_GROUPROLE_CODE ON VMSCMS.CMS_GROUP_ROLE
(CGR_INST_CODE, CGR_GRUP_CODE, CGR_ROLE_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


