CREATE UNIQUE INDEX VMSCMS.PK_CAF_INFO ON VMSCMS.CMS_CAF_INFO
(CCI_INST_CODE, CCI_PAN_CODE, CCI_MBR_NUMB)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


