CREATE UNIQUE INDEX VMSCMS.PK_CPM_INST_PROG ON VMSCMS.CMS_PROGDETL_MAST
(CPM_INST_CODE, CPM_PROG_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


