CREATE UNIQUE INDEX VMSCMS.PK_CITY_MAST ON VMSCMS.GEN_CITY_MAST
(GCM_INST_CODE, GCM_CNTRY_CODE, GCM_CITY_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


