CREATE UNIQUE INDEX VMSCMS.PK_CRM_ROLE_CODE ON VMSCMS.CMS_ROLE_MAST
(CRM_INST_CODE, CRM_ROLE_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


