CREATE UNIQUE INDEX VMSCMS.PK_CMS_MERINV_MAST ON VMSCMS.CMS_MERINV_MAST
(CMM_INST_CODE, CMM_MER_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


