CREATE UNIQUE INDEX VMSCMS.PK_CMS_STOCK_INVENTORY ON VMSCMS.CMS_STOCK_INVENTORY
(CSI_STOCKREF_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


