CREATE UNIQUE INDEX VMSCMS.PK_CARDSTATUS_MAST ON VMSCMS.CMS_CARDISSUANCE_STATUS_MAST
(CCM_STATUS_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


