CREATE UNIQUE INDEX VMSCMS.PK_CAM_INSTUSERQUST ON VMSCMS.CMS_ANSR_MAST
(CAM_INST_CODE, CAM_USER_CODE, CAM_QUST_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


