CREATE UNIQUE INDEX VMSCMS.PK_CMS_GL_CATG ON VMSCMS.CMS_GL_CATG
(CGC_INST_CODE, CGC_CATG_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


