CREATE UNIQUE INDEX VMSCMS.PK_CTRL_TABLE ON VMSCMS.CMS_CTRL_TABLE
(CCT_CTRL_CODE, CCT_CTRL_KEY, CCT_CTRL_NUMB)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


