CREATE UNIQUE INDEX VMSCMS.PK_CAFINFO_TEMP_ROWID ON VMSCMS.PCMS_CAF_INFO_TEMP
(CCI_ROW_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


