CREATE UNIQUE INDEX VMSCMS.PK_CONFIG_MAST ON VMSCMS.CMS_VENDORITEM_CONFIG_MAST
(CVC_CONFIG_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


