CREATE UNIQUE INDEX VMSCMS.PK_CFM_FILE_FIELD_ID ON VMSCMS.CMS_FIELD_MAST
(CFM_FILE_ID, CFM_FIELD_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


