CREATE UNIQUE INDEX VMSCMS.PK_CTL_INST_USER_PSWD ON VMSCMS.CMS_TRACKDETL_LGIN
(CTL_INST_CODE, CTL_USER_CODE, CTL_PSWD_TYPE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


