CREATE UNIQUE INDEX VMSCMS.PK_CHANNEL_CODE ON VMSCMS.CMS_DELCHANNEL_MAST
(CDM_CHANNEL_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


