CREATE UNIQUE INDEX VMSCMS.PK_CEP_PARAM_KEY ON VMSCMS.CMS_EMV_PARAM
(CEP_INST_CODE, CEP_PARAM_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


