CREATE UNIQUE INDEX VMSCMS.PK_CCS_PAN_CODE ON VMSCMS.CMS_CARDISSUANCE_STATUS
(CCS_PAN_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


