CREATE UNIQUE INDEX VMSCMS.PK_CUST_TYPE ON VMSCMS.CMS_CUST_TYPE
(CCT_INST_CODE, CCT_TYPE_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


