CREATE UNIQUE INDEX VMSCMS.PK_CGR_SEQ_NO ON VMSCMS.CMS_GROUP_BULKREISSUE
(CGR_SEQ_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


