CREATE UNIQUE INDEX VMSCMS.PK_DEK_INDEX_PARAM ON VMSCMS.CMS_DEK_INDEX_PARAM
(CDI_KEY_OF)
LOGGING
TABLESPACE CMS_MAST
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


