CREATE UNIQUE INDEX VMSCMS.PK_DISP_MAST ON VMSCMS.CMS_DISP_MAST
(CDM_INST_CODE, CDM_DISP_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


