CREATE UNIQUE INDEX VMSCMS.PK_DEK_KEY_DETAIL ON VMSCMS.CMS_DEK_KEY_DETAIL
(CDK_DEK_INDEX)
LOGGING
TABLESPACE CMS_MAST
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


