CREATE UNIQUE INDEX VMSCMS.PK_DECLINE_RESP ON VMSCMS.CMS_DECLINETXN_RESPONSE
(CDR_INST_CODE, CDR_DELIVERY_CHANNEL, CDR_TRAN_CODE, CDR_RESPCDE, CDR_MSG_TYPE, 
CDR_REVERSAL_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


