CREATE UNIQUE INDEX VMSCMS.PK_EMVPARM_MAST ON VMSCMS.CMS_EMVPARM_MAST
(CEM_INST_CODE, CEM_PARAM_KEY, CEM_INST_BIN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


