CREATE UNIQUE INDEX VMSCMS.PK_FEEPLAN_MAST ON VMSCMS.CMS_FEEPLAN_MAST
(CFM_INST_CODE, CFM_PLAN_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


