CREATE UNIQUE INDEX VMSCMS.PK_FROM_ACCTNO ON VMSCMS.CMS_OUTWARD_FUND
(COF_FROMACCT_NO)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


