CREATE UNIQUE INDEX VMSCMS.PK_GRP_PROG_STATUS ON VMSCMS.CMS_GROUP_PROG_STATUS
(CGP_GROUP_CODE, CGP_ROW_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


