CREATE UNIQUE INDEX VMSCMS.PK_GIFT_PLAN ON VMSCMS.CMS_GIFT_PLAN
(CGP_INST_CODE, CGP_PLAN_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


