CREATE UNIQUE INDEX VMSCMS.PK_GLMAPPING_FUNC ON VMSCMS.CMS_FUNC_PROD
(CFP_INST_CODE, CFP_PROD_CODE, CFP_PROD_CATTYPE, CFP_FUNC_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


