CREATE UNIQUE INDEX VMSCMS.PK_GIFT_CATALOGUE ON VMSCMS.CMS_GIFT_CATALOGUE
(CGC_INST_CODE, CGC_PLAN_ID, CGC_ITEM_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


