CREATE UNIQUE INDEX VMSCMS.PK_HSM_SERVMASTER ON VMSCMS.HSM_SERVER_MASTER
(HSM_NUMBER)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


