CREATE UNIQUE INDEX VMSCMS.PK_HOLDREASON ON VMSCMS.PCMS_HOLD_REASON
(PHR_INST_CODE, PHR_TXN_ID, PHR_HOLDCOND_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


