CREATE UNIQUE INDEX VMSCMS.PK_HTLST_REISU ON VMSCMS.CMS_HTLST_REISU
(CHR_INST_CODE, CHR_PAN_CODE, CHR_MBR_NUMB, CHR_NEW_PAN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


