CREATE UNIQUE INDEX VMSCMS.PK_INST_CNTRYCDE ON VMSCMS.CMS_CNTRYCODE_RULE
(CCR_INST_CODE, CCR_CNTRY_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


