CREATE UNIQUE INDEX VMSCMS.PK_INVENTORYITEM_MAST ON VMSCMS.CMS_INVENTORYITEM_MAST
(CIM_INVENTORYITEM_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


