CREATE UNIQUE INDEX VMSCMS.PK_INVENTORYCATG_MAST ON VMSCMS.CMS_INVENTORYCATG_MAST
(CIM_INVENTORYCATG_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


