CREATE UNIQUE INDEX VMSCMS.PK_INTERCHANGE_MAST ON VMSCMS.CMS_INTERCHANGE_MAST
(CIM_INST_CODE, CIM_INTERCHANGE_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


