CREATE UNIQUE INDEX VMSCMS.PK_INTER_DISP ON VMSCMS.CMS_INTER_DISP
(CID_INST_CODE, CID_DISP_CODE, CID_INTER_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


