CREATE UNIQUE INDEX VMSCMS.PK_KEY_ROTATE_LOG ON VMSCMS.CMS_KEY_ROTATE_LOG
(CKR_INST_CODE, CKR_OLD_DATA, CKR_NEW_DATA)
LOGGING
TABLESPACE CMS_BIG_TXN
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


