CREATE UNIQUE INDEX VMSCMS.PK_KEY_ROTATE_TABLE ON VMSCMS.CMS_KEY_ROTATE_TABLE
(CKR_INST_CODE, CKR_SNO, CKR_TABLE_NAME)
LOGGING
TABLESPACE CMS_MAST
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


