CREATE UNIQUE INDEX VMSCMS.PK_KEK_KEY_DETAIL ON VMSCMS.CMS_KEK_KEY_DETAIL
(CKK_KEK_INDEX)
LOGGING
TABLESPACE CMS_MAST
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


