CREATE UNIQUE INDEX VMSCMS.PK_KYCTXN_LOG ON VMSCMS.CMS_KYCTXN_LOG
(CKL_CMSREQ_REFNO)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


