CREATE UNIQUE INDEX VMSCMS.PK_LOYL_DTL ON VMSCMS.CMS_LOYL_DTL
(CLD_ID_COL)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


