CREATE UNIQUE INDEX VMSCMS.PK_LOYL_POINTS ON VMSCMS.CMS_LOYL_POINTS
(CLP_PAN_CODE, CLP_MBR_NUMB)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


