CREATE UNIQUE INDEX VMSCMS.PK_MERC_ID ON VMSCMS.CMS_MERCID_RULE
(CMR_INST_CODE, CMR_MERC_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


