CREATE UNIQUE INDEX VMSCMS.PK_MERCID_MERCIDGRP ON VMSCMS.CMS_MERCIDGRP_MERCID
(CMM_MERC_GRPCODE, CMM_MERC_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


