CREATE UNIQUE INDEX VMSCMS.PK_MONTHWISE_LOYL ON VMSCMS.CMS_MONTHWISE_LOYL
(CML_ACCT_NO, CML_TRAN_DATE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


