CREATE UNIQUE INDEX VMSCMS.PK_MONEYBACK_MAST ON VMSCMS.CMS_MONEYBACK_MAST
(CMM_MBSCHEME_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


