CREATE UNIQUE INDEX VMSCMS.PK_MERC_MAST ON VMSCMS.CMS_MERC_MAST
(CMM_INST_CODE, CMM_MERC_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


