CREATE UNIQUE INDEX VMSCMS.PK_OP_FILE_FOOT_ID ON VMSCMS.CMS_OP_FILE_FOOTER_MAST
(COM_FILE_ID, COM_CTRL_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


