CREATE UNIQUE INDEX VMSCMS.PK_OP_FILE_ID ON VMSCMS.CMS_OP_FILE_DEFN_MAST
(COM_FILE_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


