CREATE UNIQUE INDEX VMSCMS.PK_PAN_ACCT ON VMSCMS.CMS_PAN_ACCT
(CPA_INST_CODE, CPA_PAN_CODE, CPA_MBR_NUMB, CPA_ACCT_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


