CREATE UNIQUE INDEX VMSCMS.PK_PCMS_FILEUPLOAD_STAT ON VMSCMS.PCMS_FILEUPLOAD_STAT
(PFS_SEQ_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


