CREATE UNIQUE INDEX VMSCMS.PK_PROD_CATG ON VMSCMS.CMS_PROD_CATG
(CPC_INST_CODE, CPC_CATG_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


