CREATE UNIQUE INDEX VMSCMS.PK_PRODCATG_SMSEMAIL_ALERTS ON VMSCMS.CMS_PRODCATG_SMSEMAIL_ALERTS
(CPS_INST_CODE, CPS_PROD_CODE, CPS_CARD_TYPE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


