CREATE UNIQUE INDEX VMSCMS.PK_PROG_MAST ON VMSCMS.CMS_PROG_MAST
(CPM_INST_CODE, CPM_PROG_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


