CREATE UNIQUE INDEX VMSCMS.PK_PLAN_ID ON VMSCMS.CMS_COMMISSION_PLAN
(CCP_INST_CODE, CCP_PLAN_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


