CREATE UNIQUE INDEX VMSCMS.PK_PINMAILER_LOC ON VMSCMS.CMS_PINMAILER_LOC
(CPL_PINMAILER_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


