CREATE UNIQUE INDEX VMSCMS.PK_PAN_CTRL ON VMSCMS.CMS_PAN_CTRL
(CPC_INST_CODE, CPC_PAN_PREFIX)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


