CREATE UNIQUE INDEX VMSCMS.PK_PROJ_ID ON VMSCMS.SQLN_PROF_PROFILES
(PROJ_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


