CREATE UNIQUE INDEX VMSCMS.PK_PIN_CTRL ON VMSCMS.CMS_PIN_CTRL
(CPC_INST_CODE, CPC_PIN_FNAME)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


