CREATE UNIQUE INDEX VMSCMS.PK_PRODCCC_FPWAIV ON VMSCMS.CMS_PRODCCC_FPWAIV
(CPF_PROD_CODE, CPF_CARD_TYPE, CPF_CUST_CATG, CPF_CITY_CATG, CPF_CUST_TYPE, 
CPF_CARD_POSN, CPF_PLAN_CODE, CPF_FEE_CODE, CPF_VALID_FROM)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


