CREATE UNIQUE INDEX VMSCMS.PK_PROCID ON VMSCMS.PCMS_PROCESS_SCHEDULE
(PPS_PROCESS_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


