CREATE UNIQUE INDEX VMSCMS.PK_REASON_MAST ON VMSCMS.CMS_REASON_MAST
(CRM_INST_CODE, CRM_INTERCHANGE_CODE, CRM_DISP_CODE, CRM_REASON_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


