CREATE UNIQUE INDEX VMSCMS.PK_REQUEST_INVENTORY_REFNO ON VMSCMS.CMS_REQUEST_INVENTORY
(CRI_REF_NO)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


