CREATE UNIQUE INDEX VMSCMS.PK_RWRD_MAST ON VMSCMS.CMS_RWRD_MAST
(CRM_INST_CODE, CRM_RWRD_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


