CREATE UNIQUE INDEX VMSCMS.PK_REPORT_ID ON VMSCMS.CMS_REPORT_MASTER
(CRM_REPORT_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


