CREATE UNIQUE INDEX VMSCMS.PK_SUCCESS_LOG ON VMSCMS.CMS_SUCCESS_LOG
(CSL_INST_CODE, CSL_PAN_CODE, CSL_MBR_NUMB, CSL_PROCESS_TYPE, CSL_PROCESS_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


