CREATE UNIQUE INDEX VMSCMS.PK_SKIPDUP_ACCTS ON VMSCMS.CMS_SKIPDUP_ACCTS
(CSA_INST_CODE, CSA_ACCT_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


