CREATE UNIQUE INDEX VMSCMS.PK_SQLN_PROF_HASH ON VMSCMS.SQLN_PROF_UNIT_HASH
(RUNID, UNIT_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


