CREATE UNIQUE INDEX VMSCMS.PK_SPPRT_FUNCS ON VMSCMS.CMS_SPPRT_FUNCS
(CSF_INST_CODE, CSF_SPPRT_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


