CREATE UNIQUE INDEX VMSCMS.PK_SEVER_MAST ON VMSCMS.CSR_SERVER_DETAIL
(CSD_INST_CODE, CSD_PARAM_KEY, CSD_PARAM_VALUE, CSD_SERVER_ID)
LOGGING
TABLESPACE CMS_SML_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


