CREATE UNIQUE INDEX VMSCMS.PK_SMS_EMAIL ON VMSCMS.CMS_SMSEMAIL_ALERT
(CSA_INST_CODE, CSA_PAN_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


