CREATE UNIQUE INDEX VMSCMS.PK_SLAB_MAST ON VMSCMS.CMS_ITEM_SLAB_MAST
(CIS_SLAB_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


