CREATE UNIQUE INDEX VMSCMS.PK_TRN_NO ON VMSCMS.CMS_PAY_TRANSFER
(CPT_TRANSFER_NO)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


