CREATE UNIQUE INDEX VMSCMS.PK_TXNCODE_RULE ON VMSCMS.CMS_TXNCODE_RULE
(CTR_TXNRULE_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


