CREATE UNIQUE INDEX VMSCMS.PK_TXNCODE_RULEGRP ON VMSCMS.CMS_TXNCODE_RULEGRP
(CTR_TXNRULE_GRPCODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


