CREATE UNIQUE INDEX VMSCMS.PK_TERM_MAST ON VMSCMS.CMS_TERM_MAST
(CTM_INST_CODE, CTM_BANK_ID, CTM_TERM_ID)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


