CREATE UNIQUE INDEX VMSCMS.PK_TXN_MST ON VMSCMS.CMS_TRANSACTION_MAST
(CTM_INST_CODE, CTM_DELIVERY_CHANNEL, CTM_TRAN_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


