CREATE UNIQUE INDEX VMSCMS.PK_TABLE_PARAM ON VMSCMS.CMS_TABLE_PARAM
(CTP_INST_CODE, CTP_PARAM_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


