CREATE UNIQUE INDEX VMSCMS.PK_UPLOAD_CTRL_1 ON VMSCMS.CMS_BATCHUPLOAD_CTRL
(CBC_INST_CODE, CBC_FILE_NAME)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


