CREATE UNIQUE INDEX VMSCMS.PK_UPLDSMRY_FILENAME ON VMSCMS.PCMS_UPLOAD_SUMMARY
(PUC_FILE_NAME)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


