CREATE UNIQUE INDEX VMSCMS.PK_VENDOR_MAST ON VMSCMS.CMS_INVENTORYVENDOR_MAST
(CIM_VENDOR_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


