CREATE INDEX VMSCMS.PROCESS_ENTS_ENT_IDX ON VMSCMS.DMRS_PROCESS_ENTITIES
(ENTITY_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


