CREATE INDEX VMSCMS.RAGGED_HIER_LINK_ATTRS_FK_IDX ON VMSCMS.DMRS_RAGGED_HIER_LINK_ATTRS
(RAGGED_HIER_LINK_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


