CREATE INDEX VMSCMS.RECORD_STRUCTS_PK_IDX ON VMSCMS.DMRS_RECORD_STRUCTURES
(RECORD_STRUCTURE_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


