CREATE INDEX VMSCMS.RES_PARTY_CONTACTS_FK2_IDX ON VMSCMS.DMRS_RES_PARTY_CONTACTS
(CONTACT_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


