CREATE INDEX VMSCMS.RES_PARTY_ELEMENTS_FK1_IDX ON VMSCMS.DMRS_RES_PARTY_ELEMENTS
(RESPONSIBLE_PARTY_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


