CREATE INDEX VMSCMS.RESOURCE_LOCATORS_PK_IDX ON VMSCMS.DMRS_RESOURCE_LOCATORS
(RESOURCE_LOCATOR_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


