CREATE INDEX VMSCMS.SLICE_DIM_HIER_LEVEL_FK_IDX ON VMSCMS.DMRS_SLICE_DIM_HIER_LEVEL
(SLICE_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


