CREATE INDEX VMSCMS.STRUCTURED_TYPES_PK_IDX ON VMSCMS.DMRS_STRUCTURED_TYPES
(STRUCTURED_TYPE_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


