CREATE INDEX VMSCMS.STRUCT_TYPE_METHOD_PARS_FK_IDX ON VMSCMS.DMRS_STRUCT_TYPE_METHOD_PARS
(METHOD_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


