CREATE INDEX VMSCMS.TASK_PARAMS_PK_IDX ON VMSCMS.DMRS_TASK_PARAMS
(TASK_PARAMS_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


