CREATE UNIQUE INDEX VMSCMS.TPSQL_IDX ON VMSCMS.TOAD_PLAN_SQL
(STATEMENT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


