CREATE UNIQUE INDEX VMSCMS.TRANSCODE_PK ON VMSCMS.TRANSCODE
(TRANSCODE, DELIVERY_CHNNEL, ACT_INST_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


