CREATE INDEX VMSCMS.TRANSFORM_TASKS_PK_IDX ON VMSCMS.DMRS_TRANSFORMATION_TASKS
(TRANSFORMATION_TASK_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


