CREATE INDEX VMSCMS.TRANSFORM_TASK_INFOS_FK2_IDX ON VMSCMS.DMRS_TRANSFORMATION_TASK_INFOS
(INFO_STORE_OVID)
NOLOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


