CREATE UNIQUE INDEX VMSCMS.UK_BRAN_CODE ON VMSCMS.CMS_BRAN_REFRESHGRP
(CBR_INST_CODE, CBR_BRAN_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


