CREATE UNIQUE INDEX VMSCMS.UK_CORPMASTER_SHORT_NAME ON VMSCMS.PCMS_CORPORATE_MASTER
(PCM_SHORT_NAME)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


