CREATE UNIQUE INDEX VMSCMS.UK_CUST_CATG ON VMSCMS.CMS_CUST_CATG
(CCC_INST_CODE, CCC_CATG_SNAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


