CREATE UNIQUE INDEX VMSCMS.UK_CSD_SERVER_ID ON VMSCMS.CSR_SERVER_DETAIL
(CSD_SERVER_ID)
LOGGING
TABLESPACE CMS_SML_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


