CREATE UNIQUE INDEX VMSCMS.UK_COLNAME_ID ON VMSCMS.CMS_GENAUDIT_TABLE
(CGT_INST_CODE, CGT_TABLE_ID, CGT_COLUMN_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


