CREATE UNIQUE INDEX VMSCMS.UK_DEK_KEY_DETAIL ON VMSCMS.CMS_DEK_KEY_DETAIL
(CDK_INST_CODE, CDK_DEK_NAME)
LOGGING
TABLESPACE CMS_MAST
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


