CREATE UNIQUE INDEX VMSCMS.UK_DEVL_TYP_CODE ON VMSCMS.CMS_CSRREASON_MAST
(CCM_DELV_CHNL, CCM_REASON_TYPE, CCM_REASON_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


