CREATE UNIQUE INDEX VMSCMS.UK_EMPLOYEE_MASTER ON VMSCMS.PCMS_EMPLOYEE_MASTER
(PEM_ORGANIZATION_CODE, PEM_INST_CODE, PEM_EMP_NAME, PEM_EMP_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


