CREATE UNIQUE INDEX VMSCMS.UK_INVENTORYITEM_DESC ON VMSCMS.CMS_INVENTORYITEM_MAST
(CIM_INVENTORYITEM_DESC)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


