CREATE UNIQUE INDEX VMSCMS.UK_MONEYBACK_MAST ON VMSCMS.CMS_MONEYBACK_MAST
(CMM_MB_DESC)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


