CREATE UNIQUE INDEX VMSCMS.UK_PRODMAST_PRODDESC ON VMSCMS.CMS_PROD_MAST
(CPM_PROD_DESC)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


