CREATE UNIQUE INDEX VMSCMS.UK_PROD_CATTTYPE_SNAME ON VMSCMS.CMS_PROD_CATTYPE
(CPC_INST_CODE, CPC_PROD_CODE, CPC_CARDTYPE_SNAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


