CREATE UNIQUE INDEX VMSCMS.UK_PROD_CATG ON VMSCMS.CMS_PROD_CATG
(CPC_INST_CODE, CPC_CATG_APPL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


