CREATE UNIQUE INDEX VMSCMS.UK_TTUM_UPLOAD ON VMSCMS.CMS_TTUM_UPLOAD
(CTU_FEE_TRANS)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


