CREATE UNIQUE INDEX VMSCMS.UK_TXNCODE_RULE ON VMSCMS.CMS_TXNCODE_RULE
(CTR_INST_CODE, CTR_TXN_CODE, CTR_DELV_CHNL, CTR_MCC_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


