CREATE UNIQUE INDEX VMSCMS.UK_VENDORITEMCONFIG_MAST ON VMSCMS.CMS_VENDORITEM_CONFIG_MAST
(CVC_VENDOR_CODE, CVC_ITEM_CODE)
LOGGING
TABLESPACE INCOMM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


