
R18 

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_PRINTRUN_ERROR_CODES to app_vms_user;

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_PRINTRUN_TEST_DATA to app_vms_user;

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_PRINTRUN_TEST_RESULTS to app_vms_user;

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_PRODUCTTRANSFER_MATRIX to app_vms_user;

R19 

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_EMBOSS_FILE_FORMAT_STAG to app_vms_user;

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_PACKAGEID_DETL_STAG to app_vms_user;

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_PACKAGEID_MAST_STAG to app_vms_user;

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_PACKAGEID_MAST to app_vms_user;


R20 

GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_ISSUBANK_MAST to app_vms_user;
GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_OTP_RETRY to app_vms_user;
GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_OTP_TOKEN to app_vms_user;
GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_SWEEP_STATE_EXCLUSION to app_vms_user;
GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_TRANS_CONFIGURATION to app_vms_user;
GRANT SELECT,UPDATE,DELETE,INSERT on vmscms.VMS_EVENT_PROCESSING to app_vms_user;
