CREATE TABLE VMSCMS.ACHFILESUMMARY_TEMP_REPORT
(
  INCOMING_CRFILEID  VARCHAR2(20 BYTE),
  IMPDATE            VARCHAR2(30 BYTE),
  PROCESSDATE        VARCHAR2(30 BYTE),
  ACHFILENAME        VARCHAR2(40 BYTE),
  ACH_FILE_PATH      VARCHAR2(100 BYTE),
  DELIVERY_CHANNEL   VARCHAR2(2 BYTE),
  TXN_CODE           VARCHAR2(2 BYTE),
  INSTCODE           NUMBER(3),
  RESPONSE_CODE      VARCHAR2(7 BYTE),
  COMPANYNAME        VARCHAR2(36 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


