CREATE TABLE VMSCMS.CMS_MERINV_ORDR
(
  CMO_INST_CODE        NUMBER(10)               NOT NULL,
  CMO_MERPRODCAT_ID    NUMBER(10)               NOT NULL,
  CMO_LOCATION_ID      VARCHAR2(15 BYTE)        NOT NULL,
  CMO_NOCARDS_ORDR     NUMBER(10)               NOT NULL,
  CMO_AUTHORIZE_FLAG   CHAR(1 BYTE)             DEFAULT 'O'                   NOT NULL,
  CMO_AUTHORIZE_DATE   DATE                     NOT NULL,
  CMO_AUTHORIZE_USER   NUMBER(10)               NOT NULL,
  CMO_PROCESS_FLAG     CHAR(1 BYTE)             DEFAULT 'N'                   NOT NULL,
  CMO_REJECT_REASON    VARCHAR2(200 BYTE),
  CMO_PROCESS_DATE     DATE                     NOT NULL,
  CMO_PROCESS_USER     NUMBER(10)               NOT NULL,
  CMO_LUPD_DATE        DATE                     NOT NULL,
  CMO_LUPD_USER        NUMBER(10)               NOT NULL,
  CMO_INS_DATE         DATE                     NOT NULL,
  CMO_INS_USER         NUMBER(10)               NOT NULL,
  CMO_ORDR_REFRNO      VARCHAR2(11 BYTE),
  CMO_SUCCESS_RECORDS  NUMBER(10)               DEFAULT 0                     NOT NULL,
  CMO_ERROR_RECORDS    NUMBER(10)               DEFAULT 0                     NOT NULL,
  CMO_RAISE_FLAG       CHAR(1 BYTE)             NOT NULL,
  CMO_FILLER           VARCHAR2(15 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MERINV_ORDR ADD (
  CONSTRAINT PK_CMS_MERINV_ORDR
 PRIMARY KEY
 (CMO_ORDR_REFRNO))
/

ALTER TABLE VMSCMS.CMS_MERINV_ORDR ADD (
  CONSTRAINT FK_CMS_MERINV_ORDR 
 FOREIGN KEY (CMO_INST_CODE, CMO_MERPRODCAT_ID, CMO_LOCATION_ID) 
 REFERENCES VMSCMS.CMS_MERINV_STOCK (CMS_INST_CODE,CMS_MERPRODCAT_ID,CMS_LOCATION_ID))
/

