CREATE TABLE VMSCMS.CMS_PAN_EXTN
(
  CAE_INST_CODE      NUMBER(3)                  NOT NULL,
  CAE_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CAE_MBR_NUMB       VARCHAR2(3 BYTE)           NOT NULL,
  CAE_CARD_STAT      VARCHAR2(1 BYTE),
  CAE_ACTIVE_DATE    DATE,
  CAE_ACCT_ID        NUMBER(10)                 NOT NULL,
  CAE_ACCT_NO        VARCHAR2(20 BYTE),
  CAE_NEXT_MB_DATE   DATE,
  CAE_INS_USER       NUMBER(5)                  NOT NULL,
  CAE_INS_DATE       DATE                       NOT NULL,
  CAE_LUPD_USER      NUMBER(5)                  NOT NULL,
  CAE_LUPD_DATE      DATE                       NOT NULL,
  CAE_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


