CREATE TABLE VMSCMS.CMS_GENAUDIT_MAST
(
  CGM_INST_CODE    NUMBER(3),
  CGM_TABLE_ID     NUMBER(5),
  CGM_TABLE_NAME   VARCHAR2(60 BYTE),
  CGM_TABLE_ALIAS  VARCHAR2(60 BYTE),
  CGM_INS_USER     NUMBER(5),
  CGM_INS_DATE     DATE,
  CGM_LUPD_USER    NUMBER(5),
  CGM_LUPD_DATE    DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GENAUDIT_MAST ADD (
  CONSTRAINT PK_AUDITMAST_TABLEID
 PRIMARY KEY
 (CGM_INST_CODE, CGM_TABLE_ID),
  CONSTRAINT UK_AUDITMAST_TABLENAME
 UNIQUE (CGM_INST_CODE, CGM_TABLE_NAME))
/

ALTER TABLE VMSCMS.CMS_GENAUDIT_MAST ADD (
  CONSTRAINT FK_AUDITMAST_USERMAST1 
 FOREIGN KEY (CGM_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_AUDITMAST_USERMAST2 
 FOREIGN KEY (CGM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

