CREATE TABLE VMSCMS.CMS_OP_FILE_DEFN_MAST
(
  COM_FILE_ID             NUMBER(20),
  COM_FORMAT_ID           NUMBER(10),
  COM_PROCESS_ID          NUMBER(5),
  COM_INS_USER            NUMBER(5),
  COM_IND_DATE            DATE,
  COM_LUPD_USER           NUMBER(5),
  COM_LUPD_DATE           DATE,
  COM_FILE_DESC           VARCHAR2(100 BYTE),
  COM_NAME_CONV           VARCHAR2(20 BYTE),
  COM_NAME_CONSTANT       VARCHAR2(10 BYTE),
  COM_FILE_TYPE           VARCHAR2(20 BYTE),
  COM_REPORT_TITLE        VARCHAR2(30 BYTE),
  COM_GROUP_FLAG          VARCHAR2(1 BYTE),
  COM_GRP_SUMMARY_FLAG    VARCHAR2(1 BYTE),
  COM_ORDER_FLAG          VARCHAR2(1 BYTE),
  COM_FINAL_SUMMARY_FLAG  VARCHAR2(1 BYTE),
  COM_FILE_SHORT_NAME     VARCHAR2(25 BYTE),
  COM_INST_CODE           NUMBER(10),
  COM_INS_DATE            DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_OP_FILE_DEFN_MAST ADD (
  CONSTRAINT PK_OP_FILE_ID
 PRIMARY KEY
 (COM_FILE_ID))
/

ALTER TABLE VMSCMS.CMS_OP_FILE_DEFN_MAST ADD (
  CONSTRAINT FK_FORMAT_ID 
 FOREIGN KEY (COM_FORMAT_ID) 
 REFERENCES VMSCMS.CMS_OP_FORMAT_MAST (COM_FORMAT_ID))
/

