CREATE TABLE VMSCMS.CMS_AVAIL_TRANS
(
  CAT_INST_CODE           NUMBER,
  CAT_PAN_CODE            VARCHAR2(90 BYTE),
  CAT_TRAN_CODE           VARCHAR2(2 BYTE),
  CAT_TRAN_MODE           VARCHAR2(1 BYTE),
  CAT_MAXDAILY_TRANCNT    NUMBER(2),
  CAT_MAXDAILY_TRANAMT    NUMBER(6),
  CAT_MAXWEEKLY_TRANCNT   NUMBER(2),
  CAT_MAXWEEKLY_TRANAMT   NUMBER(6),
  CAT_MAXMONTHLY_TRANCNT  NUMBER(2),
  CAT_MAXMONTHLY_TRANAMT  NUMBER(6),
  CAT_INS_USER            NUMBER(5),
  CAT_INS_DATE            DATE,
  CAT_LUPD_DATE           DATE,
  CAT_LUPD_USER           NUMBER(10),
  CAT_PAN_CODE_ENCR       RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


