CREATE TABLE VMSCMS.CMS_FEE_FEEPLAN_HIST
(
  CFF_FEE_CODE   NUMBER(4),
  CFF_FEE_PLAN   NUMBER(4),
  CFF_INST_CODE  NUMBER(3),
  CFF_INS_USER   NUMBER(10),
  CFF_INS_DATE   DATE,
  CFF_LUPD_USER  NUMBER(10),
  CFF_LUPD_DATE  DATE,
  CFF_FEE_FREQ   VARCHAR2(1 BYTE),
  CFF_ACT_TYPE   VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BKUP
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


