CREATE TABLE VMSCMS.CMS_IRISTRANSACTION_MAST
(
  CIM_INST_CODE           NUMBER(3),
  CIM_TRAN_CODE           VARCHAR2(2 BYTE),
  CIM_TRAN_DESC           VARCHAR2(50 BYTE),
  CIM_CREDIT_DEBIT_FLAG   VARCHAR2(2 BYTE),
  CIM_DELIVERY_CHANNEL    VARCHAR2(2 BYTE),
  CIM_OUTPUT_TYPE         VARCHAR2(1 BYTE),
  CIM_TRAN_TYPE           VARCHAR2(1 BYTE),
  CIM_SUPPORT_TYPE        VARCHAR2(1 BYTE),
  CIM_LUPD_DATE           DATE,
  CIM_LUPD_USER           NUMBER(10),
  CIM_INS_DATE            DATE,
  CIM_INS_USER            NUMBER(10),
  CIM_SUPPORT_CATG        VARCHAR2(1 BYTE),
  CIM_PREAUTH_FLAG        VARCHAR2(1 BYTE)      DEFAULT 'N',
  CIM_AMNT_TRANSFER_FLAG  VARCHAR2(1 BYTE)      DEFAULT 'N',
  CIM_LOGIN_TXN           VARCHAR2(1 BYTE)      DEFAULT 'N',
  CIM_PRFL_FLAG           CHAR(1 BYTE)          DEFAULT 'N',
  CIM_FEE_FLAG            VARCHAR2(1 BYTE)      DEFAULT 'Y',
  CIM_IRIS_FLAG           CHAR(1 BYTE)          DEFAULT 'N'
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_IRISTRANSACTION_MAST ADD (
  CONSTRAINT CK_IRISSPPRT_CATG
 CHECK (CIM_SUPPORT_CATG in ('D','P','B')),
  CONSTRAINT PK_IRISTRANSACTION_MAST
 PRIMARY KEY
 (CIM_INST_CODE, CIM_TRAN_CODE, CIM_DELIVERY_CHANNEL))
/

ALTER TABLE VMSCMS.CMS_IRISTRANSACTION_MAST ADD (
  CONSTRAINT FK_IRISDELV_CHNNL 
 FOREIGN KEY (CIM_DELIVERY_CHANNEL) 
 REFERENCES VMSCMS.CMS_DELCHANNEL_MAST (CDM_CHANNEL_CODE))
/

