CREATE TABLE VMSCMS.CMS_CRDCLOSE_DETAIL
(
  CCD_INST_CODE     NUMBER(3),
  CCD_CARD_NO       VARCHAR2(90 BYTE),
  CCD_FILE_NAME     VARCHAR2(30 BYTE),
  CCD_REMARKS       VARCHAR2(100 BYTE),
  CCD_MSG24_FLAG    CHAR(1 BYTE)                DEFAULT 'N',
  CCD_PROCESS_FLAG  VARCHAR2(1 BYTE),
  CCD_PROCESS_MSG   VARCHAR2(300 BYTE),
  CCD_PROCESS_MODE  VARCHAR2(1 BYTE),
  CCD_INS_USER      NUMBER(5),
  CCD_INS_DATE      DATE,
  CCD_LUPD_USER     NUMBER(5),
  CCD_LUPD_DATE     DATE,
  CCD_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


