CREATE TABLE VMSCMS.CMS_ORA_ERRMSG
(
  COE_INST_CODE      NUMBER(3),
  COE_ORA_ERRORCODE  NUMBER(7),
  COE_ORA_ERRMSG     VARCHAR2(100 BYTE),
  COE_GEN_ERRMSG     VARCHAR2(300 BYTE),
  COE_INS_USER       NUMBER(5),
  COE_INS_DATE       DATE,
  COE_LUPD_USER      NUMBER(5),
  COE_LUPD_DATE      DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


