CREATE TABLE VMSCMS.CMS_REASON_MAST
(
  CRM_INST_CODE         NUMBER(3)               NOT NULL,
  CRM_INTERCHANGE_CODE  VARCHAR2(2 BYTE)        NOT NULL,
  CRM_DISP_CODE         NUMBER(2)               NOT NULL,
  CRM_REASON_CODE       VARCHAR2(2 BYTE)        NOT NULL,
  CRM_DAYS_LIMT         NUMBER(3)               NOT NULL,
  CRM_REASON_DESC       VARCHAR2(50 BYTE)       NOT NULL,
  CRM_INS_USER          NUMBER(5)               NOT NULL,
  CRM_INS_DATE          DATE                    NOT NULL,
  CRM_LUPD_USER         NUMBER(5)               NOT NULL,
  CRM_LUPD_DATE         DATE                    NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_REASON_MAST ADD (
  CONSTRAINT PK_REASON_MAST
 PRIMARY KEY
 (CRM_INST_CODE, CRM_INTERCHANGE_CODE, CRM_DISP_CODE, CRM_REASON_CODE))
/

ALTER TABLE VMSCMS.CMS_REASON_MAST ADD (
  CONSTRAINT FK_REASONMAST_INTERMAST 
 FOREIGN KEY (CRM_INST_CODE, CRM_INTERCHANGE_CODE) 
 REFERENCES VMSCMS.CMS_INTERCHANGE_MAST (CIM_INST_CODE,CIM_INTERCHANGE_CODE),
  CONSTRAINT FK_REASONMAST_DISPMAST 
 FOREIGN KEY (CRM_INST_CODE, CRM_DISP_CODE) 
 REFERENCES VMSCMS.CMS_DISP_MAST (CDM_INST_CODE,CDM_DISP_CODE),
  CONSTRAINT FK_REASONMAST_INSTMAST 
 FOREIGN KEY (CRM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

