CREATE TABLE VMSCMS.CMS_PROD_MAST_VISA
(
  CPM_INST_CODE         NUMBER(3)               NOT NULL,
  CPM_PROD_CODE         VARCHAR2(6 BYTE)        NOT NULL,
  CPM_ASSO_CODE         NUMBER(3),
  CPM_INST_TYPE         NUMBER(3),
  CPM_INTERCHANGE_CODE  VARCHAR2(2 BYTE)        NOT NULL,
  CPM_CATG_CODE         VARCHAR2(2 BYTE)        NOT NULL,
  CPM_PROD_DESC         VARCHAR2(35 BYTE)       NOT NULL,
  CPM_SWITCH_PROD       VARCHAR2(5 BYTE)        NOT NULL,
  CPM_FROM_DATE         DATE,
  CPM_TO_DATE           DATE,
  CPM_INS_USER          NUMBER(5)               NOT NULL,
  CPM_INS_DATE          DATE                    NOT NULL,
  CPM_LUPD_USER         NUMBER(5)               NOT NULL,
  CPM_LUPD_DATE         DATE                    NOT NULL,
  CPM_VALIDITY_PERIOD   NUMBER(3),
  CPM_VAR_FLAG          VARCHAR2(1 BYTE),
  CPM_RULEGROUP_CODE    VARCHAR2(4 BYTE),
  CPM_PROFILE_CODE      VARCHAR2(4 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


