CREATE TABLE VMSCMS.CMS_RATETABLE_CURRPAIR
(
  CRC_INST_CODE     NUMBER(5),
  CRC_RATETABLE_ID  NUMBER(18),
  CRC_CURRPAIR_ID   VARCHAR2(8 BYTE),
  CRC_LUPD_DATE     DATE,
  CRC_LUPD_USER     NUMBER(10),
  CRC_INS_DATE      DATE,
  CRC_INS_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_RATETABLE_CURRPAIR ADD (
  CONSTRAINT PK_RATETABLE_CURRPAIR1
 PRIMARY KEY
 (CRC_INST_CODE, CRC_RATETABLE_ID, CRC_CURRPAIR_ID))
/

