CREATE TABLE VMSCMS.CMS_CSR_XML_LOG
(
  CXL_RRN               VARCHAR2(20 BYTE),
  CXL_STAN              VARCHAR2(15 BYTE),
  CXL_REQUEST_XML       VARCHAR2(4000 BYTE),
  CXL_RESPONSE_XML      VARCHAR2(4000 BYTE),
  CXL_PAN_CODE          VARCHAR2(90 BYTE),
  CXL_DELIVERY_CHANNEL  VARCHAR2(2 BYTE),
  CXL_INST_CODE         VARCHAR2(2 BYTE),
  CXL_TXN_CODE          VARCHAR2(2 BYTE),
  CXL_RESP_CODE         VARCHAR2(3 BYTE),
  CXL_PAN_CODE_ENCR     RAW(100),
  CXL_INS_DATE          DATE,
  CXL_INS_USER          NUMBER(5),
  CXL_LUPD_DATE         DATE,
  CXL_LUPD_USER         NUMBER(5)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


