CREATE TABLE VMSCMS.CMS_SERL_CNTRL
(
  CSC_INST_CODE  NUMBER(10)                     NOT NULL,
  CSC_PROD_CODE  VARCHAR2(6 BYTE)               NOT NULL,
  CSC_PROD_CATG  NUMBER(2)                      NOT NULL,
  CSC_TOTL_CNT   NUMBER(20)                     NOT NULL,
  CSC_SERL_STRT  NUMBER(20)                     NOT NULL,
  CSC_SERL_END   NUMBER(20)                     NOT NULL,
  CSC_LUPD_DATE  DATE                           NOT NULL,
  CSC_LUPD_USER  NUMBER(10)                     NOT NULL,
  CSC_INS_DATE   DATE                           NOT NULL,
  CSC_INS_USER   NUMBER(10)                     NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SERL_CNTRL ADD (
  CONSTRAINT UK_CMS_SERL_CNTRL
 UNIQUE (CSC_INST_CODE, CSC_PROD_CODE, CSC_PROD_CATG, CSC_SERL_STRT, CSC_SERL_END))
/

