CREATE TABLE VMSCMS.CMS_REN_PAN_TEMP
(
  CRP_PAN_CODE       VARCHAR2(90 BYTE),
  CRP_LUPD_DATE      DATE,
  CRP_INST_CODE      NUMBER(10),
  CRP_LUPD_USER      NUMBER(10),
  CRP_INS_DATE       DATE,
  CRP_INS_USER       NUMBER(10),
  CRP_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


