CREATE TABLE VMSCMS.CMS_MONEYBK_DET
(
  CMD_PAN_CODE       VARCHAR2(90 BYTE),
  CMD_TRAN_AMT       NUMBER(15,6),
  CMD_FILE_GEN       VARCHAR2(1 BYTE),
  CMD_INS_DATE       DATE,
  CMD_REMARKS        VARCHAR2(100 BYTE),
  CMD_ACCT_NO        VARCHAR2(16 BYTE)          NOT NULL,
  CMD_BRANCH_CODE    VARCHAR2(5 BYTE)           NOT NULL,
  CMD_FILE_NAME      VARCHAR2(20 BYTE),
  CMD_FILEGEN_DATE   DATE,
  CMD_LUPD_DATE      DATE,
  CMD_INST_CODE      NUMBER(10),
  CMD_LUPD_USER      NUMBER(10),
  CMD_INS_USER       NUMBER(10),
  CMD_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


