CREATE TABLE VMSCMS.CMS_MERCHANT_CARDS
(
  PCC_INST_CODE    NUMBER(10),
  PCC_MERC_CODE    VARCHAR2(4 BYTE),
  PCC_PAN_NO       VARCHAR2(90 BYTE),
  PCC_INS_USER     NUMBER(10),
  PCC_INS_DATE     DATE,
  PCC_LUPD_USER    NUMBER(10),
  PCC_LUPD_DATE    DATE,
  PCC_CUST_CODE    NUMBER(10),
  PCC_PAN_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


