CREATE TABLE VMSCMS.CMS_MERCIDGRP_MERCID
(
  CMM_INST_CODE     NUMBER(10),
  CMM_MERC_GRPCODE  VARCHAR2(11 BYTE),
  CMM_MERC_ID       VARCHAR2(11 BYTE),
  CMM_LUPD_DATE     DATE,
  CMM_LUPD_USER     NUMBER(10),
  CMM_INS_DATE      DATE,
  CMM_INS_USER      NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MERCIDGRP_MERCID ADD (
  CONSTRAINT PK_MERCID_MERCIDGRP
 PRIMARY KEY
 (CMM_MERC_GRPCODE, CMM_MERC_ID))
/

ALTER TABLE VMSCMS.CMS_MERCIDGRP_MERCID ADD (
  CONSTRAINT FK_MERCID_MERCIDGRP 
 FOREIGN KEY (CMM_MERC_GRPCODE) 
 REFERENCES VMSCMS.CMS_MERCID_RULEGRP (CMR_MERC_GRPCODE))
/

