CREATE TABLE VMSCMS.CMS_BAL_ADJ_BATCH
(
  CBB_BATCH_ID         VARCHAR2(100 BYTE),
  CBB_PAN_CODE         VARCHAR2(90 BYTE),
  CBB_PAN_CODE_ENCR    RAW(100),
  CBB_TXN_AMT          NUMBER(20,3),
  CBB_FORSE_POST       VARCHAR2(3 BYTE),
  CBB_REASON_CODE      NUMBER(5),
  CBB_TXN_DESC         VARCHAR2(300 BYTE),
  CBB_BEFORE_LEDG_BAL  NUMBER(20,3),
  CBB_AFTER_LEDG_BAL   NUMBER(20,3),
  CBB_PROCESS_FLAG     VARCHAR2(2 BYTE),
  CBB_PROCESS_MSG      VARCHAR2(300 BYTE),
  CBB_INS_USER         NUMBER(5),
  CBB_INS_DATE         DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


