CREATE TABLE VMSCMS.CMS_CUSTOMER_PARAMETERS
(
  CCP_ID                  NUMBER,
  CCP_SP_CUSTACCNO        VARCHAR2(20 BYTE),
  CCP_SP_NOOF_TXNS        NUMBER,
  CCP_SP_TOTAL_AMOUNT     NUMBER(10),
  CCP_SP_TXN_PERIOD       VARCHAR2(10 BYTE),
  CCP_SP_AMOUNT_PERIOD    VARCHAR2(10 BYTE),
  CCP_AT_CUSTACCNO        VARCHAR2(20 BYTE),
  CCP_AT_TOPUP_THRESHOLD  NUMBER(10),
  CCP_AT_TOPUP_AMOUNT     NUMBER(10),
  CCP_AT_TOPUP_FREQUENCY  NUMBER(2),
  CCP_AT_TOTAL_AMOUNT     NUMBER(10),
  CCP_AT_MANDATEACCT      VARCHAR2(20 BYTE),
  CCP_AT_FREQUENCYPERIOD  VARCHAR2(10 BYTE),
  CCP_AT_AMOUNTPERIOD     VARCHAR2(10 BYTE),
  CCP_KEYWORD             VARCHAR2(10 BYTE),
  CCP_INS_USER            NUMBER(10),
  CCP_INS_DATE            DATE,
  CCP_LUPD_USER           NUMBER(10),
  CCP_LUPD_DATE           DATE,
  CCP_FROM_TIME           VARCHAR2(5 BYTE),
  CCP_TO_TIME             VARCHAR2(5 BYTE),
  CCP_SUBACCT_NO          VARCHAR2(20 BYTE),
  CCP_INST_CODE           NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


