CREATE TABLE VMSCMS.CMS_SMS_SERIAL
(
  CSS_INST_CODE      NUMBER(3)                  NOT NULL,
  CSS_SERIAL_NUMBER  NUMBER(10),
  CSS_SMS_DATE       DATE                       DEFAULT sysdate
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


