CREATE TABLE VMSCMS.CMS_LOYL_MAST
(
  CLM_INST_CODE  NUMBER(3)                      NOT NULL,
  CLM_LOYL_CATG  NUMBER(3)                      NOT NULL,
  CLM_LOYL_CODE  NUMBER(3)                      NOT NULL,
  CLM_LOYL_DESC  VARCHAR2(50 BYTE)              NOT NULL,
  CLM_INS_USER   NUMBER(5)                      NOT NULL,
  CLM_INS_DATE   DATE                           NOT NULL,
  CLM_LUPD_USER  NUMBER(5)                      NOT NULL,
  CLM_LUPD_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_LOYL_MAST ADD (
  CONSTRAINT PK_LOYL_MAST
 PRIMARY KEY
 (CLM_INST_CODE, CLM_LOYL_CODE),
  CONSTRAINT UK_LOYL_MAST
 UNIQUE (CLM_LOYL_DESC))
/

ALTER TABLE VMSCMS.CMS_LOYL_MAST ADD (
  CONSTRAINT FK_LOYLMAST_LOYLCATG 
 FOREIGN KEY (CLM_INST_CODE, CLM_LOYL_CATG) 
 REFERENCES VMSCMS.CMS_LOYL_CATG (CLC_INST_CODE,CLC_CATG_CODE),
  CONSTRAINT FK_LOYLMAST_USERMAST1 
 FOREIGN KEY (CLM_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_LOYLMAST_USERMAST2 
 FOREIGN KEY (CLM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

