CREATE TABLE VMSCMS.CMS_PRODTYPE_MAP
(
  CPM_INST_CODE         NUMBER(3),
  CPM_INTERCHANGE_CODE  VARCHAR2(2 BYTE),
  CPM_PROD_CATG         VARCHAR2(2 BYTE),
  CPM_PROD_B24          VARCHAR2(5 BYTE),
  CPM_INS_USER          NUMBER(5),
  CPM_INS_DATE          DATE,
  CPM_LUPD_USER         NUMBER(5),
  CPM_LUPD_DATE         DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


