CREATE TABLE VMSCMS.CMS_MERC_ADDR_MAST
(
  CAM_INST_CODE       NUMBER(3)                 NOT NULL,
  CAM_MERC_CODE       VARCHAR2(4 BYTE),
  CAM_ADDR_CODE       NUMBER(10)                NOT NULL,
  CAM_ADD_ONE         VARCHAR2(50 BYTE)         NOT NULL,
  CAM_ADD_TWO         VARCHAR2(50 BYTE),
  CAM_ADD_THREE       VARCHAR2(50 BYTE),
  CAM_PIN_CODE        VARCHAR2(15 BYTE),
  CAM_PHONE_ONE       VARCHAR2(40 BYTE),
  CAM_PHONE_TWO       VARCHAR2(20 BYTE),
  CAM_CNTRY_CODE      NUMBER(3)                 NOT NULL,
  CAM_CITY_NAME       VARCHAR2(25 BYTE)         NOT NULL,
  CAM_FAX_ONE         VARCHAR2(20 BYTE),
  CAM_ADDR_FLAG       CHAR(1 BYTE),
  CAM_STATE_SWITCH    VARCHAR2(3 BYTE),
  CAM_INS_USER        NUMBER(5)                 NOT NULL,
  CAM_INS_DATE        DATE                      NOT NULL,
  CAM_LUPD_USER       NUMBER(5)                 NOT NULL,
  CAM_LUPD_DATE       DATE                      NOT NULL,
  CAM_EMAIL           VARCHAR2(34 BYTE),
  CAM_ADD_FOUR        VARCHAR2(50 BYTE),
  CAM_MOBL_ONE        VARCHAR2(20 BYTE),
  CAM_STATE_CODE      NUMBER(3),
  CMA_PROPRITER_NAME  VARCHAR2(30 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MERC_ADDR_MAST ADD (
  CONSTRAINT PK_ADDR_MERCMAST
 PRIMARY KEY
 (CAM_INST_CODE, CAM_ADDR_CODE))
/

ALTER TABLE VMSCMS.CMS_MERC_ADDR_MAST ADD (
  CONSTRAINT FK_ADDRMERCMAST_CNTRYMAST 
 FOREIGN KEY (CAM_INST_CODE, CAM_CNTRY_CODE) 
 REFERENCES VMSCMS.GEN_CNTRY_MAST (GCM_INST_CODE,GCM_CNTRY_CODE),
  CONSTRAINT FK_ADDRMERCMAST_STATE_CODE 
 FOREIGN KEY (CAM_INST_CODE, CAM_STATE_CODE, CAM_CNTRY_CODE) 
 REFERENCES VMSCMS.GEN_STATE_MAST (GSM_INST_CODE,GSM_CNTRY_CODE,GSM_STATE_CODE),
  CONSTRAINT FK_ADDRMERCMAST_USERMAST1 
 FOREIGN KEY (CAM_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_ADDRMERCMAST_USERMAST2 
 FOREIGN KEY (CAM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

