CREATE TABLE VMSCMS.CMS_LOGINJOB_TRACK
(
  CLT_USER_PIN       NUMBER(10),
  CLT_FLAG           CHAR(1 BYTE),
  CLT_SCHEDULE_DATE  VARCHAR2(20 BYTE),
  CLT_MESSAGE        VARCHAR2(300 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


