CREATE TABLE VMSCMS.CMS_PROGDETL_MAST
(
  CPM_INST_CODE  NUMBER(5)                      NOT NULL,
  CPM_PROG_CODE  NUMBER(5),
  CPM_TABL_TYPE  NUMBER(1)                      NOT NULL,
  CPM_MENU_LINK  NUMBER(5)                      NOT NULL,
  CPM_MENU_PATH  VARCHAR2(200 BYTE)             NOT NULL,
  CPM_PROG_KEYS  VARCHAR2(50 BYTE)              NOT NULL,
  CPM_PROG_NAME  VARCHAR2(50 BYTE)              NOT NULL,
  CPM_PROG_ORDR  NUMBER(7,2)                    NOT NULL,
  CPM_ADMN_RGHT  NUMBER(1)                      NOT NULL,
  CPM_NRML_RGHT  NUMBER(1)                      NOT NULL,
  CPM_PROG_STUS  NUMBER(1)                      NOT NULL,
  CPM_INS_USER   NUMBER(8)                      NOT NULL,
  CPM_INS_DATE   DATE                           NOT NULL,
  CPM_LUPD_USER  NUMBER(8),
  CPM_LUPD_DATE  DATE,
  CPM_HRTX_FLAG  NUMBER(1),
  CPM_BOD_FLAG   NUMBER(1)                      DEFAULT 0
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROGDETL_MAST ADD (
  CONSTRAINT PK_CPM_INST_PROG
 PRIMARY KEY
 (CPM_INST_CODE, CPM_PROG_CODE))
/

ALTER TABLE VMSCMS.CMS_PROGDETL_MAST ADD (
  CONSTRAINT FK_CPM_INID_CIM_INST 
 FOREIGN KEY (CPM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_CPM_INST_CAD_USID 
 FOREIGN KEY (CPM_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE))
/

