CREATE TABLE VMSCMS.CMS_PAN_FIELDS
(
  CPC_INST_CODE   VARCHAR2(5 BYTE),
  CPC_FIELD_NAME  VARCHAR2(50 BYTE),
  CPC_START_FROM  VARCHAR2(3 BYTE),
  CPC_LENGTH      VARCHAR2(3 BYTE),
  CPC_VALUE       VARCHAR2(10 BYTE),
  CPC_LUPD_DATE   DATE,
  CPC_LUPD_USER   NUMBER(10),
  CPC_INS_DATE    DATE,
  CPC_INS_USER    NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


