CREATE TABLE VMSCMS.CMS_RATE_DEFINITIONTEMP
(
  CRD_INST_CODE        INTEGER                  NOT NULL,
  CRD_UNIQUE_ID        NUMBER(9),
  CRD_RATETABLE_ID     NUMBER(9),
  CRD_CURRENCYPAIR_ID  VARCHAR2(10 BYTE),
  CRD_EFFECTIVE_DATE   DATE,
  CRD_RATE_VALUE       NUMBER(15,2),
  CRD_LAST_USER        INTEGER,
  CRD_LAST_DATE        DATE,
  CRD_RATE_FILE        VARCHAR2(75 BYTE),
  CRD_EXP_CODE         CHAR(2 BYTE)             DEFAULT ('00'),
  CRD_LUPD_DATE        DATE,
  CRD_LUPD_USER        NUMBER(10),
  CRD_INS_DATE         DATE,
  CRD_INS_USER         NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_RATE_DEFINITIONTEMP ADD (
  CONSTRAINT PK_RATE_DEFINITIONTEMP1
 PRIMARY KEY
 (CRD_UNIQUE_ID, CRD_INST_CODE))
/

