CREATE TABLE VMSCMS.CMS_FEEPLAN_MAST
(
  CFM_INST_CODE  NUMBER(3)                      NOT NULL,
  CFM_PLAN_CODE  VARCHAR2(6 BYTE)               NOT NULL,
  CFM_PLAN_DESC  VARCHAR2(30 BYTE)              NOT NULL,
  CFM_INS_USER   NUMBER(5),
  CFM_INS_DATE   DATE,
  CFM_LUPD_USER  NUMBER(5),
  CFM_LUPD_DATE  DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FEEPLAN_MAST ADD (
  CONSTRAINT PK_FEEPLAN_MAST
 PRIMARY KEY
 (CFM_INST_CODE, CFM_PLAN_CODE))
/

