CREATE TABLE VMSCMS.CMS_BATCHUPLOAD_PARAM
(
  CBP_INST_CODE    NUMBER(3)                    NOT NULL,
  CBP_PARAM_KEY    VARCHAR2(35 BYTE)            NOT NULL,
  CBP_PARAM_VALUE  VARCHAR2(15 BYTE)            NOT NULL,
  CBP_PARAM_DESC   VARCHAR2(50 BYTE)            NOT NULL,
  CBP_LUPD_DATE    DATE,
  CBP_LUPD_USER    NUMBER(10),
  CBP_INS_DATE     DATE,
  CBP_INS_USER     NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BATCHUPLOAD_PARAM ADD (
  CONSTRAINT PK_BATCHUPLOAD_PARAM
 PRIMARY KEY
 (CBP_INST_CODE, CBP_PARAM_KEY, CBP_PARAM_VALUE))
/

