CREATE TABLE VMSCMS.CMS_GROUP_DEHOTLIST_TEMP
(
  CGD_CARD_NO       VARCHAR2(90 BYTE),
  CGD_FILE_NAME     VARCHAR2(30 BYTE),
  CGD_REMARKS       VARCHAR2(100 BYTE),
  CGD_INS_DATE      DATE                        DEFAULT SYSDATE,
  CGD_INST_CODE     NUMBER(10),
  CGD_INS_USER      NUMBER(10),
  CGD_PROCESS_FLAG  VARCHAR2(1 BYTE)            DEFAULT 'N',
  CGD_PROCESS_MSG   VARCHAR2(300 BYTE),
  CGD_MBR_NUMB      VARCHAR2(10 BYTE),
  CGD_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


