CREATE TABLE VMSCMS.CMS_ROLE_RELATIONS
(
  CRR_INST_CODE       NUMBER(5)                 NOT NULL,
  CRR_PARENT_ROLE_ID  NUMBER(3)                 NOT NULL,
  CRR_CHILD_ROLE_ID   NUMBER(3),
  CRR_INS_USER        NUMBER(8)                 NOT NULL,
  CRR_INS_DATE        DATE                      NOT NULL,
  CRR_LUPD_USER       NUMBER(8),
  CRR_LUPD_DATE       DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ROLE_RELATIONS ADD (
  CONSTRAINT PK_CRR_ROLEID
 PRIMARY KEY
 (CRR_INST_CODE, CRR_PARENT_ROLE_ID, CRR_CHILD_ROLE_ID))
/

