CREATE TABLE VMSCMS.CMS_SERL_ERROR
(
  CSE_INST_CODE   NUMBER(10)                    NOT NULL,
  CSE_PROD_CODE   VARCHAR2(6 BYTE)              NOT NULL,
  CSE_PROD_CATG   NUMBER(2)                     NOT NULL,
  CSE_ORDR_RFRNO  VARCHAR2(20 BYTE),
  CSE_ORDR_CNT    NUMBER(20),
  CSE_SUCS_CNT    NUMBER(20),
  CSE_EROR_CNT    NUMBER(20),
  CSE_ERR_MSEG    VARCHAR2(2000 BYTE),
  CSE_INS_DATE    DATE                          DEFAULT sysdate
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


