CREATE TABLE VMSCMS.CMS_USER_GROUP
(
  CUG_INST_CODE    NUMBER(3)                    NOT NULL,
  CUG_GROUP_CODE   NUMBER(3)                    NOT NULL,
  CUG_GROUP_NAME   VARCHAR2(20 BYTE)            NOT NULL,
  CUG_INS_USER     NUMBER(5)                    NOT NULL,
  CUG_INS_DATE     DATE                         NOT NULL,
  CUG_LUPD_USER    NUMBER(5)                    NOT NULL,
  CUG_LUPD_DATE    DATE                         NOT NULL,
  CUG_ACCESS_FLAG  VARCHAR2(1 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_USER_GROUP ADD (
  CONSTRAINT PK_USER_GROUP
 PRIMARY KEY
 (CUG_INST_CODE, CUG_GROUP_CODE),
  CONSTRAINT UK_USER_GROUP
 UNIQUE (CUG_GROUP_NAME) DISABLE)
/

ALTER TABLE VMSCMS.CMS_USER_GROUP ADD (
  CONSTRAINT FK_USERGROUP_INSTMAST 
 FOREIGN KEY (CUG_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

