CREATE TABLE VMSCMS.CMS_SPPRT_FEE_MAST
(
  CSF_INST_CODE  NUMBER(3),
  CSF_FEE_AMT    NUMBER(15,6),
  CSF_FEE_DESC   VARCHAR2(50 BYTE),
  CSF_INS_USER   NUMBER(5),
  CSF_INS_DATE   DATE,
  CSF_LUPD_USER  NUMBER(5),
  CSF_LUPD_DATE  DATE,
  CSF_SPPRT_KEY  VARCHAR2(20 BYTE)              NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SPPRT_FEE_MAST ADD (
  CONSTRAINT PK_SPPRT_FEE_MAST
 PRIMARY KEY
 (CSF_INST_CODE, CSF_SPPRT_KEY))
/

