create table vmscms.CMS_RENEWAL_CONFIG
(
CRC_PROD_CODE VARCHAR2(6) NOT NULL,
CRC_CARD_TYPE NUMBER(2) NOT NULL,
CRC_CARD_STAT VARCHAR2(2) NOT NULL,
CRC_INST_CODE NUMBER(3) NOT NULL,
CRC_INS_DATE  DATE NOT NULL,
CRC_INS_USER  NUMBER(5) NOT NULL,
CRC_LUPD_DATE DATE,
CRC_LUPD_USER NUMBER(5),
CONSTRAINT FK_RENEWALCONFIG_INSTMAST FOREIGN KEY (CRC_INST_CODE) REFERENCES vmscms.CMS_INST_MAST (CIM_INST_CODE),
CONSTRAINT FK_RENEWALCONFIG_USERMAST FOREIGN KEY (CRC_INS_USER) REFERENCES vmscms.CMS_USER_MAST (CUM_USER_PIN),
CONSTRAINT FK_RENEWALCONFIG_PRODCATTYPE FOREIGN KEY (CRC_INST_CODE,CRC_PROD_CODE,CRC_CARD_TYPE) REFERENCES vmscms.CMS_PROD_CATTYPE (CPC_INST_CODE,CPC_PROD_CODE,CPC_CARD_TYPE)
) tablespace cms_sml_txn;


