CREATE TABLE VMSCMS.CMS_TIEREDPLAN_COMMISSION
(
  CTC_INST_CODE     NUMBER(3),
  CTC_PLAN_ID       VARCHAR2(5 BYTE),
  CTC_TIERED_ID     VARCHAR2(5 BYTE),
  CTC_TIRED_TYPE    VARCHAR2(1 BYTE),
  CTC_FROM          VARCHAR2(9 BYTE),
  CTC_TO            VARCHAR2(9 BYTE),
  CTC_PLAN_AMT      NUMBER(10,4),
  CTC_PLAN_PERCENT  NUMBER(3),
  CTC_INS_USER      NUMBER(5),
  CTC_INS_DATE      DATE,
  CTC_LUPD_USER     NUMBER(5),
  CTC_LUPD_DATE     DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TIEREDPLAN_COMMISSION ADD (
  CONSTRAINT FK_TIEREDPLAN_PLANID 
 FOREIGN KEY (CTC_INST_CODE, CTC_PLAN_ID) 
 REFERENCES VMSCMS.CMS_COMMISSION_PLAN (CCP_INST_CODE,CCP_PLAN_ID))
/

