CREATE TABLE VMSCMS.CMS_IP_BLOCKLIST
(
  CIB_INST_CODE   NUMBER(3)                     NOT NULL,
  CIB_IP_ADDRESS  VARCHAR2(40 BYTE)             NOT NULL,
  CIB_INS_USER    NUMBER(5)                     NOT NULL,
  CIB_INS_DATE    DATE                          NOT NULL,
  CIB_LUPD_USER   NUMBER(5)                     NOT NULL,
  CIB_LUPD_DATE   DATE                          NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_IP_BLOCKLIST ADD (
  CONSTRAINT PK_CIB_INST_CODE
 PRIMARY KEY
 (CIB_INST_CODE, CIB_IP_ADDRESS))
/

ALTER TABLE VMSCMS.CMS_IP_BLOCKLIST ADD (
  CONSTRAINT FK_CIB_INS_USER 
 FOREIGN KEY (CIB_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CIB_LUPD_USER 
 FOREIGN KEY (CIB_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

