CREATE TABLE VMSCMS.CMS_FEEPLAN_DTL
(
  CFD_INST_CODE  NUMBER(3)                      NOT NULL,
  CFD_PLAN_CODE  VARCHAR2(6 BYTE)               NOT NULL,
  CFD_FEE_CODE   NUMBER(3)                      NOT NULL,
  CFD_INS_USER   NUMBER(5),
  CFD_INS_DATE   DATE,
  CFD_LUPD_USER  NUMBER(5),
  CFD_LUPD_DATE  DATE,
  CFD_FEE_DESC   VARCHAR2(50 BYTE)              DEFAULT 'N'                   NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FEEPLAN_DTL ADD (
  CONSTRAINT UK_CMS_FEEPLAN_DTL
 UNIQUE (CFD_INST_CODE, CFD_PLAN_CODE, CFD_FEE_CODE))
/

ALTER TABLE VMSCMS.CMS_FEEPLAN_DTL ADD (
  CONSTRAINT FK_FEEPLAN_MAST_DTL 
 FOREIGN KEY (CFD_INST_CODE, CFD_PLAN_CODE) 
 REFERENCES VMSCMS.CMS_FEEPLAN_MAST (CFM_INST_CODE,CFM_PLAN_CODE))
/

