CREATE TABLE VMSCMS.CMS_AUDIT_LOG_PROCESS
(
  CAL_INST_CODE      NUMBER(3),
  CAL_APPL_NO        VARCHAR2(30 BYTE),
  CAL_ACCT_NO        VARCHAR2(30 BYTE),
  CAL_PAN_NO         VARCHAR2(100 BYTE),
  CAL_PROD_CODE      VARCHAR2(35 BYTE),
  CAL_PRG_NAME       VARCHAR2(100 BYTE),
  CAL_ACTION         VARCHAR2(20 BYTE),
  CAL_STATUS         VARCHAR2(20 BYTE),
  CAL_IP_ADDRESS     VARCHAR2(15 BYTE),
  CAL_REF_TAB_NAME   VARCHAR2(30 BYTE),
  CAL_REF_TAB_ROWID  VARCHAR2(10 BYTE),
  CAL_PAN_ENCR       RAW(100),
  CAL_INS_USER       VARCHAR2(15 BYTE),
  CAL_INS_DATE       DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


