CREATE TABLE VMSCMS.CMS_RECEIPT_INVENTORY
(
  CRI_RECEIPT_ID        NUMBER,
  CRI_BRANCH_CODE       VARCHAR2(5 BYTE),
  CRI_RECEIPT_DATE      DATE,
  CRI_RECEIPT_TOTAL     NUMBER,
  CRI_FROMCARD_NO       VARCHAR2(90 BYTE),
  CRI_TOCARD_NO         VARCHAR2(90 BYTE),
  CRI_REF_NO            VARCHAR2(9 BYTE),
  CRI_LUPD_DATE         DATE,
  CRI_INST_CODE         NUMBER(10),
  CRI_LUPD_USER         NUMBER(10),
  CRI_INS_DATE          DATE,
  CRI_INS_USER          NUMBER(10),
  CRI_FROMCARD_NO_ENCR  RAW(100),
  CRI_TOCARD_NO_ENCR    RAW(100)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


