CREATE TABLE VMSCMS.CMS_QUICK_LINKS
(
  CQL_USER_PIN   NUMBER(4)                      NOT NULL,
  CQL_PROG_CODE  NUMBER(4)                      NOT NULL,
  CQL_SEQ_NUM    VARCHAR2(12 BYTE),
  CQL_LUPD_DATE  DATE,
  CQL_INST_CODE  NUMBER(10),
  CQL_LUPD_USER  NUMBER(10),
  CQL_INS_DATE   DATE,
  CQL_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


