CREATE TABLE VMSCMS.CMS_OP_FORMAT_MAST
(
  COM_FORMAT_ID           NUMBER(10),
  COM_INST_CODE           NUMBER(3),
  COM_INS_USER            NUMBER(5),
  COM_INS_DATE            DATE,
  COM_LUPD_USER           NUMBER(5),
  COM_LUPD_DATE           DATE,
  COM_FORMAT_DESC         VARCHAR2(100 BYTE),
  COM_SHRT_NAME           VARCHAR2(20 BYTE),
  COM_FILE_FORMAT         VARCHAR2(3 BYTE),
  COM_HEADER_FLAG         VARCHAR2(1 BYTE),
  COM_FOOTER_FLAG         VARCHAR2(1 BYTE),
  COM_HEADER_DEFIN        VARCHAR2(10 BYTE),
  COM_HEADER_POSN         NUMBER(3),
  COM_HEADER_DATA_LINE    NUMBER(3),
  COM_DATA_DATA_LINE      NUMBER(3),
  COM_DATA_FOOTER_LINE    NUMBER(3),
  COM_HEADER_BEGIN_FLAG   VARCHAR2(1 BYTE),
  COM_FOOTER_BEGIN_FLAG   VARCHAR2(1 BYTE),
  COM_DATA_BEGIN_FLAG     VARCHAR2(1 BYTE),
  COM_DELIMITER           VARCHAR2(1 BYTE),
  COM_FOOTER_TYPE         VARCHAR2(1 BYTE),
  COM_CTRL_NUM            NUMBER(2),
  COM_HEADER_BEGIN_CONST  VARCHAR2(5 BYTE),
  COM_FOOTER_BEGIN_CONST  VARCHAR2(5 BYTE),
  COM_DATA_BEGIN_CONST    VARCHAR2(5 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_OP_FORMAT_MAST ADD (
  CONSTRAINT PK_OP_FORMAT_ID
 PRIMARY KEY
 (COM_FORMAT_ID))
/

