CREATE TABLE VMSCMS.CMS_LOYL_DTL
(
  CLD_INST_CODE       NUMBER(3)                 NOT NULL,
  CLD_PAN_CODE        VARCHAR2(90 BYTE)         NOT NULL,
  CLD_MBR_NUMB        VARCHAR2(3 BYTE)          NOT NULL,
  CLD_ACCT_NO         VARCHAR2(20 BYTE)         NOT NULL,
  CLD_LOYL_CODE       NUMBER(3)                 NOT NULL,
  CLD_TRANS_AMT       NUMBER(15,6)              NOT NULL,
  CLD_LOYL_POINTS     NUMBER(5)                 NOT NULL,
  CLD_ADDON_PAN       VARCHAR2(90 BYTE),
  CLD_ADDON_MBR       VARCHAR2(3 BYTE),
  CLD_ID_COL          NUMBER(14)                NOT NULL,
  CLD_LOYL_TYPE       NUMBER(1),
  CLD_INS_USER        NUMBER(5)                 NOT NULL,
  CLD_INS_DATE        DATE                      NOT NULL,
  CLD_LUPD_USER       NUMBER(5)                 NOT NULL,
  CLD_LUPD_DATE       DATE                      NOT NULL,
  CLD_TRAN_DATE       DATE                      NOT NULL,
  CLD_ADDON_PAN_ENCR  RAW(100),
  CLD_PAN_CODE_ENCR   RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_LOYL_DTL ADD (
  CONSTRAINT PK_LOYL_DTL
 PRIMARY KEY
 (CLD_ID_COL))
/

ALTER TABLE VMSCMS.CMS_LOYL_DTL ADD (
  CONSTRAINT FK_LOYLDTL_INSTMAST 
 FOREIGN KEY (CLD_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_LOYLDTL_LOYLPOINTS 
 FOREIGN KEY (CLD_PAN_CODE, CLD_MBR_NUMB) 
 REFERENCES VMSCMS.CMS_LOYL_POINTS (CLP_PAN_CODE,CLP_MBR_NUMB),
  CONSTRAINT FK_LOYLDTL_USERMAST1 
 FOREIGN KEY (CLD_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_LOYLDTL_USERMAST2 
 FOREIGN KEY (CLD_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

