CREATE TABLE VMSCMS.CMS_TTUM_CTRL
(
  CTC_INST_CODE      NUMBER(3)                  NOT NULL,
  CTC_FILE_NAME      VARCHAR2(18 BYTE)          NOT NULL,
  CTC_FILE_TYPE      CHAR(1 BYTE),
  CTC_TOT_ROWS       NUMBER                     NOT NULL,
  CTC_TOT_AMT        NUMBER(15,2)               NOT NULL,
  CTC_FILE_INUSE     CHAR(1 BYTE)               NOT NULL,
  CTC_FILE_GEN       CHAR(1 BYTE)               NOT NULL,
  CTC_FILE_GENDATE   DATE,
  CTC_FAIL_ROWS      NUMBER(15),
  CTC_FAIL_PROCDATE  DATE,
  CTC_INS_USER       NUMBER(5)                  NOT NULL,
  CTC_INS_DATE       DATE                       NOT NULL,
  CTC_LUPD_USER      NUMBER(5)                  NOT NULL,
  CTC_LUPD_DATE      DATE                       NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TTUM_CTRL ADD (
  CONSTRAINT PK_TTUM_CTRL
 PRIMARY KEY
 (CTC_INST_CODE, CTC_FILE_NAME))
/

ALTER TABLE VMSCMS.CMS_TTUM_CTRL ADD (
  CONSTRAINT FK_TTUMCTRL_USERMAST2 
 FOREIGN KEY (CTC_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_TTUMCTRL_INSTMAST 
 FOREIGN KEY (CTC_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_TTUMCTRL_USERMAST1 
 FOREIGN KEY (CTC_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

