CREATE TABLE VMSCMS.CMS_PTLF_TIP_TRANS
(
  CPT_CRD_NUM          VARCHAR2(19 BYTE),
  CPT_AMT              VARCHAR2(19 BYTE),
  CPT_TERM_ID          VARCHAR2(16 BYTE),
  CPT_MER_NAME_LOC     VARCHAR2(40 BYTE),
  CPT_RRN_SEQ_NUM      VARCHAR2(12 BYTE),
  CPT_TRAN_DAT         VARCHAR2(6 BYTE),
  CPT_ACQ_INST_ID_NUM  VARCHAR2(11 BYTE),
  CPT_RESP_CDE         VARCHAR2(3 BYTE),
  CPT_TRAN_TIM         VARCHAR2(8 BYTE),
  CPT_TIP_FLAG         CHAR(1 BYTE)             DEFAULT 'N'                   NOT NULL,
  CPT_INS_USER         NUMBER(5)                NOT NULL,
  CPT_INS_DATE         DATE                     NOT NULL,
  CPT_LUPD_USER        NUMBER(5)                NOT NULL,
  CPT_LUPD_DATE        DATE                     NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


