CREATE TABLE VMSCMS.CMS_DEK_INDEX_PARAM
(
  CDI_INST_CODE          NUMBER(3),
  CDI_KEY_OF             VARCHAR2(3 BYTE),
  CDI_CURRENT_DEK_INDEX  VARCHAR2(3 BYTE),
  CDI_NEW_DEK_INDEX      VARCHAR2(3 BYTE),
  CDI_INS_USER           NUMBER(5),
  CDI_INS_DATE           DATE,
  CDI_LUPD_USER          NUMBER(5),
  CDI_LUPD_DATE          DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_DEK_INDEX_PARAM ADD (
  CONSTRAINT PK_DEK_INDEX_PARAM
 PRIMARY KEY
 (CDI_KEY_OF))
/

ALTER TABLE VMSCMS.CMS_DEK_INDEX_PARAM ADD (
  CONSTRAINT FK_DEK_INDEX_NEW 
 FOREIGN KEY (CDI_NEW_DEK_INDEX) 
 REFERENCES VMSCMS.CMS_DEK_KEY_DETAIL (CDK_DEK_INDEX),
  CONSTRAINT FK_DEK_INDEX_CURRENT 
 FOREIGN KEY (CDI_CURRENT_DEK_INDEX) 
 REFERENCES VMSCMS.CMS_DEK_KEY_DETAIL (CDK_DEK_INDEX))
/

