CREATE TABLE VMSCMS.CMS_DEF_LOYL
(
  CDL_INST_CODE   NUMBER(3)                     NOT NULL,
  CDL_LOYL_CODE   NUMBER(3)                     NOT NULL,
  CDL_TRANS_AMT   NUMBER(12,2)                  NOT NULL,
  CDL_LOYL_POINT  NUMBER(1)                     NOT NULL,
  CDL_INS_USER    NUMBER(5)                     NOT NULL,
  CDL_INS_DATE    DATE                          NOT NULL,
  CDL_LUPD_USER   NUMBER(5)                     NOT NULL,
  CDL_LUPD_DATE   DATE                          NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_DEF_LOYL ADD (
  CONSTRAINT PK_DEF_LOYL
 PRIMARY KEY
 (CDL_INST_CODE, CDL_LOYL_CODE))
/

ALTER TABLE VMSCMS.CMS_DEF_LOYL ADD (
  CONSTRAINT FK_DEFLOYL_LOYLMAST 
 FOREIGN KEY (CDL_INST_CODE, CDL_LOYL_CODE) 
 REFERENCES VMSCMS.CMS_LOYL_MAST (CLM_INST_CODE,CLM_LOYL_CODE),
  CONSTRAINT FK_DEFLOYL_USERMAST1 
 FOREIGN KEY (CDL_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_DEFLOYL_USERMAST2 
 FOREIGN KEY (CDL_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

