CREATE TABLE VMSCMS.CMS_BATCHPROCESS_CTRL
(
  CBC_FILE_NAME     VARCHAR2(35 BYTE),
  CBC_FILE_TYPE     VARCHAR2(30 BYTE),
  CBC_TOT_ROWS      NUMBER(8),
  CBC_PROCESS_USER  NUMBER(5),
  CBC_PROCESS_DATE  DATE,
  CBC_UPLOAD_USER   NUMBER(5),
  CBC_UPLOAD_DATE   DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


