CREATE TABLE VMSCMS.CMS_TARGETMERCH_MAST
(
  CTM_MERCHANT_NAME  VARCHAR2(50 BYTE),
  CTM_INST_CODE      NUMBER(3),
  CTM_INS_DATE       DATE,
  CTM_INS_USER       NUMBER(10),
  CTM_LUPD_DATE      DATE,
  CTM_LUPD_USER      NUMBER(10)
)
TABLESPACE CMS_DEFAULT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TARGETMERCH_MAST ADD (
  CONSTRAINT PK_TARGETMERCH_MAST
 PRIMARY KEY
 (CTM_INST_CODE, CTM_MERCHANT_NAME))
/

