CREATE TABLE VMSCMS.CMS_SAVINGSACCT_CONSTRUCT
(
  CSC_INST_CODE     VARCHAR2(5 BYTE),
  CSC_PROFILE_CODE  VARCHAR2(5 BYTE),
  CSC_FIELD_NAME    VARCHAR2(50 BYTE),
  CSC_START         VARCHAR2(3 BYTE)            DEFAULT 1,
  CSC_LENGTH        VARCHAR2(3 BYTE),
  CSC_VALUE         VARCHAR2(5 BYTE),
  CSC_TOT_LENGTH    VARCHAR2(3 BYTE),
  CSC_ORDER_BY      VARCHAR2(2 BYTE),
  CSC_START_FROM    VARCHAR2(3 BYTE),
  CSC_LUPD_DATE     DATE,
  CSC_LUPD_USER     NUMBER(10),
  CSC_INS_DATE      DATE,
  CSC_INS_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SAVINGSACCT_CONSTRUCT ADD (
  CONSTRAINT CK_CSC_START
 CHECK (CSC_START =1))
/

ALTER TABLE VMSCMS.CMS_SAVINGSACCT_CONSTRUCT ADD (
  CONSTRAINT FK_PROFILECODE 
 FOREIGN KEY (CSC_PROFILE_CODE) 
 REFERENCES VMSCMS.CMS_PROFILE_MAST (CPM_PROFILE_CODE))
/

