CREATE TABLE VMSCMS.CMS_AUDIT_TRAIL
(
  CAT_INST_CODE    NUMBER(3),
  CAT_USER_CODE    NUMBER(5),
  CAT_ACTION_DATE  DATE,
  CAT_OBJECT_NAME  VARCHAR2(250 BYTE),
  CAT_OBJECT_TYPE  VARCHAR2(10 BYTE),
  CAT_LUPD_DATE    DATE,
  CAT_LUPD_USER    NUMBER(10),
  CAT_INS_DATE     DATE,
  CAT_INS_USER     NUMBER(10),
  CAT_IP_ADDR      VARCHAR2(15 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


