CREATE TABLE VMSCMS.CMS_PRODPACKAGE_MAPPING_TEMP
(
  CPM_INS_USER             NUMBER(5)            NOT NULL,
  CPM_INS_DATE             DATE                 NOT NULL,
  CPM_LUPD_USER            NUMBER(5)            NOT NULL,
  CPM_INST_CODE            NUMBER(3)            NOT NULL,
  CPM_LUPD_DATE            DATE                 NOT NULL,
  CPM_PROD_CODE            VARCHAR2(6 BYTE)     NOT NULL,
  CPM_PRODPACK_FLAG        VARCHAR2(30 BYTE)    NOT NULL,
  CPM_DEFAULT_PRODPACK_ID  VARCHAR2(1 BYTE)     NOT NULL,
  CPM_PRODPACK_IDS         VARCHAR2(4 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PRODPACKAGE_MAPPING_TEMP ADD (
  CONSTRAINT CMS_PRODPACKAGE_MAP_TMP_C_FK1 
 FOREIGN KEY (CPM_INST_CODE, CPM_PROD_CODE) 
 REFERENCES VMSCMS.CMS_PROD_MAST (CPM_INST_CODE,CPM_PROD_CODE))
/

