CREATE TABLE VMSCMS.CMS_SPPRT_CATG
(
  CSC_INST_CODE  NUMBER(3)                      NOT NULL,
  CSC_PROD_CATG  VARCHAR2(2 BYTE)               NOT NULL,
  CSC_SPPRT_KEY  VARCHAR2(6 BYTE)               NOT NULL,
  CSC_LUPD_DATE  DATE,
  CSC_LUPD_USER  NUMBER(10),
  CSC_INS_DATE   DATE,
  CSC_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SPPRT_CATG ADD (
  CONSTRAINT PK_SPPRT_CATG
 PRIMARY KEY
 (CSC_INST_CODE, CSC_PROD_CATG, CSC_SPPRT_KEY))
/

ALTER TABLE VMSCMS.CMS_SPPRT_CATG ADD (
  CONSTRAINT FK_SPPRTCATG_SPPRTFUNCS 
 FOREIGN KEY (CSC_INST_CODE, CSC_SPPRT_KEY) 
 REFERENCES VMSCMS.CMS_SPPRT_FUNCS (CSF_INST_CODE,CSF_SPPRT_KEY),
  CONSTRAINT FK_SPPRTCATG_PRODCATG 
 FOREIGN KEY (CSC_INST_CODE, CSC_PROD_CATG) 
 REFERENCES VMSCMS.CMS_PROD_CATG (CPC_INST_CODE,CPC_CATG_CODE))
/

