CREATE TABLE VMSCMS.CMS_RWRD_MAST
(
  CRM_INST_CODE    NUMBER(3)                    NOT NULL,
  CRM_RWRD_CODE    NUMBER(3)                    NOT NULL,
  CRM_LOYL_POINTS  NUMBER(5)                    NOT NULL,
  CRM_RWRD_DESC    VARCHAR2(35 BYTE),
  CRM_REDM_AMT     NUMBER(15,2)                 NOT NULL,
  CRM_INS_USER     NUMBER(5)                    NOT NULL,
  CRM_INS_DATE     DATE                         NOT NULL,
  CRM_LUPD_USER    NUMBER(5)                    NOT NULL,
  CRM_LUPD_DATE    DATE                         NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_RWRD_MAST ADD (
  CONSTRAINT PK_RWRD_MAST
 PRIMARY KEY
 (CRM_INST_CODE, CRM_RWRD_CODE))
/

ALTER TABLE VMSCMS.CMS_RWRD_MAST ADD (
  CONSTRAINT FK_RWRDMAST_USERMAST1 
 FOREIGN KEY (CRM_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_RWRDMAST_USERMAST2 
 FOREIGN KEY (CRM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_RWRDMAST_INSTMAST 
 FOREIGN KEY (CRM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

