CREATE TABLE VMSCMS.CMS_DAILY_BIN_BAL
(
  CDB_INST_CODE  NUMBER(3),
  CDB_BIN_CODE   NUMBER(6),
  CDB_DATE       DATE,
  CDB_BALANCE    NUMBER(20,3),
  CDB_INS_USER   NUMBER(5),
  CDB_INS_DATE   DATE,
  CDB_LUPD_USER  NUMBER(5),
  CDB_LUPD_DATE  DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


