CREATE TABLE VMSCMS.CMS_UNRECON_TIP_TRANS
(
  CUT_CRD_NUM         VARCHAR2(19 BYTE),
  CUT_AMT             VARCHAR2(19 BYTE),
  CUT_TERM_ID         VARCHAR2(16 BYTE),
  CUT_MER_NAME_LOC    VARCHAR2(40 BYTE),
  CUT_RRN_SEQ_NUM     VARCHAR2(12 BYTE),
  CUT_TRAN_DAT        VARCHAR2(6 BYTE),
  CUT_INS_DATE        DATE,
  CUT_INS_USER        NUMBER(5),
  CUT_PROCESS_DATE    DATE,
  CUT_PROCESS_RESULT  VARCHAR2(300 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


