CREATE TABLE VMSCMS.CMS_AD_ERRMSG
(
  CAE_INST_CODE   NUMBER(3),
  CAE_ERROR_CODE  VARCHAR2(5 BYTE),
  CAE_ERROR_DESC  VARCHAR2(100 BYTE),
  CAE_INST_DATE   DATE,
  CAE_INS_USER    NUMBER(5)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


