CREATE TABLE VMSCMS.CMS_AUTH_DELIVERYCHANNEL
(
  CAD_DELIVERY_CHANNEL  VARCHAR2(4 BYTE),
  CAD_PIN_CLASSNAME     VARCHAR2(100 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


