CREATE TABLE VMSCMS.CMS_FEEPLAN_PROD_MAPG
(
  CFM_PLAN_ID    NUMBER(4)                      NOT NULL,
  CFM_PROD_CODE  VARCHAR2(6 BYTE)               NOT NULL,
  CFM_INST_CODE  NUMBER(3)                      NOT NULL,
  CFM_INS_USER   NUMBER(10)                     NOT NULL,
  CFM_INS_DATE   DATE                           NOT NULL,
  CFM_LUPD_USER  NUMBER(10),
  CFM_LUPD_DATE  DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FEEPLAN_PROD_MAPG ADD (
  CONSTRAINT FK_FEE_PLAN_ID 
 FOREIGN KEY (CFM_INST_CODE, CFM_PLAN_ID) 
 REFERENCES VMSCMS.CMS_FEE_PLAN (CFP_INST_CODE,CFP_PLAN_ID),
  CONSTRAINT FK_FEE_PLAN_PRODUCT 
 FOREIGN KEY (CFM_INST_CODE, CFM_PROD_CODE) 
 REFERENCES VMSCMS.CMS_PROD_MAST (CPM_INST_CODE,CPM_PROD_CODE))
/

