CREATE TABLE VMSCMS.CMS_CLOSED_ACCTS
(
  CCA_INST_CODE  NUMBER(3),
  CCA_CUST_CODE  NUMBER(10),
  CCA_ACCT_ID    NUMBER(10),
  CCA_INS_USER   NUMBER(5),
  CCA_INS_DATE   DATE,
  CCA_LUPD_USER  NUMBER(5),
  CCA_LUPD_DATE  DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


