CREATE TABLE VMSCMS.CMS_GROUP_PROG
(
  CGP_INST_CODE   NUMBER(3)                     NOT NULL,
  CGP_GROUP_CODE  NUMBER(3)                     NOT NULL,
  CGP_PROG_CODE   NUMBER(4)                     NOT NULL,
  CGP_INSR_ALLOW  NUMBER(1),
  CGP_DELE_ALLOW  NUMBER(1),
  CGP_UPDT_ALLOW  NUMBER(1),
  CGP_INS_USER    NUMBER(5)                     NOT NULL,
  CGP_INS_DATE    DATE                          NOT NULL,
  CGP_LUPD_USER   NUMBER(5)                     NOT NULL,
  CGP_LUPD_DATE   DATE                          NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GROUP_PROG ADD (
  CONSTRAINT PK_GROUP_PROG
 PRIMARY KEY
 (CGP_INST_CODE, CGP_GROUP_CODE, CGP_PROG_CODE))
/

ALTER TABLE VMSCMS.CMS_GROUP_PROG ADD (
  CONSTRAINT FK_GROUPPROG_USERGROUP 
 FOREIGN KEY (CGP_INST_CODE, CGP_GROUP_CODE) 
 REFERENCES VMSCMS.CMS_USER_GROUP (CUG_INST_CODE,CUG_GROUP_CODE),
  CONSTRAINT FK_GROUPPROG_USERMAST2 
 FOREIGN KEY (CGP_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_GROUPPROG_USERMAST1 
 FOREIGN KEY (CGP_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_GROUPPROG_PROGMAST 
 FOREIGN KEY (CGP_INST_CODE, CGP_PROG_CODE) 
 REFERENCES VMSCMS.CMS_PROG_MAST (CPM_INST_CODE,CPM_PROG_CODE))
/

