CREATE TABLE VMSCMS.CMS_BATCHUPLOAD_DETL
(
  CBD_TRAN_CODE           VARCHAR2(3 BYTE),
  CBD_PROXY_NUMBER        VARCHAR2(20 BYTE),
  CBD_TRAN_AMT            NUMBER(18,2),
  CBD_CRDR_FLAG           VARCHAR2(2 BYTE),
  CBD_SSN                 VARCHAR2(40 BYTE),
  CDB_BIRTH_DATE          DATE,
  CBD_FIRST_NAME          VARCHAR2(40 BYTE),
  CBD_MIDDLE_NAME         VARCHAR2(40 BYTE),
  CBD_LAST_NAME           VARCHAR2(40 BYTE),
  CBD_PHYADDR_LINE1       VARCHAR2(50 BYTE),
  CBD_PHYADDR_LINE2       VARCHAR2(50 BYTE),
  CBD_PHYCITY_NAME        VARCHAR2(40 BYTE),
  CBD_PHYPOSTAL_CODE      VARCHAR2(15 BYTE),
  CBD_PHONE_NUMBER        VARCHAR2(40 BYTE),
  CBD_OTHER_PHNO          VARCHAR2(40 BYTE),
  CBD_EMAIL_ID            VARCHAR2(50 BYTE),
  CBD_PHYSTATE_CODE       VARCHAR2(3 BYTE),
  CBD_PHYCNTRY_CODE       VARCHAR2(3 BYTE),
  CBD_MLGADDR_LINE1       VARCHAR2(50 BYTE),
  CBD_MLGADDR_LINE2       VARCHAR2(50 BYTE),
  CBD_MLGCITY_NAME        VARCHAR2(40 BYTE),
  CBD_MLGPOSTAL_CODE      VARCHAR2(15 BYTE),
  CBD_MLGSTATE_CODE       VARCHAR2(3 BYTE),
  CBD_MLGCNTRY_CODE       VARCHAR2(3 BYTE),
  CBD_RESPONSE_CODE       VARCHAR2(7 BYTE)      NOT NULL,
  CBD_RESPONSE_DESC       VARCHAR2(500 BYTE)    NOT NULL,
  CBD_FILE_NAME           VARCHAR2(50 BYTE)     NOT NULL,
  CBD_INS_DATE            DATE                  NOT NULL,
  CBD_INST_CODE           NUMBER(3)             NOT NULL,
  CBD_INS_USER            NUMBER(5)             NOT NULL,
  CBD_RRN                 VARCHAR2(20 BYTE)     NOT NULL,
  CBD_OPTINOPTOUT_STATUS  CHAR(1 BYTE),
  CBD_OPTINOPTOUT_DATE    DATE,
  CBD_RESON_CODE          VARCHAR2(6),
  CBD_COMMENT             VARCHAR2(100),
  CBD_MERCHANT_NAME       VARCHAR2(50),
  CBD_PINGEN_FLAG         VARCHAR2(1),
  CBD_PAN_CODE_ENCR       RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


