CREATE TABLE VMSCMS.CMS_ACCT_CTRL
(
  CAC_INST_CODE      NUMBER(3),
  CAC_BRAN_CODE      VARCHAR2(18 BYTE),
  CAC_CTRL_NUMB      VARCHAR2(10 BYTE),
  CAC_MAX_SERIAL_NO  NUMBER(12),
  CAC_LUPD_DATE      DATE,
  CAC_LUPD_USER      NUMBER(10),
  CAC_INS_DATE       DATE,
  CAC_INS_USER       NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


