CREATE TABLE vmscms.CMS_SCORECARD_MAPPING
(
  CSM_INST_CODE NUMBER(3, 0) NOT NULL,
  CSM_SCORECARD_ID NUMBER NOT NULL,
  CSM_PROD_CODE VARCHAR2(6 BYTE) NOT NULL,
  CSM_CARD_TYPE NUMBER(3, 0) NOT NULL,
  CSM_DELIVERY_CHANNEL varchar2(100) NOT NULL, 
  CSM_INS_USER NUMBER(5, 0) NOT NULL,
  CSM_INS_DATE DATE NOT NULL,
  CSM_LUPD_USER NUMBER(5, 0),
  CSM_LUPD_DATE DATE,
  constraint PK_SCORECARD_MAPPING primary key(CSM_INST_CODE,CSM_PROD_CODE,CSM_CARD_TYPE,CSM_DELIVERY_CHANNEL)  
)tablespace cms_mast;