CREATE TABLE VMSCMS.CMS_EMVPARM_MAST
(
  CEM_INST_CODE     NUMBER(3)                   NOT NULL,
  CEM_PARAM_KEY     VARCHAR2(30 BYTE)           NOT NULL,
  CEM_INST_BIN      NUMBER                      NOT NULL,
  CEM_PARAM_DESC    VARCHAR2(50 BYTE)           NOT NULL,
  CEM_PARAM_VALUE   VARCHAR2(50 BYTE)           NOT NULL,
  CEM_PARAM_TYPE    VARCHAR2(1 BYTE)            NOT NULL,
  CEM_INS_USER      NUMBER(5)                   NOT NULL,
  CEM_INS_DATE      DATE                        NOT NULL,
  CEM_LUPD_USER     NUMBER(5)                   NOT NULL,
  CEM_LUPD_DATE     DATE                        NOT NULL,
  CEM_PARAM_ORDER   NUMBER(2)                   DEFAULT 0,
  CEM_PARAM_ORDER1  NUMBER(2)                   DEFAULT 0
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_EMVPARM_MAST ADD (
  CONSTRAINT PK_EMVPARM_MAST
 PRIMARY KEY
 (CEM_INST_CODE, CEM_PARAM_KEY, CEM_INST_BIN))
/

