CREATE TABLE VMSCMS.CMS_PAN_TRANS_ATM
(
  CPT_INST_CODE      NUMBER(3)                  NOT NULL,
  CPT_ID_COL         NUMBER(14)                 NOT NULL,
  CPT_AUTH_CODE      VARCHAR2(8 BYTE),
  CPT_ARN_CODE       VARCHAR2(23 BYTE),
  CPT_MESG_TYPE      VARCHAR2(4 BYTE)           NOT NULL,
  CPT_TRANS_TYPE     NUMBER(1),
  CPT_TRANS_CODE     VARCHAR2(5 BYTE)           NOT NULL,
  CPT_REC_TYP        VARCHAR2(6 BYTE)           NOT NULL,
  CPT_TRANS_DATE     DATE                       NOT NULL,
  CPT_TRANS_TIME     DATE                       NOT NULL,
  CPT_TRANS_AMT      NUMBER(15,6),
  CPT_ACQ_BANK       VARCHAR2(11 BYTE),
  CPT_TERM_ID        VARCHAR2(12 BYTE),
  CPT_MCC_CODE       VARCHAR2(10 BYTE),
  CPT_MERC_ID        VARCHAR2(8 BYTE),
  CPT_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CPT_MBR_NUMB       VARCHAR2(3 BYTE)           NOT NULL,
  CPT_ACCT_NO        VARCHAR2(28 BYTE)          NOT NULL,
  CPT_ADDON_STAT     CHAR(1 BYTE),
  CPT_ADDON_LINK     VARCHAR2(20 BYTE),
  CPT_MBR_LINK       VARCHAR2(3 BYTE),
  CPT_PROD_CODE      VARCHAR2(6 BYTE),
  CPT_CARD_TYPE      NUMBER(2),
  CPT_CUST_CODE      NUMBER(10),
  CPT_CUST_CATG      NUMBER(5),
  CPT_LOYL_CALC      CHAR(1 BYTE),
  CPT_LOYL_CALCDATE  DATE,
  CPT_INS_USER       NUMBER(5)                  NOT NULL,
  CPT_INS_DATE       DATE                       NOT NULL,
  CPT_LUPD_USER      NUMBER(5)                  NOT NULL,
  CPT_LUPD_DATE      DATE                       NOT NULL,
  CPT_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


