CREATE TABLE VMSCMS.CMS_ERROR_LOG
(
  CEL_INST_CODE    NUMBER(3),
  CEL_FILE_NAME    VARCHAR2(35 BYTE),
  CEL_ROW_ID       VARCHAR2(5 BYTE),
  CEL_ERROR_CNT    NUMBER(3),
  CEL_ERROR_MESG   VARCHAR2(500 BYTE)           NOT NULL,
  CEL_PROB_ACTION  VARCHAR2(100 BYTE),
  CEL_LUPD_USER    NUMBER(5)                    NOT NULL,
  CEL_LUPD_DATE    DATE                         NOT NULL,
  CEL_PROCESS_ID   NUMBER(10),
  CEL_INS_DATE     DATE,
  CEL_INS_USER     NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


