CREATE TABLE VMSCMS.CMS_GROUP_CLOSE
(
  CGC_PAN_CODE       VARCHAR2(90 BYTE),
  CGC_PIN_CLOSE      VARCHAR2(1 BYTE)           DEFAULT 'N',
  CGC_FILE_NAME      VARCHAR2(30 BYTE),
  CGC_REMARK         VARCHAR2(100 BYTE),
  CGC_RESULT         VARCHAR2(500 BYTE)         DEFAULT 'NOT PROCESSED',
  CGC_INS_DATE       DATE,
  CGC_MBR_NUMB       VARCHAR2(3 BYTE)           DEFAULT '000',
  CGC_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


