CREATE TABLE VMSCMS.CMS_GROUP_ROLE
(
  CGR_INST_CODE  NUMBER(5),
  CGR_GRUP_CODE  NUMBER(5),
  CGR_GRUP_NAME  VARCHAR2(40 BYTE),
  CGR_ROLE_CODE  NUMBER(5),
  CGR_ROLE_NAME  VARCHAR2(50 BYTE),
  CGR_INS_USER   NUMBER(5)                      NOT NULL,
  CGR_INS_DATE   DATE                           NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GROUP_ROLE ADD (
  CONSTRAINT PK_CGR_GROUPROLE_CODE
 PRIMARY KEY
 (CGR_INST_CODE, CGR_GRUP_CODE, CGR_ROLE_CODE))
/

ALTER TABLE VMSCMS.CMS_GROUP_ROLE ADD (
  CONSTRAINT FK_CGR_INS_USER 
 FOREIGN KEY (CGR_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_CGR_GROUPROLE_CODE 
 FOREIGN KEY (CGR_INST_CODE, CGR_ROLE_CODE) 
 REFERENCES VMSCMS.CMS_ROLE_MAST (CRM_INST_CODE,CRM_ROLE_CODE),
  CONSTRAINT FK_CGR_ROLEGRUP_CODE 
 FOREIGN KEY (CGR_INST_CODE, CGR_GRUP_CODE) 
 REFERENCES VMSCMS.CMS_GROUPDETL_MAST (CGM_INST_CODE,CGM_GRUP_CODE),
  CONSTRAINT FK_CGR_INST_CODE 
 FOREIGN KEY (CGR_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

