CREATE TABLE VMSCMS.CMS_BINAUTH_PROCESS
(
  CBP_INST_CODE        NUMBER(3)                NOT NULL,
  CBP_BIN              NUMBER(10)               NOT NULL,
  CBP_PROCESS_KEY      VARCHAR2(20 BYTE),
  CBP_ENABLE_FLAG      VARCHAR2(10 BYTE),
  CBP_CLASS_PROCESS    VARCHAR2(100 BYTE),
  CBP_ORDER_EXECUTION  VARCHAR2(4 BYTE),
  CBP_INS_DATE         DATE,
  CBP_LUPD_DATE        DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


