CREATE TABLE VMSCMS.CMS_ACCT_DELINK_DETAIL
(
  CAD_INST_CODE      NUMBER(3),
  CAD_CARD_NO        VARCHAR2(90 BYTE),
  CAD_OLD_ACCT_NO    VARCHAR2(20 BYTE),
  CAD_NEW_ACCT_NO    VARCHAR2(20 BYTE),
  CAD_NEW_ACCT_TYPE  VARCHAR2(20 BYTE),
  CAD_NEW_ACCT_POSN  VARCHAR2(20 BYTE),
  CAD_FILE_NAME      VARCHAR2(30 BYTE),
  CAD_REMARKS        VARCHAR2(100 BYTE),
  CAD_MSG24_FLAG     CHAR(1 BYTE)               DEFAULT 'N',
  CAD_PROCESS_FLAG   VARCHAR2(1 BYTE),
  CAD_PROCESS_MSG    VARCHAR2(300 BYTE),
  CAD_PROCESS_MODE   VARCHAR2(1 BYTE),
  CAD_INS_USER       NUMBER(5),
  CAD_INS_DATE       DATE,
  CAD_LUPD_USER      NUMBER(5),
  CAD_LUPD_DATE      DATE,
  CAD_CARD_NO_ENCR   RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


