create table vmscms.CMS_SPILSERIAL_LOGGING
(
CSL_INST_CODE NUMBER(3,0),
CSL_PAN_CODE VARCHAR2(90),
CSL_DELIVERY_CHANNEL VARCHAR2(2),
CSL_TXN_CODE  VARCHAR2(2),
CSL_MSG_TYPE  VARCHAR2(10),
CSL_SERIAL_NUMBER  VARCHAR2(40),
CSL_AUTH_ID  VARCHAR2(14),
CSL_RESPONSE_CODE  VARCHAR2(7),
CSL_RRN VARCHAR2(20),
CSL_TIME_STAMP  TIMESTAMP(6)
) tablespace cms_big_txn;

CREATE INDEX VMSCMS.SPILSERIAL_INDEX ON vmscms.CMS_SPILSERIAL_LOGGING (CSL_INST_CODE, CSL_DELIVERY_CHANNEL, CSL_TXN_CODE, CSL_MSG_TYPE, CSL_SERIAL_NUMBER) TABLESPACE CMS_BIG_IDX;
