CREATE TABLE VMSCMS.CMS_FILEUPLOAD_DETL
(
  CFU_INST_CODE         NUMBER(5),
  CFU_PAN_CODE          VARCHAR2(90 BYTE),
  CFU_PAN_CODE_ENCR     RAW(100),
  CFU_FILE_TYPE         VARCHAR2(20 BYTE),
  CFU_FILE_PATH         VARCHAR2(100 BYTE),
  CFU_FILE_SIZE         VARCHAR2(50 BYTE),
  CFU_REF_NUMBER        VARCHAR2(20 BYTE),
  CFU_INS_DATE          DATE                    NOT NULL,
  CFU_INS_USER          NUMBER(5)               NOT NULL,
  CFU_LUPD_DATE         DATE,
  CFU_LUPD_USER         NUMBER(5),
  CFU_BUSINESS_DATE     VARCHAR2(8 BYTE),
  CFU_BUSINESS_TIME     VARCHAR2(10 BYTE),
  CFU_TXN_CODE          VARCHAR2(2 BYTE),
  CFU_DELIVERY_CHANNEL  VARCHAR2(2 BYTE),
  CFU_RRN               VARCHAR2(20 BYTE),
  CFU_ACCT_NO           VARCHAR2(20 BYTE),
  CFU_UPLOAD_STAT       VARCHAR2(1 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


