CREATE TABLE VMSCMS.CMS_ACCS_AUDT
(
  CAA_INST_CODE  NUMBER(5),
  CAA_GRUP_CODE  NUMBER(8),
  CAA_MENU_PATH  VARCHAR2(200 BYTE),
  CAA_ACCS_DESC  VARCHAR2(500 BYTE),
  CAA_IP_ADDR    VARCHAR2(15 BYTE),
  CAA_INS_USER   NUMBER(8)                      NOT NULL,
  CAA_INS_DATE   DATE                           NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ACCS_AUDT ADD (
  CONSTRAINT FK_CAA_LGIN_CUM_USRI 
 FOREIGN KEY (CAA_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_CAA_INST_CGM_GRUP 
 FOREIGN KEY (CAA_INST_CODE, CAA_GRUP_CODE) 
 REFERENCES VMSCMS.CMS_GROUPDETL_MAST (CGM_INST_CODE,CGM_GRUP_CODE),
  CONSTRAINT FK_CAA_LGIN_CIM_USID 
 FOREIGN KEY (CAA_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

