CREATE TABLE VMSCMS.CMS_CNTRYCODE_RULEGRP
(
  CCR_INST_CODE      NUMBER(10),
  CCR_CNTRY_GRPCODE  VARCHAR2(4 BYTE),
  CCR_GRPCODE_DESC   VARCHAR2(100 BYTE)         NOT NULL,
  CCR_GRPCODE_STUS   VARCHAR2(1 BYTE),
  CCR_LUPD_DATE      DATE,
  CCR_LUPD_USER      NUMBER(10),
  CCR_INS_DATE       DATE,
  CCR_INS_USER       NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CNTRYCODE_RULEGRP ADD (
  CONSTRAINT PK_CNTRYCODE_RULEGROUP
 PRIMARY KEY
 (CCR_CNTRY_GRPCODE))
/

