CREATE TABLE VMSCMS.CMS_GROUP_LIMITUPDATE_TEMP
(
  CUL_CARD_NO               VARCHAR2(90 BYTE),
  CUL_FILE_NAME             VARCHAR2(30 BYTE),
  CUL_REMARKS               VARCHAR2(100 BYTE),
  CUL_INS_DATE              DATE,
  CUL_INST_CODE             NUMBER(10),
  CUL_INS_USER              NUMBER(10),
  CUL_PROCESS_FLAG          VARCHAR2(1 BYTE),
  CUL_PROCESS_MSG           VARCHAR2(300 BYTE),
  CUL_MBR_NUMB              VARCHAR2(10 BYTE),
  CUL_ATM_ONLINE_LIMIT      VARCHAR2(10 BYTE),
  CUL_POS_ONLINE_LIMIT      VARCHAR2(10 BYTE),
  CUL_ATM_OFFLINE_LIMIT     VARCHAR2(10 BYTE),
  CUL_POS_OFFLINE_LIMIT     VARCHAR2(10 BYTE),
  CUL_UPDCARD_LIMIT_PARAM1  VARCHAR2(100 BYTE),
  CUL_UPDCARD_LIMIT_PARAM2  VARCHAR2(100 BYTE),
  CUL_CARD_NO_ENCR          RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


