CREATE TABLE VMSCMS.CMS_KEY_DETAILS
(
  CKD_KEY_NAME           VARCHAR2(200 BYTE),
  CKD_KEY_INDEX          VARCHAR2(3 BYTE),
  CKD_KEY_PASSWORD       VARCHAR2(200 BYTE),
  CKD_ENCRYPTED_AESKEY   VARCHAR2(200 BYTE),
  CKD_KEYSTORE_PASSWORD  VARCHAR2(200 BYTE),
  CKD_KEYSTORE_PATH      VARCHAR2(500 BYTE),
  CKD_ENCRYPTED_DES3KEY  VARCHAR2(200 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


