CREATE TABLE VMSCMS.CMS_ACHFILE_TXN_ERRLOG
(
  CAT_BATCH_NO      NUMBER(10),
  CAT_FILE_NAME     VARCHAR2(255 BYTE),
  CAT_REC_NO        NUMBER(10),
  CAT_PROXY_NO      VARCHAR2(20 BYTE),
  CAT_CUST_NAME     VARCHAR2(30 BYTE),
  CAT_TXN_TYPE      VARCHAR2(3 BYTE),
  CAT_TXN_AMT       NUMBER(20,2),
  CAT_SOURCE_SNAME  VARCHAR2(15 BYTE),
  CAT_SOURCE_FNAME  VARCHAR2(30 BYTE),
  CAT_PROCESS_DATE  DATE,
  CAT_ERR_CODE      VARCHAR2(3 BYTE),
  CAT_ERR_DESC      VARCHAR2(2000 BYTE)
)
TABLESPACE CMS_BIG_TXN;

create index VMSCMS.indx_achfile_txn_err on VMSCMS.CMS_ACHFILE_TXN_ERRLOG(cat_file_name) TABLESPACE CMS_BIG_IDX;