CREATE TABLE VMSCMS.CMS_SUB_GL_MAST_ORGNL
(
  CSM_INST_CODE    NUMBER(3),
  CSM_GL_CODE      VARCHAR2(20 BYTE),
  CSM_GLCATG_CODE  NUMBER(2),
  CSM_SUBGL_CODE   VARCHAR2(20 BYTE),
  CSM_SUBGL_DESC   VARCHAR2(50 BYTE),
  CSM_INS_DATE     DATE,
  CSM_LUPD_USER    NUMBER(5),
  CSM_LUPD_DATE    DATE,
  CSM_INS_USER     NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


