CREATE TABLE VMSCMS.CMS_REPORT_FIELDS_TEMP
(
  CRF_INST_CODE     NUMBER(3),
  CRF_FIELD_ID      VARCHAR2(20 BYTE),
  CRF_FIELD_NAME    VARCHAR2(30 BYTE),
  CRF_FIELD_COLUMN  VARCHAR2(30 BYTE),
  CRF_FIELD_TABLE   VARCHAR2(30 BYTE),
  CRF_INS_USER      NUMBER(5),
  CRF_INS_DATE      DATE,
  CRF_LUPD_USER     NUMBER(5),
  CRF_LUPD_DATE     DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


