CREATE TABLE VMSCMS.CMS_PROD_LMTPRFL
(
  CPL_INST_CODE   NUMBER(10),
  CPL_PROD_CODE   VARCHAR2(6 BYTE)              NOT NULL,
  CPL_LMTPRFL_ID  VARCHAR2(10 BYTE)             NOT NULL,
  CPL_LUPD_DATE   DATE                          NOT NULL,
  CPL_LUPD_USER   NUMBER(10)                    NOT NULL,
  CPL_INS_DATE    DATE                          NOT NULL,
  CPL_INS_USER    NUMBER(10)                    NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROD_LMTPRFL ADD (
  CONSTRAINT PK_CMS_PROD_LMTPRFL
 PRIMARY KEY
 (CPL_INST_CODE, CPL_PROD_CODE))
/

ALTER TABLE VMSCMS.CMS_PROD_LMTPRFL ADD (
  CONSTRAINT FK_INST_PROD 
 FOREIGN KEY (CPL_INST_CODE, CPL_PROD_CODE) 
 REFERENCES VMSCMS.CMS_PROD_MAST (CPM_INST_CODE,CPM_PROD_CODE),
  CONSTRAINT FK_CMS_PROD_LMTPRFL 
 FOREIGN KEY (CPL_INST_CODE, CPL_LMTPRFL_ID) 
 REFERENCES VMSCMS.CMS_LMTPRFL_MAST (CLM_INST_CODE,CLM_LMTPRFL_ID))
/

