CREATE TABLE VMSCMS.CMS_PURGE_REC
(
  CPR_PAN_CODE       VARCHAR2(90 BYTE),
  CPR_CARD_STAT      VARCHAR2(1 BYTE),
  CPR_ACCT_NO        VARCHAR2(20 BYTE),
  CPR_DISP_NAME      VARCHAR2(50 BYTE),
  CPR_PANGEN_DATE    DATE,
  CPR_PURGE_DATE     DATE,
  CPR_PURGE_FLAG     VARCHAR2(1 BYTE),
  CPR_PURGE_MSG      VARCHAR2(300 BYTE),
  CPR_MBR_NUMB       VARCHAR2(3 BYTE),
  CPR_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


