CREATE TABLE VMSCMS.CMS_PASSIVEPERIOD_FAIL_DTL
(
  CPD_INST_CODE         NUMBER(10),
  CPD_PAN_CODE          VARCHAR2(90 BYTE),
  CPD_PAN_CODE_ENCR     RAW(100),
  CPD_CURRTRAN_DATE     VARCHAR2(8 BYTE),
  CPD_CURRTRAN_TIME     VARCHAR2(8 BYTE),
  CPD_LASTTRAN_DATE     VARCHAR2(8 BYTE),
  CPD_LASTTRANTIME      VARCHAR2(8 BYTE),
  CPD_INS_USER          NUMBER(10),
  CPD_INS_DATE          DATE,
  CPD_LUPD_USER         NUMBER(10),
  CPD_LUPD_DATE         DATE,
  CPD_RESP_CODE         VARCHAR2(7 BYTE),
  CPD_PROCESS_MSG       VARCHAR2(300 BYTE),
  CPD_DELIVERY_CHANNEL  VARCHAR2(2 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


