CREATE TABLE VMSCMS.CMS_AUDIT_LOG_MAST
(
  CAT_INST_CODE  NUMBER(3),
  TOP_MENU_CODE  NUMBER(3),
  SUB_MENU_CODE  NUMBER(3),
  TOP_MENU_DESC  VARCHAR2(30 BYTE),
  SUB_MENU_DESC  VARCHAR2(30 BYTE),
  SUB_MENU_VIEW  VARCHAR2(30 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


