CREATE TABLE VMSCMS.CMS_STATUPD_LOG_FAILURE
(
  CSF_INST_CODE       NUMBER(3),
  CSF_PAN_CODE_ENCR   VARCHAR2(100 BYTE),
  CCS_PAN_CODE        VARCHAR2(90 BYTE),
  CSF_INS_DATE        DATE,
  CSF_FAILURE_REASON  VARCHAR2(2000 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


