CREATE TABLE VMSCMS.CMS_INVENTORYCATG_MAST
(
  CIM_INVENTORYCATG_CODE  VARCHAR2(10 BYTE),
  CIM_INVENTORYCATG_DESC  VARCHAR2(50 BYTE),
  CIM_INS_USER            NUMBER(5),
  CIM_INS_DATE            DATE,
  CIM_LUPD_USER           NUMBER(5),
  CIM_LUPD_DATE           DATE,
  CIM_INST_CODE           NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_INVENTORYCATG_MAST ADD (
  CONSTRAINT PK_INVENTORYCATG_MAST
 PRIMARY KEY
 (CIM_INVENTORYCATG_CODE))
/

