CREATE TABLE VMSCMS.CMS_PRODCCC_LOYL
(
  CPL_INST_CODE    NUMBER(3)                    NOT NULL,
  CPL_CUST_CATG    NUMBER(5)                    NOT NULL,
  CPL_CARD_TYPE    NUMBER(2)                    NOT NULL,
  CPL_PROD_CODE    VARCHAR2(6 BYTE)             NOT NULL,
  CPL_LOYL_CODE    NUMBER(3)                    NOT NULL,
  CPL_VALID_FROM   DATE                         NOT NULL,
  CPL_VALID_TO     DATE                         NOT NULL,
  CPL_FLOW_SOURCE  VARCHAR2(3 BYTE)             NOT NULL,
  CPL_INS_USER     NUMBER(5)                    NOT NULL,
  CPL_INS_DATE     DATE                         NOT NULL,
  CPL_LUPD_USER    NUMBER(5)                    NOT NULL,
  CPL_LUPD_DATE    DATE                         NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PRODCCC_LOYL ADD (
  CONSTRAINT FK_PRODCCCL_LOYLMAST 
 FOREIGN KEY (CPL_INST_CODE, CPL_LOYL_CODE) 
 REFERENCES VMSCMS.CMS_LOYL_MAST (CLM_INST_CODE,CLM_LOYL_CODE),
  CONSTRAINT FK_PRODCCCL_USERMAST1 
 FOREIGN KEY (CPL_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCCCL_USERMAST2 
 FOREIGN KEY (CPL_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCCCL_PRODCCC 
 FOREIGN KEY (CPL_INST_CODE, CPL_CUST_CATG, CPL_PROD_CODE, CPL_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CCC (CPC_INST_CODE,CPC_CUST_CATG,CPC_PROD_CODE,CPC_CARD_TYPE))
/

