CREATE TABLE VMSCMS.CMS_GL_MAST
(
  CGM_INST_CODE   NUMBER(3)                     NOT NULL,
  CGM_GL_CODE     VARCHAR2(20 BYTE),
  CGM_GL_DESC     VARCHAR2(50 BYTE)             NOT NULL,
  CGM_CATG_CODE   NUMBER(2),
  CGM_INS_USER    NUMBER(5)                     NOT NULL,
  CGM_INS_DATE    DATE                          NOT NULL,
  CGM_LUPD_USER   NUMBER(5)                     NOT NULL,
  CGM_LUPD_DATE   DATE                          NOT NULL,
  CGM_CHILD_FLAG  VARCHAR2(1 BYTE),
  CGM_FLOAT_FLAG  VARCHAR2(1 BYTE),
  CGM_CURR_CODE   VARCHAR2(3 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GL_MAST ADD (
  CONSTRAINT PK_CGM_GL_CODE
 PRIMARY KEY
 (CGM_GL_CODE))
/

