CREATE TABLE VMSCMS.CMS_FREETXN_RESPONSE
(
  CFR_INST_CODE         NUMBER(3),
  CFR_DELIVERY_CHANNEL  VARCHAR2(2 BYTE)        NOT NULL,
  CFR_TRAN_CODE         VARCHAR2(2 BYTE)        NOT NULL,
  CFR_MSG_TYPE          VARCHAR2(10 BYTE),
  CFR_RESPCDE           VARCHAR2(5 BYTE)        NOT NULL,
  CFR_INS_DATE          DATE,
  CFR_INS_USER          NUMBER(5),
  CFR_LUPD_UDER         NUMBER(5),
  CFR_LUPD_DATE         DATE,
  CFR_REVERSAL_CODE     NUMBER(3)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FREETXN_RESPONSE ADD (
  CONSTRAINT PK_FREETXN_RESP
 PRIMARY KEY
 (CFR_INST_CODE, CFR_DELIVERY_CHANNEL, CFR_TRAN_CODE, CFR_RESPCDE, CFR_MSG_TYPE, CFR_REVERSAL_CODE))
/

ALTER TABLE VMSCMS.CMS_FREETXN_RESPONSE ADD (
  CONSTRAINT FK_TXN_MAST_FREETXN 
 FOREIGN KEY (CFR_INST_CODE, CFR_DELIVERY_CHANNEL, CFR_TRAN_CODE) 
 REFERENCES VMSCMS.CMS_TRANSACTION_MAST (CTM_INST_CODE,CTM_DELIVERY_CHANNEL,CTM_TRAN_CODE))
/

