CREATE TABLE VMSCMS.CMS_RATE_DEFINITION
(
  CRD_INST_CODE        NUMBER(10)               NOT NULL,
  CRD_UNIQUE_ID        NUMBER(19)               NOT NULL,
  CRD_RATETABLE_ID     NUMBER(9),
  CRD_CURRENCYPAIR_ID  VARCHAR2(10 BYTE),
  CRD_EFFECTIVE_DATE   DATE,
  CRD_LAST_USER        NUMBER(10),
  CRD_LAST_DATE        DATE,
  CRD_RATE_FILE        VARCHAR2(75 BYTE),
  CRD_RATE_VALUE       NUMBER(18,5),
  CRD_LUPD_DATE        DATE,
  CRD_LUPD_USER        NUMBER(10),
  CRD_INS_DATE         DATE,
  CRD_INS_USER         NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_RATE_DEFINITION ADD (
  CONSTRAINT PK_RATE_DEFINITION1
 PRIMARY KEY
 (CRD_UNIQUE_ID, CRD_INST_CODE))
/

