CREATE TABLE VMSCMS.CMS_DISPATCH_INVENTORY
(
  CDI_DISP_ID           NUMBER,
  CDI_REF_NO            VARCHAR2(11 BYTE),
  CDI_FROMCARD_NO       VARCHAR2(90 BYTE),
  CDI_TOCARD_NO         VARCHAR2(90 BYTE),
  CDI_DISPATCH_TOTAL    NUMBER,
  CDI_COURIER_AGENCY    VARCHAR2(50 BYTE),
  CDI_DISPATCH_DATE     DATE,
  CDI_BRANCH_CODE       VARCHAR2(5 BYTE),
  CDI_LUPD_DATE         DATE,
  CDI_INST_CODE         NUMBER(10),
  CDI_LUPD_USER         NUMBER(10),
  CDI_INS_DATE          DATE,
  CDI_INS_USER          NUMBER(10),
  CDI_FROMCARD_NO_ENCR  RAW(100),
  CDI_TOCARD_NO_ENCR    RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_DISPATCH_INVENTORY ADD (
  CONSTRAINT FK_DISPATCH_INVENTORY_REFNO 
 FOREIGN KEY (CDI_REF_NO) 
 REFERENCES VMSCMS.CMS_REQUEST_INVENTORY (CRI_REF_NO))
/

