CREATE TABLE VMSCMS.CMS_KYCSTATUS_MAST
(
  CKM_INST_CODE  NUMBER(3),
  CKM_FLAG       VARCHAR2(1 BYTE),
  CKM_FLAG_DESC  VARCHAR2(50 BYTE),
  CKM_INS_USER   NUMBER(5),
  CKM_INS_DATE   DATE,
  CKM_LUPD_USER  NUMBER(5),
  CKM_LUPD_DATE  DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_KYCSTATUS_MAST ADD (
  CONSTRAINT PK_CKM_FLAG
 PRIMARY KEY
 (CKM_FLAG))
/

