CREATE TABLE VMSCMS.CMS_INVENTORYVENDOR_MAST
(
  CIM_VENDOR_CODE      VARCHAR2(10 BYTE),
  CIM_VENDOR_NAME      VARCHAR2(50 BYTE),
  CIM_CONTACT_PERSON   VARCHAR2(50 BYTE),
  CIM_ADDRESS_LINE1    VARCHAR2(50 BYTE),
  CIM_ADDRESS_LINE2    VARCHAR2(50 BYTE),
  CIM_CITY             VARCHAR2(25 BYTE),
  CIM_STATE            VARCHAR2(30 BYTE),
  CIM_COUNTRY          VARCHAR2(30 BYTE),
  CIM_ZIP_CODE         VARCHAR2(30 BYTE),
  CIM_PHONE1           VARCHAR2(10 BYTE),
  CIM_PHONE2           VARCHAR2(10 BYTE),
  CIM_FAX              VARCHAR2(10 BYTE),
  CIM_MOBILE           VARCHAR2(10 BYTE),
  CIM_EMAIL            VARCHAR2(50 BYTE),
  CIM_INS_USER         NUMBER(5),
  CIM_INS_DATE         DATE,
  CIM_LUPD_USER        NUMBER(5),
  CIM_LUPD_DATE        DATE,
  CIM_ONORDER          VARCHAR2(6 BYTE),
  CIM_INTERIM_PAYMENT  VARCHAR2(6 BYTE),
  CIM_FINAL_PAYMENT    VARCHAR2(6 BYTE),
  CIM_INST_CODE        NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_INVENTORYVENDOR_MAST ADD (
  CONSTRAINT PK_VENDOR_MAST
 PRIMARY KEY
 (CIM_VENDOR_CODE))
/

