CREATE TABLE VMSCMS.CMS_CARDBASE_ERR_LOG
(
  CEL_INST_CODE      NUMBER(3),
  CEL_BRANCH_CODE    VARCHAR2(6 BYTE),
  CEL_PAN_CODE       VARCHAR2(90 BYTE),
  CEL_ERROR_MESG     VARCHAR2(1000 BYTE),
  CEL_PROB_ACTION    VARCHAR2(50 BYTE),
  CEL_LUPD_DATE      DATE,
  CEL_LUPD_USER      NUMBER(10),
  CEL_INS_DATE       DATE,
  CEL_INS_USER       NUMBER(10),
  CEL_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


