CREATE TABLE VMSCMS.CMS_PAN_CTRL
(
  CPC_INST_CODE      NUMBER(3),
  CPC_PAN_PREFIX     VARCHAR2(18 BYTE),
  CPC_CTRL_NUMB      VARCHAR2(10 BYTE),
  CPC_MAX_SERIAL_NO  NUMBER(12),
  CPC_LUPD_DATE      DATE,
  CPC_LUPD_USER      NUMBER(10),
  CPC_INS_DATE       DATE,
  CPC_INS_USER       NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PAN_CTRL ADD (
  CONSTRAINT PK_PAN_CTRL
 PRIMARY KEY
 (CPC_INST_CODE, CPC_PAN_PREFIX))
/

