CREATE TABLE VMSCMS.CMS_COBRAND_DETAILS
(
  CCD_INST_CODE    NUMBER(3)                    DEFAULT 1                     NOT NULL,
  CCD_ASSO_CODE    NUMBER(3)                    DEFAULT 2                     NOT NULL,
  CCD_ACQ_ID       VARCHAR2(15 BYTE)            DEFAULT 1                     NOT NULL,
  CCD_TERM_ID      VARCHAR2(12 BYTE)            NOT NULL,
  CCD_INS_USER     NUMBER(5),
  CCD_INS_DATE     DATE,
  CCD_LUPD_USER    NUMBER(5),
  CCD_LUPD_DATE    DATE,
  CCD_COBRAND_BIN  NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_COBRAND_DETAILS ADD (
  CONSTRAINT PK_COBRAND_DETAILS
 PRIMARY KEY
 (CCD_INST_CODE, CCD_ASSO_CODE, CCD_ACQ_ID, CCD_TERM_ID))
/

ALTER TABLE VMSCMS.CMS_COBRAND_DETAILS ADD (
  CONSTRAINT FK_COBRANDDETAILS_USERMAST1 
 FOREIGN KEY (CCD_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_COBRANDDETAILS_USERMAST2 
 FOREIGN KEY (CCD_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_COBRANDDETAILS_ASSOMAST 
 FOREIGN KEY (CCD_INST_CODE, CCD_ASSO_CODE) 
 REFERENCES VMSCMS.CMS_ASSO_MAST (CAM_INST_CODE,CAM_ASSO_CODE),
  CONSTRAINT FK_COBRANDDETAILS_INSTMAST 
 FOREIGN KEY (CCD_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

