CREATE TABLE VMSCMS.CMS_USER_MAST_TEMP
(
  CUM_USER_PIN         NUMBER(5)                NOT NULL,
  CUM_INST_CODE        NUMBER(3)                NOT NULL,
  CUM_USER_CODE        VARCHAR2(40 BYTE)        NOT NULL,
  CUM_ENCR_PSWD        VARCHAR2(30 BYTE),
  CUM_USER_NAME        VARCHAR2(50 BYTE),
  CUM_BRAN_CODE        VARCHAR2(6 BYTE)         NOT NULL,
  CUM_VALID_FRDT       DATE,
  CUM_VALID_TODT       DATE,
  CUM_MAXM_SESS        NUMBER(1),
  CUM_CURR_SESS        NUMBER(1),
  CUM_USER_SUSP        CHAR(1 BYTE),
  CUM_PSWD_DATE        DATE                     NOT NULL,
  CUM_INS_USER         NUMBER(5)                NOT NULL,
  CUM_INS_DATE         DATE                     NOT NULL,
  CUM_LUPD_USER        NUMBER(5),
  CUM_LUPD_DATE        DATE,
  CUM_LAST_LOGINTIME   VARCHAR2(20 BYTE),
  CUM_DOMAIN_ID        NUMBER(3),
  CUM_DEF_GROUP        NUMBER(3),
  CUM_USERGROUP_IDS    VARCHAR2(100 BYTE),
  CUM_APPREJ_STATUS    VARCHAR2(2 BYTE),
  CUM_INSUPRST_STATUS  VARCHAR2(2 BYTE),
  CUM_ROW_ID           NUMBER(10),
  CUM_USERGROUPS_DESC  VARCHAR2(1000 BYTE),
  CUM_CHKR_REMARKS     VARCHAR2(150 BYTE),
  CUM_MAKER_REMARKS    VARCHAR2(150 BYTE),
  CUM_USER_EMAIL       VARCHAR2(100 BYTE),
  CUM_USER_TYPE        VARCHAR2(1 BYTE)         DEFAULT 0,
  CUM_ACCESS_FLAG      VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


