CREATE TABLE VMSCMS.CMS_REN_TEMP
(
  CRT_PAN_CODE       VARCHAR2(90 BYTE),
  CRT_FIID           VARCHAR2(6 BYTE),
  CRT_CARD_STAT      CHAR(1 BYTE),
  CRT_BIN            VARCHAR2(6 BYTE),
  CRT_FLAG           CHAR(1 BYTE),
  CRT_PERIOD         VARCHAR2(10 BYTE),
  CRT_LUPD_DATE      DATE,
  CRT_INST_CODE      NUMBER(10),
  CRT_LUPD_USER      NUMBER(10),
  CRT_INS_DATE       DATE,
  CRT_INS_USER       NUMBER(10),
  CRT_REMARKS        VARCHAR2(100 BYTE),
  CRT_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


