CREATE TABLE VMSCMS.CMS_USERDETL_MAST
(
  CUM_USER_CODE      NUMBER(8),
  CUM_LGIN_CODE      VARCHAR2(40 BYTE)          NOT NULL,
  CUM_LGIN_PSWD      VARCHAR2(200 BYTE)         NOT NULL,
  CUM_TXN_PSWD       VARCHAR2(200 BYTE),
  CUM_USER_NAME      VARCHAR2(50 BYTE)          NOT NULL,
  CUM_VALD_FRDT      DATE                       NOT NULL,
  CUM_VALD_TODT      DATE                       NOT NULL,
  CUM_USER_EMAL      VARCHAR2(100 BYTE)         NOT NULL,
  CUM_USER_MOBL      VARCHAR2(20 BYTE),
  CUM_USER_DOFB      DATE,
  CUM_FRTX_PSWD      NUMBER(1),
  CUM_FRLG_PSWD      NUMBER(1),
  CUM_HRTX_BLCK      NUMBER(1),
  CUM_PREV_EMAL      VARCHAR2(100 BYTE),
  CUM_LGPW_RSFL      NUMBER(1)                  NOT NULL,
  CUM_LGPW_RSDT      DATE,
  CUM_LGPW_DATE      DATE,
  CUM_TXPW_RSFL      NUMBER(1),
  CUM_TXPW_RSDT      DATE,
  CUM_TXPW_DATE      DATE,
  CUM_INPT_SRCE      NUMBER(1)                  NOT NULL,
  CUM_TRPF_PRIV      NUMBER(1),
  CUM_USER_STUS      NUMBER(1)                  NOT NULL,
  CUM_INS_USER       NUMBER(8)                  NOT NULL,
  CUM_INS_DATE       DATE                       NOT NULL,
  CUM_LUPD_USER      NUMBER(8),
  CUM_LUPD_DATE      DATE,
  CUM_LAST_LGDT      VARCHAR2(100 BYTE),
  CUM_SESN_PSWD      VARCHAR2(200 BYTE),
  CUM_USER_UUID      VARCHAR2(100 BYTE),
  CUM_UUID_DATE      DATE,
  CUM_USERMASK_FLAG  VARCHAR2(2 BYTE)           NOT NULL,
  CUM_AUTH_BIN       VARCHAR2(2000 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_USERDETL_MAST ADD (
  CONSTRAINT PK_CUM_USER_CODE
 PRIMARY KEY
 (CUM_USER_CODE),
  CONSTRAINT UK_CUM_LGIN_CODE
 UNIQUE (CUM_LGIN_CODE))
/

