CREATE TABLE VMSCMS.CMS_USGPDETL_MAST
(
  CUM_INST_CODE  NUMBER(5),
  CUM_USER_CODE  NUMBER(8),
  CUM_GRUP_CODE  NUMBER(5),
  CUM_USGP_STUS  NUMBER(1)                      NOT NULL,
  CUM_INS_USER   NUMBER(8)                      NOT NULL,
  CUM_INS_DATE   DATE                           NOT NULL,
  CUM_LUPD_USER  NUMBER(8),
  CUM_LUPD_DATE  DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_USGPDETL_MAST ADD (
  CONSTRAINT PK_CUM_INST_USER_GRUP
 PRIMARY KEY
 (CUM_INST_CODE, CUM_USER_CODE, CUM_GRUP_CODE))
/

ALTER TABLE VMSCMS.CMS_USGPDETL_MAST ADD (
  CONSTRAINT FK_USGP_GRP_CGM_GRP 
 FOREIGN KEY (CUM_INST_CODE, CUM_GRUP_CODE) 
 REFERENCES VMSCMS.CMS_GROUPDETL_MAST (CGM_INST_CODE,CGM_GRUP_CODE),
  CONSTRAINT FK_USGP_INST_CUI_INST 
 FOREIGN KEY (CUM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_CUM_INSUSER_CUM_USCODE 
 FOREIGN KEY (CUM_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_USGP_USER_USDETL_USER 
 FOREIGN KEY (CUM_USER_CODE) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE))
/

