CREATE TABLE VMSCMS.CMS_ITEM_SLAB_MAST
(
  CIS_SLAB_CODE    VARCHAR2(10 BYTE),
  CIS_CONFIG_CODE  VARCHAR2(10 BYTE),
  CIS_FROM_QTY     NUMBER(10),
  CIS_TO_QTY       NUMBER(10),
  CIS_PRICE        NUMBER(10,2),
  CIS_INS_USER     NUMBER(5),
  CIS_INS_DATE     DATE,
  CIS_LUPD_USER    NUMBER(5),
  CIS_LUPD_DATE    DATE,
  CIS_SLAB_ORDER   NUMBER(2),
  CIS_INST_CODE    NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ITEM_SLAB_MAST ADD (
  CONSTRAINT PK_SLAB_MAST
 PRIMARY KEY
 (CIS_SLAB_CODE),
  CONSTRAINT UK_SLABCONFIG_MAST
 UNIQUE (CIS_CONFIG_CODE, CIS_SLAB_CODE))
/

ALTER TABLE VMSCMS.CMS_ITEM_SLAB_MAST ADD (
  CONSTRAINT FK_SLABCONFIG_MAST 
 FOREIGN KEY (CIS_CONFIG_CODE) 
 REFERENCES VMSCMS.CMS_VENDORITEM_CONFIG_MAST (CVC_CONFIG_CODE))
/

