CREATE TABLE VMSCMS.CMS_REPIN_HIST
(
  CRH_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CRH_MBR_NUMB       VARCHAR2(3 BYTE),
  CRH_OLD_PIN_OFF    VARCHAR2(10 BYTE),
  CRH_NEW_PIN_OFF    VARCHAR2(10 BYTE),
  CRH_AUTH_ID        VARCHAR2(6 BYTE),
  CRH_RRN            VARCHAR2(20 BYTE),
  CRH_STAN           VARCHAR2(12 BYTE),
  CRH_BUSINESS_DATE  VARCHAR2(8 BYTE),
  CRH_BUSINESS_TIME  VARCHAR2(10 BYTE),
  CRH_INS_USER       NUMBER(5),
  CRH_INS_DATE       DATE,
  CRH_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


