CREATE TABLE VMSCMS.CMS_ISOCNTRY_MAST
(
  CIM_CNTRY_CODE     NUMBER(3)                  NOT NULL,
  CIM_ISOCNTRY_CODE  VARCHAR2(3 BYTE)           NOT NULL,
  CIM_INST_CODE      NUMBER(10),
  CIM_INS_USER       NUMBER(10)                 NOT NULL,
  CIM_INS_DATE       DATE                       NOT NULL,
  CIM_LUPD_USER      NUMBER(10),
  CIM_LUPD_DATE      DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ISOCNTRY_MAST ADD (
  CONSTRAINT PK_ISOCNTRY_MAST
 PRIMARY KEY
 (CIM_INST_CODE, CIM_CNTRY_CODE, CIM_ISOCNTRY_CODE))
/

ALTER TABLE VMSCMS.CMS_ISOCNTRY_MAST ADD (
  CONSTRAINT FK_ISOCNTRYMAST_CNTRYCODE 
 FOREIGN KEY (CIM_INST_CODE, CIM_CNTRY_CODE) 
 REFERENCES VMSCMS.GEN_CNTRY_MAST (GCM_INST_CODE,GCM_CNTRY_CODE))
/

