CREATE TABLE VMSCMS.CMS_CAF_STRUCT
(
  CCS_INST_CODE        NUMBER(3),
  CCS_FIELD_NAME       VARCHAR2(40 BYTE),
  CCS_FIELD_CAPTION    VARCHAR2(50 BYTE),
  CCS_MAX_SIXE         NUMBER(30),
  CCS_FROM_POSN        NUMBER(5),
  CCS_TO_POSN          NUMBER(5),
  CCS_INS_USER         NUMBER(5)                NOT NULL,
  CCS_INS_DATE         DATE                     NOT NULL,
  CCS_LUPD_USER        NUMBER(5)                NOT NULL,
  CCS_LUPD_DATE        DATE                     NOT NULL,
  CCS_SAMPLE_DATA      VARCHAR2(100 BYTE),
  CCS_FIELD_VALIDATOR  NUMBER(2),
  CCS_CAF_REC_TYPE     VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


