CREATE TABLE VMSCMS.CMS_DBUTILITY_VERSION
(
  CDV_BASE_VERSION  VARCHAR2(30 BYTE),
  CDV_RELEASE_NO    VARCHAR2(30 BYTE),
  CDV_RELEASE_FLAG  VARCHAR2(2 BYTE),
  CDV_INS_DATE      DATE,
  CDV_INS_USER      VARCHAR2(5 BYTE)
)
TABLESPACE USERS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


