CREATE TABLE VMSCMS.CMS_CNTRYCODE_RULE
(
  CCR_INST_CODE   NUMBER(10),
  CCR_CNTRY_CODE  VARCHAR2(3 BYTE),
  CCR_CODE_DESC   VARCHAR2(100 BYTE)            NOT NULL,
  CCR_CODE_STUS   VARCHAR2(1 BYTE),
  CCR_LUPD_DATE   DATE,
  CCR_LUPD_USER   NUMBER(10),
  CCR_INS_DATE    DATE,
  CCR_INS_USER    NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CNTRYCODE_RULE ADD (
  CONSTRAINT PK_INST_CNTRYCDE
 PRIMARY KEY
 (CCR_INST_CODE, CCR_CNTRY_CODE))
/

