CREATE TABLE VMSCMS.CMS_EOD_PROCESS
(
  CEP_LAST_EODPROCESS  DATE,
  CEP_LUPD_DATE        DATE,
  CEP_INST_CODE        NUMBER(10),
  CEP_LUPD_USER        NUMBER(10),
  CEP_INS_DATE         DATE,
  CEP_INS_USER         NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


