CREATE TABLE VMSCMS.CMS_FIN_LOG
(
  CFLL_FUNC_CODE  VARCHAR2(10 BYTE),
  CFL_CATG_CODE   VARCHAR2(10 BYTE),
  CFL_GL_CODE     VARCHAR2(10 BYTE),
  CFL_SUBGL_CODE  VARCHAR2(10 BYTE),
  CFL_ACCT_NO     VARCHAR2(20 BYTE),
  CFL_DRCR_FLAG   CHAR(2 BYTE),
  CFL_TRAN_AMT    VARCHAR2(20 BYTE),
  CFL_TRAN_DATE   DATE,
  CFL_INS_USER    NUMBER(5),
  CFL_INST_DATE   DATE,
  CFL_LUPD_USER   NUMBER(5),
  CFL_LUPD_DATE   DATE,
  CFL_INST_CODE   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


