CREATE TABLE VMSCMS.CMS_GROUP_TOPUP_HIST
(
  CGT_ACCT_NO    VARCHAR2(20 BYTE),
  CGT_TOPUP_AMT  VARCHAR2(12 BYTE),
  CGT_FILE_NAME  VARCHAR2(30 BYTE),
  CGT_INS_DATE   DATE,
  CGT_INS_USER   NUMBER(5),
  CGT_LUPD_DATE  DATE,
  CGT_INST_CODE  NUMBER(10),
  CGT_LUPD_USER  NUMBER(10)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


