CREATE TABLE VMSCMS.CMS_FEETXN_LIST
(
  CFL_INST_CODE        NUMBER(10)               NOT NULL,
  CFL_DLVR_CHNL        VARCHAR2(2 BYTE)         NOT NULL,
  CFL_TRAN_CODE        VARCHAR2(2 BYTE)         NOT NULL,
  CFL_TRAN_DESC        VARCHAR2(50 BYTE),
  CFL_OTHER_PARAM      VARCHAR2(100 BYTE),
  CFL_OTHER_PARAM_KEY  VARCHAR2(100 BYTE),
  CFL_LUPD_DATE        DATE,
  CFL_LUPD_USER        NUMBER(10),
  CFL_INS_DATE         DATE                     NOT NULL,
  CFL_INS_USER         NUMBER(10)               NOT NULL
)
TABLESPACE CMS_HIST;   