CREATE TABLE VMSCMS.CMS_REDEEM_LOYL
(
  CRL_INST_CODE    NUMBER(3),
  CRL_CURR_BRAN    VARCHAR2(6 BYTE),
  CRL_ACCT_NO      VARCHAR2(20 BYTE),
  CRL_CALC_AMT     NUMBER(15,2),
  CRL_TOT_LOYL     NUMBER(5),
  CRL_LOYL_POINTS  NUMBER(5),
  CRL_LOYL_IND     CHAR(1 BYTE),
  CRL_PARTI_CULAR  VARCHAR2(30 BYTE),
  CRL_FILE_NAME    VARCHAR2(18 BYTE),
  CRL_INS_USER     NUMBER(5),
  CRL_INS_DATE     DATE,
  CRL_LUPD_USER    NUMBER(5),
  CRL_LUPD_DATE    DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_REDEEM_LOYL ADD (
  CONSTRAINT FK_REDEEMLOYL_USERMAST1 
 FOREIGN KEY (CRL_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_REDEEMLOYL_USERMAST2 
 FOREIGN KEY (CRL_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_REDEEMLOYL_ACCTMAST 
 FOREIGN KEY (CRL_INST_CODE, CRL_ACCT_NO) 
 REFERENCES VMSCMS.CMS_ACCT_MAST (CAM_INST_CODE,CAM_ACCT_NO))
/

