CREATE TABLE VMSCMS.CMS_GROUP_REISSUE_TEMP
(
  CGH_INST_CODE         NUMBER(3),
  CGH_CARD_NO           VARCHAR2(90 BYTE),
  CGH_FILE_NAME         VARCHAR2(30 BYTE),
  CGH_REMARKS           VARCHAR2(100 BYTE),
  CGH_PROCESS_FLAG      VARCHAR2(1 BYTE)        DEFAULT 'N',
  CGH_PROCESS_MSG       VARCHAR2(300 BYTE),
  CGH_INS_USER          NUMBER(5),
  CGH_INS_DATE          DATE                    DEFAULT SYSDATE,
  CGH_NEW_CARD_NO       VARCHAR2(90 BYTE),
  CGH_MBR_NUMB          VARCHAR2(10 BYTE),
  CGH_ROWID             NUMBER(30),
  CGH_NEW_PRODUCT       VARCHAR2(6 BYTE),
  CGH_NEW_PRODUCTCAT    VARCHAR2(30 BYTE),
  CGH_NEW_DISPNAME      VARCHAR2(50 BYTE),
  CGH_DUP_FLAG          CHAR(1 BYTE)            DEFAULT 'N',
  CGH_REASON_CODE       NUMBER(5),
  CGH_PIN_REISSUE       CHAR(1 BYTE),
  CGH_LUPD_USER         NUMBER(5)               DEFAULT 1,
  CGH_MODE              VARCHAR2(1 BYTE),
  CGH_LUPD_DATE         DATE,
  CGH_CARD_NO_ENCR      RAW(100),
  CGH_NEW_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


