CREATE TABLE VMSCMS.CMS_GL_UPDATE_ERRORLOG
(
  CGE_ACCT_NO    VARCHAR2(20 BYTE),
  CGE_ERR_MSG    VARCHAR2(500 BYTE),
  CGE_INS_DATE   DATE,
  CGE_LUPD_DATE  DATE,
  CGE_INST_CODE  NUMBER(10),
  CGE_LUPD_USER  NUMBER(10),
  CGE_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


