CREATE TABLE VMSCMS.CMS_GIFT_TRANS_HIST
(
  CGT_INST_CODE   NUMBER(3),
  CGT_FILE_NAME   VARCHAR2(14 BYTE),
  CGT_GIFT_ORDER  VARCHAR2(14 BYTE),
  CGT_ITEM_ID     VARCHAR2(6 BYTE),
  CGT_STAT_CODE   VARCHAR2(3 BYTE),
  CGT_INS_USER    NUMBER(5),
  CGT_INS_DATE    DATE,
  CGT_LUPD_DATE   DATE,
  CGT_LUPD_USER   NUMBER(10)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


