CREATE TABLE VMSCMS.CMS_FEE_PROCESSLOG
(
  CFP_INST_CODE      NUMBER(10),
  CFP_PAN_CODE       VARCHAR2(90 BYTE),
  CFP_PROD_CODE      VARCHAR2(10 BYTE),
  CFP_CARD_TYPE      NUMBER(10),
  CFP_PROCESS_FLAG   CHAR(1 BYTE),
  CFP_PROCESS_MSG    VARCHAR2(500 BYTE),
  CFP_FEE_TYPE       NUMBER(10),
  CFP_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


