CREATE TABLE VMSCMS.CMS_GROUP_BULKREISSUE
(
  CGR_PAN_CODE           VARCHAR2(90 BYTE),
  CGR_PIN_REISSUE        VARCHAR2(1 BYTE)       DEFAULT 'N',
  CGR_NEW_PRODUCT        VARCHAR2(6 BYTE),
  CGR_NEW_PRODUCTCAT     VARCHAR2(30 BYTE),
  CGR_NEW_DISPNAME       VARCHAR2(50 BYTE),
  CGR_FILE_NAME          VARCHAR2(30 BYTE),
  CGR_REMARK             VARCHAR2(100 BYTE),
  CGR_RESULT             VARCHAR2(500 BYTE),
  CGR_MBR_NUMB           VARCHAR2(3 BYTE)       DEFAULT '000',
  CGR_INS_DATE           DATE                   DEFAULT sysdate,
  CGR_INS_USER           NUMBER(5)              NOT NULL,
  CGR_NEW_PAN_CODE       VARCHAR2(90 BYTE),
  CGR_APPL_BRAN          VARCHAR2(6 BYTE),
  CGR_CHKR_ID            NUMBER(5),
  CGR_CHKR_PROC_STAT     CHAR(1 BYTE)           DEFAULT 'P',
  CGR_SEQ_NO             NUMBER,
  SRNO                   VARCHAR2(30 BYTE),
  CGR_NEW_PAN_CODE_ENCR  RAW(100),
  CGR_PAN_CODE_ENCR      RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GROUP_BULKREISSUE ADD (
  CONSTRAINT PK_CGR_SEQ_NO
 PRIMARY KEY
 (CGR_SEQ_NO))
/

