CREATE TABLE VMSCMS.CMS_INNER_BREADCRUMP
(
  CBC_INST_CODE  NUMBER(3),
  CBC_MENU_PATH  VARCHAR2(200 BYTE),
  CBC_PROG_NAME  VARCHAR2(200 BYTE),
  CBC_INS_USER   NUMBER(5),
  CBC_INS_DATE   DATE,
  CBC_LUPD_USER  NUMBER(5),
  CBC_LUPD_DATE  DATE,
  CBC_MENU_LINK  NUMBER(4)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


