CREATE TABLE VMSCMS.CMS_USER_GROUP_TEMP
(
  CUG_INST_CODE             NUMBER(3)           NOT NULL,
  CUG_INS_USER              NUMBER(5)           NOT NULL,
  CUG_INS_DATE              DATE                NOT NULL,
  CUG_LUPD_USER             NUMBER(5),
  CUG_LUPD_DATE             DATE,
  CUG_OLD_GROUP_NAME        VARCHAR2(30 BYTE),
  CUG_NEW_GROUP_NAME        VARCHAR2(30 BYTE),
  CUG_USER_GROUP_CODE       VARCHAR2(30 BYTE),
  CUG_USRGRP_ACCREJ_STATUS  VARCHAR2(2 BYTE),
  CUG_USRGRP_INSUPD_STATUS  VARCHAR2(2 BYTE),
  CUG_ROW_ID                NUMBER(10),
  CUG_CHKR_REMARKS          VARCHAR2(150 BYTE),
  CUG_MAKER_REMARKS         VARCHAR2(150 BYTE),
  CUG_ACCESS_FLAG           VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_USER_GROUP_TEMP ADD (
  CONSTRAINT UK_ROW_ID
 UNIQUE (CUG_ROW_ID))
/

