CREATE TABLE VMSCMS.CMS_CSRREASON_MAST
(
  CCM_INST_CODE    NUMBER(5),
  CCM_DELV_CHNL    VARCHAR2(2 BYTE),
  CCM_REASON_TYPE  VARCHAR2(30 BYTE),
  CCM_REASON_CODE  VARCHAR2(3 BYTE),
  CCM_REASON_DESC  VARCHAR2(50 BYTE),
  CCM_ACTIVE_FLAG  VARCHAR2(1 BYTE),
  CCM_OPTION_TYPE  VARCHAR2(8 BYTE),
  CCM_INS_USER     NUMBER(5)                    NOT NULL,
  CCM_INS_DATE     DATE                         NOT NULL,
  CCM_LUPD_USER    NUMBER(5),
  CCM_LUPD_DATE    DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CSRREASON_MAST ADD (
  CONSTRAINT UK_DEVL_TYP_CODE
 UNIQUE (CCM_DELV_CHNL, CCM_REASON_TYPE, CCM_REASON_CODE))
/

