CREATE TABLE VMSCMS.CMS_DELINK_ACCT
(
  CDA_PAN_CODE          VARCHAR2(90 BYTE),
  CDA_CARD_NAME         VARCHAR2(50 BYTE),
  CDA_PRIMARY_ACCT_NO   VARCHAR2(20 BYTE),
  CDA_OLD_PRIMARY_ACCT  VARCHAR2(20 BYTE),
  CDA_ACCT_NO           VARCHAR2(20 BYTE),
  CDA_DONE_FLAG         VARCHAR2(1 BYTE),
  CDA_PROCESS_DATE      DATE,
  CDA_PROCESS_RESULT    VARCHAR2(100 BYTE),
  CDA_LUPD_USER         NUMBER(5),
  CDA_INST_CODE         NUMBER(10),
  CDA_INS_DATE          DATE,
  CDA_INS_USER          NUMBER(10),
  CDA_PAN_CODE_ENCR     RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


