CREATE TABLE VMSCMS.CMS_PRODCATTYPE_WAIV
(
  CPW_INST_CODE    NUMBER(3)                    NOT NULL,
  CPW_PROD_CODE    VARCHAR2(6 BYTE)             NOT NULL,
  CPW_CARD_TYPE    NUMBER(2)                    NOT NULL,
  CPW_FEE_CODE     NUMBER(3)                    NOT NULL,
  CPW_WAIV_PRCNT   NUMBER(5,2)                  NOT NULL,
  CPW_VALID_FROM   DATE                         NOT NULL,
  CPW_VALID_TO     DATE,
  CPW_WAIV_DESC    VARCHAR2(50 BYTE)            NOT NULL,
  CPW_FLOW_SOURCE  VARCHAR2(3 BYTE)             NOT NULL,
  CPW_INS_USER     NUMBER(5)                    NOT NULL,
  CPW_INS_DATE     DATE                         NOT NULL,
  CPW_LUPD_USER    NUMBER(5)                    NOT NULL,
  CPW_LUPD_DATE    DATE                         NOT NULL,
  CPW_FEE_TYPE     NUMBER(5),
  CPW_WAIV_ID      NUMBER(10)                   NOT NULL,
  CPW_FEE_PLAN     NUMBER(4)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PRODCATTYPE_WAIV ADD (
  CONSTRAINT FK_PRODCTW_USERMAST2 
 FOREIGN KEY (CPW_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCTW_USERMAST1 
 FOREIGN KEY (CPW_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCTW_PRODCATTYPE 
 FOREIGN KEY (CPW_INST_CODE, CPW_PROD_CODE, CPW_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CATTYPE (CPC_INST_CODE,CPC_PROD_CODE,CPC_CARD_TYPE),
  CONSTRAINT FK_PRODCTW_FEEMAST 
 FOREIGN KEY (CPW_INST_CODE, CPW_FEE_CODE) 
 REFERENCES VMSCMS.CMS_FEE_MAST (CFM_INST_CODE,CFM_FEE_CODE))
/

