CREATE TABLE VMSCMS.CMS_SMSEMAIL_ALERT
(
  CSA_INST_CODE               NUMBER(3)         NOT NULL,
  CSA_PAN_CODE                VARCHAR2(90 BYTE) NOT NULL,
  CSA_PAN_CODE_ENCR           RAW(100),
  CSA_CELLPHONECARRIER        VARCHAR2(20 BYTE),
  CSA_SMSBALCHG_FLAG          CHAR(1 BYTE),
  CSA_SMSLOWBAL_FLAG          CHAR(1 BYTE),
  CSA_SMSUSERCHG_FLAG         CHAR(1 BYTE),
  CSA_SMSPINCHG_FLAG          CHAR(1 BYTE),
  CSA_SMSMISC_FLAG            CHAR(1 BYTE),
  CSA_MAILBALCHG_FLAG         CHAR(1 BYTE),
  CSA_MAILLOWBAL_FLAG         CHAR(1 BYTE),
  CSA_MAILUSERCHG_FLAG        CHAR(1 BYTE),
  CSA_MAILCARDSTATUSCHG_FLAG  CHAR(1 BYTE),
  CSA_MAILPINCHG_FLAG         CHAR(1 BYTE),
  CSA_MAILMISC_FLAG           CHAR(1 BYTE),
  CSA_INS_USER                NUMBER(5),
  CSA_INS_DATE                DATE,
  CSA_LUPD_USER               NUMBER(5),
  CSA_LUPD_DATE               DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SMSEMAIL_ALERT ADD (
  CONSTRAINT PK_SMS_EMAIL
 PRIMARY KEY
 (CSA_INST_CODE, CSA_PAN_CODE))
/

