CREATE TABLE VMSCMS.CMS_FLATPLAN_COMMISSION
(
  CFT_INST_CODE     NUMBER(3),
  CFT_PLAN_ID       VARCHAR2(5 BYTE),
  CFT_PLAN_AMT      NUMBER(10,4),
  CFT_PLAN_PERCENT  NUMBER(3),
  CFT_INS_USER      NUMBER(5),
  CFT_INS_DATE      DATE,
  CFT_LUPD_USER     NUMBER(5),
  CFT_LUPD_DATE     DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FLATPLAN_COMMISSION ADD (
  CONSTRAINT FK_CPLAN_PLANID 
 FOREIGN KEY (CFT_INST_CODE, CFT_PLAN_ID) 
 REFERENCES VMSCMS.CMS_COMMISSION_PLAN (CCP_INST_CODE,CCP_PLAN_ID))
/

