CREATE TABLE VMSCMS.CMS_PROG_MAST
(
  CPM_INST_CODE   NUMBER(3)                     NOT NULL,
  CPM_PROG_CODE   NUMBER(4)                     NOT NULL,
  CPM_TAB_TYPE    CHAR(1 BYTE),
  CPM_MENU_LINK   NUMBER(4)                     NOT NULL,
  CPM_PROG_NAME   VARCHAR2(70 BYTE)             NOT NULL,
  CPM_MENU_PATH   VARCHAR2(100 BYTE)            NOT NULL,
  CPM_MENU_DESC   VARCHAR2(75 BYTE),
  CPM_PROG_ORDER  NUMBER(6,2),
  CPM_PROG_STAT   CHAR(1 BYTE),
  CPM_INS_USER    NUMBER(5)                     NOT NULL,
  CPM_INS_DATE    DATE                          NOT NULL,
  CPM_LUPD_USER   NUMBER(5)                     NOT NULL,
  CPM_LUPD_DATE   DATE                          NOT NULL,
  CPM_ADMIN_MENU  CHAR(1 BYTE)                  DEFAULT 'N'                   NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROG_MAST ADD (
  CONSTRAINT PK_PROG_MAST
 PRIMARY KEY
 (CPM_INST_CODE, CPM_PROG_CODE))
/

ALTER TABLE VMSCMS.CMS_PROG_MAST ADD (
  CONSTRAINT FK_PROGMAST_USERMAST2 
 FOREIGN KEY (CPM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PROGMAST_USERMAST1 
 FOREIGN KEY (CPM_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PROGMAST_INSTMAST 
 FOREIGN KEY (CPM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

