CREATE TABLE VMSCMS.CMS_TIP_CTRL
(
  CTC_INST_CODE        NUMBER(3)                NOT NULL,
  CTC_FILE_NAME        VARCHAR2(50 BYTE)        NOT NULL,
  CTC_TOT_ROWS         NUMBER(8),
  CTC_CORR_ROWS        NUMBER(8),
  CTC_ERR_ROWS         NUMBER(8),
  CTC_PROC_TRANS_DATE  DATE,
  CTC_INS_USER         NUMBER(5)                NOT NULL,
  CTC_INS_DATE         DATE                     NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


