CREATE TABLE VMSCMS.CMS_BATCH_ADJSTMENT
(
  CBA_CARD_NO          VARCHAR2(90 BYTE),
  CBA_CARD_NO_ENCR     RAW(100),
  CBA_TRANS_TYPE       VARCHAR2(5 BYTE),
  CBA_TRANS_AMOUNT     NUMBER(20,3),
  CBA_TRANS_NARRATION  VARCHAR2(200 BYTE),
  CBA_LOAD_DATE        DATE                     DEFAULT SYSDATE,
  CBA_PROCESS_DATE     DATE,
  CBA_PROCESS_STAT     VARCHAR2(2 BYTE)         DEFAULT 'N',
  CBA_PROCESS_MSG      VARCHAR2(500 BYTE),
  CBA_REASON_CODE      NUMBER(5),
  CBA_BATCH_ID         VARCHAR2(100 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


