CREATE TABLE VMSCMS.CMS_TXN_PROPERTIES
(
  CTP_TXN_CODE                   VARCHAR2(2 BYTE),
  CTP_INST_CODE                  NUMBER(3),
  CTP_MSGBODY_PROP               VARCHAR2(100 BYTE),
  CTP_HEADER_PROP                VARCHAR2(100 BYTE),
  CTP_REVERSAL_CODE              NUMBER(3),
  CTP_MSG_TYPE                   VARCHAR2(10 BYTE),
  CTP_DELIVERY_CHANNEL           VARCHAR2(2 BYTE),
  CTP_VALIDATION_PROP            VARCHAR2(100 BYTE),
  CTP_HEADERPROP_VALIDATION      VARCHAR2(100 BYTE),
  CTP_NONMANDATORY_MSGBODY_PROP  VARCHAR2(100 BYTE),
  CTP_NONMANDATORY_VALIDATION    VARCHAR2(100 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TXN_PROPERTIES ADD (
  CONSTRAINT PK_TXN_PROP
 PRIMARY KEY
 (CTP_INST_CODE, CTP_DELIVERY_CHANNEL, CTP_TXN_CODE, CTP_MSG_TYPE, CTP_REVERSAL_CODE))
/

