CREATE TABLE VMSCMS.CMS_ISO_MSGLOGGER
(
  CIM_INST_CODE        VARCHAR2(1 BYTE),
  CIM_TRANSACTION_MSG  VARCHAR2(4000 BYTE),
  CIM_INST_DATE        DATE
)
TABLESPACE CMS_DEFAULT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


