CREATE TABLE VMSCMS.CMS_FEE_FEEPLAN
(
  CFF_FEE_CODE   NUMBER(4),
  CFF_FEE_PLAN   NUMBER(4),
  CFF_INST_CODE  NUMBER(3),
  CFF_INS_USER   NUMBER(10),
  CFF_INS_DATE   DATE,
  CFF_LUPD_USER  NUMBER(10),
  CFF_LUPD_DATE  DATE,
  CFF_FEE_FREQ   VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FEE_FEEPLAN ADD (
  CONSTRAINT FK_FEEPLAN 
 FOREIGN KEY (CFF_INST_CODE, CFF_FEE_PLAN) 
 REFERENCES VMSCMS.CMS_FEE_PLAN (CFP_INST_CODE,CFP_PLAN_ID))
/

