CREATE TABLE VMSCMS.CMS_ROLE_MAST
(
  CRM_INST_CODE          NUMBER(5),
  CRM_ROLE_CODE          NUMBER(5),
  CRM_ROLE_NAME          VARCHAR2(50 BYTE),
  CRM_ROLE_DESC          VARCHAR2(100 BYTE),
  CRM_INS_USER           NUMBER(5)              NOT NULL,
  CRM_INS_DATE           DATE                   NOT NULL,
  CRM_LUPD_USER          NUMBER(5),
  CRM_LUPD_DATE          DATE,
  CRM_SPENDINGADJ_LIMIT  VARCHAR2(20 BYTE)      DEFAULT '0',
  CRM_SAVINGADJ_LIMIT    VARCHAR2(20 BYTE)      DEFAULT '0'
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ROLE_MAST ADD (
  CONSTRAINT PK_CRM_ROLE_CODE
 PRIMARY KEY
 (CRM_INST_CODE, CRM_ROLE_CODE))
/

ALTER TABLE VMSCMS.CMS_ROLE_MAST ADD (
  CONSTRAINT FK_CRM_INSUSER_CUM_USERCODE 
 FOREIGN KEY (CRM_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_CRM_INST_CIM_INST 
 FOREIGN KEY (CRM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

