CREATE TABLE VMSCMS.CMS_ACH_FILEPROCESS
(
  CAF_INST_CODE       NUMBER(5)                 NOT NULL,
  CAF_ACH_FILE        VARCHAR2(100 BYTE)        NOT NULL,
  CAF_ACH_RETURNFILE  VARCHAR2(100 BYTE),
  CAF_TRAN_DATE       VARCHAR2(100 BYTE)        NOT NULL,
  CAF_RETUNRRAN_DATE  VARCHAR2(100 BYTE),
  CAF_INST_DATE       DATE,
  CAF_LUPD_USER       NUMBER(5),
  CAF_LUPD_DATE       DATE,
  CAF_INS_USER        NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


