CREATE TABLE VMSCMS.CMS_TOPUP_DETAIL
(
  CTD_ACCT_NO        VARCHAR2(20 BYTE),
  CTD_TOPUP_AMT      VARCHAR2(12 BYTE),
  CTD_FILE_NAME      VARCHAR2(30 BYTE),
  CTD_REMARKS        VARCHAR2(100 BYTE),
  CTD_REF_NO         VARCHAR2(25 BYTE),
  CTD_PROCESS_FLAG   VARCHAR2(1 BYTE),
  CTD_PROCESS_MSG    VARCHAR2(300 BYTE),
  CTD_PROCESS_MODE   VARCHAR2(1 BYTE),
  CTD_INS_USER       NUMBER(5),
  CTD_INS_DATE       DATE,
  CTD_LUPD_USER      NUMBER(5),
  CTD_LUPD_DATE      DATE,
  CTD_INST_CODE      NUMBER(3),
  CTD_PAYMENT_MODE   VARCHAR2(15 BYTE),
  CTD_INSTRUMENT_NO  VARCHAR2(19 BYTE),
  CTD_DRAWN_DATE     DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


