CREATE TABLE VMSCMS.CMS_DELCHANNEL_MAST
(
  CDM_INST_CODE           NUMBER(5),
  CDM_CHANNEL_CODE        VARCHAR2(2 BYTE),
  CDM_CHANNEL_DESC        VARCHAR2(20 BYTE),
  CDM_TRANSACTION_FLAG    VARCHAR2(1 BYTE),
  CDM_LUPD_DATE           DATE,
  CDM_LUPD_USER           NUMBER(10),
  CDM_INS_DATE            DATE,
  CDM_INS_USER            NUMBER(10),
  CDM_PASSIVEPERIOD_FLAG  VARCHAR2(1 BYTE),
  CDM_GPRCONFIG_FLAG      VARCHAR2(1 BYTE),
  CDM_PRFL_FLAG           CHAR(1 BYTE)          DEFAULT 'N',
  CDM_DEPLOYMENT_FLAG     NUMBER(1)             DEFAULT 0
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_DELCHANNEL_MAST ADD (
  CONSTRAINT PK_CHANNEL_CODE
 PRIMARY KEY
 (CDM_CHANNEL_CODE))
/

