CREATE TABLE VMSCMS.CMS_GROUP_PROG_STATUS
(
  CGP_GROUP_CODE     NUMBER(10),
  CGP_ROW_ID         NUMBER(10),
  CGP_APPREJ_STATUS  VARCHAR2(2 BYTE),
  CGP_INST_CODE      NUMBER(10),
  CGP_INS_USER       NUMBER(10),
  CGP_INS_DATE       DATE,
  CGP_LUPD_USER      NUMBER(5),
  CGP_LUPD_DATE      DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GROUP_PROG_STATUS ADD (
  CONSTRAINT PK_GRP_PROG_STATUS
 PRIMARY KEY
 (CGP_GROUP_CODE, CGP_ROW_ID))
/

