CREATE TABLE VMSCMS.CMS_BRANCH_STOCK
(
  CBS_INST_CODE          NUMBER(3),
  CBS_BRANCH_CODE        VARCHAR2(5 BYTE),
  CBS_PRODUCT_CODE       VARCHAR2(6 BYTE),
  CBS_CARD_TYPE          NUMBER(2),
  CBS_CARD_DENOMINATION  VARCHAR2(10 BYTE),
  CBS_CARD_STOCK         NUMBER(8),
  CBS_CARD_REORDER       NUMBER,
  CBS_CARD_MAX           NUMBER,
  CBS_INS_USER           NUMBER,
  CBS_INS_DATE           DATE,
  CBS_LUPD_USER          NUMBER,
  CBS_LUPD_DATE          DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


