CREATE TABLE VMSCMS.CMS_GROUP_ACTVTCARD_TEMP
(
  CGA_CARD_NO       VARCHAR2(90 BYTE),
  CGA_FILE_NAME     VARCHAR2(30 BYTE),
  CGA_REMARKS       VARCHAR2(100 BYTE),
  CGA_INS_DATE      DATE,
  CGA_INST_CODE     NUMBER(10),
  CGA_INS_USER      NUMBER(10),
  CGA_PROCESS_FLAG  VARCHAR2(1 BYTE),
  CGA_PROCESS_MSG   VARCHAR2(300 BYTE),
  CGA_MBR_NUMB      VARCHAR2(10 BYTE),
  CGA_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


