CREATE TABLE VMSCMS.CMS_COMMISSION_PLAN
(
  CCP_INST_CODE  NUMBER(3),
  CCP_PLAN_ID    VARCHAR2(5 BYTE),
  CCP_PLAN_DESC  VARCHAR2(50 BYTE),
  CCP_PLAN_TYPE  VARCHAR2(1 BYTE),
  CCP_INS_USER   NUMBER(5),
  CCP_INS_DATE   DATE,
  CCP_LUPD_USER  NUMBER(5),
  CCP_LUPD_DATE  DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_COMMISSION_PLAN ADD (
  CONSTRAINT PK_PLAN_ID
 PRIMARY KEY
 (CCP_INST_CODE, CCP_PLAN_ID),
  CONSTRAINT CMS_COMMISSION_PLAN_U01
 UNIQUE (CCP_PLAN_DESC))
/

