CREATE TABLE VMSCMS.CMS_TABLE_PARAM
(
  CTP_PARAM_KEY    VARCHAR2(20 BYTE),
  CTP_PARAM_TYPE   VARCHAR2(20 BYTE),
  CTP_PARAM_VALUE  VARCHAR2(15 BYTE),
  CTP_PARAM_DESC   VARCHAR2(40 BYTE),
  CTP_INS_USER     NUMBER(5)                    NOT NULL,
  CTP_INS_DATE     DATE                         NOT NULL,
  CTP_LUPD_USER    NUMBER(5)                    NOT NULL,
  CTP_LUPD_DATE    DATE                         NOT NULL,
  CTP_INST_CODE    NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TABLE_PARAM ADD (
  CONSTRAINT PK_TABLE_PARAM
 PRIMARY KEY
 (CTP_INST_CODE, CTP_PARAM_KEY))
/

