CREATE TABLE VMSCMS.CMS_MOB_EMAIL_LOG
(
  CME_INST_CODE  NUMBER(3),
  CME_CUST_CODE  NUMBER(10),
  CME_OLD_PMOB   VARCHAR2(20 BYTE),
  CME_NEW_PMOB   VARCHAR2(20 BYTE),
  CME_OLD_OMOB   VARCHAR2(20 BYTE),
  CME_NEW_OMOB   VARCHAR2(20 BYTE),
  CME_OLD_PEMAL  VARCHAR2(50 BYTE),
  CME_NEW_PEMAL  VARCHAR2(50 BYTE),
  CME_OLD_OEMAL  VARCHAR2(50 BYTE),
  CME_NEW_OEMAL  VARCHAR2(50 BYTE),
  CME_INS_USER   NUMBER(5)                      NOT NULL,
  CME_INS_DATE   DATE                           NOT NULL,
  CME_LUPD_USER  NUMBER(5),
  CME_LUPD_DATE  DATE,
  CME_CHNG_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MOB_EMAIL_LOG ADD (
  CONSTRAINT PK_INST_CUST
 PRIMARY KEY
 (CME_INST_CODE, CME_CUST_CODE))
/

