CREATE TABLE VMSCMS.CMS_REFUND_DTLS
(
  CRD_ACCT_NO           VARCHAR2(20 BYTE),
  CRD_SINKBANK_NAME     VARCHAR2(30 BYTE),
  CRD_BRANCH            VARCHAR2(30 BYTE),
  CRD_SINKBANK_ACCT     VARCHAR2(15 BYTE),
  CRD_SINK_IFCS         VARCHAR2(15 BYTE),
  CRD_ACCT_BAL          NUMBER(15,2),
  CRD_TERMINATION_CHRG  NUMBER(15,2),
  CRD_REFUND_AMT        NUMBER(15,2),
  CRD_TERMINATION_DATE  DATE,
  CRD_REFUND_CHARGE     NUMBER(15,2),
  CRD_REFUND_DATE       DATE,
  CRD_INS_USER          NUMBER(5),
  CRD_INS_DATE          DATE,
  CRD_LUPD_USER         NUMBER(5),
  CRD_LUPD_DATE         DATE,
  CRD_REFUND_MODE       VARCHAR2(20 BYTE),
  CRD_CURR_PAIR         VARCHAR2(7 BYTE),
  CRD_CONV_RATE         NUMBER(18,2),
  CRD_TXN_AMOUNT        NUMBER(15,2),
  CRD_INST_CODE         NUMBER(10),
  CRD_PROCESS_MODE      VARCHAR2(1 BYTE),
  CRD_PROCESS_FLAG      VARCHAR2(1 BYTE),
  CRD_PROCESS_MSG       VARCHAR2(300 BYTE),
  CRD_MSG24_FLAG        VARCHAR2(1 BYTE),
  CRD_REMARKS           VARCHAR2(100 BYTE),
  CRD_FILE_NAME         VARCHAR2(30 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


