CREATE TABLE VMSCMS.CMS_MOBILECARRIER_MAST
(
  CMM_INST_CODE     NUMBER(3),
  CMM_CARRIER_CODE  NUMBER(3),
  CMM_CARRIER_NAME  VARCHAR2(50 BYTE),
  CMM_CARRIER_DESC  VARCHAR2(100 BYTE),
  CMM_INS_USER      NUMBER(5),
  CMM_INS_DATE      DATE,
  CMM_LUPD_USER     NUMBER(5),
  CMM_LUPD_DATE     DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MOBILECARRIER_MAST ADD (
  CONSTRAINT PK_INST_CARRIER
 PRIMARY KEY
 (CMM_INST_CODE, CMM_CARRIER_CODE, CMM_CARRIER_NAME))
/

