CREATE TABLE VMSCMS.CMS_TRANSLIMIT_CHECK
(
  CTC_PAN_CODE               VARCHAR2(90 BYTE)  NOT NULL,
  CTC_INST_CODE              NUMBER(3)          NOT NULL,
  CTC_ATM_OFFLINE_LIMIT      NUMBER(10)         DEFAULT 25000,
  CTC_ATM_ONLINE_LIMIT       NUMBER(10)         DEFAULT 50000,
  CTC_POS_OFFLINE_LIMIT      NUMBER(10)         DEFAULT 25000,
  CTC_POS_ONLINE_LIMIT       NUMBER(10)         DEFAULT 75000,
  CTC_OFFLINE_AGGR_LIMIT     NUMBER(10)         DEFAULT 25000,
  CTC_ONLINE_AGGR_LIMIT      NUMBER(10)         DEFAULT 75000,
  CTC_ATMUSAGE_AMT           NUMBER(20,3)       DEFAULT 0,
  CTC_POSUSAGE_AMT           NUMBER(20,3)       DEFAULT 0,
  CTC_MBR_NUMB               VARCHAR2(3 BYTE),
  CTC_LUPD_DATE              DATE               NOT NULL,
  CTC_INS_DATE               DATE               NOT NULL,
  CTC_ATMUSAGE_LIMIT         NUMBER(5)          DEFAULT 0,
  CTC_POSUSAGE_LIMIT         NUMBER(5)          DEFAULT 0,
  CTC_BUSINESS_DATE          DATE               DEFAULT TO_DATE(TO_CHAR(trunc(SYSDATE),'dd/mm/yyyy') ||' 23:59:59','dd/mm/yyyy hh24:mi:ss'),
  CTC_ATMUSAGE_MAXLIMIT      NUMBER(5)          DEFAULT 9999,
  CTC_POSUSAGE_MAXLIMIT      NUMBER(5)          DEFAULT 9999,
  CTC_PREAUTHUSAGE_MAXLIMIT  NUMBER(5)          DEFAULT 10,
  CTC_PREAUTHUSAGE_LIMIT     NUMBER(5)          DEFAULT 0,
  CTC_PAN_CODE_ENCR          RAW(100),
  CTC_MMPOSUSAGE_AMT         NUMBER(20,3)       DEFAULT 0,
  CTC_MMPOSUSAGE_MAXLIMIT    NUMBER(5)          DEFAULT 9999,
  CTC_MMPOSUSAGE_LIMIT       NUMBER(5)          DEFAULT 0,
  CTC_MMPOS_OFFLINE_LIMIT    NUMBER(10)         DEFAULT 25000,
  CTC_MMPOS_ONLINE_LIMIT     NUMBER(10)         DEFAULT 75000
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


