CREATE TABLE VMSCMS.CMS_IRISPARAM_MAST
(
  CIM_FILE_ID     NUMBER(3)                     NOT NULL,
  CIM_FILE_TYPE   VARCHAR2(5 BYTE)              NOT NULL,
  CIM_FILE_VRSN   VARCHAR2(2 BYTE)              NOT NULL,
  CIM_BATCH_NUMB  VARCHAR2(3 BYTE)              NOT NULL,
  CIM_FILE_DATE   VARCHAR2(8 BYTE)              NOT NULL,
  CIM_INS_USER    NUMBER(5)                     NOT NULL,
  CIM_INS_DATE    DATE                          NOT NULL,
  CIM_LUPD_USER   NUMBER(5)                     NOT NULL,
  CIM_LUPD_DATE   DATE                          NOT NULL,
  CIM_INST_CODE   NUMBER(3)                     NOT NULL,
  CIM_1STRPT_GEN  CHAR(1 BYTE)                  DEFAULT 'N',
  CIM_SRCE_FLAG   CHAR(1 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_IRISPARAM_MAST ADD (
  CONSTRAINT PK_IRISMAST
 PRIMARY KEY
 (CIM_INST_CODE, CIM_FILE_TYPE))
/

