CREATE TABLE VMSCMS.CMS_OP_FIELD_DEFN_MAST
(
  COM_FILE_ID        NUMBER(20),
  COM_FIELD_ID       NUMBER(20),
  COM_SRC_FILE_ID    NUMBER(20),
  COM_SRC_FIELD_ID   NUMBER(20),
  COM_FIELD_CAPTION  VARCHAR2(30 BYTE),
  COM_FIELD_FORMAT   VARCHAR2(20 BYTE),
  COM_FRM_POSN       NUMBER(10),
  COM_TO_POSN        NUMBER(10),
  COM_COLN_POSN      NUMBER(10),
  COM_MAX_LEN        NUMBER(10),
  COM_LUPD_DATE      DATE,
  COM_INST_CODE      NUMBER(10),
  COM_LUPD_USER      NUMBER(10),
  COM_INS_DATE       DATE,
  COM_INS_USER       NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_OP_FIELD_DEFN_MAST ADD (
  CONSTRAINT FK_OP_FLD_MAST_FILE_ID 
 FOREIGN KEY (COM_FILE_ID) 
 REFERENCES VMSCMS.CMS_OP_FILE_DEFN_MAST (COM_FILE_ID))
/

