CREATE TABLE VMSCMS.CMS_CBD_REL
(
  CCR_INST_CODE    NUMBER(3)                    NOT NULL,
  CCR_ASSO_CODE    NUMBER(3)                    NOT NULL,
  CCR_INST_TYPE    NUMBER(3)                    NOT NULL,
  CCR_MAP_CODE     VARCHAR2(12 BYTE)            NOT NULL,
  CCR_INST_STATUS  CHAR(1 BYTE)                 NOT NULL,
  CCR_INS_USER     NUMBER(5)                    NOT NULL,
  CCR_INS_DATE     DATE                         NOT NULL,
  CCR_LUPD_USER    NUMBER(5)                    NOT NULL,
  CCR_LUPD_DATE    DATE                         NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CBD_REL ADD (
  CONSTRAINT PK_CBD_REL
 PRIMARY KEY
 (CCR_INST_CODE, CCR_ASSO_CODE, CCR_INST_TYPE))
/

ALTER TABLE VMSCMS.CMS_CBD_REL ADD (
  CONSTRAINT FK_CBDREL_INSTMAST 
 FOREIGN KEY (CCR_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_CBDREL_INSTTYPE 
 FOREIGN KEY (CCR_INST_CODE, CCR_INST_TYPE) 
 REFERENCES VMSCMS.CMS_INST_TYPE (CIT_INST_CODE,CIT_TYPE_CODE),
  CONSTRAINT FK_CBDREL_USERMAST2 
 FOREIGN KEY (CCR_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CBDREL_USERMAST1 
 FOREIGN KEY (CCR_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CBDREL_ASSOMAST 
 FOREIGN KEY (CCR_INST_CODE, CCR_ASSO_CODE) 
 REFERENCES VMSCMS.CMS_ASSO_MAST (CAM_INST_CODE,CAM_ASSO_CODE))
/

