CREATE TABLE VMSCMS.CMS_CHECKDEPOSIT_TRANSACTION
(
  CCT_INST_CODE      NUMBER(3),
  CCT_CARD_NO        VARCHAR2(90 BYTE),
  CCT_CARD_NO_ENCR   RAW(100),
  CCT_ACCT_NO        VARCHAR2(20 BYTE),
  CCT_CUST_ID        VARCHAR2(20 BYTE),
  CCT_DELV_CHNL      VARCHAR2(10 BYTE),
  CCT_CHECK_IMAGEFS  BLOB,
  CCT_CHECK_IMAGEBS  BLOB,
  CCT_TXN_AMNT       NUMBER(20,3)               DEFAULT 0,
  CCT_RRN            VARCHAR2(20 BYTE),
  CCT_CHECK_NO       VARCHAR2(35 BYTE),
  CCT_ROUTING_NO     VARCHAR2(10 BYTE),
  CCT_DEPOSIT_ID     VARCHAR2(35 BYTE),
  CCT_TXN_FLAG       VARCHAR2(3 BYTE),
  CCT_INS_DATE       DATE,
  CCT_LUPD_DATE      DATE,
  CCT_AUTH_ID        VARCHAR2(14 BYTE),
  CCT_CHECK_DESC     VARCHAR2(120 BYTE),
  CCT_PEND_TIME      VARCHAR2(10 BYTE),
  CCT_PEND_DATE      VARCHAR2(8 BYTE),
  CCT_TIME_STAMP     TIMESTAMP(6),
  CCT_ACT_TIME       VARCHAR2(10 BYTE),
  CCT_ACT_DATE       VARCHAR2(8 BYTE),
  CCT_PEND_AMT       NUMBER(20,3),
  CCT_MATCH_RULE     NUMBER(1),
  CCT_REASON_CODE    NUMBER(3),
  CCT_REASON_DESC    VARCHAR2(100 BYTE),
   CONSTRAINT PK_CHECK_DEPOSIT
 PRIMARY KEY
 (CCT_INST_CODE, CCT_RRN)
)TABLESPACE CMS_SML_TXN;