CREATE TABLE VMSCMS.CMS_HIGHRISKWITH_TXN24HRS
(
  ROWNO          NUMBER(10),
  ROWIDENTIFIER  VARCHAR2(100 BYTE),
  ROWDESC        VARCHAR2(25 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


