CREATE TABLE VMSCMS.CMS_REISSUE_VALIDSTAT
(
  CRV_INST_CODE      NUMBER(5),
  CRV_VALID_CRDSTAT  CHAR(1 BYTE),
  CRV_PROD_CATG      VARCHAR2(2 BYTE),
  CRV_INS_USER       NUMBER(5),
  CRV_INS_DATE       DATE,
  CRV_LUPD_USER      NUMBER(5),
  CRV_LUPD_DATE      DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_REISSUE_VALIDSTAT ADD (
  CONSTRAINT PK_INSTCODE_VALIDCRDSTAT
 PRIMARY KEY
 (CRV_INST_CODE, CRV_VALID_CRDSTAT))
/

ALTER TABLE VMSCMS.CMS_REISSUE_VALIDSTAT ADD (
  CONSTRAINT FK_REISSUEVALIDSTAT_USERMAST1 
 FOREIGN KEY (CRV_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_REISSUEVALIDSTAT_USERMAST2 
 FOREIGN KEY (CRV_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

