CREATE TABLE VMSCMS.CMS_SMSEMAIL_ALERT_DET
(
  CAD_ALERT_ID           NUMBER(2),
  CAD_ALERT_NAME         VARCHAR2(50 BYTE),
  CAD_COLUMN_NAME        VARCHAR2(50 BYTE),
  CAD_ALERT_AMNT_COLUMN  VARCHAR2(50 BYTE),
  CAD_INS_USER           NUMBER(5),
  CAD_INS_DATE           DATE,
  CAD_LUPD_USER          NUMBER(5),
  CAD_LUPD_DATE          DATE,
  CAD_PRODCC_COLUMN      VARCHAR2(50 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


