CREATE TABLE VMSCMS.CMS_USER_MAST_CORPORATE
(
  CUM_USER_PIN        NUMBER(5)                 NOT NULL,
  CUM_INST_CODE       NUMBER(3)                 NOT NULL,
  CUM_USER_CODE       VARCHAR2(15 BYTE)         NOT NULL,
  CUM_ENCR_PSWD       VARCHAR2(100 BYTE)        NOT NULL,
  CUM_USER_NAME       VARCHAR2(50 BYTE),
  CUM_VALID_FRDT      DATE,
  CUM_VALID_TODT      DATE,
  CUM_MAXM_SESS       NUMBER(1)                 DEFAULT 1,
  CUM_CURR_SESS       NUMBER(1)                 DEFAULT 0,
  CUM_USER_SUSP       CHAR(1 BYTE),
  CUM_PSWD_DATE       DATE                      NOT NULL,
  CUM_INS_USER        NUMBER(5)                 NOT NULL,
  CUM_INS_DATE        DATE                      NOT NULL,
  CUM_LUPD_USER       NUMBER(5)                 NOT NULL,
  CUM_LUPD_DATE       DATE                      NOT NULL,
  CUM_LAST_LOGINTIME  VARCHAR2(20 BYTE),
  CUM_IPIN_OFFSET     VARCHAR2(100 BYTE),
  CUM_CORP_CODE       VARCHAR2(4 BYTE)          DEFAULT '0',
  CUM_AGENT_CODE      VARCHAR2(4 BYTE),
  CUM_USER_EMAIL      VARCHAR2(100 BYTE),
  CUM_FORCE_PSWD      VARCHAR2(1 BYTE)          DEFAULT 'N',
  CUM_USER_TYPE       VARCHAR2(1 BYTE)          DEFAULT 0
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


