CREATE TABLE VMSCMS.CMS_PROD_CATSEC
(
  CPC_INST_CODE  NUMBER(3),
  CPC_PROD_CODE  VARCHAR2(6 BYTE),
  CPC_SEC_CODE   VARCHAR2(3 BYTE),
  CPC_INS_USER   NUMBER(5),
  CPC_INS_DATE   DATE,
  CPC_LUPD_USER  NUMBER(5),
  CPC_LUPD_DATE  DATE,
  CPC_CARD_TYPE  NUMBER(2),
  CPC_TRAN_CODE  VARCHAR2(3 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROD_CATSEC ADD (
  CONSTRAINT CMS_PROD_CATSEC_U01
 UNIQUE (CPC_INST_CODE, CPC_PROD_CODE, CPC_SEC_CODE, CPC_CARD_TYPE, CPC_TRAN_CODE))
/

ALTER TABLE VMSCMS.CMS_PROD_CATSEC ADD (
  CONSTRAINT CMS_PROD_CATSEC_R01 
 FOREIGN KEY (CPC_INST_CODE, CPC_PROD_CODE, CPC_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CATTYPE (CPC_INST_CODE,CPC_PROD_CODE,CPC_CARD_TYPE))
/

