CREATE TABLE VMSCMS.CMS_BIN_MAST
(
  CBM_INST_CODE         NUMBER(3)               NOT NULL,
  CBM_INTERCHANGE_CODE  VARCHAR2(2 BYTE),
  CBM_INST_BIN          NUMBER(10)              NOT NULL,
  CBM_SERV_CODE         VARCHAR2(3 BYTE),
  CBM_VENDOR            CHAR(1 BYTE),
  CBM_INS_USER          NUMBER(5)               NOT NULL,
  CBM_INS_DATE          DATE                    NOT NULL,
  CBM_LUPD_USER         NUMBER(5)               NOT NULL,
  CBM_LUPD_DATE         DATE                    NOT NULL,
  CBM_BIN_STAT          VARCHAR2(2 BYTE)        DEFAULT '1',
  CBM_MARC_BIN_FLAG     VARCHAR2(1 BYTE)        DEFAULT 'N'                   NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BIN_MAST ADD (
  CONSTRAINT PK_BIN_MAST
 PRIMARY KEY
 (CBM_INST_CODE, CBM_INST_BIN))
/

ALTER TABLE VMSCMS.CMS_BIN_MAST ADD (
  CONSTRAINT FK_BINMAST_USERMAST1 
 FOREIGN KEY (CBM_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_BINMAST_USERMAST2 
 FOREIGN KEY (CBM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_BINMAST_INSTMAST 
 FOREIGN KEY (CBM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_BINMAST_INTERCHANGEMAST 
 FOREIGN KEY (CBM_INST_CODE, CBM_INTERCHANGE_CODE) 
 REFERENCES VMSCMS.CMS_INTERCHANGE_MAST (CIM_INST_CODE,CIM_INTERCHANGE_CODE))
/

