CREATE TABLE VMSCMS.CMS_SLAB_LOYL
(
  CSL_INST_CODE  NUMBER(3)                      NOT NULL,
  CSL_LOYL_CODE  NUMBER(3)                      NOT NULL,
  CSL_SLAB_CODE  NUMBER(3)                      NOT NULL,
  CSL_INS_USER   NUMBER(5)                      NOT NULL,
  CSL_INS_DATE   DATE                           NOT NULL,
  CSL_LUPD_USER  NUMBER(5)                      NOT NULL,
  CSL_LUPD_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SLAB_LOYL ADD (
  CONSTRAINT PK_SLAB_LOYL
 PRIMARY KEY
 (CSL_INST_CODE, CSL_LOYL_CODE),
  CONSTRAINT UK_SLAB_LOYL
 UNIQUE (CSL_INST_CODE, CSL_SLAB_CODE))
/

ALTER TABLE VMSCMS.CMS_SLAB_LOYL ADD (
  CONSTRAINT FK_SLABLOYL_LOYLMAST 
 FOREIGN KEY (CSL_INST_CODE, CSL_LOYL_CODE) 
 REFERENCES VMSCMS.CMS_LOYL_MAST (CLM_INST_CODE,CLM_LOYL_CODE),
  CONSTRAINT FK_SLABLOYL_USERMAST1 
 FOREIGN KEY (CSL_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_SLABLOYL_USERMAST2 
 FOREIGN KEY (CSL_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

