CREATE TABLE VMSCMS.CMS_CALLCATG_MAST
(
  CCM_INST_CODE  NUMBER(5),
  CCM_CATG_ID    NUMBER(3),
  CCM_CATG_DESC  VARCHAR2(50 BYTE),
  CCM_INS_USER   NUMBER(5)                      NOT NULL,
  CCM_INS_DATE   DATE                           NOT NULL,
  CCM_LUPD_USER  NUMBER(5),
  CCM_LUPD_DATE  DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


