CREATE TABLE VMSCMS.CMS_MESSAGE_LOG
(
  CML_MESSAGE_ID    NUMBER(2),
  CML_MESSAGE_DESC  VARCHAR2(200 BYTE),
  CML_ACTION_DESC   VARCHAR2(200 BYTE),
  CML_LUPD_DATE     DATE,
  CML_INST_CODE     NUMBER(10),
  CML_LUPD_USER     NUMBER(10),
  CML_INS_DATE      DATE,
  CML_INS_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


