CREATE TABLE VMSCMS.CMS_FILE_FOOTER_MAST
(
  CFF_FILE_ID             NUMBER(20),
  CFF_CTRL_ID             NUMBER(2),
  CFF_CTRL_TYPE           VARCHAR2(20 BYTE),
  CFF_CTRL_DATA_FRM_POSN  NUMBER(10),
  CFF_CTRL_DATA_TO_POSN   NUMBER(10),
  CFF_CTRL_COL_POSN       NUMBER(5),
  CFF_DATAREC_FIELD       VARCHAR2(6 BYTE),
  CFF_LUPD_DATE           DATE,
  CFF_INST_CODE           NUMBER(10),
  CFF_LUPD_USER           NUMBER(10),
  CFF_INS_DATE            DATE,
  CFF_INS_USER            NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FILE_FOOTER_MAST ADD (
  CONSTRAINT PK_CFF_FILE_ID
 PRIMARY KEY
 (CFF_FILE_ID, CFF_CTRL_ID) DISABLE)
/

ALTER TABLE VMSCMS.CMS_FILE_FOOTER_MAST ADD (
  CONSTRAINT FK_CFF_FILE_ID 
 FOREIGN KEY (CFF_FILE_ID) 
 REFERENCES VMSCMS.CMS_FILE_DEFIN_MAST (CFD_FILE_ID))
/

