CREATE TABLE VMSCMS.CMS_CCF_CTRL
(
  CCC_INST_CODE    NUMBER(3),
  CCC_CCFGEN_DATE  DATE,
  CCC_HEADER_SEQ   NUMBER(6),
  CCC_DETAIL_SEQ   NUMBER(6),
  CCC_INS_USER     NUMBER(5),
  CCC_INS_DATE     DATE,
  CCC_LUPD_USER    NUMBER(5),
  CCC_LUPD_DATE    DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


