CREATE TABLE VMSCMS.CMS_MERINV_LOCATION
(
  CML_INST_CODE      NUMBER(10),
  CML_MER_ID         NUMBER(15),
  CML_LOCATION_ID    VARCHAR2(15 BYTE),
  CML_LOCATION_NAME  VARCHAR2(50 BYTE)          NOT NULL,
  CML_PADD_ONE       VARCHAR2(50 BYTE)          NOT NULL,
  CML_PADD_TWO       VARCHAR2(50 BYTE),
  CML_PCITY_CODE     VARCHAR2(50 BYTE)          NOT NULL,
  CML_PSTATE_CODE    NUMBER(3)                  NOT NULL,
  CML_PZIP_CODE      NUMBER(10)                 NOT NULL,
  CML_PCNTRY_CODE    NUMBER(3)                  NOT NULL,
  CML_LUPD_DATE      DATE                       NOT NULL,
  CML_LUPD_USER      NUMBER(10)                 NOT NULL,
  CML_INS_DATE       DATE                       NOT NULL,
  CML_INS_USER       NUMBER(10)                 NOT NULL,
  CML_FILLER         VARCHAR2(15 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MERINV_LOCATION ADD (
  CONSTRAINT PK_CMS_MERINV_LOCATION
 PRIMARY KEY
 (CML_INST_CODE, CML_MER_ID, CML_LOCATION_ID))
/

ALTER TABLE VMSCMS.CMS_MERINV_LOCATION ADD (
  CONSTRAINT FK_CMS_MERINV_LOCATION 
 FOREIGN KEY (CML_INST_CODE, CML_MER_ID) 
 REFERENCES VMSCMS.CMS_MERINV_MAST (CMM_INST_CODE,CMM_MER_ID))
/

