CREATE TABLE VMSCMS.CMS_CHANGE_CARDSTAT
(
  CCC_STAT_CODE  CHAR(1 BYTE)                   NOT NULL,
  CCC_STAT_DESC  VARCHAR2(50 BYTE)              NOT NULL,
  CCC_LUPD_DATE  DATE,
  CCC_INST_CODE  NUMBER(10),
  CCC_LUPD_USER  NUMBER(10),
  CCC_INS_DATE   DATE,
  CCC_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


