CREATE TABLE VMSCMS.CMS_FEE_PLAN
(
  CFP_PLAN_ID    NUMBER(4),
  CFP_PLAN_DESC  VARCHAR2(50 BYTE),
  CFP_INST_CODE  NUMBER(3),
  CFP_INS_USER   NUMBER(10),
  CFP_INS_DATE   DATE,
  CFP_LUPD_USER  NUMBER(10),
  CFP_LUPD_DATE  DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FEE_PLAN ADD (
  CONSTRAINT PK_FEE_PLAN1
 PRIMARY KEY
 (CFP_INST_CODE, CFP_PLAN_ID))
/

