CREATE TABLE VMSCMS.CMS_MCC_TRAN
(
  CMT_INST_CODE  NUMBER(3),
  CMT_MCC_CODE   VARCHAR2(6 BYTE),
  CMT_INS_DATE   DATE,
  CMT_INS_USER   NUMBER(10),
  CMT_LUPD_DATE  DATE,
  CMT_LUPD_USER  NUMBER(10),
  CMT_MCC_ID     VARCHAR2(6 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MCC_TRAN ADD (
  CONSTRAINT FK_CMT_MCC_ID 
 FOREIGN KEY (CMT_MCC_ID) 
 REFERENCES VMSCMS.GPR_VALID_CARDSTAT (GVC_MCC_ID),
  CONSTRAINT FK_CMT_MCC_CODED 
 FOREIGN KEY (CMT_INST_CODE, CMT_MCC_CODE) 
 REFERENCES VMSCMS.MCCODE (ACT_INST_CODE,MCCODE))
/

