CREATE TABLE VMSCMS.CMS_STOCK_REPORT
(
  CSR_INST_CODE       NUMBER(3),
  CSR_BRAN_FIID       VARCHAR2(20 BYTE),
  CSR_INST_BIN        NUMBER(10),
  CSR_CARD_GENERATED  NUMBER(9)                 DEFAULT 0,
  CSR_LUPD_USER       NUMBER(5),
  CSR_LUPD_DATE       DATE,
  CSR_PANGEN_FLAG     VARCHAR2(2 BYTE)          DEFAULT 'N',
  CSR_FILE_NAME       VARCHAR2(35 BYTE),
  CSR_PROD_CODE       VARCHAR2(6 BYTE),
  CSR_CARD_TYPE       NUMBER(2),
  CSR_CUST_CATG       NUMBER(5)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_STOCK_REPORT ADD (
  CONSTRAINT FK_STOCKREPORT_PRODCATTYPE 
 FOREIGN KEY (CSR_INST_CODE, CSR_PROD_CODE, CSR_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CATTYPE (CPC_INST_CODE,CPC_PROD_CODE,CPC_CARD_TYPE),
  CONSTRAINT FK_STOCKREPORT_CUSTCATG 
 FOREIGN KEY (CSR_INST_CODE, CSR_CUST_CATG) 
 REFERENCES VMSCMS.CMS_CUST_CATG (CCC_INST_CODE,CCC_CATG_CODE))
/

