CREATE TABLE VMSCMS.CMS_INST_DETAILS
(
  CID_INST_CODE     NUMBER(3)                   NOT NULL,
  CID_INST_NAME     VARCHAR2(100 BYTE)          NOT NULL,
  CID_INST_ADDR1    VARCHAR2(50 BYTE),
  CID_INST_ADDR2    VARCHAR2(50 BYTE),
  CID_INST_ADDR3    VARCHAR2(50 BYTE),
  CID_INST_ZIP      NUMBER(8),
  CID_INST_CONTPER  VARCHAR2(50 BYTE),
  CID_INST_PHONE    NUMBER(10),
  CID_INST_EMAIL    VARCHAR2(20 BYTE),
  CID_INS_USER      NUMBER(5)                   NOT NULL,
  CID_INS_DATE      DATE                        NOT NULL,
  CID_LUPD_USER     NUMBER(5)                   NOT NULL,
  CID_LUPD_DATE     DATE                        NOT NULL,
  CID_INS_LOGO      VARCHAR2(100 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


