CREATE TABLE VMSCMS.CMS_SPPRT_FUNCS
(
  CSF_SPPRT_KEY   VARCHAR2(12 BYTE)             NOT NULL,
  CSF_SPPRT_DESC  VARCHAR2(50 BYTE)             NOT NULL,
  CSF_LUPD_DATE   DATE,
  CSF_INST_CODE   NUMBER(10),
  CSF_LUPD_USER   NUMBER(10),
  CSF_INS_DATE    DATE,
  CSF_INS_USER    NUMBER(10),
  CSF_TRAN_CODE   VARCHAR2(2 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SPPRT_FUNCS ADD (
  CONSTRAINT PK_SPPRT_FUNCS
 PRIMARY KEY
 (CSF_INST_CODE, CSF_SPPRT_KEY))
/

