CREATE TABLE VMSCMS.CMS_BATCHUPLOAD_TYPE
(
  CBT_INST_CODE      NUMBER(3),
  CBT_FILE_TYPE      NUMBER(5),
  CBT_FILE_TYPEDESC  VARCHAR2(100 BYTE),
  CBT_INST_USER      NUMBER(5),
  CBT_INST_DATE      DATE,
  CBT_LUPD_USER      NUMBER(5),
  CBT_LUPD_DATE      DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BATCHUPLOAD_TYPE ADD (
  CONSTRAINT PK_UPLOADTYPE
 PRIMARY KEY
 (CBT_INST_CODE, CBT_FILE_TYPE))
/

