CREATE TABLE VMSCMS.CMS_C2CTXFR_TRANSACTION
(
  CCT_INST_CODE         NUMBER(3)               NOT NULL,
  CCT_TXN_CODE          VARCHAR2(2 BYTE)        NOT NULL,
  CCT_TXN_TYPE          VARCHAR2(1 BYTE)        NOT NULL,
  CCT_RRN               VARCHAR2(20 BYTE)       NOT NULL,
  CCT_DEL_CHNL          VARCHAR2(2 BYTE)        NOT NULL,
  CCT_TXN_AMT           NUMBER(20,3)            NOT NULL,
  CCT_FROM_CARD         VARCHAR2(90 BYTE)       NOT NULL,
  CCT_TO_CARD           VARCHAR2(90 BYTE)       NOT NULL,
  CCT_DATE_TIME         DATE                    NOT NULL,
  CCT_TXN_DATE          VARCHAR2(8 BYTE)        NOT NULL,
  CCT_TXN_TIME          VARCHAR2(10 BYTE)       NOT NULL,
  CCT_TXN_STATUS        VARCHAR2(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  CCT_FROM_CARD_ENCR    RAW(100)                NOT NULL,
  CCT_TO_CARD_ENCR      RAW(100)                NOT NULL,
  CCT_FROM_ACCT         VARCHAR2(20 BYTE)       NOT NULL,
  CCT_TO_ACCT           VARCHAR2(20 BYTE)       NOT NULL,
  CCT_REQUEST_ID        NUMBER(20)              NOT NULL,
  CCT_INS_DATE          DATE                    NOT NULL,
  CCT_INS_USER          NUMBER(5)               NOT NULL,
  CCT_LUPD_DATE         DATE                    NOT NULL,
  CCT_LUPD_USER         NUMBER(5)               NOT NULL,
  CCT_PROD_CODE         VARCHAR2(6 BYTE)        NOT NULL,
  CCT_MAKER_REMARKS     VARCHAR2(500 BYTE),
  CCT_APPROVER_REMARKS  VARCHAR2(500 BYTE),
  CCT_APPROVER_USER     NUMBER(5),
  CCT_APPROVAL_DATE     DATE,
  CCT_RESPONSE_ID       NUMBER(5)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_C2CTXFR_TRANSACTION ADD (
  CONSTRAINT PK_REQ_ID
 PRIMARY KEY
 (CCT_REQUEST_ID))
/

