CREATE TABLE VMSCMS.CMS_RESPONSE_MAST
(
  CMS_INST_CODE         NUMBER(3),
  CMS_DELIVERY_CHANNEL  NUMBER(2),
  CMS_RESPONSE_ID       NUMBER(5),
  CMS_ISO_RESPCDE       VARCHAR2(5 BYTE),
  CMS_B24_RESPCDE       VARCHAR2(3 BYTE),
  CMS_RESP_DESC         VARCHAR2(300 BYTE),
  CMS_INS_USER          NUMBER(5),
  CMS_INS_DATE          DATE,
  CMS_LUPD_USER         NUMBER(5),
  CMS_LUPD_DATE         DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_RESPONSE_MAST ADD (
  CONSTRAINT PK1_RESPONSE_MAST
 PRIMARY KEY
 (CMS_INST_CODE, CMS_DELIVERY_CHANNEL, CMS_RESPONSE_ID))
/

