CREATE TABLE VMSCMS.CMS_CARDISS_PIN_HIST
(
  CCP_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CCP_MBR_NUMB       VARCHAR2(3 BYTE),
  CCP_PIN_OFF        VARCHAR2(10 BYTE),
  CCP_INS_USER       NUMBER(5),
  CCP_INS_DATE       DATE,
  CCP_RRN            VARCHAR2(20 BYTE),
  CCP_PAN_CODE_ENCR  RAW(100),
  CCP_CALL_LOGID     VARCHAR2(30 BYTE)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


