CREATE TABLE VMSCMS.CMS_TEMP_SBKIT
(
  CTS_ACCT_NO        VARCHAR2(12 BYTE),
  CTS_UNFREEZE_DATE  DATE,
  CTS_LUPD_DATE      DATE,
  CTS_INST_CODE      NUMBER(10),
  CTS_LUPD_USER      NUMBER(10),
  CTS_INS_DATE       DATE,
  CTS_INS_USER       NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


