CREATE TABLE VMSCMS.CMS_GROUP_PROG_TEMP_FORDISPLAY
(
  CGP_INST_CODE   NUMBER(3)                     NOT NULL,
  CGP_GROUP_CODE  NUMBER(3)                     NOT NULL,
  CGP_PROG_CODE   NUMBER                        NOT NULL,
  CGP_INSR_ALLOW  NUMBER(1),
  CGP_DELE_ALLOW  NUMBER(1),
  CGP_UPDT_ALLOW  NUMBER(1),
  CGP_INS_USER    NUMBER(5)                     NOT NULL,
  CGP_INS_DATE    DATE                          NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


