CREATE TABLE VMSCMS.CMS_ACCTCLOSE_TEMP
(
  CAT_INST_CODE     NUMBER(3),
  CAT_CARD_NO       VARCHAR2(90 BYTE),
  CAT_ACCT_NO       VARCHAR2(20 BYTE),
  CAT_FILE_NAME     VARCHAR2(30 BYTE),
  CAT_REMARKS       VARCHAR2(100 BYTE),
  CAT_PROCESS_FLAG  VARCHAR2(1 BYTE)            DEFAULT 'N',
  CAT_PROCESS_MSG   VARCHAR2(300 BYTE),
  CAT_LUPD_USER     NUMBER(5),
  CAT_LUPD_DATE     DATE                        DEFAULT SYSDATE,
  CAT_INS_USER      NUMBER(5),
  CAT_INS_DATE      DATE                        DEFAULT SYSDATE,
  CAT_AMOUNT        NUMBER(10),
  CAT_SINKAMT       VARCHAR2(10 BYTE),
  CAT_SINKBANKNAME  VARCHAR2(10 BYTE),
  CAT_SINKBRANCH    VARCHAR2(10 BYTE),
  CAT_SINKBANKACCT  VARCHAR2(10 BYTE),
  CAT_SINKBANKIFCS  VARCHAR2(10 BYTE),
  CAT_MBR_NUMB      VARCHAR2(10 BYTE),
  CAT_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


