CREATE TABLE VMSCMS.CMS_ANSR_MAST
(
  CAM_INST_CODE  NUMBER(5),
  CAM_USER_CODE  NUMBER(5),
  CAM_QUST_CODE  NUMBER(2),
  CAM_ANSR_DESC  VARCHAR2(100 BYTE)             NOT NULL,
  CAM_INS_USER   NUMBER(8)                      NOT NULL,
  CAM_INS_DATE   DATE                           NOT NULL,
  CAM_LUPD_USER  NUMBER(8),
  CAM_LUPD_DATE  DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ANSR_MAST ADD (
  CONSTRAINT PK_CAM_INSTUSERQUST
 PRIMARY KEY
 (CAM_INST_CODE, CAM_USER_CODE, CAM_QUST_CODE))
/

ALTER TABLE VMSCMS.CMS_ANSR_MAST ADD (
  CONSTRAINT FK_CAS_PWUS_CUM_USID 
 FOREIGN KEY (CAM_USER_CODE) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_CAS_PWIN_CUM_USID 
 FOREIGN KEY (CAM_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_CAS_INST_CIM_INST 
 FOREIGN KEY (CAM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

