CREATE TABLE VMSCMS.CMS_TRACK_LOGIN
(
  CTL_INST_CODE       NUMBER(3),
  CTL_USER_PIN        NUMBER(5),
  CTL_WRONG_LOGINCNT  NUMBER(3),
  CTL_LOGIN_DATE      DATE,
  CTL_LUPD_DATE       DATE,
  CTL_LUPD_USER       NUMBER(10),
  CTL_INS_DATE        DATE,
  CTL_INS_USER        NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TRACK_LOGIN ADD (
  CONSTRAINT FK_TRACKLOGINS_USERMAST 
 FOREIGN KEY (CTL_USER_PIN) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN) DISABLE)
/

