CREATE TABLE VMSCMS.CMS_PROD_ADHOCFEE
(
  CPA_INST_CODE      NUMBER(3),
  CPA_PROD_CODE      VARCHAR2(6 BYTE),
  CPA_SPPRT_RSNCODE  NUMBER(3),
  CPA_FEE_AMT        NUMBER(15,2)               NOT NULL,
  CPA_INS_USER       NUMBER(5)                  NOT NULL,
  CPA_INS_DATE       DATE                       NOT NULL,
  CPA_LUPD_USER      NUMBER(5),
  CPA_LUPD_DATE      DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROD_ADHOCFEE ADD (
  CONSTRAINT PK_CPA_PROD_ADHOCFEE
 PRIMARY KEY
 (CPA_INST_CODE, CPA_PROD_CODE, CPA_SPPRT_RSNCODE))
/

ALTER TABLE VMSCMS.CMS_PROD_ADHOCFEE ADD (
  CONSTRAINT FK_CPA_INSUSER 
 FOREIGN KEY (CPA_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CPA_REASONCODE 
 FOREIGN KEY (CPA_INST_CODE, CPA_SPPRT_RSNCODE) 
 REFERENCES VMSCMS.CMS_SPPRT_REASONS (CSR_INST_CODE,CSR_SPPRT_RSNCODE),
  CONSTRAINT FK_CPA_PRODCODE 
 FOREIGN KEY (CPA_INST_CODE, CPA_PROD_CODE) 
 REFERENCES VMSCMS.CMS_PROD_MAST (CPM_INST_CODE,CPM_PROD_CODE))
/

