CREATE TABLE VMSCMS.CMS_LOYL_POINTS
(
  CLP_INST_CODE      NUMBER(3)                  NOT NULL,
  CLP_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CLP_MBR_NUMB       VARCHAR2(3 BYTE)           NOT NULL,
  CLP_LOYL_POINTS    NUMBER(5)                  NOT NULL,
  CLP_LAST_RDMDATE   DATE,
  CLP_INS_USER       NUMBER(5)                  NOT NULL,
  CLP_INS_DATE       DATE                       NOT NULL,
  CLP_LUPD_USER      NUMBER(5)                  NOT NULL,
  CLP_LUPD_DATE      DATE                       NOT NULL,
  CLP_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_LOYL_POINTS ADD (
  CONSTRAINT PK_LOYL_POINTS
 PRIMARY KEY
 (CLP_PAN_CODE, CLP_MBR_NUMB))
/

ALTER TABLE VMSCMS.CMS_LOYL_POINTS ADD (
  CONSTRAINT FK_LOYLPOINTS_APPLPAN 
 FOREIGN KEY (CLP_PAN_CODE, CLP_MBR_NUMB) 
 REFERENCES VMSCMS.CMS_APPL_PAN (CAP_PAN_CODE,CAP_MBR_NUMB),
  CONSTRAINT FK_LOYLPOINTS_INSTMAST 
 FOREIGN KEY (CLP_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_LOYLPOINTS_USERMAST1 
 FOREIGN KEY (CLP_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_LOYLPOINTS_USERMAST2 
 FOREIGN KEY (CLP_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

