CREATE TABLE VMSCMS.CMS_PIN_CHECK
(
  CPC_PAN_CODE       VARCHAR2(90 BYTE),
  CPC_INST_CODE      NUMBER,
  CPC_PIN_COUNT      NUMBER,
  CPC_INS_USER       VARCHAR2(5 BYTE),
  CPC_INS_DATE       DATE,
  CPC_LUPD_DATE      DATE,
  CPC_PAN_CODE_ENCR  RAW(100),
  CPC_BUSI_DATE      DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


