CREATE TABLE VMSCMS.CMS_CALLLOG_DETAILS
(
  CCD_INST_CODE    NUMBER(5),
  CCD_CALL_ID      NUMBER(20),
  CCD_PAN_CODE     VARCHAR2(90 BYTE),
  CCD_CALL_SEQ     NUMBER(10),
  CCD_RRN          VARCHAR2(20 BYTE),
  CCD_DEVL_CHNL    VARCHAR2(2 BYTE),
  CCD_TXN_CODE     VARCHAR2(2 BYTE),
  CCD_TRAN_DATE    VARCHAR2(8 BYTE),
  CCD_TRAN_TIME    VARCHAR2(10 BYTE),
  CCD_TBL_NAMES    VARCHAR2(50 BYTE),
  CCD_COLM_NAME    VARCHAR2(1000 BYTE),
  CCD_OLD_VALUE    VARCHAR2(1000 BYTE),
  CCD_NEW_VALUE    VARCHAR2(1000 BYTE),
  CCD_COMMENTS     VARCHAR2(1000 BYTE),
  CCD_TXNPRC_FLAG  CHAR(1 BYTE)                 DEFAULT 'N',
  CCD_INS_USER     NUMBER(5)                    NOT NULL,
  CCD_INS_DATE     DATE                         NOT NULL,
  CCD_LUPD_USER    NUMBER(5),
  CCD_LUPD_DATE    DATE,
  CCD_ACCT_NO      VARCHAR2(20 BYTE)            DEFAULT 'NA'                  NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CALLLOG_DETAILS ADD (
  CONSTRAINT FK_INST_CALLID 
 FOREIGN KEY (CCD_INST_CODE, CCD_PAN_CODE, CCD_CALL_ID) 
 REFERENCES VMSCMS.CMS_CALLLOG_MAST (CCM_INST_CODE,CCM_PAN_CODE,CCM_CALL_ID))
/

