CREATE TABLE VMSCMS.CMS_BRAN_FIID
(
  CBF_INST_CODE  NUMBER(3),
  CBF_BRAN_CODE  VARCHAR2(6 BYTE),
  CBF_FIID       VARCHAR2(4 BYTE)               DEFAULT 'ICIP'                NOT NULL,
  CBF_INS_USER   NUMBER(5),
  CBF_INS_DATE   DATE,
  CBF_LUPD_DATE  DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BRAN_FIID ADD (
  CONSTRAINT PK_CBF_BRAN
 PRIMARY KEY
 (CBF_INST_CODE, CBF_BRAN_CODE))
/

ALTER TABLE VMSCMS.CMS_BRAN_FIID ADD (
  CONSTRAINT FK_BRANFIID_INSTMAST 
 FOREIGN KEY (CBF_INST_CODE, CBF_BRAN_CODE) 
 REFERENCES VMSCMS.CMS_BRAN_MAST (CBM_INST_CODE,CBM_BRAN_CODE))
/

