CREATE TABLE VMSCMS.CMS_FUNC_ACCT
(
  CFA_INST_CODE      NUMBER(3),
  CFA_FUNC_CODE      VARCHAR2(18 BYTE),
  CFA_CREDIT_ACCT    VARCHAR2(20 BYTE),
  CFA_DEBIT_ACCT     VARCHAR2(20 BYTE),
  CFA_PROCESSES_AMT  NUMBER,
  CFA_PROCESSES_TYP  VARCHAR2(1 BYTE),
  CFA_LUPD_DATE      DATE,
  CFA_LUPD_USER      NUMBER(10),
  CFA_INS_DATE       DATE,
  CFA_INS_USER       NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


