CREATE TABLE VMSCMS.CMS_GPDTDETL_AUDT
(
  CGA_INST_CODE  NUMBER(5),
  CGA_FILD_UQID  NUMBER(17),
  CGA_ENTY_TYPE  NUMBER(3),
  CGA_FILD_TYPE  NUMBER(3),
  CGA_OLD_VALU   VARCHAR2(100 BYTE),
  CGA_NEW_VALU   VARCHAR2(100 BYTE),
  CGA_INS_USER   NUMBER(8),
  CGA_INS_DATE   DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


