CREATE TABLE VMSCMS.CMS_USERDETL_AUDT
(
  CUA_USER_CODE      NUMBER(8),
  CUA_LGIN_CODE      VARCHAR2(40 BYTE)          NOT NULL,
  CUA_LGIN_PSWD      VARCHAR2(200 BYTE)         NOT NULL,
  CUA_TXN_PSWD       VARCHAR2(200 BYTE),
  CUA_USER_NAME      VARCHAR2(50 BYTE)          NOT NULL,
  CUA_VALD_FRDT      DATE                       NOT NULL,
  CUA_VALD_TODT      DATE                       NOT NULL,
  CUA_USER_EMAL      VARCHAR2(100 BYTE)         NOT NULL,
  CUA_USER_MOBL      VARCHAR2(20 BYTE),
  CUA_USER_DOFB      DATE,
  CUA_FRTX_PSWD      NUMBER(1),
  CUA_FRLG_PSWD      NUMBER(1),
  CUA_HRTX_BLCK      NUMBER(1),
  CUA_PREV_EMAL      VARCHAR2(100 BYTE),
  CUA_LGPW_RSFL      NUMBER(1)                  NOT NULL,
  CUA_LGPW_RSDT      DATE,
  CUA_LGPW_DATE      DATE,
  CUA_TXPW_RSFL      NUMBER(1),
  CUA_TXPW_RSDT      DATE,
  CUA_TXPW_DATE      DATE,
  CUA_INPT_SRCE      NUMBER(1)                  NOT NULL,
  CUA_TRPF_PRIV      NUMBER(1),
  CUA_USER_STUS      NUMBER(1)                  NOT NULL,
  CUA_INS_USER       NUMBER(8)                  NOT NULL,
  CUA_INS_DATE       DATE                       NOT NULL,
  CUA_LAST_LGDT      VARCHAR2(100 BYTE),
  CUA_SESN_PSWD      VARCHAR2(200 BYTE),
  CUA_USER_UUID      VARCHAR2(100 BYTE),
  CUA_UUID_DATE      DATE,
  CUA_USERMASK_FLAG  VARCHAR2(2 BYTE)           NOT NULL,
  CUA_AUTH_BIN       VARCHAR2(2000 BYTE),
  CUA_AUDT_FLAG      VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


