CREATE TABLE VMSCMS.CMS_ODFI_ACH_MAST_RI2311
(
  COA_INST_CODE  NUMBER(3),
  COA_PROD_CODE  VARCHAR2(6 BYTE),
  COA_ODFI_CODE  VARCHAR2(20 BYTE),
  COA_INS_DATE   DATE                           NOT NULL,
  COA_INS_USER   NUMBER                         NOT NULL,
  COA_LUPD_DATE  DATE                           NOT NULL,
  COA_LUPD_USER  NUMBER                         NOT NULL
)
TABLESPACE CMS_BKUP
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


