CREATE TABLE VMSCMS.CMS_PINMAILER_LOC
(
  CPL_PINMAILER_CODE    NUMBER(4),
  CPL_PINMAILER_ROW     NUMBER(3),
  CPL_PINMAILER_COLUMN  NUMBER(3),
  CPL_PINMAILER_LENGTH  NUMBER(3),
  CPL_LUPD_DATE         DATE,
  CPL_INST_CODE         NUMBER(10),
  CPL_LUPD_USER         NUMBER(10),
  CPL_INS_DATE          DATE,
  CPL_INS_USER          NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PINMAILER_LOC ADD (
  CONSTRAINT PK_PINMAILER_LOC
 PRIMARY KEY
 (CPL_PINMAILER_CODE))
/

ALTER TABLE VMSCMS.CMS_PINMAILER_LOC ADD (
  CONSTRAINT FK_PINMAILERLOC_PINMAILERMAST 
 FOREIGN KEY (CPL_PINMAILER_CODE) 
 REFERENCES VMSCMS.CMS_PINMAILER_MAST (CPM_PINMAILER_CODE))
/

