CREATE TABLE VMSCMS.CMS_CUSTCARD_SUSP
(
  CCS_CARD_NO    VARCHAR2(16 BYTE),
  CCS_FROM_DATE  DATE,
  CCS_TO_DATE    DATE,
  CCS_INS_DATE   DATE,
  CCS_LUPD_DATE  DATE,
  CCS_INST_CODE  NUMBER(10),
  CCS_LUPD_USER  NUMBER(10),
  CCS_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


