CREATE TABLE VMSCMS.CMS_CNTRYGRP_CNTRYCODE
(
  CCC_INST_CODE      NUMBER(10),
  CCC_CNTRY_GRPCODE  VARCHAR2(4 BYTE),
  CCC_CNTRY_CODE     VARCHAR2(4 BYTE),
  CCC_LUPD_DATE      DATE,
  CCC_LUPD_USER      NUMBER(10),
  CCC_INS_DATE       DATE,
  CCC_INS_USER       NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CNTRYGRP_CNTRYCODE ADD (
  CONSTRAINT PK_CNTRYCDE_CNTRYGRP
 PRIMARY KEY
 (CCC_CNTRY_GRPCODE, CCC_CNTRY_CODE))
/

ALTER TABLE VMSCMS.CMS_CNTRYGRP_CNTRYCODE ADD (
  CONSTRAINT FK_CNTRYGRP_CNTRYCODE 
 FOREIGN KEY (CCC_CNTRY_GRPCODE) 
 REFERENCES VMSCMS.CMS_CNTRYCODE_RULEGRP (CCR_CNTRY_GRPCODE))
/

