CREATE TABLE VMSCMS.CMS_GIFT_TRANS
(
  CGT_INST_CODE      NUMBER(3),
  CGT_ACCT_NO        VARCHAR2(20 BYTE)          NOT NULL,
  CGT_SR_NO          NUMBER(4),
  CGT_SOURCE_CODE    VARCHAR2(2 BYTE)           NOT NULL,
  CGT_RECORD_TYPE    VARCHAR2(2 BYTE)           NOT NULL,
  CGT_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CGT_GIFT_ORDER     VARCHAR2(14 BYTE)          NOT NULL,
  CGT_REDEMP_CODE    VARCHAR2(3 BYTE)           NOT NULL,
  CGT_STAT_CODE      VARCHAR2(3 BYTE)           NOT NULL,
  CGT_AIRWAY_BILLNO  VARCHAR2(12 BYTE)          NOT NULL,
  CGT_ITEM_ID        VARCHAR2(6 BYTE)           NOT NULL,
  CGT_ITEM_QTY       VARCHAR2(2 BYTE)           NOT NULL,
  CGT_REQ_DATE       DATE                       NOT NULL,
  CGT_POST_DATE      DATE,
  CGT_APPRV_DATE     DATE,
  CGT_CUST_NAME      VARCHAR2(30 BYTE),
  CGT_ADDR_LINE1     VARCHAR2(30 BYTE),
  CGT_ADDR_LINE2     VARCHAR2(30 BYTE),
  CGT_ADDR_LINE3     VARCHAR2(30 BYTE),
  CGT_ADDR_LINE4     VARCHAR2(30 BYTE),
  CGT_CITY_NAME      VARCHAR2(20 BYTE),
  CGT_PIN_CODE       VARCHAR2(6 BYTE),
  CGT_STD_CODE       VARCHAR2(5 BYTE),
  CGT_PHONE_NUMB     VARCHAR2(7 BYTE),
  CGT_REJECT_RSN     VARCHAR2(3 BYTE),
  CGT_FILE_NAME      VARCHAR2(14 BYTE),
  CGT_INS_USER       NUMBER                     NOT NULL,
  CGT_INS_DATE       DATE                       NOT NULL,
  CGT_LUPD_USER      NUMBER                     NOT NULL,
  CGT_LUPD_DATE      DATE                       NOT NULL,
  CGT_DISPATCH_DATE  VARCHAR2(8 BYTE),
  CGT_COURIER_NAME   VARCHAR2(2 BYTE),
  CGT_RECD_DATE      VARCHAR2(8 BYTE),
  CGT_DEL_PERSON     VARCHAR2(30 BYTE),
  CGT_RET_DATE       VARCHAR2(8 BYTE),
  CGT_RET_REASON     VARCHAR2(30 BYTE),
  CGT_MEMO_FIELD     VARCHAR2(30 BYTE),
  CGT_PLAN_ID        VARCHAR2(5 BYTE),
  CGT_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


