CREATE TABLE VMSCMS.CMS_OUTWARD_FUND
(
  COF_SERIAL_NO       VARCHAR2(10 BYTE),
  COF_FROMACCT_NO     VARCHAR2(20 BYTE),
  COF_BANK_NAME       VARCHAR2(30 BYTE),
  COF_BRANCH_NAME     VARCHAR2(30 BYTE),
  COF_BANK_ACCNO      VARCHAR2(20 BYTE),
  COF_BANK_IFCS       VARCHAR2(15 BYTE),
  COF_CEILING_AMOUNT  NUMBER(10),
  COF_INS_USER        NUMBER(5),
  COF_INS_DATE        DATE,
  COF_LUPD_USER       NUMBER(5),
  COF_LUPD_DATE       DATE,
  COF_INST_CODE       NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_OUTWARD_FUND ADD (
  CONSTRAINT PK_FROM_ACCTNO
 PRIMARY KEY
 (COF_FROMACCT_NO))
/

