CREATE TABLE VMSCMS.CMS_PRM_MSGLOGGER
(
  CPM_DELIVERY_CHANNEL  VARCHAR2(3 BYTE),
  CPM_TRANSACTION_CODE  VARCHAR2(3 BYTE),
  CPM_PRM_TYPE          VARCHAR2(4 BYTE),
  CPM_TRANSACTION_MSG   VARCHAR2(4000 BYTE),
  CPM_RRN               VARCHAR2(20 BYTE),
  CPM_BUSINESS_DATE     VARCHAR2(8 BYTE),
  BUSINESS_TIME         VARCHAR2(10 BYTE),
  CPM_INST_DATE         DATE,
  CPM_INST_USER         VARCHAR2(3 BYTE),
  CPM_RESPONSE_CODE     VARCHAR2(7 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


