CREATE TABLE VMSCMS.CMS_CONST_MAST
(
  CCM_CONST_CODE   NUMBER(3),
  CCM_CONST_DESC   VARCHAR2(50 BYTE),
  CCM_CONST_SNAME  VARCHAR2(10 BYTE),
  CCM_CARD_FIID    VARCHAR2(4 BYTE),
  CCM_TERM_FIID    VARCHAR2(4 BYTE),
  CCM_INS_USER     NUMBER(5),
  CCM_INS_DATE     DATE,
  CCM_LUPD_USER    NUMBER(5),
  CCM_LUPD_DATE    DATE,
  CCM_INST_CODE    NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CONST_MAST ADD (
  CONSTRAINT PK_CONST_CODE
 PRIMARY KEY
 (CCM_CONST_CODE, CCM_INST_CODE))
/

