CREATE TABLE VMSCMS.CMS_REPORT_FORFIELDS
(
  CRF_INST_CODE     NUMBER(3),
  CRF_REPORT_ID     NUMBER(4),
  CRF_FIELD_ID      VARCHAR2(20 BYTE),
  CRF_FIELD_NAME    VARCHAR2(50 BYTE),
  CRF_FIELD_COLUMN  VARCHAR2(100 BYTE),
  CRF_FIELD_TABLE   VARCHAR2(50 BYTE),
  CRF_INS_USER      NUMBER(5),
  CRF_INS_DATE      DATE,
  CRF_LUPD_USER     NUMBER(5),
  CRF_LUPD_DATE     DATE,
  CRF_FILE_NAME     VARCHAR2(30 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


