CREATE TABLE VMSCMS.CMS_LIMIT_ERRLOG
(
  CLE_INST_CODE      NUMBER(10),
  CLE_PAN_CODE       VARCHAR2(90 BYTE),
  CLE_OLD_COMB_HASH  VARCHAR2(90 BYTE),
  CLE_NEW_COMB_HASH  VARCHAR2(90 BYTE),
  CLE_ERR_MSG        VARCHAR2(4000 BYTE),
  CLE_INS_USER       NUMBER(5),
  CLE_INS_DATE       DATE
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


