CREATE TABLE VMSCMS.CMS_APPLBIN_HIST
(
  CAH_FILE_NAME         VARCHAR2(35 BYTE)       NOT NULL,
  CAH_ROW_ID            VARCHAR2(8 BYTE)        NOT NULL,
  CAH_OLD_BIN           VARCHAR2(10 BYTE),
  CAH_NEW_BIN           VARCHAR2(10 BYTE),
  CAH_CRD_TYP           VARCHAR2(5 BYTE),
  CAH_FIID              VARCHAR2(4 BYTE),
  CAH_SEG12_BRANCH_NUM  VARCHAR2(4 BYTE),
  CAH_SEG31_NUM         VARCHAR2(19 BYTE),
  CAH_INS_USER          NUMBER(5),
  CAH_INS_DATE          DATE,
  CAH_LUPD_DATE         DATE,
  CAH_INST_CODE         NUMBER(10),
  CAH_LUPD_USER         NUMBER(10)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


