CREATE TABLE VMSCMS.CMS_PRDCATTYPE_LMTPRFL
(
  CPL_INST_CODE   NUMBER(10),
  CPL_PROD_CODE   VARCHAR2(6 BYTE)              NOT NULL,
  CPL_CARD_TYPE   NUMBER(2)                     NOT NULL,
  CPL_LMTPRFL_ID  VARCHAR2(10 BYTE)             NOT NULL,
  CPL_LUPD_DATE   DATE                          NOT NULL,
  CPL_LUPD_USER   NUMBER(10)                    NOT NULL,
  CPL_INS_DATE    DATE                          NOT NULL,
  CPL_INS_USER    NUMBER(10)                    NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PRDCATTYPE_LMTPRFL ADD (
  CONSTRAINT PK_CMS_PRDCATTYPE_LMTPRFL
 PRIMARY KEY
 (CPL_INST_CODE, CPL_PROD_CODE, CPL_CARD_TYPE))
/

ALTER TABLE VMSCMS.CMS_PRDCATTYPE_LMTPRFL ADD (
  CONSTRAINT FK_PRDCATTYPE 
 FOREIGN KEY (CPL_INST_CODE, CPL_PROD_CODE, CPL_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CATTYPE (CPC_INST_CODE,CPC_PROD_CODE,CPC_CARD_TYPE),
  CONSTRAINT FK_CMS_PRDCATTYPE_LMTPRFL 
 FOREIGN KEY (CPL_INST_CODE, CPL_LMTPRFL_ID) 
 REFERENCES VMSCMS.CMS_LMTPRFL_MAST (CLM_INST_CODE,CLM_LMTPRFL_ID))
/

