CREATE TABLE VMSCMS.CMS_TOPUPTRANS_COUNT
(
  CTC_INST_CODE      NUMBER(10),
  CTC_PAN_CODE       VARCHAR2(90 BYTE),
  CTC_TOTAVAIL_DAYS  NUMBER(10),
  CTC_INS_USER       NUMBER(10),
  CTC_INS_DATE       DATE,
  CTC_LUPD_USER      NUMBER(10),
  CTC_LUPD_DATE      DATE,
  CTC_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


