CREATE TABLE VMSCMS.CMS_MERCID_RULE
(
  CMR_INST_CODE    NUMBER(10),
  CMR_MERC_ID      VARCHAR2(11 BYTE),
  CMR_MERCID_DESC  VARCHAR2(100 BYTE)           NOT NULL,
  CMR_MERCID_STUS  VARCHAR2(1 BYTE),
  CMR_LUPD_DATE    DATE,
  CMR_LUPD_USER    NUMBER(10),
  CMR_INS_DATE     DATE,
  CMR_INS_USER     NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MERCID_RULE ADD (
  CONSTRAINT PK_MERC_ID
 PRIMARY KEY
 (CMR_INST_CODE, CMR_MERC_ID))
/

