CREATE TABLE VMSCMS.CMS_TIP_TEMP
(
  CTT_CRD_NUM         VARCHAR2(19 BYTE),
  CTT_AMT             VARCHAR2(19 BYTE),
  CTT_TERM_ID         VARCHAR2(16 BYTE),
  CTT_MER_NAME_LOC    VARCHAR2(40 BYTE),
  CTT_RRN_SEQ_NUM     VARCHAR2(12 BYTE),
  CTT_TRAN_DAT        VARCHAR2(6 BYTE),
  CTT_INS_DATE        DATE,
  CTT_INS_USER        NUMBER(5),
  CTT_DONE_FLAG       VARCHAR2(1 BYTE)          DEFAULT 'N',
  CTT_PROCESS_DATE    DATE,
  CTT_PROCESS_RESULT  VARCHAR2(300 BYTE)        DEFAULT 'Not Processed'
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


