CREATE TABLE VMSCMS.CMS_PRODCATTYPE_WAIV_HIST
(
  CPW_INST_CODE    NUMBER(3)                    NOT NULL,
  CPW_PROD_CODE    VARCHAR2(6 BYTE)             NOT NULL,
  CPW_CARD_TYPE    NUMBER(2)                    NOT NULL,
  CPW_FEE_CODE     NUMBER(3)                    NOT NULL,
  CPW_WAIV_PRCNT   NUMBER(5,2)                  NOT NULL,
  CPW_VALID_FROM   DATE                         NOT NULL,
  CPW_VALID_TO     DATE,
  CPW_WAIV_DESC    VARCHAR2(50 BYTE)            NOT NULL,
  CPW_FLOW_SOURCE  VARCHAR2(3 BYTE)             NOT NULL,
  CPW_INS_USER     NUMBER(5)                    NOT NULL,
  CPW_INS_DATE     DATE                         NOT NULL,
  CPW_LUPD_USER    NUMBER(5)                    NOT NULL,
  CPW_LUPD_DATE    DATE                         NOT NULL,
  CPW_FEE_TYPE     NUMBER(5),
  CPW_WAIV_ID      NUMBER(10)                   NOT NULL,
  CPW_FEE_PLAN     NUMBER(4),
  CPW_ACT_DATE     DATE,
  CPW_ACT_TYPE     VARCHAR2(10 BYTE),
  CPW_CHNG_REASON  VARCHAR2(100 BYTE)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


