CREATE TABLE VMSCMS.CMS_IRIS_PRODCATGMAST
(
  CPM_INST_CODE  NUMBER(3)                      NOT NULL,
  CPM_PROD_CODE  VARCHAR2(6 BYTE)               NOT NULL,
  CPM_CATG_CODE  VARCHAR2(2 BYTE)               NOT NULL,
  CPM_IRIS_FLAG  CHAR(1 BYTE)                   NOT NULL,
  CPM_INS_USER   NUMBER(5)                      NOT NULL,
  CPM_INS_DATE   DATE                           NOT NULL,
  CPM_LUPD_USER  NUMBER(5)                      NOT NULL,
  CPM_LUPD_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_IRIS_PRODCATGMAST ADD (
  CONSTRAINT PK_PRODCATG
 PRIMARY KEY
 (CPM_INST_CODE, CPM_PROD_CODE, CPM_CATG_CODE))
/

