CREATE TABLE VMSCMS.CMS_CARDSTAT_PRIORITY
(
  CCP_PRIORITY   NUMBER(2)                      NOT NULL,
  CCP_INT_STAT   VARCHAR2(1 BYTE)               NOT NULL,
  CCP_PIN_STAT   VARCHAR2(1 BYTE)               NOT NULL,
  CCP_MCC_STAT   VARCHAR2(1 BYTE)               NOT NULL,
  CCP_INS_DATE   DATE,
  CCP_INS_USER   NUMBER,
  CCP_LUPD_DATE  DATE,
  CCP_LUPD_USER  NUMBER
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


