CREATE TABLE VMSCMS.CMS_BRANCH_REGION
(
  CBR_INST_CODE  NUMBER(3),
  CBR_REGION_ID  VARCHAR2(8 BYTE),
  CBR_BRAN_CODE  VARCHAR2(6 BYTE),
  CBR_INS_USER   NUMBER(5),
  CBR_INS_DATE   DATE,
  CBR_LUPD_USER  NUMBER(5),
  CBR_LUPD_DATE  DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BRANCH_REGION ADD (
  CONSTRAINT FK_REGION_ID 
 FOREIGN KEY (CBR_REGION_ID) 
 REFERENCES VMSCMS.CMS_REGION_MAST (CRM_REGION_ID),
  CONSTRAINT FK_BRANCH_CODE 
 FOREIGN KEY (CBR_INST_CODE, CBR_BRAN_CODE) 
 REFERENCES VMSCMS.CMS_BRAN_MAST (CBM_INST_CODE,CBM_BRAN_CODE))
/

