CREATE TABLE VMSCMS.CMS_BULK_ACTIVITY_REPORT
(
  CBA_USER_PIN       NUMBER(5),
  CBA_INS_DATE       DATE,
  CBA_USER_ACTIVITY  VARCHAR2(25 BYTE),
  CBA_FILE_UPLOADED  VARCHAR2(25 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


