CREATE TABLE VMSCMS.CMS_GROUPDETL_MAST
(
  CGM_INST_CODE  NUMBER(5),
  CGM_GRUP_CODE  NUMBER(8),
  CGM_GRUP_NAME  VARCHAR2(40 BYTE)              NOT NULL,
  CGM_GRUP_DESC  VARCHAR2(100 BYTE),
  CGM_LGPW_CHIN  NUMBER(3)                      NOT NULL,
  CGM_TXPW_CHIN  NUMBER(3)                      NOT NULL,
  CGM_GRUP_STUS  NUMBER(1)                      NOT NULL,
  CGM_VALD_IPAD  NUMBER(1)                      NOT NULL,
  CGM_INS_USER   NUMBER(8)                      NOT NULL,
  CGM_INS_DATE   DATE                           NOT NULL,
  CGM_LUPD_USER  NUMBER(8),
  CGM_LUPD_DATE  DATE,
  CGM_AUTH_BIN   VARCHAR2(2000 BYTE),
  CGM_OWNER_ID   NUMBER(3)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GROUPDETL_MAST ADD (
  CONSTRAINT PK_CGM_INST_GRUP
 PRIMARY KEY
 (CGM_INST_CODE, CGM_GRUP_CODE),
  CONSTRAINT UK_CGM_GRUP_NAME
 UNIQUE (CGM_INST_CODE, CGM_GRUP_NAME))
/

ALTER TABLE VMSCMS.CMS_GROUPDETL_MAST ADD (
  CONSTRAINT FK_CGM_INST_CUM_USID 
 FOREIGN KEY (CGM_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_CGM_INST_CIM_INST 
 FOREIGN KEY (CGM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_INST_OWN_ID 
 FOREIGN KEY (CGM_INST_CODE, CGM_OWNER_ID) 
 REFERENCES VMSCMS.CMS_OWNER_MAST (COM_INST_CODE,COM_OWNER_ID))
/

