CREATE TABLE VMSCMS.CMS_GROUP_ACCTDELINK_TEMP
(
  CGD_INST_CODE     NUMBER(3),
  CGD_CARD_NO       VARCHAR2(90 BYTE),
  CGD_OLD_ACCT_NO   VARCHAR2(20 BYTE),
  CGD_FILE_NAME     VARCHAR2(30 BYTE),
  CGD_REMARKS       VARCHAR2(100 BYTE),
  CGD_PROCESS_FLAG  VARCHAR2(1 BYTE),
  CGD_PROCESS_MSG   VARCHAR2(300 BYTE),
  CGD_INS_USER      NUMBER(5),
  CGD_INS_DATE      DATE,
  CGD_MBR_NUMB      VARCHAR2(10 BYTE),
  CGD_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


