CREATE TABLE VMSCMS.CMS_GROUP_CHNGESTAT
(
  CGC_CARD_NO        VARCHAR2(90 BYTE),
  CGC_PIN_CHNGESTAT  VARCHAR2(1 BYTE)           DEFAULT 'N',
  CGC_NEW_STAT       CHAR(1 BYTE),
  CGC_REMARK         VARCHAR2(100 BYTE),
  CGC_RESULT         VARCHAR2(500 BYTE)         DEFAULT 'NOT PROCESSED',
  CGC_MBR_NUMB       VARCHAR2(3 BYTE)           DEFAULT '000',
  CGC_INS_DATE       DATE,
  CGC_FILE_NAME      VARCHAR2(30 BYTE),
  CGC_LUPD_DATE      DATE,
  CGC_INST_CODE      NUMBER(10),
  CGC_LUPD_USER      NUMBER(10),
  CGC_INS_USER       NUMBER(10),
  CGC_PROCESS_FLAG   VARCHAR2(1 BYTE)           DEFAULT 'N',
  CGC_PROCESS_MSG    VARCHAR2(100 BYTE),
  CGC_CARD_NO_ENCR   RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


