CREATE TABLE VMSCMS.CMS_ROLE_PROG
(
  CRP_INST_CODE  NUMBER(5),
  CRP_PROG_CODE  NUMBER(5),
  CRP_PROG_NAME  VARCHAR2(50 BYTE),
  CRP_ROLE_CODE  NUMBER(5),
  CRP_ROLE_NAME  VARCHAR2(50 BYTE),
  CRP_INS_USER   NUMBER(5)                      NOT NULL,
  CRP_INS_DATE   DATE                           NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ROLE_PROG ADD (
  CONSTRAINT PK_CRP_INST_PROG_ROLE
 PRIMARY KEY
 (CRP_INST_CODE, CRP_PROG_CODE, CRP_ROLE_CODE))
/

ALTER TABLE VMSCMS.CMS_ROLE_PROG ADD (
  CONSTRAINT FK_CRP_INST_ROLE 
 FOREIGN KEY (CRP_INST_CODE, CRP_ROLE_CODE) 
 REFERENCES VMSCMS.CMS_ROLE_MAST (CRM_INST_CODE,CRM_ROLE_CODE),
  CONSTRAINT FK_CRP_INST_PROG 
 FOREIGN KEY (CRP_INST_CODE, CRP_PROG_CODE) 
 REFERENCES VMSCMS.CMS_PROGDETL_MAST (CPM_INST_CODE,CPM_PROG_CODE),
  CONSTRAINT FK_CRP_INST_CODE 
 FOREIGN KEY (CRP_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_CRP_INS_USER 
 FOREIGN KEY (CRP_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE))
/

