CREATE TABLE VMSCMS.CMS_MANUAL_ADJUSTMENT
(
  CMA_INST_CODE         NUMBER(3),
  CMA_ADJUSTMENT_DATE   DATE,
  CMA_PAN_CODE          VARCHAR2(90 BYTE),
  CMA_PAN_CODE_ENCR     RAW(100),
  CMA_ADJUSTMENT_TYPE   NUMBER(3),
  CMA_DEBIT_AMOUNT      NUMBER(20,3)            DEFAULT 0,
  CMA_CREDIT_AMOUNT     NUMBER(20,3)            DEFAULT 0,
  CMA_TRAN_CODE         VARCHAR2(2 BYTE),
  CMA_TRAN_MODE         VARCHAR2(1 BYTE),
  CMA_DELIVERY_CHANNEL  VARCHAR2(2 BYTE),
  CMA_INS_USER          NUMBER(5),
  CMA_INS_DATE          DATE,
  CMA_LUPD_USER         NUMBER(5),
  CMA_LUPD_DATE         DATE,
  CMA_ACCT_NO           VARCHAR2(20 BYTE),
  CMA_ACCT_TYPE         NUMBER(3)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MANUAL_ADJUSTMENT ADD (
  CONSTRAINT FK_MANUALADJ_SPPRT_REASONS 
 FOREIGN KEY (CMA_INST_CODE, CMA_ADJUSTMENT_TYPE) 
 REFERENCES VMSCMS.CMS_SPPRT_REASONS (CSR_INST_CODE,CSR_SPPRT_RSNCODE),
  CONSTRAINT FK_MANUALADJ_INSTMAST 
 FOREIGN KEY (CMA_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

