CREATE TABLE VMSCMS.CMS_TERM_ID_OTH
(
  CTI_TERM_ID    VARCHAR2(20 BYTE),
  CTI_LUPD_DATE  DATE,
  CTI_INST_CODE  NUMBER(10),
  CTI_LUPD_USER  NUMBER(10),
  CTI_INS_DATE   DATE,
  CTI_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


