CREATE TABLE VMSCMS.CMS_CARD_EXCPWAIV_HIST
(
  CCE_INST_CODE      NUMBER(3)                  NOT NULL,
  CCE_FEE_CODE       NUMBER(3)                  NOT NULL,
  CCE_WAIV_PRCNT     NUMBER(5,2)                NOT NULL,
  CCE_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CCE_MBR_NUMB       VARCHAR2(3 BYTE)           NOT NULL,
  CCE_VALID_FROM     DATE                       NOT NULL,
  CCE_VALID_TO       DATE,
  CCE_WAIV_DESC      VARCHAR2(50 BYTE)          NOT NULL,
  CCE_FLOW_SOURCE    VARCHAR2(3 BYTE)           NOT NULL,
  CCE_INS_USER       NUMBER(5)                  NOT NULL,
  CCE_INS_DATE       DATE                       NOT NULL,
  CCE_LUPD_USER      NUMBER(5)                  NOT NULL,
  CCE_LUPD_DATE      DATE                       NOT NULL,
  CCE_CARD_WAIV_ID   NUMBER(10),
  CCE_PAN_CODE_ENCR  RAW(100),
  CCE_FEE_PLAN       NUMBER(4),
  CCE_ACT_DATE       DATE,
  CCE_ACT_TYPE       VARCHAR2(10 BYTE),
  CCE_CHNG_REASON    VARCHAR2(100 BYTE)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


