CREATE TABLE VMSCMS.CMS_SMS_RESPONSE
(
  CSR_INST_CODE             NUMBER(3),
  CSR_PAN_CODE              VARCHAR2(90 BYTE),
  CSR_PAN_CODE_ENCR         RAW(100),
  CSR_MOBILE_NUMBER         VARCHAR2(15 BYTE),
  CSR_BANK_ID               VARCHAR2(6 BYTE),
  CSR_TRANSACTION_ID        VARCHAR2(15 BYTE),
  CSR_TRAN_DATE_TIME        DATE,
  CSR_RESPONSE_CODE         VARCHAR2(3 BYTE),
  CSR_RESPONSE_DESCRIPTION  VARCHAR2(50 BYTE),
  CSR_INS_USER              NUMBER(5),
  CSR_INS_DATE              DATE,
  CSR_LUPD_USER             NUMBER(5),
  CSR_LUPD_DATE             DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


