CREATE TABLE VMSCMS.CMS_FILE_DEFIN_MAST
(
  CFD_FILE_ID               NUMBER(20),
  CFD_INST_CODE             NUMBER(3),
  CFD_INS_USER              NUMBER(5),
  CFD_LUPD_USER             NUMBER(5),
  CFD_INS_DATE              DATE,
  CFD_LUPD_DATE             DATE,
  CFD_FILE_NAME             VARCHAR2(50 BYTE),
  CFD_SHORT_NAME            VARCHAR2(30 BYTE),
  CFD_NAME_CONV_FLAG        VARCHAR2(1 BYTE),
  CFD_FILEMAX_LENGTH        NUMBER(10),
  CFD_FILE_BEGIN_FLAG       VARCHAR2(1 BYTE),
  CFD_FILE_BEGIN_NAME       VARCHAR2(10 BYTE),
  CFD_NAME_CONV             VARCHAR2(20 BYTE),
  CFD_NAME_CONSTANT         VARCHAR2(10 BYTE),
  CFD_FILE_TYPE             VARCHAR2(20 BYTE),
  CFD_HEADER_FLAG           VARCHAR2(1 BYTE),
  CFD_FOOTER_FLAG           VARCHAR2(1 BYTE),
  CFD_DULICATE_CHK_FLAG     VARCHAR2(1 BYTE),
  CFD_HEADER_POSN           NUMBER(3),
  CFD_HEADER_DATA_FRM_POSN  NUMBER(3),
  CFD_HEADER_DATA_TO_POSN   NUMBER(3),
  CFD_HEADER_DATA_LINES     NUMBER(2),
  CFD_DATA_DATA_LINES       NUMBER(2),
  CFD_FOOTER_DATA_LINES     NUMBER(2),
  CFD_HEADER_BEGIN_FLAG     VARCHAR2(1 BYTE),
  CFD_FOOTER_BEGIN_FLAG     VARCHAR2(1 BYTE),
  CFD_DATA_BEGIN_FLAG       VARCHAR2(1 BYTE),
  CFD_HEADER_CONSTANT       VARCHAR2(5 BYTE),
  CFD_FOOTER_CONSTANT       VARCHAR2(5 BYTE),
  CFD_DATA_CONSTANT         VARCHAR2(5 BYTE),
  CFD_DELIMITER             VARCHAR2(1 BYTE),
  CFD_BLK_LENGTH            NUMBER(10),
  CFD_RECORD_LENGTH         NUMBER(10),
  CFD_RECORD_TYPE           NUMBER(5),
  CFD_FOOTER_TYPE           VARCHAR2(1 BYTE),
  CFD_CTRL_TAG_FOOTER       NUMBER(2),
  CFD_FILE_PATH             VARCHAR2(50 BYTE),
  CFD_MENU_CAPS             VARCHAR2(20 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FILE_DEFIN_MAST ADD (
  CONSTRAINT PK_CFD_FILE_ID
 PRIMARY KEY
 (CFD_FILE_ID))
/

ALTER TABLE VMSCMS.CMS_FILE_DEFIN_MAST ADD (
  CONSTRAINT FK_CFD_INST_CODE 
 FOREIGN KEY (CFD_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

