CREATE TABLE VMSCMS.CMS_DECLINETXN_RESPONSE
(
  CDR_INST_CODE         NUMBER(3),
  CDR_DELIVERY_CHANNEL  VARCHAR2(2 BYTE)        NOT NULL,
  CDR_TRAN_CODE         VARCHAR2(2 BYTE)        NOT NULL,
  CDR_MSG_TYPE          VARCHAR2(10 BYTE),
  CDR_RESPCDE           VARCHAR2(5 BYTE)        NOT NULL,
  CDR_INS_DATE          DATE,
  CDR_INS_USER          NUMBER(5),
  CDR_LUPD_UDER         NUMBER(5),
  CDR_LUPD_DATE         DATE,
  CDR_REVERSAL_CODE     NUMBER(3)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_DECLINETXN_RESPONSE ADD (
  CONSTRAINT PK_DECLINE_RESP
 PRIMARY KEY
 (CDR_INST_CODE, CDR_DELIVERY_CHANNEL, CDR_TRAN_CODE, CDR_RESPCDE, CDR_MSG_TYPE, CDR_REVERSAL_CODE))
/

ALTER TABLE VMSCMS.CMS_DECLINETXN_RESPONSE ADD (
  CONSTRAINT FK_TXN_MAST 
 FOREIGN KEY (CDR_INST_CODE, CDR_DELIVERY_CHANNEL, CDR_TRAN_CODE) 
 REFERENCES VMSCMS.CMS_TRANSACTION_MAST (CTM_INST_CODE,CTM_DELIVERY_CHANNEL,CTM_TRAN_CODE))
/

