CREATE TABLE VMSCMS.CMS_GROUP_CARDCLOSE_TEMP
(
  CGC_INST_CODE      NUMBER(3),
  CGC_PAN_CODE       VARCHAR2(90 BYTE),
  CGC_PIN_CLOSE      VARCHAR2(1 BYTE),
  CGC_FILE_NAME      VARCHAR2(30 BYTE),
  CGC_REMARK         VARCHAR2(100 BYTE),
  CGC_RESULT         VARCHAR2(500 BYTE),
  CGC_INS_DATE       DATE,
  CGC_MBR_NUMB       VARCHAR2(3 BYTE),
  CGC_INS_USER       NUMBER(5),
  CGC_PROCESS_FLAG   VARCHAR2(1 BYTE),
  CGC_PROCESS_MSG    VARCHAR2(350 BYTE),
  CGC_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


