ALTER TABLE VMSCMS.CMS_PROD_MAST ADD CPM_RULESET_ID NUMBER(9);
ALTER TABLE VMSCMS.CMS_PROD_MAST ADD CONSTRAINT FK_PRODMAST_RULESETMAST FOREIGN KEY
 (CPM_RULESET_ID) REFERENCES VMSCMS.VMS_RULESET_MAST (VRS_RULESET_ID);