CREATE TABLE VMSCMS.CMS_KEY_ROTATE_TABLE
(
  CKR_INST_CODE    NUMBER(3),
  CKR_SNO          NUMBER(5),
  CKR_TABLE_NAME   VARCHAR2(100 BYTE),
  CKR_ENCR_COLUMN  VARCHAR2(100 BYTE),
  CKR_HASH_COLUMN  VARCHAR2(100 BYTE),
  CKR_REMARKS      VARCHAR2(500 BYTE),
  CKR_ROTATE_FLAG  CHAR(1 BYTE)                 NOT NULL,
  CKR_INS_USER     NUMBER(5),
  CKR_INS_DATE     DATE,
  CKR_LUPD_USER    NUMBER(5),
  CKR_LUPD_DATE    DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_KEY_ROTATE_TABLE ADD (
  CONSTRAINT PK_KEY_ROTATE_TABLE
 PRIMARY KEY
 (CKR_INST_CODE, CKR_SNO, CKR_TABLE_NAME))
/

