CREATE TABLE VMSCMS.CMS_BRANCH_TYPE
(
  CBT_CATG_CODE       VARCHAR2(5 BYTE),
  CBT_TYPE_CODE       VARCHAR2(5 BYTE),
  CBT_TYPE_DESC       VARCHAR2(50 BYTE),
  CBT_REPORTING_BRAN  VARCHAR2(5 BYTE),
  CBT_INS_USER        NUMBER(5),
  CBT_INS_DATE        DATE,
  CBT_LUPD_USER       NUMBER(5),
  CBT_LUPD_DATE       DATE,
  CBT_INST_CODE       NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BRANCH_TYPE ADD (
  CONSTRAINT PK_BRANCHTYPE_MAST
 PRIMARY KEY
 (CBT_INST_CODE, CBT_TYPE_CODE))
/

ALTER TABLE VMSCMS.CMS_BRANCH_TYPE ADD (
  CONSTRAINT FK_BRANCHTYPE_MAST 
 FOREIGN KEY (CBT_INST_CODE, CBT_CATG_CODE) 
 REFERENCES VMSCMS.CMS_BRANCH_CATG (CBC_INST_CODE,CBC_CATG_CODE))
/

