CREATE TABLE VMSCMS.CMS_FUNDTRANSFER_MAST
(
  CFM_BANK_NAME             VARCHAR2(100 BYTE),
  CFM_ACCT_NO               VARCHAR2(20 BYTE),
  CFM_PAN_CODE              VARCHAR2(90 BYTE),
  CFM_PROD_CODE             VARCHAR2(6 BYTE),
  CFM_PROD_DESC             VARCHAR2(35 BYTE),
  CFM_PROD_CATG             VARCHAR2(2 BYTE),
  CFM_FUNDETRANSFER_AMOUNT  NUMBER(15,6),
  CFM_LUPD_DATE             DATE,
  CFM_INST_CODE             NUMBER(10),
  CFM_LUPD_USER             NUMBER(10),
  CFM_INS_DATE              DATE,
  CFM_INS_USER              NUMBER(10),
  CFM_PAN_CODE_ENCR         RAW(100)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


