CREATE TABLE VMSCMS.CMS_USER_GROUPMAST
(
  CUG_INST_CODE   NUMBER(3)                     NOT NULL,
  CUG_GROUP_CODE  NUMBER(3)                     NOT NULL,
  CUG_USER_CODE   VARCHAR2(40 BYTE)             NOT NULL,
  CUG_USER_STAT   CHAR(1 BYTE)                  NOT NULL,
  CUG_INS_USER    NUMBER(5)                     NOT NULL,
  CUG_INS_DATE    DATE                          NOT NULL,
  CUG_LUPD_USER   NUMBER(5)                     NOT NULL,
  CUG_LUPD_DATE   DATE                          NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_USER_GROUPMAST ADD (
  CONSTRAINT PK_USER_GROUPMAST
 PRIMARY KEY
 (CUG_INST_CODE, CUG_GROUP_CODE, CUG_USER_CODE))
/

ALTER TABLE VMSCMS.CMS_USER_GROUPMAST ADD (
  CONSTRAINT FK_USERGROUPMAST_USERGROUP 
 FOREIGN KEY (CUG_INST_CODE, CUG_GROUP_CODE) 
 REFERENCES VMSCMS.CMS_USER_GROUP (CUG_INST_CODE,CUG_GROUP_CODE),
  CONSTRAINT FK_USERGROUPMAST_USERMAST 
 FOREIGN KEY (CUG_INST_CODE, CUG_USER_CODE) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_INST_CODE,CUM_USER_CODE))
/

