CREATE TABLE VMSCMS.CMS_GROUPIP_MAST
(
  CGM_INST_CODE  NUMBER(5),
  CGM_GRUP_CODE  NUMBER(8),
  CGM_IP_ADDR    VARCHAR2(15 BYTE),
  CGM_IP_STUS    NUMBER(1)                      NOT NULL,
  CGM_INS_USER   NUMBER(8)                      NOT NULL,
  CGM_INS_DATE   DATE                           NOT NULL,
  CGM_LUPD_USER  NUMBER(8),
  CGM_LUPD_DATE  DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GROUPIP_MAST ADD (
  CONSTRAINT FK_CGM_INID_CIM_INST 
 FOREIGN KEY (CGM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_CGM_INST_CUM_USERCODE 
 FOREIGN KEY (CGM_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE))
/

