CREATE TABLE VMSCMS.CMS_HTLST_REISU
(
  CHR_INST_CODE      NUMBER(3)                  NOT NULL,
  CHR_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CHR_MBR_NUMB       VARCHAR2(3 BYTE)           NOT NULL,
  CHR_NEW_PAN        VARCHAR2(90 BYTE)          NOT NULL,
  CHR_NEW_MBR        VARCHAR2(3 BYTE)           NOT NULL,
  CHR_REISU_CAUSE    CHAR(1 BYTE)               NOT NULL,
  CHR_INS_USER       NUMBER(5)                  NOT NULL,
  CHR_INS_DATE       DATE                       NOT NULL,
  CHR_LUPD_USER      NUMBER(5)                  NOT NULL,
  CHR_LUPD_DATE      DATE                       NOT NULL,
  CHR_NEW_PAN_ENCR   RAW(100),
  CHR_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_HTLST_REISU ADD (
  CONSTRAINT PK_HTLST_REISU
 PRIMARY KEY
 (CHR_INST_CODE, CHR_PAN_CODE, CHR_MBR_NUMB, CHR_NEW_PAN))
/

