CREATE TABLE VMSCMS.CMS_GROUPDETL_AUDT
(
  CGA_INST_CODE  NUMBER(5),
  CGA_GRUP_CODE  NUMBER(8),
  CGA_GRUP_NAME  VARCHAR2(40 BYTE)              NOT NULL,
  CGA_GRUP_DESC  VARCHAR2(100 BYTE),
  CGA_LGPW_CHIN  NUMBER(3)                      NOT NULL,
  CGA_TXPW_CHIN  NUMBER(3)                      NOT NULL,
  CGA_GRUP_STUS  NUMBER(1)                      NOT NULL,
  CGA_VALD_IPAD  NUMBER(1)                      NOT NULL,
  CGA_INS_USER   NUMBER(8)                      NOT NULL,
  CGA_INS_DATE   DATE                           NOT NULL,
  CGA_OWNER_ID   NUMBER(3),
  CGA_AUTH_BIN   VARCHAR2(2000 BYTE),
  CGA_ROLE_ID    NUMBER(3),
  CGA_AUDT_FLAG  VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


