CREATE TABLE VMSCMS.CMS_BATCHUPLOAD_CTRL
(
  CBC_INST_CODE    NUMBER(3)                    NOT NULL,
  CBC_BRAN_CODE    VARCHAR2(6 BYTE),
  CBC_FILE_NAME    VARCHAR2(35 BYTE)            NOT NULL,
  CBC_FILE_HEADER  VARCHAR2(50 BYTE),
  CBC_UPLD_DATE    DATE,
  CBC_TOT_ROWS     NUMBER(8),
  CBC_CORR_ROWS    NUMBER(8),
  CBC_ERR_ROWS     NUMBER(8),
  CBC_UPLD_STAT    CHAR(1 BYTE),
  CBC_INS_USER     NUMBER(5)                    NOT NULL,
  CBC_INS_DATE     DATE                         NOT NULL,
  CBC_LUPD_USER    NUMBER(5),
  CBC_LUPD_DATE    DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BATCHUPLOAD_CTRL ADD (
  CONSTRAINT PK_UPLOAD_CTRL_1
 PRIMARY KEY
 (CBC_INST_CODE, CBC_FILE_NAME))
/

