CREATE TABLE VMSCMS.CMS_TEMP_ROWID
(
  CTR_ROW_ID     VARCHAR2(8 BYTE),
  CTR_LUPD_DATE  DATE,
  CTR_INST_CODE  NUMBER(10),
  CTR_LUPD_USER  NUMBER(10),
  CTR_INS_DATE   DATE,
  CTR_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


