CREATE TABLE VMSCMS.CMS_LIMT_MAST
(
  CLM_INST_CODE         NUMBER(3),
  CLM_INST_BIN          NUMBER(10),
  CLM_ATM_UPLIMT        VARCHAR2(12 BYTE),
  CLM_ATM_FLLIMT        VARCHAR2(12 BYTE),
  CLM_ATM_B24PFX_LIMT   VARCHAR2(12 BYTE),
  CLM_POS_UPLIMT        VARCHAR2(12 BYTE),
  CLM_POS_FLLIMT        VARCHAR2(12 BYTE),
  CLM_POS_B24PFX_LIMT   VARCHAR2(12 BYTE),
  CLM_ECOM_UPLIMT       VARCHAR2(12 BYTE),
  CLM_ECOM_FLLIMT       VARCHAR2(12 BYTE),
  CLM_ECOM_B24PFX_LIMT  VARCHAR2(12 BYTE),
  CLM_INST_USER         NUMBER(10),
  CLM_INST_DATE         DATE                    DEFAULT SYSDATE,
  CLM_UPLD_USER         NUMBER(10),
  CLM_UPLD_DATE         DATE                    DEFAULT SYSDATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


