CREATE TABLE VMSCMS.CMS_SCORECARD_CONFIG
(
  CSC_INST_CODE         NUMBER(3)               NOT NULL,
  CSC_SCORECARD_ID      NUMBER                  NOT NULL,
  CSC_SCORECARD_NAME    VARCHAR2(15 BYTE)       NOT NULL,
  CSC_IDOLOGY_USERID    VARCHAR2(15 BYTE)       NOT NULL,
  CSC_IDOLOGY_PASSWORD  VARCHAR2(15 BYTE)       NOT NULL,
  CSC_INS_USER          NUMBER(5)               NOT NULL,
  CSC_INS_DATE          DATE                    NOT NULL,
  CSC_LUPD_USER         NUMBER(5),
  CSC_LUPD_DATE         DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SCORECARD_CONFIG ADD (
  CONSTRAINT PK_SCORECARD_CONFIG
 PRIMARY KEY
 (CSC_INST_CODE, CSC_SCORECARD_ID))
/

