ALTER TABLE vmscms.CMS_TXN_ISO_DETL ADD (
CTI_DE61_CAVVRESULTCODE VARCHAR2(20),
CTI_DE61_CHIPTRANSIND VARCHAR2(20),
CTI_DE61_MAILPHONEECOMPAYIND VARCHAR2(20), 
CTI_DE61_ACCTDATACOMPINFO VARCHAR2(50), 
CTI_DE61_UNICHAUTHFIELD VARCHAR2(50), 
CTI_DE61_SECSERVADDLDATA VARCHAR2(200), 
CTI_DE61_FRAUDSCORINGDATA VARCHAR2(50), 
CTI_DE61_ADDRVERIFSERVREQ NUMBER(20),
CTI_DE61_MCMAPSERVICEACCTNO VARCHAR2(50),
CTI_DE61_MCCUSTIDENTIFIER VARCHAR2(100), 
CTI_DE61_CARDHOLDERNAME VARCHAR2(50));

ALTER TABLE vmscms.CMS_TXN_ISO_DETL MODIFY (
CTI_DE61_STIPSWITCH_REASONCDE VARCHAR2(20));

UPDATE vmscms.CMS_TXN_ISO_DETL SET CTI_DE61_ADDRVERIFSERVREQ='';
ALTER TABLE vmscms.CMS_TXN_ISO_DETL MODIFY CTI_DE61_ADDRVERIFSERVREQ VARCHAR2(20);