CREATE TABLE VMSCMS.CMS_TRANSMODE_DTL
(
  CTD_INST_CODE         NUMBER(3),
  CTD_TRANSACTION_MODE  VARCHAR2(2 BYTE),
  CTD_TRANSMODE_DESC    VARCHAR2(50 BYTE),
  CTD_INS_USER          NUMBER(5),
  CTD_INS_DATE          DATE,
  CTD_LUPD_USER         NUMBER(5),
  CTD_LUPD_DATE         DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


