CREATE TABLE VMSCMS.CMS_OWNER_MAST
(
  COM_INST_CODE   NUMBER(5)                     NOT NULL,
  COM_OWNER_ID    NUMBER(3)                     NOT NULL,
  COM_OWNER_DESC  VARCHAR2(100 BYTE),
  COM_INS_USER    NUMBER(8)                     NOT NULL,
  COM_INS_DATE    DATE                          NOT NULL,
  COM_LUPD_USER   NUMBER(8),
  COM_LUPD_DATE   DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_OWNER_MAST ADD (
  CONSTRAINT PK_COM_INST_OWNER
 PRIMARY KEY
 (COM_INST_CODE, COM_OWNER_ID),
  CONSTRAINT UK_COM_OWNER_DESC
 UNIQUE (COM_OWNER_DESC))
/

