CREATE TABLE VMSCMS.CMS_MSGCENTER_QUESTIONS
(
  CMQ_INST_CODE       NUMBER(3)                 NOT NULL,
  CMQ_MSGCENTER_CODE  VARCHAR2(20 BYTE),
  CMQ_PAN_CODE        VARCHAR2(90 BYTE),
  CMQ_SUBJECT_DESC    VARCHAR2(30 BYTE),
  CMQ_QUESTION        VARCHAR2(1250 BYTE),
  CMQ_INS_DATE        DATE                      NOT NULL,
  CMQ_LUPD_DATE       DATE                      NOT NULL,
  CMQ_IP_ADDRESS      VARCHAR2(20 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MSGCENTER_QUESTIONS ADD (
  CONSTRAINT PK_MSGCENTER_QUESTIONS
 PRIMARY KEY
 (CMQ_INST_CODE, CMQ_MSGCENTER_CODE))
/

