CREATE TABLE VMSCMS.CMS_WFEE_ERLOG
(
  CWE_INST_CODE  NUMBER(3),
  CWE_PAN_CODE   VARCHAR2(90 BYTE),
  CWE_ATCH_TYPE  VARCHAR2(2 BYTE),
  CWE_ERR_MSG    VARCHAR2(500 BYTE),
  CWE_INS_USER   VARCHAR2(2 BYTE),
  CWE_INS_DATE   DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


