CREATE TABLE VMSCMS.CMS_FLOAT_TOTAL_REPORT
(
  CFTR_INS_DATE    DATE,
  CFTR_CURR_CODE   VARCHAR2(3 BYTE),
  CFTR_PARAM_KEY   VARCHAR2(300 BYTE),
  CFTR_CREDIT_AMT  NUMBER,
  CFTR_DEBIT_AMT   NUMBER,
  CFT_LUPD_DATE    DATE,
  CFT_INST_CODE    NUMBER(10),
  CFT_LUPD_USER    NUMBER(10),
  CFT_INS_USER     NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


