CREATE TABLE VMSCMS.CMS_LOGIN_AUDT
(
  CLA_INST_CODE  NUMBER(5),
  CLA_GRUP_CODE  NUMBER(8),
  CLA_LGIN_MESG  VARCHAR2(200 BYTE),
  CLA_NUMB_ATMP  NUMBER(5),
  CLA_INS_USER   NUMBER(8)                      NOT NULL,
  CLA_INS_DATE   DATE                           NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_LOGIN_AUDT ADD (
  CONSTRAINT FK_CLA_LGIN_USID 
 FOREIGN KEY (CLA_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_CLA_LGIN_GRUP 
 FOREIGN KEY (CLA_INST_CODE, CLA_GRUP_CODE) 
 REFERENCES VMSCMS.CMS_GROUPDETL_MAST (CGM_INST_CODE,CGM_GRUP_CODE),
  CONSTRAINT FK_CLA_INST_CODE 
 FOREIGN KEY (CLA_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

