CREATE TABLE VMSCMS.CMS_EMBOSS_DETAILS
(
  CED_INST_CODE     NUMBER(3),
  CED_CARD_TYPE     VARCHAR2(2 BYTE),
  CED_INST_BIN      VARCHAR2(6 BYTE),
  CED_BRANCH_CODE   VARCHAR2(4 BYTE),
  CED_BRANCH_FIID   VARCHAR2(4 BYTE),
  CED_EMB_LINE1     VARCHAR2(50 BYTE),
  CED_EMB_LINE2     VARCHAR2(50 BYTE),
  CED_EMB_LINE3     VARCHAR2(50 BYTE),
  CED_EMB_LINE4     VARCHAR2(50 BYTE),
  CED_IND_LINE      VARCHAR2(50 BYTE),
  CED_TRACK1_DATA   VARCHAR2(80 BYTE),
  CED_TRACK2_DATA   VARCHAR2(80 BYTE),
  CED_TRACK3_DATA   VARCHAR2(80 BYTE),
  CED_SERIAL_NO     NUMBER(2),
  CED_PROFILE_CODE  VARCHAR2(5 BYTE),
  CED_LUPD_DATE     DATE,
  CED_LUPD_USER     NUMBER(10),
  CED_INS_DATE      DATE,
  CED_INS_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


