CREATE TABLE VMSCMS.CMS_PROD_ADHOCFEE_HIST
(
  CPA_INST_CODE      NUMBER(3)                  NOT NULL,
  CPA_PROD_CODE      VARCHAR2(6 BYTE)           NOT NULL,
  CPA_SPPRT_RSNCODE  VARCHAR2(50 BYTE)          NOT NULL,
  CPA_FEE_AMT        NUMBER(15,2)               NOT NULL,
  CPA_INS_USER       NUMBER(5)                  NOT NULL,
  CPA_INS_DATE       DATE                       NOT NULL,
  CPA_LUPD_USER      NUMBER(5),
  CPA_LUPD_DATE      DATE
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


