CREATE TABLE VMSCMS.CMS_STOCK_MAST
(
  CSM_INST_CODE       NUMBER(3)                 NOT NULL,
  CSM_BRAN_FIID       VARCHAR2(20 BYTE)         NOT NULL,
  CSM_INST_BIN        NUMBER(10)                NOT NULL,
  CSM_CARD_THRESHOLD  NUMBER(9)                 NOT NULL,
  CSM_CARD_GENERATED  NUMBER(5),
  CSM_INS_USER        NUMBER(5)                 NOT NULL,
  CSM_INS_DATE        DATE,
  CSM_LUPD_USER       NUMBER(5),
  CSM_LUPD_DATE       DATE,
  CSM_TOTAL_STOCK     NUMBER(5),
  CSM_PROD_CODE       VARCHAR2(6 BYTE)          NOT NULL,
  CSM_CARD_TYPE       NUMBER(2)                 NOT NULL,
  CSM_CUST_CATG       NUMBER(5)                 NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_STOCK_MAST ADD (
  CONSTRAINT PK_STOCK_MAST
 PRIMARY KEY
 (CSM_BRAN_FIID, CSM_PROD_CODE, CSM_CARD_TYPE, CSM_CUST_CATG))
/

ALTER TABLE VMSCMS.CMS_STOCK_MAST ADD (
  CONSTRAINT FK_STOCKMAST_PRODCATTYPE 
 FOREIGN KEY (CSM_INST_CODE, CSM_PROD_CODE, CSM_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CATTYPE (CPC_INST_CODE,CPC_PROD_CODE,CPC_CARD_TYPE),
  CONSTRAINT FK_STOCKMAST_CUSTCATG 
 FOREIGN KEY (CSM_INST_CODE, CSM_CUST_CATG) 
 REFERENCES VMSCMS.CMS_CUST_CATG (CCC_INST_CODE,CCC_CATG_CODE))
/

