CREATE TABLE VMSCMS.CMS_FEEPLIMITPRFL_DTL
(
  CFD_INST_CODE      NUMBER(3)                  NOT NULL,
  CFD_ACCT_NO        VARCHAR2(20 BYTE),
  CFD_PROXY_NO       VARCHAR2(19 BYTE),
  CFD_ATTCH_TYPE     CHAR(1 BYTE),
  CFD_FEELIMIT_CODE  VARCHAR2(10 BYTE),
  CFD_RESP_MSG       VARCHAR2(200 BYTE),
  CFD_FILE_NAME      VARCHAR2(50 BYTE)          NOT NULL,
  CFD_ROW_ID         NUMBER(10)                 NOT NULL,
  CFD_INS_USER       NUMBER(10)                 NOT NULL,
  CFD_INS_DATE       DATE                       NOT NULL,
  CONSTRAINT PK_FEEPLAN_LIMITPRFL
 PRIMARY KEY
 (CFD_INST_CODE,CFD_FILE_NAME, CFD_ROW_ID)
)
TABLESPACE CMS_BIG_TXN
/