CREATE TABLE VMSCMS.CMS_SKIPDUP_ACCTS
(
  CSA_INST_CODE  NUMBER(3),
  CSA_ACCT_NO    VARCHAR2(20 BYTE),
  CSA_INS_USER   NUMBER(5),
  CSA_INS_DATE   DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SKIPDUP_ACCTS ADD (
  CONSTRAINT PK_SKIPDUP_ACCTS
 PRIMARY KEY
 (CSA_INST_CODE, CSA_ACCT_NO))
/

