CREATE TABLE VMSCMS.CMS_GROUP_REISSUE
(
  CGR_PAN_CODE          VARCHAR2(90 BYTE),
  CGR_PIN_REISSUE       VARCHAR2(1 BYTE)        DEFAULT 'N',
  CGR_NEW_PRODUCT       VARCHAR2(6 BYTE),
  CGR_NEW_PRODUCTCAT    VARCHAR2(30 BYTE),
  CGR_NEW_DISPNAME      VARCHAR2(50 BYTE),
  CGR_FILE_NAME         VARCHAR2(30 BYTE),
  CGR_REMARK            VARCHAR2(100 BYTE),
  CGR_NEWPAN_CODE       VARCHAR2(90 BYTE),
  CGR_RESULT            VARCHAR2(500 BYTE)      DEFAULT 'NOT PROCESSED',
  CGR_MBR_NUMB          VARCHAR2(3 BYTE)        DEFAULT '000',
  CGR_INS_DATE          DATE,
  CGR_INS_USER          NUMBER(5)               DEFAULT 1                     NOT NULL,
  CGR_LUPD_DATE         DATE,
  CGR_INST_CODE         NUMBER(10),
  CGR_LUPD_USER         NUMBER(10),
  CGR_NEWPAN_CODE_ENCR  RAW(100),
  CGR_PAN_CODE_ENCR     RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


