CREATE TABLE VMSCMS.CMS_BATCHUPLOAD_DETAILS
(
  CBD_INST_CODE        NUMBER(3),
  CBD_FILE_TYPE        NUMBER(5),
  CBD_FILE_PATH        VARCHAR2(200 BYTE),
  CBD_FILE_NAME        VARCHAR2(100 BYTE),
  CBD_PROD_CODE        VARCHAR2(10 BYTE),
  CBD_PROD_CATG        VARCHAR2(2 BYTE),
  CBD_BATCH_ID         VARCHAR2(100 BYTE),
  CBD_FILE_STATUS      NUMBER(5),
  CBD_RESULTFILE_NAME  VARCHAR2(100 BYTE),
  CBD_UPLOAD_USER      VARCHAR2(50 BYTE),
  CBD_APPR_REJE_USER   VARCHAR2(50 BYTE),
  CBD_INS_USER         NUMBER(5),
  CBD_INS_DATE         DATE,
  CBD_LUPD_USER        NUMBER(5),
  CBD_LUPD_DATE        DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


