CREATE TABLE VMSCMS.CMS_VENDORITEM_CONFIG_MAST
(
  CVC_CONFIG_CODE    VARCHAR2(10 BYTE),
  CVC_VENDOR_CODE    VARCHAR2(10 BYTE),
  CVC_ITEM_CODE      VARCHAR2(10 BYTE),
  CVC_MIN_UNITS      NUMBER(10),
  CVC_MAX_UNITS      NUMBER(10),
  CVC_SLABS          NUMBER(2),
  CVC_INS_USER       NUMBER(5),
  CVC_INS_DATE       DATE,
  CVC_LUPD_USER      NUMBER(5),
  CVC_LUPD_DATE      DATE,
  CVC_VENDOR_RATING  VARCHAR2(1 BYTE),
  CVC_INST_CODE      NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_VENDORITEM_CONFIG_MAST ADD (
  CONSTRAINT PK_CONFIG_MAST
 PRIMARY KEY
 (CVC_CONFIG_CODE),
  CONSTRAINT UK_VENDORITEMCONFIG_MAST
 UNIQUE (CVC_VENDOR_CODE, CVC_ITEM_CODE))
/

ALTER TABLE VMSCMS.CMS_VENDORITEM_CONFIG_MAST ADD (
  CONSTRAINT FK_ITEMCONFIG_MAST 
 FOREIGN KEY (CVC_ITEM_CODE) 
 REFERENCES VMSCMS.CMS_INVENTORYITEM_MAST (CIM_INVENTORYITEM_CODE),
  CONSTRAINT FK_VENDORCONFIG_MAST 
 FOREIGN KEY (CVC_VENDOR_CODE) 
 REFERENCES VMSCMS.CMS_INVENTORYVENDOR_MAST (CIM_VENDOR_CODE))
/

