CREATE TABLE VMSCMS.CMS_PURGECARD_STAT
(
  CPS_PAN_CODE       VARCHAR2(90 BYTE),
  CPS_CARD_STAT      VARCHAR2(1 BYTE),
  CPS_PURGE_FLAG     VARCHAR2(1 BYTE),
  CPS_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


