CREATE TABLE VMSCMS.CMS_GROUP_PROG_TEMP
(
  CGP_INST_CODE      NUMBER(3)                  NOT NULL,
  CGP_GROUP_CODE     NUMBER(3)                  NOT NULL,
  CGP_PROG_CODE      NUMBER                     NOT NULL,
  CGP_INSR_ALLOW     NUMBER(1),
  CGP_DELE_ALLOW     NUMBER(1),
  CGP_UPDT_ALLOW     NUMBER(1),
  CGP_INS_USER       NUMBER(5)                  NOT NULL,
  CGP_INS_DATE       DATE                       NOT NULL,
  CGP_LUPD_USER      NUMBER(5),
  CGP_LUPD_DATE      DATE,
  CGP_ROW_ID         NUMBER(10),
  CGP_APPREJ_STATUS  VARCHAR2(2 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GROUP_PROG_TEMP ADD (
  CONSTRAINT PK_GRP_PROG_TEMP
 PRIMARY KEY
 (CGP_GROUP_CODE, CGP_PROG_CODE, CGP_ROW_ID))
/

