CREATE TABLE VMSCMS.CMS_JHLOAD_REASON_MAST
(
   CJM_INST_CODE        NUMBER (3, 0),
   CJM_REASON_CODE      VARCHAR2 (1 BYTE),
   CJM_REASON_DESC      VARCHAR2 (50 BYTE),
   CJM_LOGREASON_CODE   VARCHAR2 (3),
   CJM_INS_USER         NUMBER (10, 0),
   CJM_INS_DATE         DATE,
   CJM_LUPD_USER        NUMBER (10, 0),
   CJM_LUPD_DATE        DATE,
   CONSTRAINT PK_JHLOAD_REASON PRIMARY KEY (CJM_INST_CODE, CJM_REASON_CODE)
) TABLESPACE CMS_BIG_TXN;