CREATE TABLE VMSCMS.CMS_DEPLOYMENT_DTL
(
  CDD_RELEASE_VER  VARCHAR2(20 BYTE),
  CDD_INCOMM_VER   VARCHAR2(20 BYTE),
  CDD_START_TIME   TIMESTAMP(3),
  CDD_END_TIME     TIMESTAMP(3)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


