CREATE TABLE VMSCMS.CMS_GRP_CHANGE_CRDSTAT_TEMP
(
  CGC_INST_CODE     NUMBER(10),
  CGC_CARD_NO       VARCHAR2(90 BYTE),
  CGC_FILE_NAME     VARCHAR2(30 BYTE),
  CGC_NEW_STAT      CHAR(1 BYTE),
  CGC_REMARK        VARCHAR2(100 BYTE),
  CGC_MBR_NUMB      VARCHAR2(3 BYTE),
  CGC_INS_USER      NUMBER(10),
  CGC_INS_DATE      DATE,
  CGC_LUPD_USER     NUMBER(10),
  CGC_LUPD_DATE     DATE,
  CGC_PROCESS_FLAG  VARCHAR2(1 BYTE)            DEFAULT 'N',
  CGC_PROCESS_MSG   VARCHAR2(100 BYTE),
  CGC_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


