CREATE TABLE VMSCMS.CMS_KYCUPLOAD_ENTRY
(
  KYC_FILE_NAME    VARCHAR2(100 BYTE),
  KYC_FILE_HEADER  VARCHAR2(200 BYTE),
  KYC_UPLD_DATE    DATE,
  KYC_UPLD_STAT    CHAR(1 BYTE),
  KYC_UPLD_USER    VARCHAR2(100 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


