CREATE TABLE VMSCMS.CMS_PROD_CATG
(
  CPC_INST_CODE  NUMBER(3)                      NOT NULL,
  CPC_CATG_CODE  VARCHAR2(2 BYTE)               NOT NULL,
  CPC_CATG_APPL  NUMBER(2)                      NOT NULL,
  CPC_CATG_NAME  VARCHAR2(20 BYTE)              NOT NULL,
  CPC_INS_USER   NUMBER(5)                      NOT NULL,
  CPC_INS_DATE   DATE                           NOT NULL,
  CPC_LUPD_USER  NUMBER(5)                      NOT NULL,
  CPC_LUPD_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROD_CATG ADD (
  CONSTRAINT PK_PROD_CATG
 PRIMARY KEY
 (CPC_INST_CODE, CPC_CATG_CODE),
  CONSTRAINT UK_PROD_CATG
 UNIQUE (CPC_INST_CODE, CPC_CATG_APPL))
/

ALTER TABLE VMSCMS.CMS_PROD_CATG ADD (
  CONSTRAINT FK_PRODCATG_USERMAST2 
 FOREIGN KEY (CPC_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCATG_USERMAST1 
 FOREIGN KEY (CPC_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCATG_INSTMAST 
 FOREIGN KEY (CPC_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

