CREATE TABLE VMSCMS.CMS_MONTHWISE_LOYL
(
  CML_INST_CODE    NUMBER(3)                    NOT NULL,
  CML_ACCT_NO      VARCHAR2(20 BYTE)            NOT NULL,
  CML_TRAN_DATE    VARCHAR2(7 BYTE)             NOT NULL,
  CML_LOYLOPN_BAL  NUMBER(5)                    DEFAULT 0,
  CML_LOYL_POINTS  NUMBER(5)                    DEFAULT 0,
  CML_REDEEM       NUMBER(5)                    DEFAULT 0,
  CML_LOCK         CHAR(1 BYTE),
  CML_INS_USER     NUMBER(5)                    NOT NULL,
  CML_INS_DATE     DATE                         NOT NULL,
  CML_LUPD_USER    NUMBER(5)                    NOT NULL,
  CML_LUPD_DATE    DATE                         NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MONTHWISE_LOYL ADD (
  CONSTRAINT PK_MONTHWISE_LOYL
 PRIMARY KEY
 (CML_ACCT_NO, CML_TRAN_DATE))
/

