CREATE TABLE VMSCMS.CMS_CARDTYPE_MAST
(
  CCM_CARDTYPE_CODE  VARCHAR2(10 BYTE),
  CCM_CARDTYPE_DESC  VARCHAR2(50 BYTE),
  CCM_INS_USER       NUMBER(5),
  CCM_INS_DATE       DATE,
  CCM_LUPD_USER      NUMBER(5),
  CCM_LUPD_DATE      DATE,
  CCM_INST_CODE      NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CARDTYPE_MAST ADD (
  CONSTRAINT PK_CARDTYPE_MAST
 PRIMARY KEY
 (CCM_CARDTYPE_CODE))
/

