CREATE TABLE VMSCMS.CMS_CARD_EXCPWAIV
(
  CCE_INST_CODE      NUMBER(3)                  NOT NULL,
  CCE_FEE_CODE       NUMBER(3)                  NOT NULL,
  CCE_WAIV_PRCNT     NUMBER(5,2)                NOT NULL,
  CCE_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CCE_MBR_NUMB       VARCHAR2(3 BYTE)           NOT NULL,
  CCE_VALID_FROM     DATE                       NOT NULL,
  CCE_VALID_TO       DATE,
  CCE_WAIV_DESC      VARCHAR2(50 BYTE)          NOT NULL,
  CCE_FLOW_SOURCE    VARCHAR2(3 BYTE)           NOT NULL,
  CCE_INS_USER       NUMBER(5)                  NOT NULL,
  CCE_INS_DATE       DATE                       NOT NULL,
  CCE_LUPD_USER      NUMBER(5)                  NOT NULL,
  CCE_LUPD_DATE      DATE                       NOT NULL,
  CCE_CARD_WAIV_ID   NUMBER(10),
  CCE_PAN_CODE_ENCR  RAW(100),
  CCE_FEE_PLAN       NUMBER(4)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CARD_EXCPWAIV ADD (
  CONSTRAINT FK_CARDEXCPWAIV_USERMAST1 
 FOREIGN KEY (CCE_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CARDEXCPWAIV_USERMAST2 
 FOREIGN KEY (CCE_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CARDEXCPWAIV_FEEMAST 
 FOREIGN KEY (CCE_INST_CODE, CCE_FEE_CODE) 
 REFERENCES VMSCMS.CMS_FEE_MAST (CFM_INST_CODE,CFM_FEE_CODE),
  CONSTRAINT FK_CARDEXCPWAIV_APPLPAN 
 FOREIGN KEY (CCE_PAN_CODE, CCE_MBR_NUMB) 
 REFERENCES VMSCMS.CMS_APPL_PAN (CAP_PAN_CODE,CAP_MBR_NUMB))
/

