CREATE TABLE VMSCMS.CMS_VERIFICATION_DATA
(
  CVD_INST_CODE  NUMBER(10),
  CVD_PAN_CODE   VARCHAR2(90 BYTE),
  CVD_RRN        VARCHAR2(20 BYTE),
  CVD_DATE       VARCHAR2(8 BYTE),
  CVD_TIME       VARCHAR2(6 BYTE),
  CVD_TXN_CODE   VARCHAR2(2 BYTE),
  CVD_DELV_CHNL  VARCHAR2(2 BYTE),
  CVD_TXN_DESC   VARCHAR2(50 BYTE),
  CVD_VERF_FLDS  VARCHAR2(100 BYTE),
  CVD_INS_USER   NUMBER(10)                     NOT NULL,
  CVD_INS_DATE   DATE                           NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


