CREATE TABLE VMSCMS.CMS_PAN_CONSTRUCT
(
  CPC_INST_CODE     VARCHAR2(5 BYTE),
  CPC_PROFILE_CODE  VARCHAR2(5 BYTE),
  CPC_FIELD_NAME    VARCHAR2(50 BYTE),
  CPC_START         VARCHAR2(3 BYTE)            DEFAULT 1,
  CPC_LENGTH        VARCHAR2(3 BYTE),
  CPC_VALUE         VARCHAR2(5 BYTE),
  CPC_ORDER_BY      VARCHAR2(2 BYTE),
  CPC_START_FROM    VARCHAR2(3 BYTE),
  CPC_LUPD_DATE     DATE,
  CPC_LUPD_USER     NUMBER(10),
  CPC_INS_DATE      DATE,
  CPC_INS_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PAN_CONSTRUCT ADD (
  CONSTRAINT CK_PANCONSTRUCT_CPC_START
 CHECK (CPC_START =1))
/

ALTER TABLE VMSCMS.CMS_PAN_CONSTRUCT ADD (
  CONSTRAINT FK_PANCONSTRUCT_PROFILECODE 
 FOREIGN KEY (CPC_PROFILE_CODE) 
 REFERENCES VMSCMS.CMS_PROFILE_MAST (CPM_PROFILE_CODE))
/

