CREATE TABLE VMSCMS.CMS_PINMAILER_MAST
(
  CPM_PINMAILER_CODE       NUMBER(4),
  CPM_PINMAILER_TABLENAME  VARCHAR2(50 BYTE),
  CPM_PINMAILER_FIELDNAME  VARCHAR2(50 BYTE),
  CPM_PINMAILER_DESC       VARCHAR2(75 BYTE),
  CPM_PINMAILER_MAXLENGTH  NUMBER(3),
  CPM_PINMAILER_DATATYPE   VARCHAR2(20 BYTE)    NOT NULL,
  CPM_LUPD_DATE            DATE,
  CPM_INST_CODE            NUMBER(10),
  CPM_LUPD_USER            NUMBER(10),
  CPM_INS_DATE             DATE,
  CPM_INS_USER             NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PINMAILER_MAST ADD (
  CONSTRAINT PK_PINMAILER_MAST
 PRIMARY KEY
 (CPM_PINMAILER_CODE))
/

