CREATE TABLE VMSCMS.CMS_CONST_PART_MAST
(
  CCP_CPART_CODE   NUMBER(5),
  CCP_CPART_DESC   VARCHAR2(50 BYTE),
  CCP_CPART_SNAME  VARCHAR2(10 BYTE),
  CCP_CONST_CODE   NUMBER(3),
  CCP_CARD_FIID    VARCHAR2(4 BYTE),
  CCP_TERM_FIID    VARCHAR2(4 BYTE),
  CCP_INS_USER     NUMBER(5),
  CCP_INS_DATE     DATE,
  CCP_LUPD_USER    NUMBER(5),
  CCP_LUPD_DATE    DATE,
  CCP_INST_CODE    NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CONST_PART_MAST ADD (
  CONSTRAINT FK_CONSTCODE_CONST_MAST 
 FOREIGN KEY (CCP_CONST_CODE, CCP_INST_CODE) 
 REFERENCES VMSCMS.CMS_CONST_MAST (CCM_CONST_CODE,CCM_INST_CODE))
/

