CREATE TABLE VMSCMS.CMS_PROD_CCC_HIST
(
  CPC_INST_CODE  NUMBER(3),
  CPC_CUST_CATG  NUMBER(5),
  CPC_CARD_TYPE  NUMBER(2),
  CPC_PROD_CODE  VARCHAR2(6 BYTE),
  CPC_INS_USER   NUMBER(5),
  CPC_INS_DATE   DATE,
  CPC_LUPD_DATE  DATE,
  CPC_LUPD_USER  NUMBER(10)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


