CREATE TABLE VMSCMS.CMS_REPORT_MASTER
(
  CRM_REPORT_ID    NUMBER(4),
  CRM_REPORT_NAME  VARCHAR2(30 BYTE),
  CRM_INS_USER     NUMBER(5),
  CRM_INS_DATE     DATE,
  CRM_LUPD_USER    NUMBER(5),
  CRM_LUPD_DATE    DATE,
  CRM_INST_CODE    NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_REPORT_MASTER ADD (
  CONSTRAINT PK_REPORT_ID
 PRIMARY KEY
 (CRM_REPORT_ID))
/

