CREATE TABLE VMSCMS.CMS_ACCT_STAT
(
  CAS_INST_CODE        NUMBER(3)                NOT NULL,
  CAS_STAT_CODE        NUMBER(3)                NOT NULL,
  CAS_STAT_DESC        VARCHAR2(50 BYTE)        NOT NULL,
  CAS_SWITCH_STATCODE  VARCHAR2(2 BYTE)         NOT NULL,
  CAS_INS_USER         NUMBER(5)                NOT NULL,
  CAS_INS_DATE         DATE                     NOT NULL,
  CAS_LUPD_USER        NUMBER(5)                NOT NULL,
  CAS_LUPD_DATE        DATE                     NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ACCT_STAT ADD (
  CONSTRAINT PK_ACCT_STAT
 PRIMARY KEY
 (CAS_INST_CODE, CAS_STAT_CODE))
/

ALTER TABLE VMSCMS.CMS_ACCT_STAT ADD (
  CONSTRAINT FK_ACCTSTAT_USERMAST2 
 FOREIGN KEY (CAS_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_ACCTSTAT_USERMAST1 
 FOREIGN KEY (CAS_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_ACCTSTAT_INSTMAST 
 FOREIGN KEY (CAS_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

