CREATE TABLE VMSCMS.CMS_TIREDCOMMISSION_HIST
(
  CTH_INST_CODE        NUMBER(10),
  CTH_PLAN_AMT         NUMBER(10,4),
  CTH_PLAN_PERCENT     NUMBER(3),
  CTH_PAN_CODE         VARCHAR2(90 BYTE),
  CTH_PLAN_ID          VARCHAR2(10 BYTE),
  CTH_BRANCH_CODE      VARCHAR2(6 BYTE),
  CTH_COMMISSION_CALC  NUMBER(10,4),
  CTH_INS_USER         NUMBER(10),
  CTH_INS_DATE         DATE,
  CTH_LUPD_USER        NUMBER(10),
  CTH_LUPD_DATE        DATE,
  CTH_PAN_CODE_ENCR    RAW(100)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


