CREATE TABLE VMSCMS.CMS_KYCTXN_LOG
(
  CKL_CMSREQ_REFNO               VARCHAR2(20 BYTE) NOT NULL,
  CKL_KYCRES_REFNO               VARCHAR2(20 BYTE),
  CKL_KYC_REQ                    VARCHAR2(4000 BYTE),
  CKL_KYC_RES                    VARCHAR2(4000 BYTE),
  CKL_KYCREQ_DATE                DATE,
  CKL_KYCRES_DATE                DATE,
  CKL_KYC_FLAG                   VARCHAR2(2 BYTE),
  CKL_INST_CODE                  NUMBER(3),
  CKL_KYC_MSG                    VARCHAR2(300 BYTE),
  CKL_KYC_TYPE                   VARCHAR2(100 BYTE),
  CKL_KYCRES_QUALIFIER_KEY       VARCHAR2(100 BYTE),
  CKL_KYCRES_QUALIFIER_MESSAGE   VARCHAR2(100 BYTE),
  CKL_ROW_ID                     VARCHAR2(8 BYTE),
  CKL_KYCRES_RESTRICTED_KEY      VARCHAR2(100 BYTE),
  CKL_KYCRES_RESTRICTED_MESSAGE  VARCHAR2(100 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_KYCTXN_LOG ADD (
  CONSTRAINT PK_KYCTXN_LOG
 PRIMARY KEY
 (CKL_CMSREQ_REFNO, CKL_KYCREQ_DATE))
/

