CREATE TABLE VMSCMS.CMS_FLOAT_SGLWSE_DETAIL_ORGNL
(
  CFSR_TRAN_DATE      DATE,
  CFSR_CURR_CODE      VARCHAR2(9 BYTE),
  CFSR_PARAM_KEY      VARCHAR2(300 BYTE),
  CFSR_GL_CODE        VARCHAR2(21 BYTE),
  CFSR_GL_DESC        VARCHAR2(300 BYTE),
  CFSR_SUBGL_CODE     VARCHAR2(21 BYTE),
  CFSR_SUBGL_DESC     VARCHAR2(300 BYTE),
  CFSR_CREDIT_AMOUNT  NUMBER,
  CFSR_DEBIT_AMOUNT   NUMBER,
  CFS_LUPD_DATE       DATE,
  CFS_INST_CODE       NUMBER(10),
  CFS_LUPD_USER       NUMBER(10),
  CFS_INS_DATE        DATE,
  CFS_INS_USER        NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


