CREATE TABLE VMSCMS.CMS_SPIL_KYCQUE
(
  CSK_INST_CODE        NUMBER(3)                NOT NULL,
  CSK_RRN              VARCHAR2(20 BYTE)        NOT NULL,
  CSK_CARD_NO_ENCR     RAW(100)                 NOT NULL,
  CSK_CARD_NO          VARCHAR2(90 BYTE)        NOT NULL,
  CSK_PROD_CODE        VARCHAR2(6 BYTE)         NOT NULL,
  CSK_CARD_TYPE        VARCHAR2(2 BYTE)         NOT NULL,
  CSK_SCHEDULE_DATE    VARCHAR2(20 BYTE)        NOT NULL,
  CSK_PROCESS_FLAG     CHAR(2 BYTE)             DEFAULT 'N'                   NOT NULL,
  CSK_VERIFICATION_ID  VARCHAR2(15 BYTE)        NOT NULL,
  CSK_INS_DATE         DATE                     NOT NULL,
  CSK_INS_USER         NUMBER(10)               NOT NULL,
  CSK_LUPD_DATE        DATE                     NOT NULL,
  CSK_LUPD_USER        NUMBER(10)               NOT NULL
)
TABLESPACE CMS_DEFAULT
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SPIL_KYCQUE ADD (
  CONSTRAINT PK_SPIL_KYCQUE
 PRIMARY KEY
 (CSK_INST_CODE, CSK_CARD_NO, CSK_VERIFICATION_ID))
/

