CREATE TABLE VMSCMS.CMS_ACCTCLAWBACK_DTL
(
  CAD_INST_CODE         NUMBER(3),
  CAD_ACCT_NO           VARCHAR2(20 BYTE),
  CAD_PAN_CODE          VARCHAR2(90 BYTE),
  CAD_PAN_CODE_ENCR     RAW(100),
  CAD_CLAWBACK_AMNT     NUMBER(20,3),
  CAD_RECOVERY_FLAG     VARCHAR2(1 BYTE),
  CAD_INS_DATE          DATE,
  CAD_LUPD_DATE         DATE,
  CAD_DELIVERY_CHANNEL  VARCHAR2(2 BYTE),
  CAD_TXN_CODE          VARCHAR2(2 BYTE),
  CAD_INS_USER          NUMBER(1),
  CAD_LUPD_USER         NUMBER(5)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


