ALTER TABLE VMSCMS.CMS_LIMIT_PRFL MODIFY (CLP_WMAX_TXNCNT  NULL,CLP_WMAX_TXNAMNT  NULL,CLP_YMAX_TXNAMNT  NULL,CLP_YMAX_TXNCNT  NULL);
ALTER TABLE VMSCMS.CMS_LIMIT_PRFL MODIFY (CLP_DMAX_TXNCNT  NULL);
ALTER TABLE VMSCMS.CMS_LIMIT_PRFL MODIFY (CLP_DMAX_TXNAMNT  NULL);
ALTER TABLE VMSCMS.CMS_LIMIT_PRFL MODIFY (CLP_MMAX_TXNAMNT  NULL);
ALTER TABLE VMSCMS.CMS_LIMIT_PRFL MODIFY (CLP_MMAX_TXNCNT  NULL);