CREATE TABLE VMSCMS.CMS_PRODCCC_FEES
(
  CPF_INST_CODE    NUMBER(3)                    NOT NULL,
  CPF_CUST_CATG    NUMBER(5)                    NOT NULL,
  CPF_CARD_TYPE    NUMBER(2)                    NOT NULL,
  CPF_PROD_CODE    VARCHAR2(6 BYTE)             NOT NULL,
  CPF_FEE_CODE     NUMBER(5)                    NOT NULL,
  CPF_VALID_FROM   DATE                         NOT NULL,
  CPF_VALID_TO     DATE                         NOT NULL,
  CPF_FLOW_SOURCE  VARCHAR2(3 BYTE)             NOT NULL,
  CPF_INS_USER     NUMBER(5)                    NOT NULL,
  CPF_INS_DATE     DATE                         NOT NULL,
  CPF_LUPD_USER    NUMBER(5)                    NOT NULL,
  CPF_LUPD_DATE    DATE                         NOT NULL,
  CPF_TRAN_CODE    VARCHAR2(10 BYTE),
  CPF_FEE_TYPE     VARCHAR2(10 BYTE)            NOT NULL,
  CPF_FUNC_CODE    VARCHAR2(10 BYTE)            NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PRODCCC_FEES ADD (
  CONSTRAINT FK_PRODCCCF_USERMAST1 
 FOREIGN KEY (CPF_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCCCF_USERMAST2 
 FOREIGN KEY (CPF_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCCCF_CCC 
 FOREIGN KEY (CPF_INST_CODE, CPF_CUST_CATG, CPF_PROD_CODE, CPF_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CCC (CPC_INST_CODE,CPC_CUST_CATG,CPC_PROD_CODE,CPC_CARD_TYPE),
  CONSTRAINT FK_PRODCCCF_FEEMAST 
 FOREIGN KEY (CPF_INST_CODE, CPF_FEE_CODE) 
 REFERENCES VMSCMS.CMS_FEE_MAST (CFM_INST_CODE,CFM_FEE_CODE))
/

