CREATE TABLE VMSCMS.CMS_UPDATE_LIMITS
(
  CUL_INST_CODE      NUMBER(3)                  DEFAULT 1,
  CUL_PAN_CODE       VARCHAR2(90 BYTE),
  CUL_MBR_NUMB       VARCHAR2(3 BYTE),
  CUL_ATM_LIMIT      VARCHAR2(12 BYTE),
  CUL_POS_LIMIT      VARCHAR2(12 BYTE),
  CUP_PROCESSED      CHAR(1 BYTE)               DEFAULT 'N',
  CUL_LUPD_DATE      DATE,
  CUL_LUPD_USER      NUMBER(10),
  CUL_INS_DATE       DATE,
  CUL_INS_USER       NUMBER(10),
  CUP_INS_USER       NUMBER(10),
  CUL_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


