CREATE TABLE VMSCMS.CMS_CUST_ACCT
(
  CCA_INST_CODE               NUMBER(3)         NOT NULL,
  CCA_CUST_CODE               NUMBER(10)        NOT NULL,
  CCA_ACCT_ID                 NUMBER(10)        NOT NULL,
  CCA_ACCT_NAME               VARCHAR2(50 BYTE),
  CCA_HOLD_POSN               NUMBER(10)        NOT NULL,
  CCA_REL_STAT                CHAR(1 BYTE)      NOT NULL,
  CCA_INS_USER                NUMBER(5)         NOT NULL,
  CCA_INS_DATE                DATE              NOT NULL,
  CCA_LUPD_USER               NUMBER(5)         NOT NULL,
  CCA_LUPD_DATE               DATE              NOT NULL,
  CCA_THRESHOLD_LIMIT         NUMBER,
  CCA_THRESHOLD_AMT           NUMBER,
  CCA_THRESHOLD_ACCTNO        NUMBER(10),
  CCA_THRESHOLD_BANK          VARCHAR2(30 BYTE),
  CCA_THRESHOLD_BRANCH        VARCHAR2(30 BYTE),
  CCA_THRESHOLD_IFCS          VARCHAR2(15 BYTE),
  CCA_THRESHOLD_RTG           VARCHAR2(15 BYTE),
  CCA_THRESHOLD_MICR          VARCHAR2(15 BYTE),
  CCA_FUNDTRANS_AMT           NUMBER,
  CCA_FUNDTRANS_ACCTNO        NUMBER(11),
  CCA_FUNDTRANS_BANK          VARCHAR2(30 BYTE),
  CCA_FUNDTRANS_BRANCH        VARCHAR2(30 BYTE),
  CCA_FUNDTRANS_IFCS          VARCHAR2(15 BYTE),
  CCA_FUNDTRANS_RTG           VARCHAR2(15 BYTE),
  CCA_FUNDTRANS_MICR          VARCHAR2(15 BYTE),
  CCA_THRESHOLD_FILEGEN_FLAG  VARCHAR2(1 BYTE),
  CCA_FUNDTRANS_FILEGEN_FLAG  VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CUST_ACCT ADD (
  CONSTRAINT PK_CUST_ACCT
 PRIMARY KEY
 (CCA_INST_CODE, CCA_CUST_CODE, CCA_ACCT_ID))
/

ALTER TABLE VMSCMS.CMS_CUST_ACCT ADD (
  CONSTRAINT FK_CUSTACCT_USERMAST1 
 FOREIGN KEY (CCA_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CUSTACCT_USERMAST2 
 FOREIGN KEY (CCA_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CUSTACCT_CUSTMAST 
 FOREIGN KEY (CCA_INST_CODE, CCA_CUST_CODE) 
 REFERENCES VMSCMS.CMS_CUST_MAST (CCM_INST_CODE,CCM_CUST_CODE),
  CONSTRAINT FK_CUSTACCT_ACCTMAST 
 FOREIGN KEY (CCA_INST_CODE, CCA_ACCT_ID) 
 REFERENCES VMSCMS.CMS_ACCT_MAST (CAM_INST_CODE,CAM_ACCT_ID))
/

