CREATE TABLE VMSCMS.CMS_PANGEN_COUNT
(
  CPC_PAN_COUNT  NUMBER(6),
  CPC_LUPD_DATE  DATE,
  CPC_INST_CODE  NUMBER(10),
  CPC_LUPD_USER  NUMBER(10),
  CPC_INS_DATE   DATE,
  CPC_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


