CREATE TABLE VMSCMS.CMS_MSGTYPMAP_SPIL
(
  CMS_MSGTYPE_SPIL      VARCHAR2(50 BYTE),
  CMS_TXN_CODE          VARCHAR2(2 BYTE),
  CMS_MSG_TYPE          VARCHAR2(10 BYTE),
  CMS_REVERSAL_CODE     VARCHAR2(3 BYTE),
  CMS_DELIVERY_CHANNEL  VARCHAR2(3 BYTE),
  CMS_TXN_MODE          VARCHAR2(1 BYTE),
  CMS_INST_CODE         VARCHAR2(3 BYTE),
  CMS_INS_DATE          DATE,
  CMS_LUPD_DATE         DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MSGTYPMAP_SPIL ADD (
  CONSTRAINT PK_MSGTYPMAP_SPIL1
 PRIMARY KEY
 (CMS_MSGTYPE_SPIL))
/

