CREATE TABLE VMSCMS.CMS_APPL_DET
(
  CAD_APPL_CODE  NUMBER(14)                     NOT NULL,
  CAD_ACCT_ID    NUMBER(10)                     NOT NULL,
  CAD_ACCT_POSN  NUMBER(3)                      NOT NULL,
  CAD_INS_USER   NUMBER(5)                      NOT NULL,
  CAD_INS_DATE   DATE                           NOT NULL,
  CAD_LUPD_USER  NUMBER(5)                      NOT NULL,
  CAD_LUPD_DATE  DATE                           NOT NULL,
  CAD_INST_CODE  NUMBER(3)                      DEFAULT 1
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_APPL_DET ADD (
  CONSTRAINT PK_APPL_DET
 PRIMARY KEY
 (CAD_APPL_CODE, CAD_ACCT_ID))
/

ALTER TABLE VMSCMS.CMS_APPL_DET ADD (
  CONSTRAINT FK_APPLDET_USERMAST1 
 FOREIGN KEY (CAD_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_APPLDET_USERMAST2 
 FOREIGN KEY (CAD_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_APPLDET_APPLMAST 
 FOREIGN KEY (CAD_APPL_CODE) 
 REFERENCES VMSCMS.CMS_APPL_MAST (CAM_APPL_CODE))
/

