CREATE TABLE VMSCMS.CMS_DISP_MAST
(
  CDM_INST_CODE  NUMBER(3)                      NOT NULL,
  CDM_DISP_CODE  NUMBER(2)                      NOT NULL,
  CDM_DISP_DESC  VARCHAR2(35 BYTE)              NOT NULL,
  CDM_INS_USER   NUMBER(5)                      NOT NULL,
  CDM_INS_DATE   DATE                           NOT NULL,
  CDM_LUPD_USER  NUMBER(5)                      NOT NULL,
  CDM_LUPD_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_DISP_MAST ADD (
  CONSTRAINT PK_DISP_MAST
 PRIMARY KEY
 (CDM_INST_CODE, CDM_DISP_CODE))
/

ALTER TABLE VMSCMS.CMS_DISP_MAST ADD (
  CONSTRAINT FK_DISPMAST_INSTMAST 
 FOREIGN KEY (CDM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_DISPMAST_USERMAST1 
 FOREIGN KEY (CDM_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_DISPMAST_USERMAST2 
 FOREIGN KEY (CDM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

