CREATE TABLE VMSCMS.CMS_MAX_USERS
(
  CMU_INST_CODE  NUMBER(3),
  CMU_MAX_USERS  NUMBER(5),
  CMU_LUPD_DATE  DATE,
  CMU_LUPD_USER  NUMBER(10),
  CMU_INS_DATE   DATE,
  CMU_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


