CREATE TABLE VMSCMS.CMS_PINMAILER_FORMAT
(
  CPF_INST_CODE   NUMBER(10),
  CPF_HSM_NO      NUMBER(10),
  CPF_FIELD_NAME  VARCHAR2(40 BYTE),
  CPF_ROW_NO      VARCHAR2(3 BYTE),
  CPF_COL_NO      VARCHAR2(3 BYTE),
  CPF_FLD_NO      VARCHAR2(3 BYTE),
  CPF_INS_DATE    DATE,
  CPF_INS_USER    NUMBER(10),
  CPF_LUPD_DATE   DATE,
  CPF_LUPD_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


