CREATE TABLE VMSCMS.CMS_LIMITUPDATE_DETAIL
(
  CLD_INST_CODE          NUMBER(3),
  CLD_CARD_NO            VARCHAR2(90 BYTE),
  CLD_FILE_NAME          VARCHAR2(30 BYTE),
  CLD_REMARKS            VARCHAR2(100 BYTE),
  CLD_OLDATM_LIMIT       VARCHAR2(10 BYTE),
  CLD_OLDPOS_LIMIT       VARCHAR2(10 BYTE),
  CLD_MSG24_FLAG         CHAR(1 BYTE)           DEFAULT 'N',
  CLD_PROCESS_FLAG       VARCHAR2(1 BYTE),
  CLD_PROCESS_MSG        VARCHAR2(300 BYTE),
  CLD_PROCESS_MODE       VARCHAR2(1 BYTE),
  CLD_INS_USER           NUMBER(5),
  CLD_INS_DATE           DATE,
  CLD_LUPD_USER          NUMBER(5),
  CLD_LUPD_DATE          DATE,
  CLD_ATM_OFFLINE_LIMIT  VARCHAR2(10 BYTE),
  CLD_ATM_ONLINE_LIMIT   VARCHAR2(10 BYTE),
  CLD_POS_OFFLINE_LIMIT  VARCHAR2(10 BYTE),
  CLD_POS_ONLINE_LIMIT   VARCHAR2(10 BYTE),
  CLD_CARD_NO_ENCR       RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


