CREATE TABLE VMSCMS.CMS_CUST_GROUP
(
  CCG_INST_CODE   NUMBER(3)                     NOT NULL,
  CCG_GROUP_CODE  NUMBER(3)                     NOT NULL,
  CCG_GROUP_DESC  VARCHAR2(50 BYTE)             NOT NULL,
  CCG_INS_USER    NUMBER(5)                     NOT NULL,
  CCG_INS_DATE    DATE                          NOT NULL,
  CCG_LUPD_USER   NUMBER(5)                     NOT NULL,
  CCG_LUPD_DATE   DATE                          NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CUST_GROUP ADD (
  CONSTRAINT PK_CUST_GROUP
 PRIMARY KEY
 (CCG_INST_CODE, CCG_GROUP_CODE))
/

ALTER TABLE VMSCMS.CMS_CUST_GROUP ADD (
  CONSTRAINT FK_CUSTGROUP_INSTMAST 
 FOREIGN KEY (CCG_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

