CREATE TABLE VMSCMS.CMS_BLOCK_DETAIL
(
  CBD_INST_CODE     NUMBER(3),
  CBD_CARD_NO       VARCHAR2(90 BYTE),
  CBD_FILE_NAME     VARCHAR2(30 BYTE),
  CBD_REMARKS       VARCHAR2(100 BYTE),
  CBD_MSG24_FLAG    CHAR(1 BYTE)                DEFAULT 'N',
  CBD_PROCESS_FLAG  VARCHAR2(1 BYTE),
  CBD_PROCESS_MSG   VARCHAR2(300 BYTE),
  CBD_PROCESS_MODE  VARCHAR2(1 BYTE),
  CBD_INS_USER      NUMBER(5),
  CBD_INS_DATE      DATE,
  CBD_LUPD_USER     NUMBER(5),
  CBD_LUPD_DATE     DATE,
  CBD_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


