CREATE TABLE VMSCMS.CMS_TXNCODE_RULE
(
  CTR_INST_CODE          NUMBER(10),
  CTR_TXN_CODE           VARCHAR2(4 BYTE),
  CTR_DELV_CHNL          VARCHAR2(2 BYTE),
  CTR_TXN_TYPE           VARCHAR2(2 BYTE),
  CTR_TXN_DESC           VARCHAR2(50 BYTE)      NOT NULL,
  CTR_TXNRULE_ID         VARCHAR2(5 BYTE),
  CTR_MCC_CODE           VARCHAR2(4 BYTE),
  CTR_FIXEDHOLD_AMOUNT   NUMBER(6,2)            DEFAULT 0,
  CTR_PERHOLD_AMOUNT     NUMBER(5,2)            DEFAULT 0,
  CTR_HOLD_DAYS          NUMBER(4),
  CTR_ACTIVATION_STATUS  VARCHAR2(1 BYTE),
  CTR_LUPD_DATE          DATE,
  CTR_LUPD_USER          NUMBER(10),
  CTR_INS_DATE           DATE,
  CTR_INS_USER           NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TXNCODE_RULE ADD (
  CONSTRAINT PK_TXNCODE_RULE
 PRIMARY KEY
 (CTR_TXNRULE_ID),
  CONSTRAINT UK_TXNCODE_RULE
 UNIQUE (CTR_INST_CODE, CTR_TXN_CODE, CTR_DELV_CHNL, CTR_MCC_CODE))
/

ALTER TABLE VMSCMS.CMS_TXNCODE_RULE ADD (
  CONSTRAINT FK_INST_TXN_DEVL_CODE 
 FOREIGN KEY (CTR_INST_CODE, CTR_DELV_CHNL, CTR_TXN_CODE) 
 REFERENCES VMSCMS.CMS_TRANSACTION_MAST (CTM_INST_CODE,CTM_DELIVERY_CHANNEL,CTM_TRAN_CODE))
/

