CREATE TABLE VMSCMS.CMS_PREV_PSWDS
(
  CPP_INST_CODE  NUMBER(3)                      NOT NULL,
  CPP_USER_PIN   NUMBER(5)                      NOT NULL,
  CPP_PREV_PSWD  VARCHAR2(100 BYTE)             NOT NULL,
  CPP_PSWD_DATE  DATE                           NOT NULL,
  CPP_LUPD_DATE  DATE,
  CPP_LUPD_USER  NUMBER(10),
  CPP_INS_DATE   DATE,
  CPP_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


