CREATE TABLE VMSCMS.CMS_RENCAF_HEADER
(
  CRH_INST_CODE     NUMBER(3)                   NOT NULL,
  CRH_RENCAF_FNAME  VARCHAR2(20 BYTE)           NOT NULL,
  CRH_FILE_GEN      VARCHAR2(1 BYTE)            NOT NULL,
  CRH_INS_USER      NUMBER(5)                   NOT NULL,
  CRH_INS_DATE      DATE                        NOT NULL,
  CRH_LUPD_USER     NUMBER(5)                   NOT NULL,
  CRH_LUPD_DATE     DATE                        NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


