CREATE TABLE VMSCMS.CMS_KEY_HISTORY
(
  CKH_INST_CODE      NUMBER(3),
  CKH_OLD_DEK_INDEX  VARCHAR2(3 BYTE),
  CKH_NEW_DEK_INDEX  VARCHAR2(3 BYTE),
  CKH_ROTATION_DATE  DATE,
  CKH_INS_USER       NUMBER(5),
  CKH_INS_DATE       DATE,
  CKH_LUPD_USER      NUMBER(5),
  CKH_LUPD_DATE      DATE
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_KEY_HISTORY ADD (
  CONSTRAINT FK_KEY_HISTORY_NEW 
 FOREIGN KEY (CKH_NEW_DEK_INDEX) 
 REFERENCES VMSCMS.CMS_DEK_KEY_DETAIL (CDK_DEK_INDEX),
  CONSTRAINT FK_KEY_HISTORY_OLD 
 FOREIGN KEY (CKH_OLD_DEK_INDEX) 
 REFERENCES VMSCMS.CMS_DEK_KEY_DETAIL (CDK_DEK_INDEX))
/

