CREATE TABLE VMSCMS.CMS_STOCK_INVENTORY
(
  CSI_STOCKREF_CODE  VARCHAR2(11 BYTE),
  CSI_VENDOR_CODE    VARCHAR2(10 BYTE),
  CSI_INVCATG_CODE   VARCHAR2(10 BYTE),
  CSI_INVITEM_CODE   VARCHAR2(10 BYTE),
  CSI_PRICEPER_UNIT  NUMBER(10,2),
  CSI_QTY_ORDERED    NUMBER(10),
  CSI_ORDER_COST     NUMBER(10,2),
  CSI_SERVICE_TAX    NUMBER(10,2),
  CSI_EDU_TAX        NUMBER(10,2),
  CSI_TOTAL_COST     NUMBER(10,2),
  CSI_ORDER_FLAG     VARCHAR2(1 BYTE),
  CSI_INS_USER       VARCHAR2(5 BYTE),
  CSI_INS_DATE       DATE,
  CSI_RECEIVED_DATE  DATE,
  CSI_CHECKED_USER   NUMBER(5),
  CSI_CHECKED_DATE   DATE,
  CSI_QTY_RECEIVED   NUMBER(10),
  CSI_LUPD_DATE      DATE,
  CSI_INST_CODE      NUMBER(10),
  CSI_LUPD_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_STOCK_INVENTORY ADD (
  CONSTRAINT PK_CMS_STOCK_INVENTORY
 PRIMARY KEY
 (CSI_STOCKREF_CODE))
/

ALTER TABLE VMSCMS.CMS_STOCK_INVENTORY ADD (
  CONSTRAINT FK_STOCK_INVENTORY_INVCATGCODE 
 FOREIGN KEY (CSI_INVCATG_CODE) 
 REFERENCES VMSCMS.CMS_INVENTORYCATG_MAST (CIM_INVENTORYCATG_CODE),
  CONSTRAINT FK_STOCK_INVENTORY_INVITEMCODE 
 FOREIGN KEY (CSI_INVITEM_CODE) 
 REFERENCES VMSCMS.CMS_INVENTORYITEM_MAST (CIM_INVENTORYITEM_CODE),
  CONSTRAINT FK_STOCK_INVENTORY_VENDORCODE 
 FOREIGN KEY (CSI_VENDOR_CODE) 
 REFERENCES VMSCMS.CMS_INVENTORYVENDOR_MAST (CIM_VENDOR_CODE))
/

