CREATE TABLE VMSCMS.CMS_TRACKDETL_LGIN
(
  CTL_INST_CODE  NUMBER(5)                      NOT NULL,
  CTL_USER_CODE  NUMBER(5)                      NOT NULL,
  CTL_PSWD_TYPE  NUMBER(1)                      NOT NULL,
  CTL_INVL_LGIN  NUMBER(2)                      NOT NULL,
  CTL_INS_USER   NUMBER(8)                      NOT NULL,
  CTL_INS_DATE   DATE                           NOT NULL,
  CTL_LUPD_USER  NUMBER(8),
  CTL_LUPD_DATE  DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TRACKDETL_LGIN ADD (
  CONSTRAINT PK_CTL_INST_USER_PSWD
 PRIMARY KEY
 (CTL_INST_CODE, CTL_USER_CODE, CTL_PSWD_TYPE))
/

ALTER TABLE VMSCMS.CMS_TRACKDETL_LGIN ADD (
  CONSTRAINT FK_CTL_PWIN_CUM_USID 
 FOREIGN KEY (CTL_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_CTL_INST_CIM_INST 
 FOREIGN KEY (CTL_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

