CREATE TABLE VMSCMS.CMS_TTUM_UPLOAD
(
  CTU_INST_CODE    NUMBER(3)                    NOT NULL,
  CTU_FILE_NAME    VARCHAR2(18 BYTE)            NOT NULL,
  CTU_ROW_ID       VARCHAR2(10 BYTE)            NOT NULL,
  CTU_REC_SOURCE   VARCHAR2(4 BYTE)             NOT NULL,
  CTU_ACCT_NO      VARCHAR2(16 BYTE)            NOT NULL,
  CTU_CURR_CODE    VARCHAR2(3 BYTE)             NOT NULL,
  CTU_SOLID_CODE   VARCHAR2(8 BYTE)             NOT NULL,
  CTU_TRAN_TYPE    CHAR(1 BYTE)                 NOT NULL,
  CTU_TRANS_AMT    VARCHAR2(15 BYTE)            NOT NULL,
  CTU_PARTI_CULAR  VARCHAR2(100 BYTE)           NOT NULL,
  CTU_FEE_TRANS    NUMBER(13),
  CTU_INS_USER     NUMBER(5)                    NOT NULL,
  CTU_INS_DATE     DATE                         NOT NULL,
  CTU_LUPD_USER    NUMBER(5)                    NOT NULL,
  CTU_LUPD_DATE    DATE                         NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TTUM_UPLOAD ADD (
  CONSTRAINT PK_TTUM_UPLOAD
 PRIMARY KEY
 (CTU_INST_CODE, CTU_FILE_NAME, CTU_ROW_ID),
  CONSTRAINT UK_TTUM_UPLOAD
 UNIQUE (CTU_FEE_TRANS))
/

ALTER TABLE VMSCMS.CMS_TTUM_UPLOAD ADD (
  CONSTRAINT FK_TTUMUPLD_TTUMCTRL 
 FOREIGN KEY (CTU_INST_CODE, CTU_FILE_NAME) 
 REFERENCES VMSCMS.CMS_TTUM_CTRL (CTC_INST_CODE,CTC_FILE_NAME),
  CONSTRAINT FK_TTUMUPLD_USERMAST1 
 FOREIGN KEY (CTU_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_TTUMUPLD_USERMAST2 
 FOREIGN KEY (CTU_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

