CREATE TABLE VMSCMS.CMS_GROUP_UNBLOCK_TEMP
(
  CGU_INST_CODE     NUMBER(3),
  CGU_CARD_NO       VARCHAR2(90 BYTE),
  CGU_FILE_NAME     VARCHAR2(30 BYTE),
  CGU_REMARKS       VARCHAR2(100 BYTE),
  CGU_PROCESS_FLAG  VARCHAR2(1 BYTE)            DEFAULT 'N',
  CGU_PROCESS_MSG   VARCHAR2(300 BYTE),
  CGU_INS_USER      NUMBER(5),
  CGU_INS_DATE      DATE                        DEFAULT SYSDATE,
  CGU_MBR_NUMB      VARCHAR2(10 BYTE),
  CGU_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


