CREATE TABLE VMSCMS.CMS_MERC_CATG
(
  CMC_INST_CODE  NUMBER(3)                      NOT NULL,
  CMC_CATG_CODE  VARCHAR2(4 BYTE)               NOT NULL,
  CMC_CATG_DESC  VARCHAR2(100 BYTE)             NOT NULL,
  CMC_INS_USER   NUMBER(5)                      NOT NULL,
  CMC_INS_DATE   DATE                           NOT NULL,
  CMC_LUPD_USER  NUMBER(5)                      NOT NULL,
  CMC_LUPD_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MERC_CATG ADD (
  CONSTRAINT PK_MERC_CATG
 PRIMARY KEY
 (CMC_INST_CODE, CMC_CATG_CODE))
/

ALTER TABLE VMSCMS.CMS_MERC_CATG ADD (
  CONSTRAINT FK_MERCCATG_INSTMAST 
 FOREIGN KEY (CMC_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_MERCCATG_USERMAST1 
 FOREIGN KEY (CMC_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_MERCCATG_USERMAST2 
 FOREIGN KEY (CMC_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

