CREATE TABLE VMSCMS.CMS_SUCCESS_LOG
(
  CSL_INST_CODE      NUMBER(3)                  NOT NULL,
  CSL_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CSL_MBR_NUMB       VARCHAR2(3 BYTE)           NOT NULL,
  CSL_PROCESS_TYPE   VARCHAR2(10 BYTE)          NOT NULL,
  CSL_PROCESS_ID     NUMBER(10)                 NOT NULL,
  CSL_MESSG          VARCHAR2(500 BYTE),
  CSL_ADDR_REPFLAG   CHAR(1 BYTE),
  CSL_LUPD_DATE      DATE,
  CSL_LUPD_USER      NUMBER(10),
  CSL_INS_DATE       DATE,
  CSL_INS_USER       NUMBER(10),
  CSL_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SUCCESS_LOG ADD (
  CONSTRAINT PK_SUCCESS_LOG
 PRIMARY KEY
 (CSL_INST_CODE, CSL_PAN_CODE, CSL_MBR_NUMB, CSL_PROCESS_TYPE, CSL_PROCESS_ID))
/

