CREATE TABLE VMSCMS.CMS_INST_DSN
(
  INST_ID             VARCHAR2(4 BYTE),
  JNDI_DSN            VARCHAR2(30 BYTE),
  CID_INST_SHORTNAME  VARCHAR2(5 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


