CREATE TABLE VMSCMS.CMS_CARD_MASTER
(
  CCM_CARD_NO       VARCHAR2(90 BYTE),
  CCM_FLAG          CHAR(1 BYTE)                DEFAULT 'N',
  CCM_INS_DATE      DATE,
  CCM_INS_USER      NUMBER(5),
  CCM_LUPD_USER     NUMBER(5)                   DEFAULT 1,
  CCM_LUPD_DATE     DATE,
  CCM_ROWID         NUMBER(20),
  CCM_DELINS_USER   NUMBER(5),
  CCM_DELINS_DATE   DATE,
  CCM_DELLUPD_USER  NUMBER(5),
  CCM_DELLUPD_DATE  DATE,
  CCM_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


