CREATE TABLE VMSCMS.CMS_PROD_BIN
(
  CPB_INST_CODE          NUMBER(3)              NOT NULL,
  CPB_PROD_CODE          VARCHAR2(6 BYTE)       NOT NULL,
  CPB_INST_BIN           NUMBER(10)             NOT NULL,
  CPB_INTERCHANGE_CODE   VARCHAR2(2 BYTE),
  CPB_ACTIVE_BIN         CHAR(1 BYTE)           NOT NULL,
  CPB_INS_USER           NUMBER(5)              NOT NULL,
  CPB_INS_DATE           DATE                   NOT NULL,
  CPB_LUPD_USER          NUMBER(5)              NOT NULL,
  CPB_LUPD_DATE          DATE                   NOT NULL,
  CPB_MARC_PRODBIN_FLAG  VARCHAR2(1 BYTE)       DEFAULT 'N'                   NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROD_BIN ADD (
  CONSTRAINT PK_PROD_BIN
 PRIMARY KEY
 (CPB_INST_CODE, CPB_PROD_CODE, CPB_INST_BIN))
/

ALTER TABLE VMSCMS.CMS_PROD_BIN ADD (
  CONSTRAINT FK_PRODBIN_USERMAST2 
 FOREIGN KEY (CPB_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODBIN_USERMAST1 
 FOREIGN KEY (CPB_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODBIN_PRODMAST 
 FOREIGN KEY (CPB_INST_CODE, CPB_PROD_CODE) 
 REFERENCES VMSCMS.CMS_PROD_MAST (CPM_INST_CODE,CPM_PROD_CODE),
  CONSTRAINT FK_PRODBIN_BINMAST 
 FOREIGN KEY (CPB_INST_CODE, CPB_INST_BIN) 
 REFERENCES VMSCMS.CMS_BIN_MAST (CBM_INST_CODE,CBM_INST_BIN))
/

