CREATE TABLE VMSCMS.CMS_VLCTYLD1000_TEMP_TXN24HRS
(
  CHR_ROW_ID               VARCHAR2(30 BYTE),
  CHR_PRIMARY_CARD_NUMBER  VARCHAR2(90 BYTE),
  CHR_TXN_DATE             VARCHAR2(100 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


