CREATE TABLE VMSCMS.CMS_CARDRENEWAL_ERRLOG
(
  CCE_PAN_CODE       VARCHAR2(90 BYTE),
  CCE_DISP_NAME      VARCHAR2(50 BYTE),
  CCE_ACCT_NO        VARCHAR2(20 BYTE),
  CCE_CARD_STAT      CHAR(1 BYTE),
  CCE_EXPRY_DATE     DATE,
  CCE_ERROR_MESG     VARCHAR2(500 BYTE),
  CCE_INS_USER       NUMBER(5),
  CCE_INS_DATE       DATE,
  CCE_LUPD_DATE      DATE,
  CCE_INST_CODE      NUMBER(10),
  CCE_LUPD_USER      NUMBER(10),
  CCE_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


