CREATE TABLE VMSCMS.CMS_CARDFNDSTRANS_COUNTER
(
  CCC_INST_CODE       NUMBER(10),
  CCC_TRACK_ID        NUMBER(38),
  CCC_FROM_CARD       VARCHAR2(90 BYTE),
  CCC_TO_CARD         VARCHAR2(90 BYTE),
  CCC_AMOUNT          VARCHAR2(10 BYTE),
  CCC_INS_USER        NUMBER(10),
  CCC_INS_DATE        DATE,
  CCC_LUPD_USER       NUMBER(10),
  CCC_LUPD_DATE       DATE,
  CCC_FROM_CARD_ENCR  RAW(100),
  CCC_TO_CARD_ENCR    RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


