CREATE TABLE VMSCMS.CMS_KEY_ROTATE_LOG
(
  CKR_INST_CODE  NUMBER(3),
  CKR_OLD_DATA   RAW(100),
  CKR_NEW_DATA   RAW(100),
  CKR_HASH_DATA  VARCHAR2(90 BYTE),
  CKR_DATA_OF    VARCHAR2(3 BYTE),
  CKR_REMARKS    VARCHAR2(500 BYTE),
  CKR_INS_USER   NUMBER(5),
  CKR_INS_DATE   DATE,
  CKR_LUPD_USER  NUMBER(5),
  CKR_LUPD_DATE  DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_KEY_ROTATE_LOG ADD (
  CONSTRAINT PK_KEY_ROTATE_LOG
 PRIMARY KEY
 (CKR_INST_CODE, CKR_OLD_DATA, CKR_NEW_DATA))
/

ALTER TABLE VMSCMS.CMS_KEY_ROTATE_LOG ADD (
  CONSTRAINT FK_KEY_ROTATE_LOG 
 FOREIGN KEY (CKR_DATA_OF) 
 REFERENCES VMSCMS.CMS_DEK_INDEX_PARAM (CDI_KEY_OF))
/

