CREATE TABLE VMSCMS.CMS_ATTCHFEE_HIST
(
  CAH_INST_CODE      NUMBER(3),
  CAH_FEE_CODE       NUMBER(3),
  CAH_OLD_FROMDATE   DATE,
  CAH_OLD_TODATE     DATE,
  CAH_CHANGE_LEVEL   VARCHAR2(3 BYTE),
  CAH_PROD_CODE      VARCHAR2(6 BYTE),
  CAH_CAT_TYPE       NUMBER(2),
  CAH_CUST_CATG      NUMBER(5),
  CAH_PAN_CODE       VARCHAR2(90 BYTE),
  CAH_MBR_NUMB       VARCHAR2(3 BYTE),
  CAH_CHANGE_SOURCE  VARCHAR2(3 BYTE),
  CAH_ACTION_TAKEN   VARCHAR2(6 BYTE),
  CAH_CHANGE_USER    NUMBER(5),
  CAH_CHANGE_DATE    DATE,
  CAH_LUPD_DATE      DATE,
  CAH_LUPD_USER      NUMBER(10),
  CAH_INS_DATE       DATE,
  CAH_INS_USER       NUMBER(10),
  CAH_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


