CREATE TABLE VMSCMS.CMS_CSR_DATAVERIFIED
(
  CCD_INST_CODE          NUMBER(5),
  CCD_PAN_CODE           RAW(100),
  CCD_DATA_VERIFIED      VARCHAR2(150 BYTE),
  CCD_CALLCENTER_USERID  VARCHAR2(4 BYTE),
  CCD_INS_DATE           DATE,
  CCD_LUPD_USERID        VARCHAR2(4 BYTE),
  CCD_LUPD_DATE          DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


