CREATE TABLE VMSCMS.CMS_MERCHANT_PREVPSWDS
(
  CMP_INST_CODE  NUMBER(3)                      NOT NULL,
  CMP_USER_PIN   NUMBER(5)                      NOT NULL,
  CMP_PREV_PSWD  VARCHAR2(100 BYTE)             NOT NULL,
  CMP_PSWD_DATE  DATE                           NOT NULL,
  CMP_LUPD_DATE  DATE,
  CMP_INS_DATE   DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


