CREATE TABLE VMSCMS.CMS_PASSWORD_PARAM
(
  CPP_INST_CODE        NUMBER(3)                NOT NULL,
  CPP_PROFILE_NAME     VARCHAR2(20 BYTE)        NOT NULL,
  CPP_PARAM_KEY        VARCHAR2(20 BYTE)        NOT NULL,
  CPP_PARAM_DESC       VARCHAR2(50 BYTE)        NOT NULL,
  CPP_PARAM_VALUE      VARCHAR2(15 BYTE)        NOT NULL,
  CPP_INS_USER         NUMBER(5)                NOT NULL,
  CPP_INS_DATE         DATE                     NOT NULL,
  CPP_LUPD_USER        NUMBER(5)                NOT NULL,
  CPP_LUPD_DATE        DATE                     NOT NULL,
  CPP_ACTIVATION_FLAG  CHAR(1 BYTE)             NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


