CREATE TABLE VMSCMS.CMS_GROUP_HOTREISSUE
(
  CGH_PAN_CODE          VARCHAR2(90 BYTE),
  CGH_PIN_HOTREISSUE    VARCHAR2(1 BYTE)        DEFAULT 'N',
  CGH_NEW_PRODUCT       VARCHAR2(6 BYTE),
  CGH_NEW_PRODUCTCAT    VARCHAR2(30 BYTE),
  CGH_NEW_DISPNAME      VARCHAR2(50 BYTE),
  CGH_FILE_NAME         VARCHAR2(30 BYTE),
  CGH_REMARK            VARCHAR2(100 BYTE),
  CGH_NEWPAN_CODE       VARCHAR2(90 BYTE),
  CGH_RESULT            VARCHAR2(500 BYTE)      DEFAULT 'NOT PROCESSED',
  CGH_MBR_NUMB          VARCHAR2(3 BYTE)        DEFAULT '000',
  CGH_INS_DATE          DATE,
  CGH_LUPD_DATE         DATE,
  CGH_INST_CODE         NUMBER(10),
  CGH_LUPD_USER         NUMBER(10),
  CGH_INS_USER          NUMBER(10),
  CGH_NEWPAN_CODE_ENCR  RAW(100),
  CGH_PAN_CODE_ENCR     RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


