CREATE TABLE VMSCMS.CMS_REQRESP_LOG
(
  CRL_INST_CODE      NUMBER(3),
  CRL_PAN_CODE       VARCHAR2(90 BYTE),
  CRL_ACCT_NO        VARCHAR2(20 BYTE),
  CRL_PROC_CODE      VARCHAR2(6 BYTE),
  CRL_REASON_CODE    VARCHAR2(5 BYTE),
  CRL_REMARKS        VARCHAR2(50 BYTE),
  CRL_EMP_ID         VARCHAR2(15 BYTE),
  CRL_STATUS_FLAG    VARCHAR2(1 BYTE)           DEFAULT 'N',
  CRL_STATUS_DESC    VARCHAR2(50 BYTE),
  CRL_REQ_XML        VARCHAR2(1000 BYTE),
  CRL_RESP_XML       VARCHAR2(1000 BYTE),
  CRL_INST_USER      NUMBER(10),
  CRL_INST_DATE      DATE                       DEFAULT SYSDATE,
  CRL_UPLD_USER      NUMBER(10),
  CRL_UPLD_DATE      DATE                       DEFAULT SYSDATE,
  CRL_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


