CREATE TABLE VMSCMS.CMS_SPPRTFUNC_LOG_DTL
(
  CSD_DELIVERY_CHANNEL       VARCHAR2(2 BYTE),
  CSD_TXN_CODE               VARCHAR2(2 BYTE),
  CSD_TXN_TYPE               VARCHAR2(2 BYTE),
  CSD_TXN_MODE               VARCHAR2(1 BYTE),
  CSD_BUSINESS_DATE          VARCHAR2(8 BYTE),
  CSD_BUSINESS_TIME          VARCHAR2(9 BYTE),
  CSD_CUSTOMER_CARD_NO       VARCHAR2(90 BYTE),
  CSD_SPPRT_FUNC             VARCHAR2(30 BYTE),
  CSD_PROCESS_FLAG           VARCHAR2(1 BYTE),
  CSD_PROCESS_MSG            VARCHAR2(300 BYTE),
  CSD_LUPD_DATE              DATE,
  CSD_INST_CODE              NUMBER(10),
  CSD_LUPD_USER              NUMBER(10),
  CSD_INS_DATE               DATE,
  CSD_INS_USER               NUMBER(10),
  CSD_CUSTOMER_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


