CREATE TABLE VMSCMS.CMS_DELUSER_MAST
(
  CDM_ROWID            NUMBER(10),
  CDM_FLAG             CHAR(1 BYTE)             DEFAULT 'N',
  CDM_USER_PIN         NUMBER(5),
  CDM_USER_CODE        VARCHAR2(15 BYTE),
  CDM_USER_NAME        VARCHAR2(50 BYTE),
  CDM_MAKER_REMARKS    VARCHAR2(200 BYTE),
  CDM_MAKER_DATE       DATE,
  CDM_MAKER_USER       NUMBER(5),
  CDM_CHECKER_DATE     DATE,
  CDM_CHECKER_USER     NUMBER(5),
  CDM_CHECKER_REMARKS  VARCHAR2(200 BYTE),
  CDM_PSWD             VARCHAR2(100 BYTE),
  CDM_GROUP_CODE       VARCHAR2(100 BYTE),
  CDM_GROUP_DESC       VARCHAR2(100 BYTE),
  CDM_RESET_PSWD       VARCHAR2(1 BYTE),
  CDM_INST_CODE        NUMBER(3)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


