CREATE TABLE VMSCMS.CMS_RECON_REPORT
(
  CRR_MONTH_YEAR           VARCHAR2(10 BYTE),
  CRR_PREAUTH_CNT          NUMBER(10),
  CRR_PREAUTH_AMT          NUMBER(30,2),
  CRR_PREAUTH_FEE_CNT      NUMBER(10),
  CRR_PREAUTH_FEE_AMT      NUMBER(30,2),
  CRR_PURCHASE_CNT         NUMBER(10),
  CRR_PURCHASE_AMT         NUMBER(30,2),
  CRR_PURCHASE_FEE_CNT     NUMBER(10),
  CRR_PURCHASE_FEE_AMT     NUMBER(30,2),
  CRR_MERCHRETURN_CNT      NUMBER(10),
  CRR_MERCHRETURN_AMT      NUMBER(30,2),
  CRR_MERCHRETURN_FEE_CNT  NUMBER(10),
  CRR_MERCHRETURN_FEE_AMT  NUMBER(30,2),
  CRR_CASHBACK_CNT         NUMBER(10),
  CRR_CASHBACK_AMT         NUMBER(30,2),
  CRR_CASHBACK_FEE_CNT     NUMBER(10),
  CRR_CASHBACK_FEE_AMT     NUMBER(30,2),
  CRR_WITHDRAWAL_CNT       NUMBER(10),
  CRR_WITHDRAWAL_AMT       NUMBER(30,2),
  CRR_WITHDRAWAL_FEE_CNT   NUMBER(10),
  CRR_WITHDRAWAL_FEE_AMT   NUMBER(30,2),
  CRR_INS_USER             NUMBER(10),
  CRR_INS_DATE             DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


