CREATE TABLE VMSCMS.CMS_EMV_PARAM_TEMP
(
  CEP_INST_CODE    NUMBER(3)                    NOT NULL,
  CEP_ROWID        NUMBER(6)                    NOT NULL,
  CEP_INST_BIN     NUMBER(6)                    NOT NULL,
  CEP_PARAM_KEY    VARCHAR2(30 BYTE)            NOT NULL,
  CEP_PARAM_VALUE  VARCHAR2(50 BYTE)            NOT NULL,
  CEP_INS_USER     NUMBER(5)                    NOT NULL,
  CEP_INS_DATE     DATE                         NOT NULL,
  CEP_LUPD_USER    NUMBER(5)                    NOT NULL,
  CEP_LUPD_DATE    DATE                         NOT NULL,
  CEP_PEND_FLAG    CHAR(1 BYTE)                 DEFAULT 'N'
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_EMV_PARAM_TEMP ADD (
  CONSTRAINT CMS_EMV_PARAM_TEMP_PK
 PRIMARY KEY
 (CEP_INST_CODE, CEP_ROWID, CEP_INST_BIN))
/

