CREATE TABLE VMSCMS.CMS_TOBEAPPRV_PANS
(
  CTP_INST_CODE  NUMBER(3)                      NOT NULL,
  CTP_FILE_NAME  VARCHAR2(45 BYTE)              NOT NULL,
  CTP_APPL_CODE  VARCHAR2(14 BYTE)              NOT NULL,
  CTP_INS_DATE   DATE                           NOT NULL,
  CTP_LUPD_DATE  DATE,
  CTP_LUPD_USER  NUMBER(10),
  CTP_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


