CREATE TABLE VMSCMS.CMS_FUNC_MAST_CRCH
(
  CFM_INST_CODE            NUMBER(3),
  CFM_FUNC_CODE            VARCHAR2(18 BYTE),
  CFM_FUNC_DESC            VARCHAR2(50 BYTE),
  CFM_FUNCIDENTF1_RECTYPE  VARCHAR2(5 BYTE),
  CFM_FUNCIDENTF2_RESPCDE  VARCHAR2(9 BYTE),
  CFM_FUNCIDENTF3_T_CDE    VARCHAR2(2 BYTE),
  CFM_FUNCIDENTF4_RVSLRSN  VARCHAR2(5 BYTE),
  CFM_FUNCIDENTF5_INTFLAG  VARCHAR2(1 BYTE),
  CFM_FUNCIDENTF6_TMODE    NUMBER(3),
  CFM_INS_USER             NUMBER(5),
  CFM_INS_DATE             DATE,
  CFM_LUPD_USER            NUMBER(5),
  CFM_LUPD_DATE            DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


