CREATE TABLE VMSCMS.CMS_MERC_WALLET
(
  CMW_INST_CODE    NUMBER(10),
  CMW_ACCT_ID      NUMBER(10),
  CMW_PAN_NO       VARCHAR2(90 BYTE),
  CMW_BRAN_CODE    VARCHAR2(6 BYTE),
  CMW_INS_USER     NUMBER(10),
  CMW_INS_DATE     DATE,
  CMW_LUPD_USER    NUMBER(10),
  CMW_LUPS_DATE    DATE,
  CMW_PAN_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


