CREATE TABLE VMSCMS.CMS_CMF
(
  CMF_ID                    NUMBER,
  CMF_DATE                  DATE,
  ESIGN_INDI                CHAR(1 BYTE),
  RECORD_TYPE               CHAR(1 BYTE),
  ACCTCRTDT                 VARCHAR2(8 BYTE),
  EMAIL_ONE                 VARCHAR2(50 BYTE),
  UNIQUE_PROGRAM_ID         VARCHAR2(4 BYTE),
  CARDNO                    RAW(100),
  CARD_ISSUED_DT            VARCHAR2(8 BYTE),
  ACCOUNT_EXPIRATION_DT     CHAR(1 BYTE),
  SSN                       VARCHAR2(40 BYTE),
  CARD_HOLDER_FIRST_NAME    VARCHAR2(40 BYTE)   NOT NULL,
  CARD_HOLDER_LAST_NAME     VARCHAR2(40 BYTE),
  ADDR1                     VARCHAR2(50 BYTE)   NOT NULL,
  ADDR2                     VARCHAR2(50 BYTE),
  CITY                      VARCHAR2(40 BYTE)   NOT NULL,
  STATE                     VARCHAR2(3 BYTE),
  ZIP                       VARCHAR2(15 BYTE),
  CARD_MAILING_ADDR1        VARCHAR2(50 BYTE),
  CARD_MAILING_ADDR2        VARCHAR2(50 BYTE),
  CARD_MAILING_CITY         VARCHAR2(40 BYTE),
  CARD_MAILING_STATE        VARCHAR2(3 BYTE),
  CARD_MAILING_ZIP          VARCHAR2(15 BYTE),
  PRI_PHONE                 VARCHAR2(40 BYTE),
  SEC_PHONE                 VARCHAR2(40 BYTE),
  CARD_STATUS               VARCHAR2(2 BYTE),
  CARD_STATUS_DT            VARCHAR2(8 BYTE),
  CURR_BAL                  VARCHAR2(14 BYTE),
  CURR_BAL_SIGN             CHAR(1 BYTE),
  ACCOUNT_CREATED_DT        VARCHAR2(8 BYTE),
  CARD_ACTIVATION_DATE      VARCHAR2(8 BYTE),
  CARD_TRANSFER_NO_FROM     VARCHAR2(4000 BYTE),
  DT_OF_NEG_BAL             VARCHAR2(8 BYTE),
  NEG_BAL_PRINICIPLE_AMT    VARCHAR2(14 BYTE),
  NEG_BAL_FEE_AMT           VARCHAR2(14 BYTE),
  RELOAD_INDICATOR          NUMBER,
  ACCOUNT_NO                VARCHAR2(20 BYTE),
  TYPE_OF_CARD              VARCHAR2(30 BYTE),
  AUTHENTICATION_TYP        CHAR(3 BYTE),
  ENROLL_NO                 CHAR(1 BYTE),
  ACCOUNT_STAT              VARCHAR2(22 BYTE),
  ACCOUNT_STAT_DT           CHAR(1 BYTE),
  ACCOUNT_TRANSFER_NO_FROM  CHAR(1 BYTE),
  ACCOUNT_TRANSFER_TO       CHAR(1 BYTE),
  DOB                       VARCHAR2(8 BYTE),
  AVAIL_BAL                 VARCHAR2(14 BYTE),
  AVAIL_BAL_SIGN            CHAR(1 BYTE),
  PRI_CARD                  VARCHAR2(1 BYTE),
  CARD_EXPIRY_DT            VARCHAR2(8 BYTE),
  CARD_TRANSFER_NO_TO       VARCHAR2(4000 BYTE),
  FIRST_LOAD_DT             VARCHAR2(8 BYTE),
  LAST_TXN_DT               VARCHAR2(8 BYTE),
  LAST_REISUED_DT           VARCHAR2(8 BYTE),
  CRD_FIRST_MAILED_DT       VARCHAR2(8 BYTE),
  CRD_LAST_MAILED_DT        VARCHAR2(8 BYTE),
  NO_OF_PLASTICS            NUMBER,
  ALT_ID_TYP                VARCHAR2(40 BYTE),
  ALT_ID_VAL                VARCHAR2(40 BYTE),
  RANKS                     NUMBER,
  PROXY_NUMBER              VARCHAR2(20 BYTE),
  FEE_PLAN_ID               NUMBER(4),
  PROD_CODE                 VARCHAR2(6 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CMF ADD (
  CONSTRAINT PK_CMS_CMF
 PRIMARY KEY
 (CMF_ID, CMF_DATE, ACCOUNT_NO))
/

