CREATE TABLE VMSCMS.CMS_STATMENT_LOG
(
  CSL_PAN_NO            VARCHAR2(90 BYTE),
  CSL_OPENING_BAL       VARCHAR2(20 BYTE),
  CSL_TRANS_AMOUNT      VARCHAR2(10 BYTE),
  CSL_TRANS_TYPE        VARCHAR2(3 BYTE),
  CSL_TRANS_DATE        DATE,
  CSL_CLOSING_BALANCE   VARCHAR2(20 BYTE),
  CSL_TRANS_NARRRATION  VARCHAR2(30 BYTE),
  CSL_LUPD_DATE         DATE,
  CSL_INST_CODE         NUMBER(10),
  CSL_LUPD_USER         NUMBER(10),
  CSL_INS_DATE          DATE,
  CSL_INS_USER          NUMBER(10),
  CSL_PAN_NO_ENCR       RAW(100)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


