CREATE TABLE VMSCMS.CMS_REISSUE_OLDCARDSTAT
(
  CRO_INST_CODE             NUMBER(5),
  CRO_OLDCARD_STAT          CHAR(1 BYTE),
  CRO_OLDCARD_REISSUE_STAT  CHAR(1 BYTE),
  CRO_SPPRT_KEY             VARCHAR2(10 BYTE),
  CRO_PROD_CATG             CHAR(1 BYTE),
  CRO_INS_USER              NUMBER(5),
  CRO_INST_DATE             DATE,
  CRO_LUPD_USER             NUMBER(5),
  CRO_LUPD_DATE             DATE
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


