CREATE TABLE VMSCMS.CMS_SSN_CARDSTAT
(
  CSC_INST_CODE  NUMBER(3),
  CSC_CARD_STAT  VARCHAR2(2 BYTE),
  CSC_STAT_DESC  VARCHAR2(30 BYTE),
  CSC_STAT_FLAG  VARCHAR2(1 BYTE),
  CSC_INS_USER   NUMBER(5)                      NOT NULL,
  CSC_INS_DATE   DATE                           NOT NULL,
  CSC_LUPD_USER  NUMBER(5)                      NOT NULL,
  CSC_LUPD_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SSN_CARDSTAT ADD (
  CONSTRAINT PK_SSN_CARDSTAT
 PRIMARY KEY
 (CSC_INST_CODE, CSC_CARD_STAT))
/

