CREATE TABLE VMSCMS.CMS_MENUFILE_CREATION_STATUS
(
  CMC_PHYSICAL_SERVER     VARCHAR2(75 BYTE),
  CMC_MANAGED_SERVER      VARCHAR2(50 BYTE),
  CMC_FILETOBE_GENERATED  VARCHAR2(1 BYTE),
  CMC_INS_DATE            DATE,
  CMC_INS_USER            NUMBER(5),
  CMC_LUPD_USER           NUMBER(5),
  CMC_LUPD_DATE           DATE,
  CMC_LISTEN_PORT         NUMBER(4)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


