CREATE TABLE VMSCMS.CMS_LAST_PTLF_EXTR_DATE
(
  CLP_LAST_EXTR_DATE   DATE,
  CLP_FTPTLF_DATETIME  VARCHAR2(26 BYTE),
  CLP_INS_DATE         DATE,
  CLP_INS_USER         NUMBER(5)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


