CREATE TABLE VMSCMS.CMS_DFG_PARAM_LYFEHOST
(
  CDP_INST_CODE       NUMBER(3)                 NOT NULL,
  CDP_PARAM_KEY       VARCHAR2(30 BYTE)         NOT NULL,
  CDP_PARAM_VALUE     VARCHAR2(15 BYTE)         NOT NULL,
  CDP_INST_USER       NUMBER(5)                 NOT NULL,
  CDP_INS_DATE        DATE                      NOT NULL,
  CDP_LUPD_USER       NUMBER(5)                 NOT NULL,
  CDP_LUPD_DATE       DATE                      NOT NULL,
  CDP_MANDARORY_FLAG  VARCHAR2(1 BYTE)          NOT NULL,
  CDP_PROD_CODE       VARCHAR2(6 BYTE)
)
TABLESPACE CMS_BKUP
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


