CREATE TABLE VMSCMS.CMS_CURR_MAST_MCURR
(
  CCM_CURR_CODE        VARCHAR2(4 BYTE)         NOT NULL,
  CCM_INST_CODE        NUMBER(10)               NOT NULL,
  CCM_ACQ_CURR_FLAG    CHAR(1 BYTE),
  CCM_PAY_CURR_FLAG    CHAR(1 BYTE),
  CCM_SETTL_CURR_FLAG  CHAR(1 BYTE),
  CCM_CURR_EXP         NUMBER(10),
  CCM_ROUND_FACTOR     NUMBER(9,2),
  CCM_LAST_USER        NUMBER(10),
  CCM_LAST_DATE        DATE,
  CCM_MAJOR_CURR       CHAR(1 BYTE),
  CCM_LUPD_DATE        DATE,
  CCM_LUPD_USER        NUMBER(10),
  CCM_INS_DATE         DATE,
  CCM_INS_USER         NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CURR_MAST_MCURR ADD (
  CONSTRAINT PK_CURR_MAST_MCURR2
 PRIMARY KEY
 (CCM_CURR_CODE, CCM_INST_CODE))
/

