CREATE TABLE VMSCMS.CMS_DEK_KEY_DETAIL
(
  CDK_INST_CODE      NUMBER(3)                  NOT NULL,
  CDK_KEK_INDEX      VARCHAR2(200 BYTE),
  CDK_DEK_INDEX      VARCHAR2(3 BYTE),
  CDK_DEK_NAME       VARCHAR2(200 BYTE)         NOT NULL,
  CDK_ENCRYPTED_DEK  VARCHAR2(200 BYTE)         NOT NULL,
  CDK_INS_USER       NUMBER(5),
  CDK_INS_DATE       DATE,
  CDK_LUPD_USER      NUMBER(5),
  CDK_LUPD_DATE      DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_DEK_KEY_DETAIL ADD (
  CONSTRAINT PK_DEK_KEY_DETAIL
 PRIMARY KEY
 (CDK_DEK_INDEX),
  CONSTRAINT UK_DEK_KEY_DETAIL
 UNIQUE (CDK_INST_CODE, CDK_DEK_NAME))
/

ALTER TABLE VMSCMS.CMS_DEK_KEY_DETAIL ADD (
  CONSTRAINT FK_DEK_KEY_DETAIL 
 FOREIGN KEY (CDK_KEK_INDEX) 
 REFERENCES VMSCMS.CMS_KEK_KEY_DETAIL (CKK_KEK_INDEX))
/

