CREATE TABLE VMSCMS.CMS_RENEWAL_LOG
(
  CRL_INST_CODE      NUMBER(3),
  CRL_INS_USER       NUMBER(5),
  CRL_INS_DATE       DATE,
  CRL_LUPD_USER      NUMBER(5),
  CRL_LUPD_DATE      DATE,
  CRL_FLAG           CHAR(1 BYTE),
  CRL_ROW_ID         NUMBER(10),
  CRL_REMARKS        VARCHAR2(50 BYTE),
  CRL_BIN_LIST       VARCHAR2(500 BYTE),
  CRL_FROM_BRANCODE  VARCHAR2(50 BYTE),
  CRL_TO_BRANCODE    VARCHAR2(300 BYTE),
  CRL_LOCN_CODE      NUMBER(5),
  CRL_FOR_DATE       DATE,
  CRL_BINLIST_MOD    VARCHAR2(500 BYTE),
  CRL_FOR_DAY        NUMBER(10),
  CRL_FOR_MONTH      NUMBER(10),
  CRL_FOR_YEAR       NUMBER(10),
  CRL_REGION         VARCHAR2(20 BYTE),
  CRL_REGION_NAME    VARCHAR2(20 BYTE),
  CRL_CHECKER_RMKS   VARCHAR2(500 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


