CREATE TABLE VMSCMS.CMS_SMS_ALERT_MESSAGE_FORMAT
(
  CSF_INST_CODE          NUMBER(10),
  CSF_ALERT_TYPE         VARCHAR2(50 BYTE),
  CSF_MSG_FORMAT         VARCHAR2(1000 BYTE),
  CSF_INS_USER           NUMBER(5),
  CSF_INS_DATE           DATE,
  CSF_LUPD_USER          NUMBER(5),
  CSF_LUPD_DATE          DATE,
  CSF_CONFIGURED_TOKENS  VARCHAR2(500 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SMS_ALERT_MESSAGE_FORMAT ADD (
  CONSTRAINT PK_INST_ALERT
 PRIMARY KEY
 (CSF_INST_CODE, CSF_ALERT_TYPE))
/

