CREATE TABLE VMSCMS.CMS_TARGETMERCH_MAST_HIST
(
  CTM_MERCHANT_NAME  VARCHAR2(50 BYTE),
  CTM_INST_CODE      NUMBER(3),
  CTM_INS_DATE       DATE,
  CTM_INS_USER       NUMBER(10),
  CTM_LUPD_USER      NUMBER(10),
  CTM_LUPD_DATE      DATE
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


