CREATE TABLE VMSCMS.CMS_GROUP_DEBLOCK
(
  CGD_PAN_CODE       VARCHAR2(90 BYTE),
  CGD_PIN_DEBLOCK    VARCHAR2(1 BYTE)           DEFAULT 'N',
  CGD_FILE_NAME      VARCHAR2(30 BYTE),
  CGD_REMARK         VARCHAR2(100 BYTE),
  CGD_RESULT         VARCHAR2(500 BYTE)         DEFAULT 'NOT PROCESSED',
  CGD_MBR_NUMB       VARCHAR2(3 BYTE)           DEFAULT '000',
  CGD_INS_DATE       DATE,
  CGD_LUPD_DATE      DATE,
  CGD_INST_CODE      NUMBER(10),
  CGD_LUPD_USER      NUMBER(10),
  CGD_INS_USER       NUMBER(10),
  CGD_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


