CREATE TABLE VMSCMS.CMS_TRANSACTION_SUMMARY
(
  CTS_TRAN_DATE      DATE,
  CTS_TRAN_HEAD      VARCHAR2(9 BYTE),
  CTS_GL_CATGCODE    NUMBER(2),
  CTS_GL_CODE        VARCHAR2(15 BYTE),
  CTS_SUBGL_CODE     VARCHAR2(15 BYTE),
  CTS_SUBGL_BALANCE  NUMBER,
  CTS_LUPD_DATE      DATE,
  CTS_INST_CODE      NUMBER(10),
  CTS_LUPD_USER      NUMBER(10),
  CTS_INS_DATE       DATE,
  CTS_INS_USER       NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_TRANSACTION_SUMMARY ADD (
  CONSTRAINT FK_GLMAST_GLCODE 
 FOREIGN KEY (CTS_GL_CODE) 
 REFERENCES VMSCMS.CMS_GL_MAST (CGM_GL_CODE))
/

