CREATE TABLE VMSCMS.CMS_EMV_PARAM
(
  CEP_INST_CODE    NUMBER(3)                    NOT NULL,
  CEP_PARAM_KEY    VARCHAR2(30 BYTE)            NOT NULL,
  CEP_PARAM_DESC   VARCHAR2(50 BYTE)            NOT NULL,
  CEP_PARAM_VALUE  VARCHAR2(50 BYTE)            NOT NULL,
  CEP_PARAM_TYPE   VARCHAR2(1 BYTE)             NOT NULL,
  CEP_INS_USER     NUMBER(5)                    NOT NULL,
  CEP_INS_DATE     DATE                         NOT NULL,
  CEP_LUPD_USER    NUMBER(5)                    NOT NULL,
  CEP_LUPD_DATE    DATE                         NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_EMV_PARAM ADD (
  CONSTRAINT PK_CEP_PARAM_KEY
 PRIMARY KEY
 (CEP_INST_CODE, CEP_PARAM_KEY))
/

