CREATE TABLE VMSCMS.CMS_INST_PARAM_PROD
(
  CIP_INST_CODE        NUMBER(3)                NOT NULL,
  CIP_PARAM_KEY        VARCHAR2(50 BYTE)        NOT NULL,
  CIP_PARAM_DESC       VARCHAR2(50 BYTE)        NOT NULL,
  CIP_PARAM_VALUE      VARCHAR2(15 BYTE)        NOT NULL,
  CIP_INS_USER         NUMBER(5)                NOT NULL,
  CIP_INS_DATE         DATE                     NOT NULL,
  CIP_LUPD_USER        NUMBER(5)                NOT NULL,
  CIP_LUPD_DATE        DATE                     NOT NULL,
  CIP_ALLOWED_VALUES   VARCHAR2(100 BYTE),
  CIP_MANDATORY_FLAG   VARCHAR2(1 BYTE),
  CIP_DISPLAY_FLAG     VARCHAR2(1 BYTE),
  CIP_PARAM_UNIT       VARCHAR2(15 BYTE),
  CIP_PARAM_DISP_TYPE  VARCHAR2(15 BYTE),
  CIP_MULTILING_DESC   VARCHAR2(50 BYTE),
  CIP_VALIDATION_TYPE  VARCHAR2(2 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


