CREATE TABLE VMSCMS.CMS_BRANCH_CATG
(
  CBC_CATG_CODE      VARCHAR2(5 BYTE),
  CBC_CATG_DESC      VARCHAR2(30 BYTE),
  CBC_LUPD_DATE      DATE,
  CBC_INST_CODE      NUMBER(10),
  CBC_LUPD_USER      NUMBER(10),
  CBC_INS_DATE       DATE,
  CBC_INS_USER       NUMBER(10),
  CBC_CATG_FOR_PROD  VARCHAR2(3 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BRANCH_CATG ADD (
  CONSTRAINT PK_BRANCHCATG_MAST
 PRIMARY KEY
 (CBC_INST_CODE, CBC_CATG_CODE))
/

