CREATE TABLE VMSCMS.CMS_PROC_CTRL
(
  CPC_PROC_NAME        VARCHAR2(20 BYTE)        NOT NULL,
  CPC_LAST_RUNFORDATE  DATE                     NOT NULL,
  CPC_LAST_RUNDATE     DATE                     NOT NULL,
  CPC_SUCC_FLAG        CHAR(1 BYTE)             NOT NULL,
  CPC_LUPD_DATE        DATE,
  CPC_INST_CODE        NUMBER(10),
  CPC_LUPD_USER        NUMBER(10),
  CPC_INS_DATE         DATE,
  CPC_INS_USER         NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


