CREATE TABLE VMSCMS.CMS_CILS_LOYL
(
  CCL_INST_CODE   NUMBER(3)                     NOT NULL,
  CCL_LOYL_CODE   NUMBER(3)                     NOT NULL,
  CCL_LOYL_POINT  NUMBER(1)                     NOT NULL,
  CCL_INS_USER    NUMBER(5)                     NOT NULL,
  CCL_INS_DATE    DATE                          NOT NULL,
  CCL_LUPD_USER   NUMBER(5)                     NOT NULL,
  CCL_LUPD_DATE   DATE                          NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CILS_LOYL ADD (
  CONSTRAINT PK_CILS_LOYL
 PRIMARY KEY
 (CCL_INST_CODE, CCL_LOYL_CODE))
/

ALTER TABLE VMSCMS.CMS_CILS_LOYL ADD (
  CONSTRAINT FK_CILSLOYL_LOYLMAST 
 FOREIGN KEY (CCL_INST_CODE, CCL_LOYL_CODE) 
 REFERENCES VMSCMS.CMS_LOYL_MAST (CLM_INST_CODE,CLM_LOYL_CODE),
  CONSTRAINT FK_CILSLOYL_USERMAST1 
 FOREIGN KEY (CCL_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CILSLOYL_USERMAST2 
 FOREIGN KEY (CCL_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

