CREATE TABLE VMSCMS.CMS_MAIL_NOTIFICATION
(
  CMN_PROCESS_ID    VARCHAR2(5 BYTE),
  CMN_PROCESS_DESC  VARCHAR2(30 BYTE),
  CMN_ADMIN1_NAME   VARCHAR2(50 BYTE),
  CMN_ADMIN1_MAIL   VARCHAR2(50 BYTE),
  CMN_ADMIN2_NAME   VARCHAR2(50 BYTE),
  CMN_ADMIN2_MAIL   VARCHAR2(50 BYTE),
  CMN_INS_USER      NUMBER(5),
  CMN_INS_DATE      DATE,
  CMN_LUPD_USER     NUMBER(5),
  CMN_LUPD_DATE     DATE,
  CMN_INST_CODE     NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MAIL_NOTIFICATION ADD (
  CONSTRAINT PK_CMS_MAIL_NOTIFICATION
 PRIMARY KEY
 (CMN_PROCESS_ID))
/

