CREATE TABLE VMSCMS.CMS_EXPCRD_ERRLOG
(
  CEE_PAN_CODE       VARCHAR2(90 BYTE),
  CEE_ERR_MSG        VARCHAR2(200 BYTE),
  CEE_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


