CREATE TABLE VMSCMS.CMS_OP_FILE_FOOTER_MAST
(
  COM_FILE_ID      NUMBER(20),
  COM_CTRL_ID      NUMBER(2),
  COM_CTRL_TYPE    VARCHAR2(20 BYTE),
  COM_FRM_TO_POSN  NUMBER(10),
  COM_COLN_POSN    NUMBER(10),
  COM_DATA_FIELD   NUMBER(10),
  COM_LUPD_DATE    DATE,
  COM_INST_CODE    NUMBER(10),
  COM_LUPD_USER    NUMBER(10),
  COM_INS_DATE     DATE,
  COM_INS_USER     NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_OP_FILE_FOOTER_MAST ADD (
  CONSTRAINT PK_OP_FILE_FOOT_ID
 PRIMARY KEY
 (COM_FILE_ID, COM_CTRL_ID))
/

ALTER TABLE VMSCMS.CMS_OP_FILE_FOOTER_MAST ADD (
  CONSTRAINT FK_OP_FILE_FOOT_FILE_ID 
 FOREIGN KEY (COM_FILE_ID) 
 REFERENCES VMSCMS.CMS_OP_FILE_DEFN_MAST (COM_FILE_ID))
/

