CREATE TABLE VMSCMS.CMS_PARTACQ_MAST
(
  RAM_PART_CODE    NUMBER(3)                    NOT NULL,
  RAM_ACQ_CODE     VARCHAR2(16 BYTE)            NOT NULL,
  RAM_LUPD_USER    NUMBER(5)                    NOT NULL,
  RAM_LUPD_DATE    DATE                         NOT NULL,
  RAM_INTERCHANGE  CHAR(1 BYTE)                 NOT NULL,
  RAM_INST_CODE    NUMBER(10),
  RAM_INS_DATE     DATE,
  RAM_INS_USER     NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PARTACQ_MAST ADD (
  CONSTRAINT PK_PARTACQ_MAST
 PRIMARY KEY
 (RAM_PART_CODE, RAM_ACQ_CODE),
  CONSTRAINT UK_PARTACQ_MAST
 UNIQUE (RAM_ACQ_CODE))
/

