CREATE TABLE VMSCMS.CMS_CARD_EXCPFEE
(
  CCE_INST_CODE          NUMBER(3)              NOT NULL,
  CCE_FEE_CODE           NUMBER(3),
  CCE_PAN_CODE           VARCHAR2(90 BYTE)      NOT NULL,
  CCE_MBR_NUMB           VARCHAR2(3 BYTE)       DEFAULT '000'                 NOT NULL,
  CCE_VALID_FROM         DATE                   NOT NULL,
  CCE_VALID_TO           DATE,
  CCE_FLOW_SOURCE        VARCHAR2(3 BYTE)       NOT NULL,
  CCE_INS_USER           NUMBER(5)              NOT NULL,
  CCE_INS_DATE           DATE                   NOT NULL,
  CCE_LUPD_USER          NUMBER(5)              NOT NULL,
  CCE_LUPD_DATE          DATE                   NOT NULL,
  CCE_CRGL_CODE          VARCHAR2(20 BYTE),
  CCE_CRSUBGL_CODE       VARCHAR2(20 BYTE),
  CCE_CRACCT_NO          VARCHAR2(20 BYTE),
  CCE_DRGL_CATG          VARCHAR2(20 BYTE),
  CCE_DRGL_CODE          VARCHAR2(20 BYTE),
  CCE_DRSUBGL_CODE       VARCHAR2(20 BYTE),
  CCE_DRACCT_NO          VARCHAR2(20 BYTE),
  CCE_CRGL_CATG          VARCHAR2(20 BYTE),
  CCE_ST_CRGL_CATG       VARCHAR2(20 BYTE),
  CCE_ST_CRGL_CODE       VARCHAR2(20 BYTE),
  CCE_ST_CRSUBGL_CODE    VARCHAR2(20 BYTE),
  CCE_ST_CRACCT_NO       VARCHAR2(20 BYTE),
  CCE_ST_DRGL_CATG       VARCHAR2(20 BYTE),
  CCE_ST_DRGL_CODE       VARCHAR2(20 BYTE),
  CCE_ST_DRSUBGL_CODE    VARCHAR2(20 BYTE),
  CCE_ST_DRACCT_NO       VARCHAR2(20 BYTE),
  CCE_CESS_CRGL_CATG     VARCHAR2(20 BYTE),
  CCE_CESS_CRGL_CODE     VARCHAR2(20 BYTE),
  CCE_CESS_CRSUBGL_CODE  VARCHAR2(20 BYTE),
  CCE_CESS_CRACCT_NO     VARCHAR2(20 BYTE),
  CCE_CESS_DRGL_CATG     VARCHAR2(20 BYTE),
  CCE_CESS_DRGL_CODE     VARCHAR2(20 BYTE),
  CCE_CESS_DRSUBGL_CODE  VARCHAR2(20 BYTE),
  CCE_CESS_DRACCT_NO     VARCHAR2(20 BYTE),
  CCE_ST_CALC_FLAG       NUMBER(1),
  CCE_CESS_CALC_FLAG     NUMBER(1),
  CCE_FEE_TYPE           NUMBER(5),
  CCE_CARDFEE_ID         NUMBER                 NOT NULL,
  CCE_PAN_CODE_ENCR      RAW(100),
  CCE_TRAN_CODE          VARCHAR2(10 BYTE),
  CCE_FEE_PLAN           NUMBER(4)              NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CARD_EXCPFEE ADD (
  CONSTRAINT UK_CARD_EXCPFEE1
 UNIQUE (CCE_CARDFEE_ID))
/

ALTER TABLE VMSCMS.CMS_CARD_EXCPFEE ADD (
  CONSTRAINT FK_CARDEXCPFEE_USERMAST2 
 FOREIGN KEY (CCE_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CARDEXCPFEE_USERMAST1 
 FOREIGN KEY (CCE_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CARDEXCPFEE_FEEMAST 
 FOREIGN KEY (CCE_INST_CODE, CCE_FEE_CODE) 
 REFERENCES VMSCMS.CMS_FEE_MAST (CFM_INST_CODE,CFM_FEE_CODE),
  CONSTRAINT FK_CARDEXCPFEE_FEETYPE 
 FOREIGN KEY (CCE_INST_CODE, CCE_FEE_TYPE) 
 REFERENCES VMSCMS.CMS_FEE_TYPES (CFT_INST_CODE,CFT_FEETYPE_CODE),
  CONSTRAINT FK_CARDEXCPFEE_APPLPAN 
 FOREIGN KEY (CCE_PAN_CODE, CCE_MBR_NUMB) 
 REFERENCES VMSCMS.CMS_APPL_PAN (CAP_PAN_CODE,CAP_MBR_NUMB))
/

