CREATE TABLE VMSCMS.CMS_LIMIT_PRFL_HIST
(
  CLP_INST_CODE       NUMBER(10),
  CLP_LMTPRFL_ID      VARCHAR2(10 BYTE),
  CLP_DLVR_CHNL       VARCHAR2(2 BYTE),
  CLP_TRAN_CODE       VARCHAR2(2 BYTE),
  CLP_TRAN_TYPE       VARCHAR2(1 BYTE),
  CLP_INTL_FLAG       CHAR(2 BYTE),
  CLP_PNSIGN_FLAG     CHAR(2 BYTE),
  CLP_MCC_CODE        VARCHAR2(4 BYTE),
  CLP_PERTXN_MINAMNT  NUMBER(20),
  CLP_PERTXN_MAXAMNT  NUMBER(20),
  CLP_DMAX_TXNCNT     NUMBER(20),
  CLP_DMAX_TXNAMNT    NUMBER(20),
  CLP_WMAX_TXNCNT     NUMBER(20),
  CLP_WMAX_TXNAMNT    NUMBER(20),
  CLP_MMAX_TXNCNT     NUMBER(20),
  CLP_MMAX_TXNAMNT    NUMBER(20),
  CLP_YMAX_TXNCNT     NUMBER(20),
  CLP_YMAX_TXNAMNT    NUMBER(20),
  CLP_COMB_HASH       VARCHAR2(90 BYTE),
  CLP_TRFR_CRDACNT    CHAR(2 BYTE),
  CLP_LUPD_DATE       DATE,
  CLP_LUPD_USER       NUMBER(10),
  CLP_ORGINS_USER     NUMBER(10),
  CLP_ORGINS_DATE     DATE,
  CLP_INS_DATE        DATE
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


