CREATE TABLE VMSCMS.CMS_IDTYPE_MAST
(
  CIM_INST_CODE    NUMBER(3),
  CIM_IDTYPE_CODE  VARCHAR2(5 BYTE),
  CIM_IDTYPE_DESC  VARCHAR2(30 BYTE)            NOT NULL,
  CSC_INS_USER     NUMBER(5)                    NOT NULL,
  CSC_INS_DATE     DATE                         NOT NULL,
  CSC_LUPD_USER    NUMBER(5)                    NOT NULL,
  CSC_LUPD_DATE    DATE                         NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_IDTYPE_MAST ADD (
  CONSTRAINT PK_IDTYPE_MAST
 PRIMARY KEY
 (CIM_INST_CODE, CIM_IDTYPE_CODE))
/

