CREATE TABLE VMSCMS.CMS_CARDISSUE_STATCHANGE_HIST
(
  CCH_INST_CODE      NUMBER(3),
  CCH_PAN_CODE       VARCHAR2(90 BYTE),
  CCH_CARD_STATUS    VARCHAR2(2 BYTE),
  CCH_INS_USER       NUMBER(5),
  CCH_INS_DATE       DATE,
  CCH_LUPD_USER      NUMBER(5),
  CCH_LUPD_DATE      DATE,
  CCH_PAN_CODE_ENCR  VARCHAR2(100 BYTE),
  CCH_CCF_FNAME      VARCHAR2(50 BYTE)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CARDISSUE_STATCHANGE_HIST ADD (
  CONSTRAINT FK_CARDSTATUSMAST_STATHIST 
 FOREIGN KEY (CCH_CARD_STATUS) 
 REFERENCES VMSCMS.CMS_CARDISSUANCE_STATUS_MAST (CCM_STATUS_CODE))
/

