CREATE TABLE VMSCMS.CMS_PIN_CTRL
(
  CPC_INST_CODE  NUMBER(3)                      NOT NULL,
  CPC_PIN_FNAME  VARCHAR2(30 BYTE)              NOT NULL,
  CPC_INS_USER   NUMBER(5)                      NOT NULL,
  CPC_INS_DATE   DATE                           NOT NULL,
  CPC_LUPD_USER  NUMBER(5)                      NOT NULL,
  CPC_LUPD_DATE  DATE                           NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PIN_CTRL ADD (
  CONSTRAINT PK_PIN_CTRL
 PRIMARY KEY
 (CPC_INST_CODE, CPC_PIN_FNAME))
/

