CREATE TABLE VMSCMS.CMS_BIN_LEVEL_CONFIG
(
  CBL_INST_CODE            NUMBER(3)            NOT NULL,
  CBL_INST_BIN             NUMBER(10)           NOT NULL,
  CBL_ADDR_VER_CHECK       CHAR(1 BYTE),
  CBL_INTERNATIONAL_CHECK  CHAR(1 BYTE),
  CBL_INS_USER             NUMBER(5)            NOT NULL,
  CBL_INS_DATE             DATE                 NOT NULL,
  CBL_LUPD_USER            NUMBER(5),
  CBL_LUPD_DATE            DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BIN_LEVEL_CONFIG ADD (
  CONSTRAINT PK_BIN_LEVEL_CONFIG
 PRIMARY KEY
 (CBL_INST_CODE, CBL_INST_BIN))
/

ALTER TABLE VMSCMS.CMS_BIN_LEVEL_CONFIG ADD (
  CONSTRAINT FK_BIN_LEVEL_CONFIG_INSTMAST 
 FOREIGN KEY (CBL_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

