CREATE TABLE VMSCMS.CMS_PROD_THRESHOLD
(
  CPT_INST_CODE       NUMBER(3),
  CPT_PROD_CODE       VARCHAR2(6 BYTE),
  CPT_PROD_THRESHOLD  NUMBER(3)                 NOT NULL,
  CPT_INS_USER        NUMBER(5)                 NOT NULL,
  CPT_INS_DATE        DATE                      NOT NULL,
  CPT_LUPD_USER       NUMBER(5)                 NOT NULL,
  CPT_LUPD_DATE       DATE                      NOT NULL
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROD_THRESHOLD ADD (
  CONSTRAINT PK_THRESHOLD_PROD
 PRIMARY KEY
 (CPT_INST_CODE, CPT_PROD_CODE))
/

ALTER TABLE VMSCMS.CMS_PROD_THRESHOLD ADD (
  CONSTRAINT FK_THRESHOLD_PROD 
 FOREIGN KEY (CPT_INST_CODE, CPT_PROD_CODE) 
 REFERENCES VMSCMS.CMS_PROD_MAST (CPM_INST_CODE,CPM_PROD_CODE),
  CONSTRAINT FK_CPT_INS_USER 
 FOREIGN KEY (CPT_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CPT_LUPD_USER 
 FOREIGN KEY (CPT_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

