CREATE TABLE VMSCMS.CMS_USER_REPORT_TEMP
(
  CUR_USER_ID      NUMBER(5),
  CUR_REPORT_ID    NUMBER(4),
  CUR_FIELD_ID     VARCHAR2(20 BYTE),
  CUR_FIELD_POSN   NUMBER(3),
  CUR_INS_USER     NUMBER(5),
  CUR_INS_DATE     DATE,
  CUR_GROUP_ID     NUMBER(5),
  CUR_STATUS_CODE  CHAR(1 BYTE),
  CUR_LUPD_DATE    DATE,
  CUR_INST_CODE    NUMBER(10),
  CUR_LUPD_USER    NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


