CREATE TABLE VMSCMS.CMS_GL_ACCT_MAST_ORGNL
(
  CGA_INST_CODE    NUMBER(3),
  CGA_GLCATG_CODE  NUMBER(2)                    NOT NULL,
  CGA_GL_CODE      VARCHAR2(20 BYTE)            NOT NULL,
  CGA_SUBGL_CODE   VARCHAR2(20 BYTE)            NOT NULL,
  CGA_ACCT_CODE    VARCHAR2(20 BYTE)            NOT NULL,
  CGA_ACCT_DESC    VARCHAR2(50 BYTE),
  CGA_TRAN_AMT     NUMBER(20),
  CGA_INS_DATE     DATE,
  CGA_LUPD_USER    NUMBER(5),
  CGA_LUPD_DATE    DATE,
  CGA_INS_USER     NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


