CREATE TABLE VMSCMS.CMS_CALLCENTER_USER
(
  CCU_USER_NAME       VARCHAR2(50 BYTE)         NOT NULL,
  CCU_USER_CODE       VARCHAR2(15 BYTE)         NOT NULL,
  CCU_USER_PSWD       VARCHAR2(100 BYTE)        NOT NULL,
  CCU_VALID_FRDT      DATE,
  CCU_VALID_TODT      DATE,
  CCU_USER_STAT       CHAR(1 BYTE),
  CCU_INS_USER        NUMBER(5)                 NOT NULL,
  CCU_INS_DATE        DATE                      NOT NULL,
  CCU_LUPD_USER       NUMBER(5)                 NOT NULL,
  CCU_LUPD_DATE       DATE                      NOT NULL,
  CCU_LAST_LOGINTIME  DATE                      NOT NULL,
  CCU_INST_CODE       NUMBER(10),
  CCU_PSWD_DATE       DATE,
  CCU_EMAIL_ID        VARCHAR2(50 BYTE),
  CCU_CALLCENTER_ID   VARCHAR2(20 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CALLCENTER_USER ADD (
  CONSTRAINT PK_CALLCENTERUSER_USER_CODE
 PRIMARY KEY
 (CCU_USER_CODE))
/

