CREATE TABLE VMSCMS.CMS_DEHOTLIST_DETAIL
(
  CDD_INST_CODE     NUMBER(3),
  CDD_CARD_NO       VARCHAR2(90 BYTE),
  CDD_FILE_NAME     VARCHAR2(30 BYTE),
  CDD_REMARKS       VARCHAR2(100 BYTE),
  CDD_MSG24_FLAG    CHAR(1 BYTE)                DEFAULT 'N',
  CDD_PROCESS_FLAG  VARCHAR2(1 BYTE),
  CDD_PROCESS_MSG   VARCHAR2(300 BYTE),
  CDD_PROCESS_MODE  VARCHAR2(1 BYTE),
  CDD_INS_USER      NUMBER(5),
  CDD_INS_DATE      DATE,
  CDD_LUPD_USER     NUMBER(5),
  CDD_LUPD_DATE     DATE,
  CDD_CARD_NO_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


