CREATE TABLE VMSCMS.CMS_RAWFILE_HEADER
(
  CRH_RECORD_TYPE      VARCHAR2(6 BYTE),
  CRH_SETTLEMENT_DATE  VARCHAR2(8 BYTE)         NOT NULL,
  CRH_CREATION_DATE    VARCHAR2(8 BYTE),
  CRH_CREATION_TIME    VARCHAR2(6 BYTE),
  CRH_FILE_NAME        VARCHAR2(100 BYTE)       NOT NULL,
  CRH_INS_USER         NUMBER(5)                NOT NULL,
  CRH_INS_DATE         DATE                     NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


