CREATE TABLE VMSCMS.CMS_CARD_EXCPFEE_HIST
(
  CCE_INST_CODE          NUMBER(3)              NOT NULL,
  CCE_FEE_CODE           NUMBER(3),
  CCE_PAN_CODE           VARCHAR2(90 BYTE)      NOT NULL,
  CCE_MBR_NUMB           VARCHAR2(3 BYTE)       NOT NULL,
  CCE_VALID_FROM         DATE                   NOT NULL,
  CCE_VALID_TO           DATE,
  CCE_FLOW_SOURCE        VARCHAR2(3 BYTE)       NOT NULL,
  CCE_INS_USER           NUMBER(5)              NOT NULL,
  CCE_INS_DATE           DATE                   NOT NULL,
  CCE_LUPD_USER          NUMBER(5)              NOT NULL,
  CCE_LUPD_DATE          DATE                   NOT NULL,
  CCE_CRGL_CODE          VARCHAR2(20 BYTE),
  CCE_CRSUBGL_CODE       VARCHAR2(20 BYTE),
  CCE_CRACCT_NO          VARCHAR2(20 BYTE),
  CCE_DRGL_CATG          VARCHAR2(20 BYTE),
  CCE_DRGL_CODE          VARCHAR2(20 BYTE),
  CCE_DRSUBGL_CODE       VARCHAR2(15 BYTE),
  CCE_DRACCT_NO          VARCHAR2(20 BYTE),
  CCE_CRGL_CATG          VARCHAR2(20 BYTE),
  CCE_ST_CRGL_CATG       VARCHAR2(20 BYTE),
  CCE_ST_CRGL_CODE       VARCHAR2(20 BYTE),
  CCE_ST_CRSUBGL_CODE    VARCHAR2(20 BYTE),
  CCE_ST_CRACCT_NO       VARCHAR2(20 BYTE),
  CCE_ST_DRGL_CATG       VARCHAR2(20 BYTE),
  CCE_ST_DRGL_CODE       VARCHAR2(20 BYTE),
  CCE_ST_DRSUBGL_CODE    VARCHAR2(15 BYTE),
  CCE_ST_DRACCT_NO       VARCHAR2(20 BYTE),
  CCE_CESS_CRGL_CATG     VARCHAR2(20 BYTE),
  CCE_CESS_CRGL_CODE     VARCHAR2(20 BYTE),
  CCE_CESS_CRSUBGL_CODE  VARCHAR2(20 BYTE),
  CCE_CESS_CRACCT_NO     VARCHAR2(20 BYTE),
  CCE_CESS_DRGL_CATG     VARCHAR2(20 BYTE),
  CCE_CESS_DRGL_CODE     VARCHAR2(20 BYTE),
  CCE_CESS_DRSUBGL_CODE  VARCHAR2(20 BYTE),
  CCE_CESS_DRACCT_NO     VARCHAR2(20 BYTE),
  CCE_ST_CALC_FLAG       NUMBER(1),
  CCE_CESS_CALC_FLAG     NUMBER(1),
  CCE_FEE_TYPE           NUMBER(5),
  CCE_ACT_DATE           DATE,
  CCE_ACT_TYPE           VARCHAR2(2 BYTE),
  CCE_CARDFEE_ID         NUMBER(10)             NOT NULL,
  CCE_PAN_CODE_ENCR      RAW(100),
  CCE_FEE_PLAN           NUMBER(4)              NOT NULL
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


