CREATE TABLE VMSCMS.CMS_SLABLOYL_DTL
(
  CSD_INST_CODE   NUMBER(3),
  CSD_SLAB_CODE   NUMBER(3),
  CSD_FROM_AMT    NUMBER(15,6)                  NOT NULL,
  CSD_TO_AMT      NUMBER(15,6)                  NOT NULL,
  CSD_TRANS_AMT   NUMBER(15,6)                  NOT NULL,
  CSD_LOYL_POINT  NUMBER(1)                     NOT NULL,
  CSD_INS_USER    NUMBER(5)                     NOT NULL,
  CSD_INS_DATE    DATE                          NOT NULL,
  CSD_LUPD_USER   NUMBER(5)                     NOT NULL,
  CSD_LUPD_DATE   DATE                          NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_SLABLOYL_DTL ADD (
  CONSTRAINT FK_SLABLOYLDTL_USERMAST1 
 FOREIGN KEY (CSD_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_SLABLOYLDTL_USERMAST2 
 FOREIGN KEY (CSD_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_SLABLOYLDTL_SLABLOYL 
 FOREIGN KEY (CSD_INST_CODE, CSD_SLAB_CODE) 
 REFERENCES VMSCMS.CMS_SLAB_LOYL (CSL_INST_CODE,CSL_SLAB_CODE))
/

