CREATE TABLE VMSCMS.CMS_TMODE_DTL
(
  CTD_TRAN_CODE         VARCHAR2(2 BYTE),
  CTD_TRAN_DESC         VARCHAR2(90 BYTE),
  CTD_TRAN_ID           NUMBER,
  CTD_TRAN_TYPE         VARCHAR2(4 BYTE),
  CTD_TRANHEAD_FLAG     VARCHAR2(2 BYTE),
  CTD_LUPD_DATE         DATE,
  CTD_INST_CODE         NUMBER(10),
  CTD_LUPD_USER         NUMBER(10),
  CTD_INS_DATE          DATE,
  CTD_INS_USER          NUMBER(10),
  CTD_REVERSAL_CODE     NUMBER(3),
  CTD_MSG_TYPE          VARCHAR2(4 BYTE),
  CTD_DELIVERY_CHANNEL  VARCHAR2(2 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


