CREATE TABLE VMSCMS.CMS_CITY_LOYL
(
  CCL_INST_CODE   NUMBER(3)                     NOT NULL,
  CCL_LOYL_CODE   NUMBER(3)                     NOT NULL,
  CCL_CNTRY_CODE  NUMBER(3)                     NOT NULL,
  CCL_CITY_CODE   NUMBER(5)                     NOT NULL,
  CCL_TRANS_AMT   NUMBER(12,2)                  NOT NULL,
  CCL_LOYL_POINT  NUMBER(1)                     NOT NULL,
  CCL_INS_USER    NUMBER(5)                     NOT NULL,
  CCL_INS_DATE    DATE                          NOT NULL,
  CCL_LUPD_USER   NUMBER(5)                     NOT NULL,
  CCL_LUPD_DATE   DATE                          NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CITY_LOYL ADD (
  CONSTRAINT PK_CITY_LOYL
 PRIMARY KEY
 (CCL_INST_CODE, CCL_LOYL_CODE))
/

ALTER TABLE VMSCMS.CMS_CITY_LOYL ADD (
  CONSTRAINT FK_CITYLOYL_CITYMAST 
 FOREIGN KEY (CCL_INST_CODE, CCL_CNTRY_CODE, CCL_CITY_CODE) 
 REFERENCES VMSCMS.GEN_CITY_MAST (GCM_INST_CODE,GCM_CNTRY_CODE,GCM_CITY_CODE) DISABLE,
  CONSTRAINT FK_CITYLOYL_LOYLMAST 
 FOREIGN KEY (CCL_INST_CODE, CCL_LOYL_CODE) 
 REFERENCES VMSCMS.CMS_LOYL_MAST (CLM_INST_CODE,CLM_LOYL_CODE),
  CONSTRAINT FK_CITYLOYL_USERMAST1 
 FOREIGN KEY (CCL_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CITYLOYL_USERMAST2 
 FOREIGN KEY (CCL_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

