CREATE TABLE VMSCMS.CMS_REISSUE_CLOSE
(
  CRC_PAN_CODE        VARCHAR2(90 BYTE),
  CRC_FIRSTUSED_DATE  VARCHAR2(20 BYTE),
  CRC_FILE_NAME       VARCHAR2(30 BYTE),
  CRC_INS_DATE        DATE,
  CRC_INS_USER        NUMBER(5)                 DEFAULT 1                     NOT NULL,
  CRC_FLAG            VARCHAR2(2 BYTE)          DEFAULT 'N',
  CRC_PROCESS_RESULT  VARCHAR2(300 BYTE)        DEFAULT 'NOT PROCESSED',
  CRC_INST_CODE       NUMBER(5),
  CRC_PAN_CODE_ENCR   RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


