CREATE TABLE VMSCMS.CMS_PINBLK_MAST
(
  CPM_INST_CODE      NUMBER(3),
  CPM_PAN_CODE       VARCHAR2(90 BYTE),
  CPM_PIN_BLOCK      VARCHAR2(16 BYTE),
  CPM_INS_DATE       DATE,
  CPM_INS_USER       NUMBER(5),
  CPM_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


