CREATE TABLE VMSCMS.CMS_ACCTCLOSE_HIST
(
  CAH_ACCT_NO    VARCHAR2(20 BYTE),
  CAH_INS_DATE   DATE,
  CAH_LUPD_DATE  DATE,
  CAH_INST_CODE  NUMBER(10),
  CAH_LUPD_USER  NUMBER(10),
  CAH_INS_USER   NUMBER(10)
)
TABLESPACE CMS_HIST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


