CREATE TABLE VMSCMS.CMS_DELCHGROUP_MAST
(
  CDM_INST_CODE                NUMBER(3),
  CDM_DELIVERY_CHANNEL         VARCHAR2(2 BYTE),
  CDM_INTERNATIONAL_INDICATOR  VARCHAR2(2 BYTE),
  CDM_PINSIGN_VALIDATE         VARCHAR2(2 BYTE),
  CDM_MCC_VALIDATE             VARCHAR2(2 BYTE),
  CDM_INS_DATE                 DATE,
  CDM_INS_USER                 NUMBER(10),
  CDM_LUPD_DATE                DATE,
  CDM_LUPD_USER                NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


