CREATE TABLE VMSCMS.CMS_ALERT_USER
(
  CAU_USER_PIN   NUMBER(5),
  CAU_ITEM_CODE  VARCHAR2(10 BYTE),
  CAU_LUPD_DATE  DATE,
  CAU_INST_CODE  NUMBER(10),
  CAU_LUPD_USER  NUMBER(10),
  CAU_INS_DATE   DATE,
  CAU_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_ALERT_USER ADD (
  CONSTRAINT FK_ALERTUSER_PIN 
 FOREIGN KEY (CAU_USER_PIN) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN))
/

