CREATE TABLE VMSCMS.CMS_INST_MAST
(
  CIM_INST_CODE       NUMBER(3)                 NOT NULL,
  CIM_INST_NAME       VARCHAR2(100 BYTE)        NOT NULL,
  CIM_PAN_OFFSET      NUMBER(2),
  CIM_PAN_LENGTH      NUMBER(2),
  CIM_PAD_CHAR        CHAR(1 BYTE),
  CIM_DECI_VALUE      VARCHAR2(20 BYTE),
  CIM_PVT_KEY         VARCHAR2(20 BYTE),
  CIM_PIN_LENGTH      NUMBER(2),
  CIM_PAN_VRFY        NUMBER(2),
  CIM_INS_USER        NUMBER(5)                 NOT NULL,
  CIM_INS_DATE        DATE                      NOT NULL,
  CIM_LUPD_USER       NUMBER(5)                 NOT NULL,
  CIM_LUPD_DATE       DATE                      NOT NULL,
  CIM_CARD_VV1        VARCHAR2(20 BYTE),
  CIM_CARD_VV2        VARCHAR2(20 BYTE),
  CIM_MBR_NUMB        VARCHAR2(3 BYTE),
  CIM_INST_SHORTNAME  VARCHAR2(5 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_INST_MAST ADD (
  CONSTRAINT PK_INST_MAST
 PRIMARY KEY
 (CIM_INST_CODE))
/

