CREATE TABLE VMSCMS.CMS_FIELD_MAST
(
  CFM_FILE_ID          NUMBER(20),
  CFM_FIELD_ID         NUMBER(20),
  CFM_NAME             VARCHAR2(50 BYTE),
  CFM_SHORT_NAME       VARCHAR2(20 BYTE),
  CFM_FIELD_TYPE       VARCHAR2(20 BYTE),
  CFM_FIELD_FORMAT     VARCHAR2(15 BYTE),
  CFM_FROM_POSN        NUMBER(10),
  CFM_TO_POSN          NUMBER(20),
  CFM_COL_POSN         NUMBER(10),
  CFM_MAX_LENGTH       NUMBER(2),
  CFM_COMPULSORY_FLAG  VARCHAR2(1 BYTE),
  CFM_AMOUNT_FLAG      VARCHAR2(1 BYTE),
  CFM_SIGN_FLAG        VARCHAR2(1 BYTE),
  CFM_AMOUNT_STATUS    VARCHAR2(10 BYTE),
  CFM_DEBIT_VALUE      VARCHAR2(5 BYTE),
  CFM_CREDIT_VALUE     VARCHAR2(5 BYTE),
  CFM_TAB_FIELD_NAME   VARCHAR2(30 BYTE),
  CFM_INDEX_NAME       VARCHAR2(50 BYTE),
  CFM_LUPD_DATE        DATE,
  CFM_INST_CODE        NUMBER(10),
  CFM_LUPD_USER        NUMBER(10),
  CFM_INS_DATE         DATE,
  CFM_INS_USER         NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_FIELD_MAST ADD (
  CONSTRAINT PK_CFM_FILE_FIELD_ID
 PRIMARY KEY
 (CFM_FILE_ID, CFM_FIELD_ID))
/

ALTER TABLE VMSCMS.CMS_FIELD_MAST ADD (
  CONSTRAINT FK_IFD_FILE_ID 
 FOREIGN KEY (CFM_FILE_ID) 
 REFERENCES VMSCMS.CMS_FILE_DEFIN_MAST (CFD_FILE_ID))
/

