CREATE TABLE VMSCMS.CMS_GROUP_TOPUP
(
  CGT_ACCT_NO        VARCHAR2(20 BYTE),
  CGT_TOPUP_AMT      VARCHAR2(12 BYTE),
  CGT_FILE_NAME      VARCHAR2(20 BYTE),
  CGT_INS_DATE       DATE,
  CGT_INS_USER       NUMBER(5),
  CGT_REMARKS        VARCHAR2(100 BYTE),
  CGT_PROCESS_FLAG   VARCHAR2(1 BYTE),
  CGT_REF_NO         VARCHAR2(25 BYTE),
  CGT_MSG24_FLAG     CHAR(1 BYTE)               DEFAULT 'N',
  CGT_LUPD_DATE      DATE,
  CGT_PAYMENT_MODE   VARCHAR2(15 BYTE),
  CGT_INSTRUMENT_NO  VARCHAR2(19 BYTE),
  CGT_DRAWN_DATE     DATE,
  CGT_ROW_ID         VARCHAR2(8 BYTE),
  CGT_INST_CODE      NUMBER(10),
  CGT_LUPD_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


