CREATE TABLE VMSCMS.CMS_CHARGE_DTL
(
  CCD_INST_CODE         NUMBER(3),
  CCD_FEE_TRANS         NUMBER(13)              NOT NULL,
  CCD_PAN_CODE          VARCHAR2(90 BYTE),
  CCD_MBR_NUMB          VARCHAR2(3 BYTE),
  CCD_CUST_CODE         NUMBER(10),
  CCD_ACCT_ID           NUMBER(10),
  CCD_ACCT_NO           VARCHAR2(20 BYTE),
  CCD_FEE_FREQ          VARCHAR2(2 BYTE),
  CCD_FEETYPE_CODE      NUMBER(5),
  CCD_FEE_CODE          NUMBER(4),
  CCD_CALC_AMT          NUMBER(15,6),
  CCD_EXPCALC_DATE      DATE,
  CCD_CALC_DATE         DATE,
  CCD_FILE_DATE         DATE,
  CCD_FILE_NAME         VARCHAR2(18 BYTE),
  CCD_FILE_STATUS       CHAR(1 BYTE),
  CCD_INS_USER          NUMBER(5),
  CCD_INS_DATE          DATE,
  CCD_LUPD_USER         NUMBER(5),
  CCD_LUPD_DATE         DATE,
  CCD_PROCESS_ID        NUMBER(10),
  CCD_PLAN_CODE         VARCHAR2(6 BYTE),
  CCD_GEFU_GEN          VARCHAR2(1 BYTE)        DEFAULT 'N',
  CFP_NEWBILL_DATE      DATE,
  CFP_OLDBILL_DATE      DATE,
  CCD_PAN_CODE_ENCR     RAW(100),
  CCD_CLAWBACK          VARCHAR2(1 BYTE),
  CCD_FEE_PLAN          NUMBER(4),
  CCD_GL_ACCT_NO        VARCHAR2(20 BYTE),
  CCD_CLAWBACK_AMNT     NUMBER(15,6),
  CCD_PROCESS_MSG       VARCHAR2(300 BYTE),
  CCD_DEBITED_AMNT      NUMBER(15,6),
  CCD_RRN               VARCHAR2(20 BYTE),
  CCD_DELIVERY_CHANNEL  VARCHAR2(2 BYTE),
  CCD_TXN_CODE          VARCHAR2(2 BYTE),
  CCD_FEEATTACHTYPE     VARCHAR2(2 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_CHARGE_DTL ADD (
  CONSTRAINT PK_CHARGE_DTL
 PRIMARY KEY
 (CCD_FEE_TRANS))
/

ALTER TABLE VMSCMS.CMS_CHARGE_DTL ADD (
  CONSTRAINT FK_CHARGEDTL_APPLPAN 
 FOREIGN KEY (CCD_PAN_CODE, CCD_MBR_NUMB) 
 REFERENCES VMSCMS.CMS_APPL_PAN (CAP_PAN_CODE,CAP_MBR_NUMB),
  CONSTRAINT FK_CHARGECTL_USERMAST2 
 FOREIGN KEY (CCD_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CHARGEDTL_USERMAST1 
 FOREIGN KEY (CCD_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_CHARGEDTL_CUSTMAST 
 FOREIGN KEY (CCD_INST_CODE, CCD_CUST_CODE) 
 REFERENCES VMSCMS.CMS_CUST_MAST (CCM_INST_CODE,CCM_CUST_CODE),
  CONSTRAINT FK_CHARGEDTL_FEEMAST 
 FOREIGN KEY (CCD_INST_CODE, CCD_FEE_CODE) 
 REFERENCES VMSCMS.CMS_FEE_MAST (CFM_INST_CODE,CFM_FEE_CODE),
  CONSTRAINT FK_CHARGEDTL_FEETYPES 
 FOREIGN KEY (CCD_INST_CODE, CCD_FEETYPE_CODE) 
 REFERENCES VMSCMS.CMS_FEE_TYPES (CFT_INST_CODE,CFT_FEETYPE_CODE))
/

