CREATE TABLE VMSCMS.CMS_BRANPROD_STOCK
(
  CBS_INST_CODE      NUMBER(3),
  CBS_PROD_SNAME     VARCHAR2(50 BYTE),
  CBS_BRAN_CODE      VARCHAR2(6 BYTE),
  CBS_STOCK          NUMBER(5),
  CBS_INS_USER       NUMBER(5),
  CBS_INS_DATE       DATE,
  CBS_LUPD_USER      NUMBER(5),
  CBS_LUPD_DATE      DATE,
  CBS_REORDER_LEVEL  NUMBER(5)                  DEFAULT 0
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


