CREATE TABLE VMSCMS.CMS_SUPPORTFUNCTIONS_LOG
(
  CSL_CARD_NO           VARCHAR2(90 BYTE),
  CSL_FLAG              CHAR(1 BYTE)            DEFAULT 'N',
  CSL_INS_DATE          DATE,
  CSL_INS_USER          NUMBER(5),
  CSL_LUPD_USER         NUMBER(5)               DEFAULT NULL,
  CSL_LUPD_DATE         DATE,
  CSL_ROWID             NUMBER(20),
  CSL_FUNC_REMARK       VARCHAR2(50 BYTE),
  CSL_SPPRTFUNC_CODE    NUMBER(5),
  CSL_RSN_CODE          VARCHAR2(20 BYTE),
  CSL_REMARKS           VARCHAR2(500 BYTE),
  CSL_NEWDISP_NAME      VARCHAR2(50 BYTE),
  CSL_PROD_CAT          VARCHAR2(20 BYTE),
  CSL_PROD_CODE         VARCHAR2(6 BYTE),
  CSL_OLD_CARDSTAT      VARCHAR2(25 BYTE),
  CSL_NEW_CARDSTAT      VARCHAR2(10 BYTE),
  CSL_ONLINE_ATMLIMIT   NUMBER(10),
  CSL_OFFLINE_ATMLIMIT  NUMBER(10),
  CSL_ONLINE_POSLIMIT   NUMBER(10),
  CSL_OFFLINE_POSLIMIT  NUMBER(10),
  CSL_ONLINE_RECLIMIT   NUMBER(10),
  CSL_OFFLINE_RECLIMIT  NUMBER(10),
  CSL_ADDR_CODE         NUMBER(10),
  CSL_INST_CODE         NUMBER(3)               DEFAULT null,
  CSL_CUST_CODE         NUMBER(10),
  CSL_ADD_ONE           VARCHAR2(50 BYTE),
  CSL_ADD_TWO           VARCHAR2(50 BYTE),
  CSL_ADD_THREE         VARCHAR2(50 BYTE),
  CSL_PIN_CODE          VARCHAR2(15 BYTE),
  CSL_PHONE_ONE         VARCHAR2(40 BYTE),
  CSL_PHONE_TWO         VARCHAR2(20 BYTE),
  CSL_CNTRY_CODE        NUMBER(3),
  CSL_CITY_NAME         VARCHAR2(25 BYTE),
  CSL_FAX_ONE           VARCHAR2(20 BYTE),
  CSL_ADDR_FLAG         CHAR(1 BYTE),
  CSL_STATE_SWITCH      VARCHAR2(3 BYTE),
  CSL_ADDR_NEW          VARCHAR2(1 BYTE)        DEFAULT 'N',
  CSL_ACCT_ID           NUMBER(10),
  CSL_ACCT_NO           VARCHAR2(20 BYTE),
  CSL_CHECKER_RMKS      VARCHAR2(500 BYTE)      DEFAULT 'NIL',
  CSL_PROCESS_RESULT    VARCHAR2(500 BYTE)      DEFAULT 'NOT PROCESSED',
  CSL_OLD_DISPNAME      VARCHAR2(50 BYTE),
  CSL_CARD_NO_ENCR      RAW(100),
  CSL_IP_ADDRESS        VARCHAR2(20 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


