CREATE TABLE VMSCMS.CMS_MERCID_RULEGRP
(
  CMR_INST_CODE     NUMBER(10),
  CMR_MERC_GRPCODE  VARCHAR2(11 BYTE),
  CMR_GRPCODE_DESC  VARCHAR2(100 BYTE)          NOT NULL,
  CMR_GRPCODE_STUS  VARCHAR2(1 BYTE),
  CMR_LUPD_DATE     DATE,
  CMR_LUPD_USER     NUMBER(10),
  CMR_INS_DATE      DATE,
  CMR_INS_USER      NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_MERCID_RULEGRP ADD (
  CONSTRAINT PK_MERCID_RULEGRP
 PRIMARY KEY
 (CMR_MERC_GRPCODE))
/

