CREATE TABLE VMSCMS.CMS_DUP_ACCT_PAN
(
  CDA_ACCT_NO       VARCHAR2(20 BYTE),
  CDA_ACCT_ID       NUMBER(10),
  CDA_PAN_CODE      VARCHAR2(90 BYTE),
  CDA_NEW_ACCT_NO   VARCHAR2(20 BYTE),
  CDA_NEW_ACCT_ID   NUMBER(10),
  CDA_CUST_CODE     NUMBER(10),
  CDA_CARD_STAT     VARCHAR2(1 BYTE),
  CDA_MASK_PAN      VARCHAR2(20 BYTE),
  CDA_PROCESS_FLAG  VARCHAR2(1 BYTE),
  CDA_PROCESS_MSG   VARCHAR2(300 BYTE),
  CDA_INS_DATE      DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


