CREATE TABLE VMSCMS.CMS_GROUP_TOPUP_TEMP
(
  CGT_ACCT_NO        VARCHAR2(20 BYTE),
  CGT_TOPUP_AMT      VARCHAR2(12 BYTE),
  CGT_FILE_NAME      VARCHAR2(30 BYTE),
  CGT_INS_DATE       DATE                       DEFAULT sysdate,
  CGT_INS_USER       NUMBER(5),
  CGT_REMARKS        VARCHAR2(100 BYTE),
  CGT_PROCESS_FLAG   VARCHAR2(1 BYTE)           DEFAULT 'N',
  CGT_REF_NO         VARCHAR2(25 BYTE),
  CGT_PROCESS_MSG    VARCHAR2(300 BYTE),
  CGT_INST_CODE      NUMBER(3),
  CGT_LUPD_DATE      DATE,
  CGT_LUPD_USER      NUMBER(10),
  CGT_PAYMENT_MODE   VARCHAR2(15 BYTE),
  CGT_INSTRUMENT_NO  VARCHAR2(19 BYTE),
  CGT_DRAWN_DATE     DATE,
  CGT_MBR_NUMB       VARCHAR2(10 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


