CREATE TABLE VMSCMS.CMS_PAN_SPPRT
(
  CPS_INST_CODE      NUMBER(3)                  NOT NULL,
  CPS_PAN_CODE       VARCHAR2(90 BYTE)          NOT NULL,
  CPS_MBR_NUMB       VARCHAR2(3 BYTE)           NOT NULL,
  CPS_PROD_CATG      VARCHAR2(2 BYTE)           NOT NULL,
  CPS_SPPRT_KEY      VARCHAR2(10 BYTE)          NOT NULL,
  CPS_SPPRT_RSNCODE  NUMBER(3)                  NOT NULL,
  CPS_FUNC_REMARK    VARCHAR2(800 BYTE),
  CPS_INS_USER       NUMBER(5)                  NOT NULL,
  CPS_INS_DATE       DATE                       NOT NULL,
  CPS_LUPD_USER      NUMBER(5)                  NOT NULL,
  CPS_LUPD_DATE      DATE                       NOT NULL,
  CPS_CMD_MODE       NUMBER(1)                  DEFAULT 0,
  CPS_PAN_CODE_ENCR  RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PAN_SPPRT ADD (
  CONSTRAINT FK_PANSPPRT_SPPRTREASONS 
 FOREIGN KEY (CPS_INST_CODE, CPS_SPPRT_RSNCODE) 
 REFERENCES VMSCMS.CMS_SPPRT_REASONS (CSR_INST_CODE,CSR_SPPRT_RSNCODE),
  CONSTRAINT FK_PANSPPRT_APPLPAN 
 FOREIGN KEY (CPS_PAN_CODE, CPS_MBR_NUMB) 
 REFERENCES VMSCMS.CMS_APPL_PAN (CAP_PAN_CODE,CAP_MBR_NUMB))
/

