CREATE TABLE VMSCMS.CMS_CARDMAST_AUDIT
(
  CCA_CRD_NUM     VARCHAR2(20 BYTE),
  CCA_TAB_ACTION  VARCHAR2(20 BYTE),
  CCA_ACT_BY      NUMBER(5),
  CCA_ACT_TIME    DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


