CREATE TABLE VMSCMS.CMS_BACKUP_LOG
(
  CBL_ACCT_NO       VARCHAR2(20 BYTE),
  CBL_PROCESS_FLAG  VARCHAR2(1 BYTE),
  CBL_PROCESS_MSG   VARCHAR2(300 BYTE),
  CBL_INS_DATE      DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


