CREATE TABLE VMSCMS.CMS_PROD_B24
(
  CPB_INST_CODE     NUMBER(3)                   NOT NULL,
  CPB_B24_PRODCODE  VARCHAR2(5 BYTE)            NOT NULL,
  CPB_PROD_DESC     VARCHAR2(50 BYTE)           NOT NULL,
  CPB_LUPD_DATE     DATE,
  CPB_LUPD_USER     NUMBER(10),
  CPB_INS_DATE      DATE,
  CPB_INS_USER      NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


