CREATE TABLE VMSCMS.CMS_GIFT_PLAN
(
  CGP_INST_CODE    NUMBER(3),
  CGP_PLAN_ID      VARCHAR2(5 BYTE),
  CGP_PLAN_DESC    VARCHAR2(100 BYTE)           NOT NULL,
  CGP_VALID_FRDT   DATE                         NOT NULL,
  CGP_VALID_TODT   DATE                         NOT NULL,
  CGP_PLAN_STATUS  CHAR(1 BYTE)                 NOT NULL,
  CGP_INS_USER     NUMBER(5)                    NOT NULL,
  CGP_INS_DATE     DATE                         NOT NULL,
  CGP_LUPD_USER    NUMBER(5)                    NOT NULL,
  CGP_LUPD_DATE    DATE                         NOT NULL
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_GIFT_PLAN ADD (
  CONSTRAINT PK_GIFT_PLAN
 PRIMARY KEY
 (CGP_INST_CODE, CGP_PLAN_ID),
  CONSTRAINT UK_GIFT_MAST
 UNIQUE (CGP_PLAN_DESC))
/

