CREATE TABLE VMSCMS.CMS_GROUP_INITIALLOAD_TEMP
(
  CGI_ACCT_NO        VARCHAR2(20 BYTE),
  CGI_INITIAL_AMT    VARCHAR2(12 BYTE),
  CGI_FILE_NAME      VARCHAR2(30 BYTE),
  CGI_INS_DATE       DATE                       DEFAULT SYSDATE,
  CGI_INS_USER       NUMBER(5),
  CGI_REMARKS        VARCHAR2(100 BYTE),
  CGI_PROCESS_FLAG   VARCHAR2(1 BYTE)           DEFAULT 'N',
  CGI_REF_NO         VARCHAR2(25 BYTE),
  CGI_PROCESS_MSG    VARCHAR2(300 BYTE),
  CGI_INST_CODE      NUMBER(3),
  CGI_LUPD_DATE      DATE,
  CGI_LUPD_USER      NUMBER(10),
  CGI_MBR_NUMB       VARCHAR2(10 BYTE),
  CGI_PAYMENT_MODE   VARCHAR2(15 BYTE),
  CGI_INSTRUMENT_NO  VARCHAR2(19 BYTE),
  CGI_DRAWN_DATE     DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


