CREATE TABLE VMSCMS.CMS_UPLOAD_CTRL
(
  CUC_INST_CODE    NUMBER(3)                    NOT NULL,
  CUC_BRAN_CODE    VARCHAR2(6 BYTE),
  CUC_FILE_NAME    VARCHAR2(35 BYTE)            NOT NULL,
  CUC_FILE_HEADER  VARCHAR2(50 BYTE),
  CUC_UPLD_DATE    DATE,
  CUC_TOT_ROWS     NUMBER(8),
  CUC_CORR_ROWS    NUMBER(8),
  CUC_ERR_ROWS     NUMBER(8),
  CUC_UPLD_STAT    CHAR(1 BYTE),
  CUC_INS_USER     NUMBER(5)                    NOT NULL,
  CUC_INS_DATE     DATE                         NOT NULL,
  CUC_LUPD_USER    NUMBER(5),
  CUC_LUPD_DATE    DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_UPLOAD_CTRL ADD (
  CONSTRAINT PK_UPLOAD_CTRL
 PRIMARY KEY
 (CUC_INST_CODE, CUC_FILE_NAME))
/

