CREATE TABLE VMSCMS.CMS_PINMAILER_FIELDS
(
  CPF_FIELD_NAME  VARCHAR2(25 BYTE),
  CPF_TABLE_NAME  VARCHAR2(25 BYTE),
  CPF_COL_NAME    VARCHAR2(25 BYTE),
  CPF_INS_DATE    DATE,
  CPF_LUPD_DATE   DATE,
  CPF_INST_CODE   NUMBER(10),
  CPF_LUPD_USER   NUMBER(10),
  CPF_INS_USER    NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


