CREATE TABLE VMSCMS.CMS_BRAN_MAST
(
  CBM_CNTRY_CODE       NUMBER(3),
  CBM_STATE_CODE       NUMBER(3),
  CBM_INST_CODE        NUMBER(3)                NOT NULL,
  CBM_BRAN_CODE        VARCHAR2(6 BYTE)         NOT NULL,
  CBM_BRAN_FIID        VARCHAR2(6 BYTE)         NOT NULL,
  CBM_MICR_NO          VARCHAR2(20 BYTE),
  CBM_BRAN_LOCN        VARCHAR2(30 BYTE)        NOT NULL,
  CBM_ADDR_ONE         VARCHAR2(50 BYTE)        NOT NULL,
  CBM_ADDR_TWO         VARCHAR2(50 BYTE),
  CBM_ADDR_THREE       VARCHAR2(50 BYTE),
  CBM_CITY_CODE        NUMBER(5),
  CBM_PIN_CODE         NUMBER(6)                NOT NULL,
  CBM_PHON_ONE         VARCHAR2(20 BYTE)        NOT NULL,
  CBM_PHON_TWO         VARCHAR2(20 BYTE),
  CBM_PHON_THREE       VARCHAR2(20 BYTE),
  CBM_CONT_PRSN        VARCHAR2(35 BYTE)        NOT NULL,
  CBM_FAX_NO           VARCHAR2(20 BYTE),
  CBM_EMAIL_ID         VARCHAR2(50 BYTE),
  CBM_INS_USER         NUMBER(5)                NOT NULL,
  CBM_INS_DATE         DATE                     NOT NULL,
  CBM_LUPD_USER        NUMBER(5)                NOT NULL,
  CBM_LUPD_DATE        DATE                     NOT NULL,
  CBM_TOT_LIMIT        NUMBER(10)               DEFAULT 0,
  CBM_AVAIL_LIMIT      NUMBER(10)               DEFAULT 0,
  CBM_BRAN_CATG        VARCHAR2(5 BYTE),
  CBM_BRAN_TYPE        VARCHAR2(5 BYTE),
  CBM_REPORTING_BRAN   VARCHAR2(5 BYTE),
  CBM_ACCT_ID          NUMBER(10),
  CBM_WALLET_CATG      VARCHAR2(30 BYTE),
  CBM_WALLET_TYPE      VARCHAR2(30 BYTE),
  CBM_COMMISSION_PLAN  VARCHAR2(30 BYTE),
  CBM_DEFINE_COMMPLAN  VARCHAR2(1 BYTE),
  CBM_SALE_TRANS       VARCHAR2(1 BYTE),
  CBM_TOPUP_TRANS      VARCHAR2(1 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BRAN_MAST ADD (
  CONSTRAINT PK_BRAN_MAST
 PRIMARY KEY
 (CBM_INST_CODE, CBM_BRAN_CODE))
/

ALTER TABLE VMSCMS.CMS_BRAN_MAST ADD (
  CONSTRAINT FK_BRANMAST_INSTMAST 
 FOREIGN KEY (CBM_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE),
  CONSTRAINT FK_BRANMAST_USERMAST1 
 FOREIGN KEY (CBM_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_BRANMAST_USERMAST2 
 FOREIGN KEY (CBM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_BRANCATG 
 FOREIGN KEY (CBM_INST_CODE, CBM_BRAN_CATG) 
 REFERENCES VMSCMS.CMS_BRANCH_CATG (CBC_INST_CODE,CBC_CATG_CODE),
  CONSTRAINT FK_BRANTYPE 
 FOREIGN KEY (CBM_INST_CODE, CBM_BRAN_TYPE) 
 REFERENCES VMSCMS.CMS_BRANCH_TYPE (CBT_INST_CODE,CBT_TYPE_CODE),
  CONSTRAINT FK_BRANMAST_CITYMAST 
 FOREIGN KEY (CBM_INST_CODE, CBM_CNTRY_CODE, CBM_CITY_CODE) 
 REFERENCES VMSCMS.GEN_CITY_MAST (GCM_INST_CODE,GCM_CNTRY_CODE,GCM_CITY_CODE) DISABLE)
/

