CREATE TABLE VMSCMS.CMS_PROD_CCC
(
  CPC_INST_CODE   NUMBER(3)                     NOT NULL,
  CPC_CUST_CATG   NUMBER(5)                     NOT NULL,
  CPC_CARD_TYPE   NUMBER(2)                     NOT NULL,
  CPC_PROD_CODE   VARCHAR2(6 BYTE)              NOT NULL,
  CPC_INS_USER    NUMBER(5)                     NOT NULL,
  CPC_INS_DATE    DATE                          NOT NULL,
  CPC_LUPD_USER   NUMBER(5)                     NOT NULL,
  CPC_LUPD_DATE   DATE                          NOT NULL,
  CPC_VENDOR      CHAR(1 BYTE),
  CPC_STOCK       CHAR(1 BYTE),
  CPC_PROD_SNAME  VARCHAR2(50 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_PROD_CCC ADD (
  CONSTRAINT PK_PROD_CCC
 PRIMARY KEY
 (CPC_INST_CODE, CPC_CUST_CATG, CPC_PROD_CODE, CPC_CARD_TYPE))
/

ALTER TABLE VMSCMS.CMS_PROD_CCC ADD (
  CONSTRAINT FK_PRODCCC_USERMAST1 
 FOREIGN KEY (CPC_INS_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCCC_USERMAST2 
 FOREIGN KEY (CPC_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_PRODCCC_PRODCATTYPE 
 FOREIGN KEY (CPC_INST_CODE, CPC_PROD_CODE, CPC_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CATTYPE (CPC_INST_CODE,CPC_PROD_CODE,CPC_CARD_TYPE),
  CONSTRAINT FK_PRODCCC_CUSTCATG 
 FOREIGN KEY (CPC_INST_CODE, CPC_CUST_CATG) 
 REFERENCES VMSCMS.CMS_CUST_CATG (CCC_INST_CODE,CCC_CATG_CODE))
/

