CREATE TABLE VMSCMS.CMS_ACHFILE_UPD_ERRLOG
(
  CAU_BATCH_NO      NUMBER(10),
  CAU_FILE_NAME     VARCHAR2(255),
  CAU_REC_NO        NUMBER(10),
  CAT_PROCESS_MSG   VARCHAR2(3000),
  CAT_PROCESS_DATE  DATE
)
TABLESPACE CMS_BIG_TXN;