CREATE TABLE VMSCMS.CMS_APPL_MAST
(
  CAM_INST_CODE             NUMBER(3)           NOT NULL,
  CAM_ASSO_CODE             NUMBER(3)           NOT NULL,
  CAM_INST_TYPE             NUMBER(3)           NOT NULL,
  CAM_APPL_CODE             NUMBER(14)          NOT NULL,
  CAM_APPL_NO               VARCHAR2(21 BYTE),
  CAM_APPL_DATE             DATE                NOT NULL,
  CAM_REG_DATE              DATE,
  CAM_CUST_CODE             NUMBER(10),
  CAM_APPL_BRAN             VARCHAR2(6 BYTE)    NOT NULL,
  CAM_PROD_CODE             VARCHAR2(6 BYTE)    NOT NULL,
  CAM_CARD_TYPE             NUMBER(2),
  CAM_CUST_CATG             NUMBER(5),
  CAM_ACTIVE_DATE           DATE,
  CAM_EXPRY_DATE            DATE,
  CAM_DISP_NAME             VARCHAR2(50 BYTE)   NOT NULL,
  CAM_LIMIT_AMT             NUMBER(15,6)        NOT NULL,
  CAM_ADDON_ISSU            CHAR(1 BYTE)        NOT NULL,
  CAM_USE_LIMIT             NUMBER(2),
  CAM_TOT_ACCT              NUMBER(3)           NOT NULL,
  CAM_APPL_STAT             CHAR(1 BYTE)        DEFAULT 'A'                   NOT NULL,
  CAM_ADDON_STAT            CHAR(1 BYTE)        NOT NULL,
  CAM_ADDON_LINK            NUMBER(14)          NOT NULL,
  CAM_BILL_ADDR             NUMBER(10)          NOT NULL,
  CAM_CHNL_CODE             NUMBER(3),
  CAM_APPL_USER             NUMBER(5)           NOT NULL,
  CAM_APPR_USER             NUMBER(5),
  CAM_APPR_DATE             DATE,
  CAM_LUPD_USER             NUMBER(5)           NOT NULL,
  CAM_LUPD_DATE             DATE                NOT NULL,
  CAM_FILE_NAME             VARCHAR2(35 BYTE),
  CAM_ROW_ID                VARCHAR2(8 BYTE),
  CAM_REQUEST_ID            VARCHAR2(35 BYTE),
  CAM_PAYMENT_REF           VARCHAR2(20 BYTE),
  CAM_INITIAL_TOPUP_AMOUNT  NUMBER(10,2),
  CAM_PROCESS_MSG           VARCHAR2(300 BYTE),
  CAM_INS_DATE              DATE,
  CAM_INS_USER              NUMBER(10),
  CAM_APPL_PARAM1           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM2           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM3           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM4           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM5           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM6           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM7           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM8           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM9           VARCHAR2(100 BYTE),
  CAM_APPL_PARAM10          VARCHAR2(100 BYTE),
  CAM_IKIT_FLAG             VARCHAR2(1 BYTE),
  CAM_STARTER_CARD          VARCHAR2(1 BYTE)    DEFAULT 'N'
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_APPL_MAST ADD (
  CONSTRAINT PK_APPL_MAST
 PRIMARY KEY
 (CAM_APPL_CODE))
/

ALTER TABLE VMSCMS.CMS_APPL_MAST ADD (
  CONSTRAINT FK_APPLMAST_BRANMAST 
 FOREIGN KEY (CAM_INST_CODE, CAM_APPL_BRAN) 
 REFERENCES VMSCMS.CMS_BRAN_MAST (CBM_INST_CODE,CBM_BRAN_CODE),
  CONSTRAINT FK_APPLMAST_ADDRMAST 
 FOREIGN KEY (CAM_INST_CODE, CAM_BILL_ADDR) 
 REFERENCES VMSCMS.CMS_ADDR_MAST (CAM_INST_CODE,CAM_ADDR_CODE),
  CONSTRAINT FK_APPLMAST_USERMAST2 
 FOREIGN KEY (CAM_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USER_MAST (CUM_USER_PIN),
  CONSTRAINT FK_APPLMAST_PRODCCC 
 FOREIGN KEY (CAM_INST_CODE, CAM_CUST_CATG, CAM_PROD_CODE, CAM_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CCC (CPC_INST_CODE,CPC_CUST_CATG,CPC_PROD_CODE,CPC_CARD_TYPE),
  CONSTRAINT FK_APPLMAST_PRODCATTYPE 
 FOREIGN KEY (CAM_INST_CODE, CAM_PROD_CODE, CAM_CARD_TYPE) 
 REFERENCES VMSCMS.CMS_PROD_CATTYPE (CPC_INST_CODE,CPC_PROD_CODE,CPC_CARD_TYPE),
  CONSTRAINT FK_APPLMAST_PRODMAST 
 FOREIGN KEY (CAM_INST_CODE, CAM_PROD_CODE) 
 REFERENCES VMSCMS.CMS_PROD_MAST (CPM_INST_CODE,CPM_PROD_CODE),
  CONSTRAINT FK_APPLMAST_CUSTMAST 
 FOREIGN KEY (CAM_INST_CODE, CAM_CUST_CODE) 
 REFERENCES VMSCMS.CMS_CUST_MAST (CCM_INST_CODE,CCM_CUST_CODE),
  CONSTRAINT FK_APPLMAST_CBDREL 
 FOREIGN KEY (CAM_INST_CODE, CAM_ASSO_CODE, CAM_INST_TYPE) 
 REFERENCES VMSCMS.CMS_CBD_REL (CCR_INST_CODE,CCR_ASSO_CODE,CCR_INST_TYPE),
  CONSTRAINT FK_APPLMAST_CHNLMAST 
 FOREIGN KEY (CAM_INST_CODE, CAM_CHNL_CODE) 
 REFERENCES VMSCMS.CMS_CHNL_MAST (CCM_INST_CODE,CCM_CHNL_CODE))
/

