CREATE TABLE VMSCMS.CMS_FLOAT_GLWISE_REPORT
(
  CFGR_TRAN_DATE      DATE,
  CFGR_CURR_CODE      VARCHAR2(9 BYTE),
  CFGR_PARAM_KEY      VARCHAR2(300 BYTE),
  CFGR_GL_CODE        VARCHAR2(21 BYTE),
  CFGR_GL_DESC        VARCHAR2(300 BYTE),
  CFGR_CREDIT_AMOUNT  NUMBER,
  CFGR_DEBIT_AMOUNT   NUMBER,
  CFG_LUPD_DATE       DATE,
  CFG_INST_CODE       NUMBER(10),
  CFG_LUPD_USER       NUMBER(10),
  CFG_INS_DATE        DATE,
  CFG_INS_USER        NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


