CREATE TABLE VMSCMS.CMS_REISSUE_INPUT
(
  CRI_ACCT_NO      VARCHAR2(20 BYTE),
  CRI_USER_REMARK  VARCHAR2(50 BYTE),
  CRI_FILE_NAME    VARCHAR2(30 BYTE),
  CRI_INS_DATE     DATE,
  CRI_INS_USER     NUMBER(5)                    DEFAULT 1                     NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


