CREATE TABLE VMSCMS.CMS_TRANSACTION_VERIFICATIONS
(
  CTV_TXN_CODE         VARCHAR2(2 BYTE),
  CTV_MSG_TYPE         VARCHAR2(4 BYTE),
  CTV_VERIFY_CNAME     VARCHAR2(100 BYTE),
  CTV_INST_CODE        NUMBER(3),
  CTV_INST_BIN         NUMBER(10),
  CTV_SHORT_NAME       VARCHAR2(5 BYTE),
  CTV_REVERSAL_CODE    NUMBER(3),
  CTV_DAO_CNAME        VARCHAR2(100 BYTE),
  CTV_DELIVERY_CHANEL  VARCHAR2(3 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


