CREATE TABLE VMSCMS.CMS_VELOCITYLOAD_TXN12HRS
(
  CHR_ROW_ID               VARCHAR2(30 BYTE),
  CHR_PRIMARY_CARD_NUMBER  VARCHAR2(90 BYTE),
  CHR_TXN_DATE             VARCHAR2(100 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


