CREATE TABLE VMSCMS.CMS_BIN_SCHEME
(
  CBS_INST_CODE      NUMBER(3)                  NOT NULL,
  CBS_INST_BIN       NUMBER(10)                 NOT NULL,
  CBS_MBSCHEME_CODE  NUMBER(3)                  NOT NULL,
  CBS_ATTACH_DATE    DATE                       NOT NULL,
  CBS_MB_PERIOD      NUMBER(10)                 NOT NULL,
  CBS_INS_USER       NUMBER(5)                  NOT NULL,
  CBS_INS_DATE       DATE                       NOT NULL,
  CBS_LUPD_DATE      DATE,
  CBS_LUPD_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CMS_BIN_SCHEME ADD (
  CONSTRAINT PK_BIN_SCHEME
 PRIMARY KEY
 (CBS_INST_CODE, CBS_INST_BIN))
/

ALTER TABLE VMSCMS.CMS_BIN_SCHEME ADD (
  CONSTRAINT FK_BINSCHEME_BINMAST 
 FOREIGN KEY (CBS_INST_CODE, CBS_INST_BIN) 
 REFERENCES VMSCMS.CMS_BIN_MAST (CBM_INST_CODE,CBM_INST_BIN),
  CONSTRAINT FK_BINSCHEME_MONEYBK 
 FOREIGN KEY (CBS_MBSCHEME_CODE) 
 REFERENCES VMSCMS.CMS_MONEYBACK_MAST (CMM_MBSCHEME_CODE))
/

