CREATE TABLE VMSCMS.CREATE$JAVA$LOB$TABLE
(
  NAME      VARCHAR2(700 BYTE),
  LOB       BLOB,
  LOADTIME  DATE
)
TABLESPACE CMS_DEFAULT
LOGGING 
NOCOMPRESS 
LOB (LOB) STORE AS 
      ( TABLESPACE  CMS_DEFAULT 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE CMS_DEFAULT)
      )
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CREATE$JAVA$LOB$TABLE ADD (
  UNIQUE (NAME))
/

