CREATE TABLE VMSCMS.CSR_SERVER_DETAIL
(
  CSD_INST_CODE    NUMBER(3),
  CSD_SERVER_ID    VARCHAR2(20 BYTE),
  CSD_SERVER_NAME  VARCHAR2(50 BYTE),
  CSD_SERVER_IP    VARCHAR2(50 BYTE),
  CSD_PARAM_KEY    VARCHAR2(20 BYTE),
  CSD_PARAM_DESC   VARCHAR2(50 BYTE),
  CSD_PARAM_VALUE  VARCHAR2(1 BYTE),
  CSD_INS_USER     NUMBER(5)                    NOT NULL,
  CSD_INS_DATE     DATE                         NOT NULL,
  CSD_LUPD_USER    NUMBER(5),
  CSD_LUPD_DATE    DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CSR_SERVER_DETAIL ADD (
  CONSTRAINT PK_SEVER_MAST
 PRIMARY KEY
 (CSD_INST_CODE, CSD_PARAM_KEY, CSD_PARAM_VALUE, CSD_SERVER_ID),
  CONSTRAINT UK_CSD_SERVER_ID
 UNIQUE (CSD_SERVER_ID))
/

ALTER TABLE VMSCMS.CSR_SERVER_DETAIL ADD (
  CONSTRAINT FK_INSTSERVER_USERMAST1 
 FOREIGN KEY (CSD_INS_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_INSTSERVER_USERMAST2 
 FOREIGN KEY (CSD_LUPD_USER) 
 REFERENCES VMSCMS.CMS_USERDETL_MAST (CUM_USER_CODE),
  CONSTRAINT FK_INSTSEVER_INSTMAST 
 FOREIGN KEY (CSD_INST_CODE) 
 REFERENCES VMSCMS.CMS_INST_MAST (CIM_INST_CODE))
/

