CREATE TABLE VMSCMS.CURRENCYCODE
(
  CURRENCYCODE      VARCHAR2(4 BYTE),
  CURRENCYCODEDESC  VARCHAR2(50 BYTE)           NOT NULL,
  ACTIVATIONSTATUS  VARCHAR2(1 BYTE),
  SHORTNAME         VARCHAR2(4 BYTE),
  ACT_LUPD_DATE     DATE,
  ACT_INST_CODE     NUMBER(10),
  ACT_LUPD_USER     NUMBER(10),
  ACT_INS_DATE      DATE,
  ACT_INS_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.CURRENCYCODE ADD (
  CONSTRAINT PK_CURRENCYCODE
 PRIMARY KEY
 (CURRENCYCODE))
/

