CREATE TABLE VMSCMS.DCMS_CARD_DETAILS_TABLE
(
  CARD_NO        VARCHAR2(20 BYTE),
  BCIF_ID        VARCHAR2(20 BYTE),
  PARAMETER1     VARCHAR2(20 BYTE),
  PARAMETER2     VARCHAR2(20 BYTE),
  PARAMETER3     VARCHAR2(20 BYTE),
  PARAMETER4     VARCHAR2(20 BYTE),
  PARAMETER5     VARCHAR2(20 BYTE),
  BCI_LUPD_DATE  DATE,
  BCI_INST_CODE  NUMBER(10),
  BCI_LUPD_USER  NUMBER(10),
  BCI_INS_DATE   DATE,
  BCI_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


