CREATE TABLE VMSCMS.FHM_RESP_TMP
(
  FRT_MSG_ID     NUMBER                         NOT NULL,
  FRT_TRACE_ID   NUMBER(10),
  FRT_ISO_MSG    VARCHAR2(2048 BYTE),
  FRT_MSG_TYPE   VARCHAR2(5 BYTE),
  FRT_FUNC_CODE  NUMBER(10),
  FRT_RESP_CODE  CHAR(3 BYTE),
  FRT_UPD_DATE   DATE                           DEFAULT SYSDATE,
  FRT_LUPD_DATE  DATE,
  FRT_INST_CODE  NUMBER(10),
  FRT_LUPD_USER  NUMBER(10),
  FRT_INS_DATE   DATE,
  FRT_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


