CREATE TABLE VMSCMS.FHM_MSG_MAST
(
  FMM_MSG_TYPE   VARCHAR2(5 BYTE),
  FMM_MSG_DESC   VARCHAR2(200 BYTE),
  FMM_RESP_MSG   VARCHAR2(5 BYTE),
  FMM_LUPD_DATE  DATE,
  FMM_INST_CODE  NUMBER(10),
  FMM_LUPD_USER  NUMBER(10),
  FMM_INS_DATE   DATE,
  FMM_INS_USER   NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


