CREATE TABLE VMSCMS.FHM_DE_MAST
(
  FDM_DE_CODE     VARCHAR2(6 BYTE),
  FDM_DE_POS      NUMBER(10),
  FDM_DE_DESC     VARCHAR2(200 BYTE),
  FDM_CONS_VALUE  VARCHAR2(20 BYTE),
  FDM_SUB_FLAG    CHAR(1 BYTE),
  FDM_DATA_MAP    VARCHAR2(50 BYTE),
  FDM_DATA_LEN    NUMBER(10),
  FDM_LUPD_DATE   DATE,
  FDM_INST_CODE   NUMBER(10),
  FDM_LUPD_USER   NUMBER(10),
  FDM_INS_DATE    DATE,
  FDM_INS_USER    NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


