CREATE TABLE VMSCMS.FHM_SENT_MSGS
(
  FSM_MSG_ID         NUMBER                     NOT NULL,
  FSM_TRACE_ID       NUMBER(10),
  FSM_CARD_NO        NUMBER(16),
  FSM_ISO_MSG        VARCHAR2(2048 BYTE),
  FSM_REQ_DATE_TIME  DATE,
  FSM_REQ_ATTMPT     NUMBER(10),
  FSM_LUPD_DATE      DATE,
  FSM_INST_CODE      NUMBER(10),
  FSM_LUPD_USER      NUMBER(10),
  FSM_INS_DATE       DATE,
  FSM_INS_USER       NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.FHM_SENT_MSGS ADD (
  CONSTRAINT FSM_MSG_ID_PK
 PRIMARY KEY
 (FSM_MSG_ID))
/

