CREATE TABLE VMSCMS.FHM_REQ_MAST
(
  FRM_FUNC_ID    NUMBER(10)                     NOT NULL,
  FRM_FUNC_DESC  VARCHAR2(32 BYTE),
  FRM_LUPD_DATE  DATE,
  FRM_INST_CODE  NUMBER(10),
  FRM_LUPD_USER  NUMBER(10),
  FRM_INS_DATE   DATE,
  FRM_INS_USER   NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.FHM_REQ_MAST ADD (
  CONSTRAINT FRM_FUNC_ID_PK
 PRIMARY KEY
 (FRM_FUNC_ID))
/

