CREATE TABLE VMSCMS.FHM_MSG_LOG
(
  FML_MSG_ID         NUMBER                     NOT NULL,
  FML_TRACE_ID       NUMBER(10),
  FML_CARD_NO        NUMBER(16),
  FML_REQ_MSG        VARCHAR2(2048 BYTE),
  FML_REQ_DATE_TIME  DATE,
  FML_RES_DATE_TIME  DATE,
  FML_RES_MSG        VARCHAR2(2048 BYTE),
  FML_MSG_TYPE       VARCHAR2(50 BYTE),
  FML_FUNC_CODE      NUMBER(10),
  FML_RESP_CODE      CHAR(3 BYTE),
  FML_UPD_DATE       DATE                       DEFAULT SYSDATE,
  FML_REQ_ATTMPT     NUMBER(3),
  FML_LUPD_DATE      DATE,
  FML_INST_CODE      NUMBER(10),
  FML_LUPD_USER      NUMBER(10),
  FML_INS_DATE       DATE,
  FML_INS_USER       NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.FHM_MSG_LOG ADD (
  CONSTRAINT FML_MSG_ID_PK
 PRIMARY KEY
 (FML_MSG_ID))
/

