CREATE TABLE VMSCMS.FHM_PRM_MAST
(
  FPM_PRM_ID     NUMBER(10)                     NOT NULL,
  FPM_PRM_DESC   VARCHAR2(32 BYTE),
  FPM_PRM_VALUE  VARCHAR2(32 BYTE),
  FPM_LUPD_DATE  DATE,
  FPM_INST_CODE  NUMBER(10),
  FPM_LUPD_USER  NUMBER(10),
  FPM_INS_DATE   DATE,
  FPM_INS_USER   NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.FHM_PRM_MAST ADD (
  CONSTRAINT FPM_PRM_ID_PK
 PRIMARY KEY
 (FPM_PRM_ID))
/

