CREATE TABLE VMSCMS.FHM_MSG_DE
(
  FMD_MSG_TYPE     VARCHAR2(5 BYTE),
  FMD_FUNC_CODE    NUMBER(10),
  FMD_DE_CODE      VARCHAR2(6 BYTE),
  FMD_SUB_DE       NUMBER(10),
  FMD_DEF_VALUE    VARCHAR2(50 BYTE),
  FMD_PARAM_VALUE  VARCHAR2(10 BYTE),
  FMD_LUPD_DATE    DATE,
  FMD_INST_CODE    NUMBER(10),
  FMD_LUPD_USER    NUMBER(10),
  FMD_INS_DATE     DATE,
  FMD_INS_USER     NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.FHM_MSG_DE ADD (
  CONSTRAINT FHM_MSG_DE_UNIQ
 UNIQUE (FMD_MSG_TYPE, FMD_FUNC_CODE, FMD_DE_CODE, FMD_SUB_DE))
/

