CREATE TABLE VMSCMS.FHM_SUB_DE
(
  FSD_DE_CODE      VARCHAR2(6 BYTE),
  FSD_SUB_DE       NUMBER(10),
  FSD_SUB_DESC     VARCHAR2(100 BYTE),
  FSD_POS_FROM     NUMBER(10),
  FSD_POS_TO       NUMBER(10),
  FSD_DATA_TYPE    CHAR(1 BYTE),
  FSD_DATA_LENGTH  NUMBER(10),
  FSD_PAD_CHAR     CHAR(1 BYTE),
  FSD_PAD_DIR      CHAR(1 BYTE),
  FSD_CONS_VALUE   VARCHAR2(200 BYTE),
  FSD_DATA_MAP     VARCHAR2(50 BYTE),
  FSD_LUPD_DATE    DATE,
  FSD_INST_CODE    NUMBER(10),
  FSD_LUPD_USER    NUMBER(10),
  FSD_INS_DATE     DATE,
  FSD_INS_USER     NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


