CREATE TABLE VMSCMS.FHM_MSG_FUNC
(
  FMF_MSG_TYPE   VARCHAR2(5 BYTE)               NOT NULL,
  FMF_FUNC_CODE  NUMBER(10)                     NOT NULL,
  FMF_PRI_MAP    VARCHAR2(16 BYTE)              NOT NULL,
  FMF_SEC_MAP    VARCHAR2(16 BYTE)              NOT NULL,
  FMF_LUPD_DATE  DATE,
  FMF_INST_CODE  NUMBER(10),
  FMF_LUPD_USER  NUMBER(10),
  FMF_INS_DATE   DATE,
  FMF_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


