CREATE TABLE VMSCMS.FHM_ISORESP_MAST
(
  FIM_RESP_CODE  VARCHAR2(10 BYTE),
  FIM_RESP_DESC  VARCHAR2(500 BYTE),
  FIM_LUPD_DATE  DATE,
  FIM_INST_CODE  NUMBER(10),
  FIM_LUPD_USER  NUMBER(10),
  FIM_INS_DATE   DATE,
  FIM_INS_USER   NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


