CREATE TABLE VMSCMS.FHM_RES_INFO
(
  FRI_MSG_ID     NUMBER                         NOT NULL,
  FRI_TEMP_ID    NUMBER(10)                     NOT NULL,
  FRI_PRM_ID     NUMBER(10),
  FRI_PRM_VALUE  VARCHAR2(64 BYTE),
  FRI_LUPD_DATE  DATE,
  FRI_INST_CODE  NUMBER(10),
  FRI_LUPD_USER  NUMBER(10),
  FRI_INS_DATE   DATE,
  FRI_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.FHM_RES_INFO ADD (
  CONSTRAINT FRI_MSG_ID_PK
 PRIMARY KEY
 (FRI_MSG_ID))
/

