CREATE TABLE VMSCMS.GEN_CURR_MAST_MAPS
(
  GCM_CURR_CODE     VARCHAR2(4 BYTE)            NOT NULL,
  GCM_CURR_DESC     VARCHAR2(50 BYTE),
  GCM_CURR_SYBL     VARCHAR2(5 BYTE),
  GCM_CNTRY_CODE    VARCHAR2(4 BYTE),
  GCM_CURR_EXP      NUMBER(10),
  GCM_ROUND_FACTOR  NUMBER(9,2),
  GCM_LAST_USER     NUMBER(10),
  GCM_LAST_DATE     DATE,
  GCM_LUPD_DATE     DATE,
  GCM_INST_CODE     NUMBER(10),
  GCM_LUPD_USER     NUMBER(10),
  GCM_INS_DATE      DATE,
  GCM_INS_USER      NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.GEN_CURR_MAST_MAPS ADD (
  CONSTRAINT PK_CURR_MAST_MAPS1
 PRIMARY KEY
 (GCM_CURR_CODE))
/

