CREATE TABLE VMSCMS.GEN_CNTRY_MAST_MAPS
(
  GCM_INST_CODE       NUMBER(10)                NOT NULL,
  GCM_CNTRY_CODE      VARCHAR2(4 BYTE)          NOT NULL,
  GCM_CURR_CODE       VARCHAR2(4 BYTE),
  GCM_CNTRY_NAME      VARCHAR2(50 BYTE),
  GCM_CNTRY_INITIALS  VARCHAR2(5 BYTE),
  GCM_LAST_USER       NUMBER(10),
  GCM_LAST_DATE       DATE,
  GCM_LUPD_DATE       DATE,
  GCM_LUPD_USER       NUMBER(10),
  GCM_INS_DATE        DATE,
  GCM_INS_USER        NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.GEN_CNTRY_MAST_MAPS ADD (
  CONSTRAINT PK_CNTRY_MAST_MAPS1
 PRIMARY KEY
 (GCM_CNTRY_CODE, GCM_INST_CODE))
/

