CREATE TABLE VMSCMS.GEN_SLAB_DEF
(
  GSD_SLAB_DEF   VARCHAR2(10 BYTE),
  GSD_SLAB_FROM  NUMBER(15),
  GSD_SLAB_TO    NUMBER(15),
  GSD_LUPD_DATE  DATE,
  GSD_INST_CODE  NUMBER(10),
  GSD_LUPD_USER  NUMBER(10),
  GSD_INS_DATE   DATE,
  GSD_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


