CREATE TABLE VMSCMS.GEN_CURR_MAST
(
  GCM_CURR_CODE     VARCHAR2(5 BYTE)            NOT NULL,
  GCM_CURR_NAME     VARCHAR2(10 BYTE)           NOT NULL,
  GCM_CURR_DESC     VARCHAR2(50 BYTE)           NOT NULL,
  GCM_BUYING_RATE   NUMBER,
  GCM_SELLING_RATE  NUMBER,
  GCM_LUPD_USER     NUMBER(5),
  GCM_LUPD_DATE     DATE,
  GCM_INST_CODE     NUMBER(10),
  GCM_INS_DATE      DATE,
  GCM_INS_USER      NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.GEN_CURR_MAST ADD (
  CONSTRAINT PK_CURR_MAST
 PRIMARY KEY
 (GCM_INST_CODE, GCM_CURR_CODE),
  CONSTRAINT UK_CURR_MAST
 UNIQUE (GCM_INST_CODE, GCM_CURR_NAME))
/

