CREATE TABLE VMSCMS.HSM_PRINT_FORMAT_DETAIL
(
  HPD_HSM_NUMBER         NUMBER(5)              NOT NULL,
  HPD_LINE_NUMBER        NUMBER(2),
  HPD_FIELD_NUMBER       NUMBER(2),
  HPD_FIELD_DESCRIPTION  VARCHAR2(20 BYTE),
  HPD_INS_DATE           DATE,
  HPD_LUPD_DATE          DATE,
  HPD_INST_CODE          NUMBER(10),
  HPD_LUPD_USER          NUMBER(10),
  HPD_INS_USER           NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


