CREATE TABLE VMSCMS.HSM_LOG_DETAIL
(
  HLD_HSM_NUMBER       NUMBER(5)                NOT NULL,
  HLD_PAN_CODE         VARCHAR2(19 BYTE),
  HLD_REQUEST_CODE     VARCHAR2(2 BYTE),
  HLD_PIN_OFFSET       VARCHAR2(5 BYTE),
  HLD_RESPONSE_STATUS  VARCHAR2(15 BYTE),
  HLD_RESPONSE_CODE    VARCHAR2(2 BYTE),
  HLD_PINGEN_DATE      DATE,
  HLD_PINGEN_FLAG      VARCHAR2(1 BYTE),
  HLD_PINPRINT_FLAG    VARCHAR2(1 BYTE),
  HLD_PINGEN_USER      VARCHAR2(5 BYTE),
  HLD_INS_DATE         DATE,
  HLD_LUPD_DATE        DATE,
  HLD_INST_CODE        NUMBER(10),
  HLD_LUPD_USER        NUMBER(10),
  HLD_INS_USER         NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


