CREATE TABLE VMSCMS.HSM_CMD_MAST
(
  HCM_HSM_NUMBER       NUMBER(5)                NOT NULL,
  HCM_COMMAND_SEQ      NUMBER(5),
  HCM_COMMAND_DESC     VARCHAR2(10 BYTE),
  HCM_SERVER_COMMAND   VARCHAR2(3 BYTE),
  HCM_RESPONSE_LENGTH  NUMBER(4),
  HCM_COMMAND_TYPE     VARCHAR2(15 BYTE),
  HCM_INS_DATE         DATE,
  HCM_LUPD_DATE        DATE,
  HCM_INST_CODE        NUMBER(10),
  HCM_LUPD_USER        NUMBER(10),
  HCM_INS_USER         NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


