CREATE TABLE VMSCMS.HSM_CONFIG_MASTER
(
  HCM_NUMBER     NUMBER(5)                      NOT NULL,
  HSM_PROCESS    VARCHAR2(30 BYTE),
  HCM_LUPD_DATE  DATE,
  HCM_INST_CODE  NUMBER(10),
  HCM_LUPD_USER  NUMBER(10),
  HCM_INS_DATE   DATE,
  HCM_INS_USER   NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


