CREATE TABLE VMSCMS.HSM_PRINT_FORMAT_HEADER
(
  HPH_HSM_NUMBER      NUMBER(5)                 NOT NULL,
  HPH_PAGE_LENGTH     NUMBER(2),
  HPH_COLOUMN_LENGTH  NUMBER(2),
  HPH_TOTAL_COLUMNS   NUMBER(2),
  HPH_CUSTOM_FOOTER   VARCHAR2(40 BYTE),
  HPH_HEADER_LENGTH   NUMBER(2),
  HPH_FOOTER_LENGTH   NUMBER(2),
  HPH_INS_DATE        DATE,
  HPH_LUPD_DATE       DATE,
  HPH_INST_CODE       NUMBER(10),
  HPH_LUPD_USER       NUMBER(10),
  HPH_INS_USER        NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


