CREATE TABLE VMSCMS.HSM_SERVER_MASTER
(
  HSM_NUMBER                 NUMBER(5),
  HSM_NAME                   VARCHAR2(40 BYTE),
  HSM_MODEL                  VARCHAR2(25 BYTE),
  HSM_MESSAGE_HEADER_LENGTH  NUMBER(5)          NOT NULL,
  HSM_CONNECTION_TYPE        VARCHAR2(10 BYTE),
  HSM_IP_NUMBER              VARCHAR2(15 BYTE),
  HSM_PORT_NUMBER            VARCHAR2(5 BYTE),
  HSM_PIN_LENGTH             NUMBER(2)          NOT NULL,
  HSM_ENCRYPTED_PIN_LENGTH   NUMBER(2)          NOT NULL,
  HSM_PAN_LENGTH             NUMBER(2),
  HSM_PAN_VERIFY             NUMBER(2),
  HSM_PAN_OFFSET             NUMBER(2),
  HSM_PAD_CHAR               VARCHAR2(1 BYTE),
  HSM_DECI_VALUE             VARCHAR2(16 BYTE),
  HSM_PVV_KEY                VARCHAR2(16 BYTE)  NOT NULL,
  HSM_INS_DATE               DATE               NOT NULL,
  HSM_LUPD_DATE              DATE               NOT NULL,
  HSM_CVK_A                  VARCHAR2(16 BYTE),
  HSM_CVK_B                  VARCHAR2(16 BYTE),
  HSM_ACTIVE_STATUS          CHAR(1 BYTE),
  HSM_MAX_CONN               VARCHAR2(15 BYTE),
  HSM_PPK_KEY                VARCHAR2(32 BYTE),
  HSM_LUPD_USER              NUMBER(10),
  HSM_INS_USER               NUMBER(10),
  HSM_INST_CODE              NUMBER(3),
  HSM_PINBLOCK_FRMT          VARCHAR2(2 BYTE),
  HSM_PVKKEY_SPEC            NUMBER(2),
  HSM_PPKKEY_SPEC            NUMBER(2),
  HSM_PPKOKEY_SEPC           VARCHAR2(16 BYTE),
  HSM_TYPE                   VARCHAR2(20 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.HSM_SERVER_MASTER ADD (
  CONSTRAINT PK_HSM_SERVMASTER
 PRIMARY KEY
 (HSM_NUMBER))
/

