CREATE TABLE VMSCMS.HSM_PRINT_FORMAT
(
  HPF_HSM_NUMBER        NUMBER(5)               NOT NULL,
  HPF_ROW_POSITION      VARCHAR2(3 BYTE),
  HPF_COLOUMN_POSITION  VARCHAR2(3 BYTE),
  HPF_COLUMN_NUMBER     VARCHAR2(3 BYTE),
  HPF_COLUMN_NAME       VARCHAR2(40 BYTE),
  HPF_INS_DATE          DATE,
  HPF_LUPD_DATE         DATE,
  HPF_INST_CODE         NUMBER(10),
  HPF_LUPD_USER         NUMBER(10),
  HPF_INS_USER          NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


