CREATE TABLE VMSCMS.IKIT_RE_UPD
(
  BRANCH         VARCHAR2(6 BYTE),
  ACCT_NO        VARCHAR2(20 BYTE),
  UNFREEZE_DATE  DATE,
  ACC_LUPD_DATE  DATE,
  ACC_INST_CODE  NUMBER(10),
  ACC_LUPD_USER  NUMBER(10),
  ACC_INS_DATE   DATE,
  ACC_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


