CREATE TABLE VMSCMS.ILFDATA
(
  RBI_RECON             NUMBER(1)               NOT NULL,
  RBI_PROCESS_DATE      VARCHAR2(20 BYTE)       NOT NULL,
  RBI_FILE_TYPE         VARCHAR2(4 BYTE),
  RBI_FILE_NAME         VARCHAR2(25 BYTE)       NOT NULL,
  RBI_REC_TYP           VARCHAR2(6 BYTE),
  RBI_TRAN_TYP          VARCHAR2(4 BYTE),
  RBI_RESP_CDE          VARCHAR2(8 BYTE),
  RBI_RVSL_CDE          VARCHAR2(2 BYTE),
  RBI_POST_DAT          VARCHAR2(6 BYTE),
  RBI_ACQ_INST_ID_NUM   VARCHAR2(11 BYTE),
  RBI_TERM_ID           VARCHAR2(16 BYTE),
  RBI_TERM_NAME_LOC     VARCHAR2(25 BYTE),
  RBI_TERM_OWNER_NAME   VARCHAR2(22 BYTE),
  RBI_TERM_CITY         VARCHAR2(13 BYTE),
  RBI_TERM_ST_X         VARCHAR2(3 BYTE),
  RBI_TERM_CNTRY_X      VARCHAR2(2 BYTE),
  RBI_SEQ_NUM           VARCHAR2(12 BYTE),
  RBI_INVOICE_NUM       VARCHAR2(10 BYTE),
  RBI_RETL_ID           VARCHAR2(19 BYTE),
  RBI_TRAN_CDE          VARCHAR2(5 BYTE),
  RBI_RESPONDER         VARCHAR2(1 BYTE),
  RBI_PAN               VARCHAR2(19 BYTE),
  RBI_MBR_NUM           VARCHAR2(3 BYTE),
  RBI_AMT1              VARCHAR2(19 BYTE),
  RBI_AMT2              VARCHAR2(19 BYTE),
  RBI_SETL_CRNCY_CDE    VARCHAR2(3 BYTE),
  RBI_SETL_CONV_RATE    VARCHAR2(8 BYTE),
  RBI_TRAN_DAT          VARCHAR2(6 BYTE),
  RBI_TRAN_TIM          VARCHAR2(8 BYTE),
  RBI_PT_SRV_COND_CDE   VARCHAR2(2 BYTE),
  RBI_PT_SRV_ENTRY_MDE  VARCHAR2(3 BYTE),
  RBI_FROM_ACCT_TYP     VARCHAR2(2 BYTE),
  RBI_FROM_ACCT         VARCHAR2(28 BYTE),
  RBI_ORIG_CRNCY_CDE    VARCHAR2(3 BYTE),
  RBI_RESP              VARCHAR2(3 BYTE),
  RBI_MAT_CAT_CODE      VARCHAR2(10 BYTE),
  RBI_IBR_GEN           NUMBER(1),
  TRACE_NUM             VARCHAR2(10 BYTE),
  TO_ACCT_TYP           VARCHAR2(2 BYTE),
  TO_ACCT               VARCHAR2(40 BYTE),
  IDCOL                 VARCHAR2(10 BYTE),
  IDC_LUPD_DATE         DATE,
  IDC_INST_CODE         NUMBER(10),
  IDC_LUPD_USER         NUMBER(10),
  IDC_INS_DATE          DATE,
  IDC_INS_USER          NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


