CREATE TABLE VMSCMS.INVENTORYSTATUS
(
  INVENTORYSTATUSID        NUMBER(10)           NOT NULL,
  INSTITUTION              VARCHAR2(20 BYTE),
  INVENTORYSTATUSCODE      VARCHAR2(15 BYTE),
  ISRECEIPT                CHAR(1 BYTE),
  ISISSUE                  CHAR(1 BYTE),
  ISINTERLOCATIONTRANSFER  CHAR(1 BYTE),
  ISADJUSTMENT             CHAR(1 BYTE),
  INS_LUPD_DATE            DATE,
  INS_INST_CODE            NUMBER(10),
  INS_LUPD_USER            NUMBER(10),
  INS_INS_DATE             DATE,
  INS_INS_USER             NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.INVENTORYSTATUS ADD (
  CONSTRAINT PK_NTORYSTATUS1
 PRIMARY KEY
 (INVENTORYSTATUSID))
/

