CREATE TABLE VMSCMS.MCCODE_GROUP
(
  MCCODE         VARCHAR2(4 BYTE)               NOT NULL,
  MCCODEGROUPID  VARCHAR2(4 BYTE)               NOT NULL,
  MCC_LUPD_DATE  DATE,
  MCC_INST_CODE  NUMBER(10),
  MCC_LUPD_USER  NUMBER(10),
  MCC_INS_DATE   DATE,
  MCC_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.MCCODE_GROUP ADD (
  CONSTRAINT MCCODEGROUP
 PRIMARY KEY
 (MCCODE, MCCODEGROUPID))
/

ALTER TABLE VMSCMS.MCCODE_GROUP ADD (
  CONSTRAINT MCCGROUP_PK 
 FOREIGN KEY (MCCODEGROUPID) 
 REFERENCES VMSCMS.MCCODEGROUPING (MCCODEGROUPID))
/

