CREATE TABLE VMSCMS.NEW_CMS_STATEMENTS_LOG
(
  CSL_PAN_NO            VARCHAR2(20 BYTE),
  CSL_OPENING_BAL       NUMBER(20,3),
  CSL_TRANS_AMOUNT      NUMBER(20,3),
  CSL_TRANS_TYPE        VARCHAR2(2 BYTE),
  CSL_TRANS_DATE        DATE,
  CSL_CLOSING_BALANCE   NUMBER(20,3),
  CSL_TRANS_NARRRATION  VARCHAR2(50 BYTE),
  CSL_LUPD_DATE         DATE,
  CSL_INST_CODE         NUMBER(10),
  CSL_LUPD_USER         NUMBER(10),
  CSL_INS_DATE          DATE,
  CSL_INS_USER          NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


