CREATE TABLE VMSCMS.PCMS_INVENTORY_LOCTYPE
(
  LOC_TYPE_ID           NUMBER(19)              NOT NULL,
  INSTITUTION           VARCHAR2(20 BYTE),
  LOC_TYPE              VARCHAR2(20 BYTE)       NOT NULL,
  LOC_TYPE_DESC         VARCHAR2(20 BYTE)       NOT NULL,
  IS_RECEIPT            CHAR(1 BYTE),
  IS_ISSUE              CHAR(1 BYTE),
  IS_INTERLOC           CHAR(1 BYTE),
  IS_ADJUSTMENT         CHAR(1 BYTE),
  IS_LOC_CODE_RELEVANT  CHAR(1 BYTE),
  IS_REQUISITION        CHAR(1 BYTE)            DEFAULT 'N',
  IS_COURIER            CHAR(1 BYTE)            DEFAULT 'N',
  INS_LUPD_DATE         DATE,
  INS_LUPD_USER         NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_INVENTORY_LOCTYPE ADD (
  CONSTRAINT PK__INVENTORY_LOCTYPE1
 PRIMARY KEY
 (LOC_TYPE_ID))
/

