CREATE TABLE VMSCMS.PCMS_PROCESS_STATUS
(
  PPS_START_TIME      DATE,
  PPS_END_TIME        DATE,
  PPS_PROCESS_NAME    VARCHAR2(50 BYTE),
  PPS_PROCESS_STATUS  VARCHAR2(1 BYTE),
  PPS_REASON          VARCHAR2(500 BYTE),
  PPS_INS_DATE        DATE,
  PPS_PROCESS_ID      VARCHAR2(5 BYTE),
  PPS_FILE_ID         VARCHAR2(5 BYTE)          DEFAULT 0,
  PPS_FILE_NAME       VARCHAR2(70 BYTE),
  PPS_PROCESS_TYPE    VARCHAR2(1 BYTE)          DEFAULT 'S',
  PPS_INST_CODE       NUMBER(3)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


