CREATE TABLE VMSCMS.PCMS_FILEUPLOAD_STAT
(
  PFS_FILE_NAME  VARCHAR2(50 BYTE)              NOT NULL,
  PFS_SEQ_CODE   VARCHAR2(20 BYTE)              NOT NULL,
  PFS_FILE_STAT  CHAR(1 BYTE)                   NOT NULL,
  PFS_LUPD_USER  INTEGER                        NOT NULL,
  PFS_LUPD_DATE  DATE                           DEFAULT sysdate               NOT NULL,
  PFS_INST_CODE  NUMBER(10),
  PFS_INS_DATE   DATE,
  PFS_INS_USER   NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_FILEUPLOAD_STAT ADD (
  CONSTRAINT PK_PCMS_FILEUPLOAD_STAT
 PRIMARY KEY
 (PFS_SEQ_CODE))
/

