CREATE TABLE VMSCMS.PCMS_MARC_INFO_ENTRY
(
  PMI_INST_CODE             NUMBER(3),
  PMI_FILE_NAME             VARCHAR2(35 BYTE),
  PMI_ROW_ID                VARCHAR2(8 BYTE)    NOT NULL,
  PMI_APPL_CODE             VARCHAR2(30 BYTE),
  PMI_APPL_NO               VARCHAR2(20 BYTE),
  PMI_PAN_CODE              VARCHAR2(19 BYTE),
  PMI_MBR_NUMB              VARCHAR2(3 BYTE),
  PMI_CRD_STAT              CHAR(1 BYTE),
  PMI_EXP_DAT               VARCHAR2(4 BYTE),
  PMI_REC_TYP               CHAR(1 BYTE),
  PMI_CRD_TYP               VARCHAR2(5 BYTE),
  PMI_REQUESTER_NAME        VARCHAR2(30 BYTE),
  PMI_PROD_CODE             VARCHAR2(12 BYTE),
  PMI_CARD_TYPE             NUMBER(2)           DEFAULT 1,
  PMI_SEG12_BRANCH_NUM      VARCHAR2(4 BYTE),
  PMI_FIID                  VARCHAR2(4 BYTE),
  PMI_TITLE                 VARCHAR2(5 BYTE),
  PMI_SEG12_NAME_LINE1      VARCHAR2(30 BYTE)   NOT NULL,
  PMI_SEG12_NAME_LINE2      VARCHAR2(30 BYTE),
  PMI_BIRTH_DATE            DATE,
  PMI_MOTHER_NAME           VARCHAR2(40 BYTE),
  PMI_HOBBIES               VARCHAR2(10 BYTE),
  PMI_CUST_ID               VARCHAR2(4 BYTE),
  PMI_COMM_TYPE             VARCHAR2(3 BYTE),
  PMI_SEG12_ADDR_LINE1      VARCHAR2(34 BYTE),
  PMI_SEG12_ADDR_LINE2      VARCHAR2(34 BYTE),
  PMI_SEG12_CITY            VARCHAR2(22 BYTE),
  PMI_SEG12_STATE           VARCHAR2(3 BYTE),
  PMI_SEG12_POSTAL_CODE     VARCHAR2(15 BYTE),
  PMI_SEG12_COUNTRY_CODE    VARCHAR2(3 BYTE),
  PMI_SEG12_MOBILENO        VARCHAR2(15 BYTE),
  PMI_SEG12_HOMEPHONE_NO    VARCHAR2(15 BYTE),
  PMI_SEG12_OFFICEPHONE_NO  VARCHAR2(15 BYTE),
  PMI_SEG12_EMAILID         VARCHAR2(34 BYTE),
  PMI_PROD_AMT              VARCHAR2(10 BYTE),
  PMI_FEE_AMT               VARCHAR2(10 BYTE),
  PMI_TOT_AMT               VARCHAR2(10 BYTE),
  PMI_PAYMENT_MODE          VARCHAR2(15 BYTE),
  PMI_INSTRUMENT_NO         VARCHAR2(15 BYTE),
  PMI_INSTRUMENT_AMT        VARCHAR2(10 BYTE),
  PMI_DRAWN_DATE            DATE,
  PMI_PAYREF_NO             VARCHAR2(20 BYTE),
  PMI_EMP_ID                VARCHAR2(15 BYTE),
  PMI_KYC_REASON            VARCHAR2(30 BYTE),
  PMI_KYC_FLAG              VARCHAR2(1 BYTE)    DEFAULT 'P'                   NOT NULL,
  PMI_ADDON_FLAG            VARCHAR2(6 BYTE)    DEFAULT 'False',
  PMI_VIRTUAL_ACCT          VARCHAR2(19 BYTE),
  PMI_DOCUMENT_VERIFY       VARCHAR2(100 BYTE),
  PMI_EXCHANGE_RATE         VARCHAR2(25 BYTE),
  PMI_UPLD_STAT             VARCHAR2(1 BYTE),
  PMI_APPROVED              VARCHAR2(1 BYTE)    DEFAULT 'N',
  PMI_COMMENTS              VARCHAR2(200 BYTE),
  PMI_INSTRUMENT_REALISED   VARCHAR2(1 BYTE),
  PMI_PROCESS_MSG           VARCHAR2(500 BYTE),
  PMI_MAKER_USER_ID         NUMBER(5),
  PMI_MAKER_DATE            DATE,
  PMI_CHECKER_USER_ID       NUMBER(5),
  PMI_CHEKER_DATE           DATE,
  PMI_AUTH_USER_ID          NUMBER(5),
  PMI_AUTH_DATE             DATE,
  PMI_INS_USER              NUMBER(5),
  PMI_INS_DATE              DATE                NOT NULL,
  PMI_LUPD_USER             NUMBER(5),
  PMI_LUPD_DATE             DATE,
  PMI_MARC_CATG_CODE        VARCHAR2(4 BYTE),
  PMI_MARC_DESC             VARCHAR2(100 BYTE)  NOT NULL,
  PMI_ACTIVATION_STATUS     VARCHAR2(1 BYTE),
  PMI_MARC_PROD_TYPE        VARCHAR2(1 BYTE),
  PMI_MARC_CODE             VARCHAR2(4 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_MARC_INFO_ENTRY ADD (
  CONSTRAINT PK_MARC_INFO_ENTRY
 PRIMARY KEY
 (PMI_ROW_ID))
/

