CREATE TABLE VMSCMS.PCMS_INVENTORY_LOG
(
  PIL_REQUEST_ID        VARCHAR2(20 BYTE),
  PIL_BRANCH_CODE       VARCHAR2(6 BYTE),
  PIL_QUANTITY_RECEIVE  NUMBER(10),
  PIL_CARDTYPE_SNAME    VARCHAR2(3 BYTE),
  PIL_AMOUNT            NUMBER(20,3),
  PIL_STATUS            VARCHAR2(2 BYTE),
  PIL_QUANTITY_RETURN   NUMBER(10),
  PIL_MESSAGE           VARCHAR2(30 BYTE),
  PIL_BATCH_NO          VARCHAR2(15 BYTE),
  PIL_INST_CODE         NUMBER(3),
  PIL_LUPD_DATE         DATE,
  PIL_LUPD_USER         NUMBER(10),
  PIL_INS_DATE          DATE,
  PIL_INS_USER          NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_INVENTORY_LOG ADD (
  CONSTRAINT FK_ 
 FOREIGN KEY (PIL_INST_CODE, PIL_BRANCH_CODE) 
 REFERENCES VMSCMS.CMS_BRAN_MAST (CBM_INST_CODE,CBM_BRAN_CODE))
/

