CREATE TABLE VMSCMS.PCMS_CORPORATE_USER_MAST
(
  PCU_CORP_CODE      VARCHAR2(4 BYTE),
  PCU_CORP_ID        VARCHAR2(15 BYTE),
  PCU_CORP_PASSWORD  VARCHAR2(100 BYTE),
  PCU_INST_CODE      NUMBER,
  PCU_CORP_SUSP      CHAR(1 BYTE),
  PCU_LUPD_USER      NUMBER,
  PCU_LUPD_DATE      DATE,
  PCU_INST_USER      NUMBER,
  PCU_INST_DATE      DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


