CREATE TABLE VMSCMS.PCMS_PROCESS_DEFN_MAST
(
  PPM_INST_CODE     NUMBER(3),
  PPM_PROCESS_ID    NUMBER(5),
  PPM_FILE_ID       NUMBER(20),
  PPM_PROCESS_NAME  VARCHAR2(100 BYTE),
  PPM_INS_DATE      DATE,
  PPM_INS_USER      NUMBER(5),
  PPM_LUPD_DATE     DATE,
  PPM_LUPD_USER     NUMBER(5)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_PROCESS_DEFN_MAST ADD (
  CONSTRAINT PK_PPM_PROCESS_ID
 PRIMARY KEY
 (PPM_PROCESS_ID))
/

