CREATE TABLE VMSCMS.PCMS_HOLD_REASON
(
  PHR_INST_CODE      NUMBER(5)                  NOT NULL,
  PHR_TXN_ID         NUMBER(16),
  PHR_HOLD_STATUS    CHAR(1 BYTE),
  PHR_HOLDCOND_CODE  NUMBER(5,3),
  PHR_STATUS_FLAG    CHAR(1 BYTE),
  PHR_REPORT_FLAG    CHAR(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_HOLD_REASON ADD (
  CONSTRAINT PK_HOLDREASON
 PRIMARY KEY
 (PHR_INST_CODE, PHR_TXN_ID, PHR_HOLDCOND_CODE))
/

