CREATE TABLE VMSCMS.PCMS_TERMINAL_MAST
(
  PTM_INST_CODE                   NUMBER(3)     NOT NULL,
  PTM_TERMINAL_ID                 VARCHAR2(20 BYTE) NOT NULL,
  PTM_TERMINAL_DESC               VARCHAR2(30 BYTE),
  PTM_INS_USER                    NUMBER(5),
  PTM_INS_DATE                    DATE          NOT NULL,
  PTM_LUPD_USER                   NUMBER(5),
  PTM_LUPD_DATE                   DATE,
  PTM_RESPONSE_CODE               VARCHAR2(2 BYTE),
  PTM_APPLICATION_OPERATION_FLAG  VARCHAR2(1 BYTE),
  PTM_IDLEDISPLINE1               VARCHAR2(20 BYTE),
  PTM_IDLEDISPLINE2               VARCHAR2(20 BYTE),
  PTM_ADMINPIN                    VARCHAR2(6 BYTE),
  PTM_MERCHANT_ID                 VARCHAR2(15 BYTE),
  PTM_MAXTXNLIMIT                 VARCHAR2(12 BYTE),
  PTM_MINTXNLIMIT                 VARCHAR2(12 BYTE),
  PTM_TOTALTXNCNTR                VARCHAR2(4 BYTE),
  PTM_CHECKBINLENGTH              VARCHAR2(2 BYTE),
  PTM_DISPLAYPAN                  VARCHAR2(1 BYTE),
  PTM_PAN_MASKING                 VARCHAR2(1 BYTE),
  PTM_AMOUNT_DUAL_ENTRY           VARCHAR2(1 BYTE),
  PTM_SLIP_REQUIRED               VARCHAR2(1 BYTE),
  PTM_REPRINT_SLIP_REQUIRED       VARCHAR2(1 BYTE),
  PTM_ERRORSLIPREQUIRED           VARCHAR2(1 BYTE),
  PTM_PRINT_SLIP_NAME             VARCHAR2(20 BYTE),
  PTM_REPRINTSLIP_NAME            VARCHAR2(20 BYTE),
  PTM_SLIP_HEADER1                VARCHAR2(20 BYTE),
  PTM_SLIP_HEADER2                VARCHAR2(20 BYTE),
  PTM_TERMINAL_INDICATOR          VARCHAR2(1 BYTE) DEFAULT 0 NOT NULL,
  PTM_DISPLAY_PURCHASETXN         VARCHAR2(1 BYTE),
  PTM_DISPLAY_BALINQ              VARCHAR2(1 BYTE),
  PTM_DISPLAY_C2CTXN              VARCHAR2(1 BYTE),
  PTM_DISPLAY_PINCHG              VARCHAR2(1 BYTE),
  PTM_DISPLAY_MINSTMT             VARCHAR2(1 BYTE),
  PTM_SERVER_DATE                 VARCHAR2(8 BYTE),
  PTM_SERVER_TIME                 VARCHAR2(14 BYTE),
  PTM_OPERATOR_TIMEOUT            VARCHAR2(2 BYTE),
  PTM_MAINMENU_TIMEOUT            VARCHAR2(3 BYTE),
  PTM_TXN_TIMEOUT                 VARCHAR2(2 BYTE),
  PTM_TERM_LOCATION               VARCHAR2(50 BYTE),
  PTM_TERM_COUNTRY                VARCHAR2(10 BYTE),
  PTM_TERM_STATE                  VARCHAR2(10 BYTE),
  PTM_TERM_CITY                   VARCHAR2(10 BYTE),
  PTM_MACHINE_ID                  VARCHAR2(15 BYTE)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_TERMINAL_MAST ADD (
  CONSTRAINT PK_TERMAST_TERMINALID
 PRIMARY KEY
 (PTM_TERMINAL_ID))
/

