CREATE TABLE VMSCMS.PCMS_CUST_INBOX
(
  PCI_REQ_ID        NUMBER(10),
  PCI_RESP_ID       NUMBER(10),
  PCI_PAN_CODE      VARCHAR2(20 BYTE),
  PCI_SUBJECT       VARCHAR2(200 BYTE),
  PCI_MAIL_CONTENT  VARCHAR2(4000 BYTE),
  PCI_SENT_BY       NUMBER(5),
  PCI_SENT_DATE     DATE,
  PCI_LUPD_DATE     DATE,
  PCI_INST_CODE     NUMBER(10),
  PCI_LUPD_USER     NUMBER(10),
  PCI_INS_DATE      DATE,
  PCI_INS_USER      NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


