CREATE TABLE VMSCMS.PCMS_REQUISITION_CTRL
(
  PRC_REQUISITION_DATE  DATE,
  PRC_CTRL_NUMB         NUMBER,
  PRC_LUPD_DATE         DATE,
  PRC_INST_CODE         NUMBER(10),
  PRC_LUPD_USER         NUMBER(10),
  PRC_INS_DATE          DATE,
  PRC_INS_USER          NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


