CREATE TABLE VMSCMS.PCMS_CUST_OUTBOX
(
  PCO_REQ_ID        NUMBER(10),
  PCO_RESP_ID       NUMBER(10),
  PCO_PAN_CODE      VARCHAR2(20 BYTE),
  PCO_SUBJECT       VARCHAR2(200 BYTE),
  PCO_MAIL_CONTENT  VARCHAR2(4000 BYTE),
  PCO_SENT_DATE     DATE,
  PCO_LUPD_DATE     DATE,
  PCO_INST_CODE     NUMBER(10),
  PCO_LUPD_USER     NUMBER(10),
  PCO_INS_DATE      DATE,
  PCO_INS_USER      NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


