CREATE TABLE VMSCMS.PCMS_CAF_INFO_INV
(
  CCI_INST_CODE             NUMBER(3),
  CCI_FILE_NAME             VARCHAR2(50 BYTE),
  CCI_ROW_ID                VARCHAR2(8 BYTE)    NOT NULL,
  CCI_APPL_NO               VARCHAR2(20 BYTE),
  CCI_PAN_CODE              VARCHAR2(19 BYTE),
  CCI_MBR_NUMB              VARCHAR2(3 BYTE),
  CCI_CRD_STAT              CHAR(1 BYTE),
  CCI_EXP_DAT               VARCHAR2(4 BYTE),
  CCI_REC_TYP               CHAR(1 BYTE),
  CCI_CRD_TYP               VARCHAR2(5 BYTE),
  CCI_PROD_CODE             VARCHAR2(12 BYTE),
  CCI_CARD_TYPE             VARCHAR2(3 BYTE),
  CCI_SEG12_BRANCH_NUM      VARCHAR2(4 BYTE),
  CCI_FIID                  VARCHAR2(4 BYTE),
  CCI_SEG12_NAME_LINE1      VARCHAR2(30 BYTE),
  CCI_SEG12_NAME_LINE2      VARCHAR2(30 BYTE),
  CCI_CUST_ID               VARCHAR2(10 BYTE),
  CCI_COMM_TYPE             VARCHAR2(3 BYTE),
  CCI_SEG12_ADDR_LINE1      VARCHAR2(34 BYTE),
  CCI_SEG12_ADDR_LINE2      VARCHAR2(34 BYTE),
  CCI_SEG12_CITY            VARCHAR2(22 BYTE),
  CCI_SEG12_STATE           VARCHAR2(3 BYTE),
  CCI_SEG12_POSTAL_CODE     VARCHAR2(15 BYTE),
  CCI_SEG12_COUNTRY_CODE    VARCHAR2(3 BYTE),
  CCI_SEG12_MOBILENO        VARCHAR2(15 BYTE),
  CCI_SEG12_HOMEPHONE_NO    VARCHAR2(40 BYTE),
  CCI_SEG12_OFFICEPHONE_NO  VARCHAR2(15 BYTE),
  CCI_SEG12_EMAILID         VARCHAR2(34 BYTE),
  CCI_SEG31_LGTH            VARCHAR2(4 BYTE),
  CCI_SEG31_ACCT_CNT        VARCHAR2(4 BYTE),
  CCI_SEG31_TYP             VARCHAR2(2 BYTE),
  CCI_SEG31_NUM             VARCHAR2(19 BYTE),
  CCI_SEG31_STAT            CHAR(1 BYTE),
  CCI_PROD_AMT              VARCHAR2(10 BYTE),
  CCI_PAYREF_NO             VARCHAR2(20 BYTE),
  CCI_EMP_ID                VARCHAR2(15 BYTE),
  CCI_UPLD_STAT             VARCHAR2(1 BYTE),
  CCI_APPROVED              VARCHAR2(1 BYTE),
  CCI_PROCESS_MSG           VARCHAR2(500 BYTE),
  CCI_INS_USER              NUMBER(5),
  CCI_INS_DATE              DATE                NOT NULL,
  CCI_LUPD_USER             NUMBER(5),
  CCI_LUPD_DATE             DATE,
  CCI_TITLE                 VARCHAR2(10 BYTE),
  CCI_OADDR1                VARCHAR2(50 BYTE),
  CCI_OADDR2                VARCHAR2(34 BYTE),
  CCI_OCITY                 VARCHAR2(21 BYTE),
  CCI_OSTATE                VARCHAR2(3 BYTE),
  CCI_OPOSTAL_CODE          VARCHAR2(9 BYTE),
  CCI_OCOUNTRY_CODE         VARCHAR2(3 BYTE),
  CCI_OPHONE                VARCHAR2(40 BYTE),
  CCI_OMOBILE               VARCHAR2(15 BYTE),
  CCI_OEMAIL                VARCHAR2(30 BYTE),
  CCI_COMM_ADDR             VARCHAR2(3 BYTE),
  CCI_APPL_CODE             VARCHAR2(30 BYTE)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


