CREATE TABLE VMSCMS.PCMS_TXN_LOG_SNAP
(
  PTL_TXN_NO         VARCHAR2(10 BYTE),
  PTL_TXN_TYPE       VARCHAR2(10 BYTE),
  PTL_PAN_CODE       VARCHAR2(20 BYTE),
  PTL_AMOUNT         NUMBER(20,3),
  PTL_DATE           DATE,
  PTL_BRANCH_CODE    VARCHAR2(6 BYTE),
  PTL_DEBIT_CREDIT   VARCHAR2(1 BYTE),
  PTL_DESCRIPTION    VARCHAR2(13 BYTE),
  PTL_B24_UPLOAD     VARCHAR2(1 BYTE)           DEFAULT 'N',
  PTL_TRACK_TO_DATA  VARCHAR2(40 BYTE),
  PTL_INS_USER       NUMBER(5),
  PTL_INS_DATE       DATE,
  PTL_LUPD_USER      NUMBER(5),
  PTL_LUPD_DATE      DATE,
  PTL_INST_CODE      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_TXN_LOG_SNAP ADD (
  CHECK (PTL_B24_UPLOAD IN ('Y','N')),
  CONSTRAINT PK_PTL_TXN_NO
 PRIMARY KEY
 (PTL_TXN_NO))
/

