CREATE TABLE VMSCMS.PCMS_SCHEDULER_RUNNING
(
  PSR_INST_CODE          NUMBER(3),
  PSR_PHYSICAL_SERVER    VARCHAR2(75 BYTE),
  PSR_MANAGED_SERVER     VARCHAR2(50 BYTE),
  PSR_SCHEDULER_RUNNING  VARCHAR2(1 BYTE),
  PSR_INS_USER           NUMBER(5),
  PSR_INS_DATE           DATE,
  PSR_LUPD_USER          NUMBER(5),
  PSR_LUPD_DATE          DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


