CREATE TABLE VMSCMS.PCMS_TRANCODE_REVERSETRANCODE
(
  PTR_INST_CODE        NUMBER(3),
  PTR_ORGNL_TRAN_CODE  VARCHAR2(2 BYTE),
  PTR_RVSL_TRAN_CODE   VARCHAR2(2 BYTE),
  PTR_INS_USER         NUMBER(5),
  PTR_INS_DATE         DATE,
  PTR_LUPD_USER        NUMBER(5),
  PTR_LUPD_DATE        DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


