CREATE TABLE VMSCMS.PCMS_INVENTORY_LOCCODE
(
  LOC_CODE_ID    NUMBER(19)                     NOT NULL,
  INSTITUTION    VARCHAR2(20 BYTE),
  LOC_TYPE       VARCHAR2(20 BYTE)              NOT NULL,
  LOC_CODE       VARCHAR2(20 BYTE)              NOT NULL,
  LOC_CODE_DESC  VARCHAR2(50 BYTE)              NOT NULL,
  LOC_ADDRESS1   VARCHAR2(50 BYTE),
  LOC_ADDRESS2   VARCHAR2(50 BYTE),
  LOC_ADDRESS3   VARCHAR2(50 BYTE),
  PIN_CODE       VARCHAR2(10 BYTE),
  STATE          VARCHAR2(20 BYTE),
  COUNTRY        VARCHAR2(20 BYTE),
  IS_ACTIVE      CHAR(1 BYTE)                   NOT NULL,
  COU_LUPD_DATE  DATE,
  COU_INST_CODE  NUMBER(10),
  COU_LUPD_USER  NUMBER(10),
  COU_INS_DATE   DATE,
  COU_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_INVENTORY_LOCCODE ADD (
  CONSTRAINT PK__INVENTORY_LOCCODE1
 PRIMARY KEY
 (LOC_CODE_ID))
/

