CREATE TABLE VMSCMS.PCMS_CARDINVENTORY
(
  CARD_INVENTORY_ID         NUMBER(19)          NOT NULL,
  INSTITUTION               VARCHAR2(20 BYTE),
  PRODUCT_CODE              VARCHAR2(20 BYTE)   NOT NULL,
  PRODUCT_DESCRIPTION       VARCHAR2(20 BYTE)   NOT NULL,
  CARD_TYPE                 VARCHAR2(20 BYTE)   NOT NULL,
  CARD_DESCRIPTION          VARCHAR2(20 BYTE)   NOT NULL,
  AMOUNT                    VARCHAR2(20 BYTE)   NOT NULL,
  REQUISITION_NO            VARCHAR2(30 BYTE)   NOT NULL,
  APPLICATION_NO            VARCHAR2(20 BYTE),
  BATCH_NO                  VARCHAR2(20 BYTE)   NOT NULL,
  PAN_NO                    VARCHAR2(20 BYTE)   NOT NULL,
  SERIAL_NO                 VARCHAR2(20 BYTE)   NOT NULL,
  CARD_NO                   VARCHAR2(20 BYTE)   NOT NULL,
  TRACKING_NO               VARCHAR2(20 BYTE),
  INVENTORY_STATUS          VARCHAR2(20 BYTE)   NOT NULL,
  REASON_FOR_STATUS_CHANGE  VARCHAR2(20 BYTE),
  INVENTORY_LOC_TYPE        VARCHAR2(20 BYTE)   NOT NULL,
  INVENTORY_LOC_CODE        VARCHAR2(20 BYTE)   NOT NULL,
  BELONGSTO_LOC_TYPE        VARCHAR2(20 BYTE)   NOT NULL,
  BELONGSTO_LOC_CODE        VARCHAR2(20 BYTE)   NOT NULL,
  COURIER_CODE              VARCHAR2(20 BYTE),
  DELIVERY_DATE             VARCHAR2(20 BYTE),
  UDF1                      VARCHAR2(20 BYTE),
  UDF2                      VARCHAR2(20 BYTE),
  UDF3                      VARCHAR2(20 BYTE),
  AMO_LUPD_DATE             DATE,
  AMO_INST_CODE             NUMBER(10),
  AMO_LUPD_USER             NUMBER(10),
  AMO_INS_DATE              DATE,
  AMO_INS_USER              NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_CARDINVENTORY ADD (
  CONSTRAINT PK__CARDINVENTORY1
 PRIMARY KEY
 (CARD_INVENTORY_ID))
/

