CREATE TABLE VMSCMS.PCMS_TRANAUTH_PARAM
(
  PTP_INST_CODE    NUMBER(5),
  PTP_PARAM_NAME   VARCHAR2(90 BYTE),
  PTP_PARAM_VALUE  VARCHAR2(1 BYTE),
  PTP_LUPD_DATE    DATE,
  PTP_LUPD_USER    NUMBER(10),
  PTP_INS_DATE     DATE,
  PTP_INS_USER     NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


