CREATE TABLE VMSCMS.PCMS_INVENTORYSTATUS
(
  INVENTORY_STATUS_ID    NUMBER(19)             NOT NULL,
  INSTITUTION            VARCHAR2(20 BYTE),
  INVENTORY_STATUS_CODE  VARCHAR2(30 BYTE)      NOT NULL,
  IS_RECEIPT             CHAR(1 BYTE),
  IS_ISSUE               CHAR(1 BYTE),
  IS_INTERLOC            CHAR(1 BYTE),
  IS_ADJUSTMENT          CHAR(1 BYTE),
  INS_LUPD_DATE          DATE,
  INS_INST_CODE          NUMBER(10),
  INS_LUPD_USER          NUMBER(10),
  INS_INS_DATE           DATE,
  INS_INS_USER           NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_INVENTORYSTATUS ADD (
  CONSTRAINT PK__INVENTORYSTATUS1
 PRIMARY KEY
 (INVENTORY_STATUS_ID))
/

