CREATE TABLE VMSCMS.PCMS_INVENTORY_TRANSACTION_LOG
(
  TRANS_LOG_ID        NUMBER(19)                NOT NULL,
  INSTITUTION         VARCHAR2(20 BYTE),
  SERIAL_NO           VARCHAR2(20 BYTE),
  CARD_NO             VARCHAR2(20 BYTE),
  APPLICATION_NO      VARCHAR2(20 BYTE),
  INVENTORY_LOC_TYPE  VARCHAR2(20 BYTE),
  INVENTORY_LOC_CODE  VARCHAR2(20 BYTE),
  INVENTORY_STATUS    VARCHAR2(20 BYTE),
  FROM_INV_LOC_TYPE   VARCHAR2(20 BYTE),
  FROM_INV_LOC_CODE   VARCHAR2(20 BYTE),
  REFERENCE           VARCHAR2(20 BYTE),
  USER_ID             VARCHAR2(20 BYTE),
  CREATED_DATE        DATE,
  AUTHROIZED_BY       VARCHAR2(20 BYTE),
  AUTHORIZED_DATE     DATE,
  APP_LUPD_DATE       DATE,
  APP_INST_CODE       NUMBER(10),
  APP_LUPD_USER       NUMBER(10),
  APP_INS_DATE        DATE,
  APP_INS_USER        NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_INVENTORY_TRANSACTION_LOG ADD (
  CONSTRAINT PK__INVENTORY_TRANSACTION_LOG1
 PRIMARY KEY
 (TRANS_LOG_ID))
/

