CREATE TABLE VMSCMS.PCMS_ATTCHRULEGROUP_HIST
(
  PAH_INST_CODE       NUMBER(3),
  PAH_RULEGROUP_CODE  VARCHAR2(4 BYTE),
  PAH_OLD_FROMDATE    DATE,
  PAH_OLD_TODATE      DATE,
  PAH_CHANGE_LEVEL    VARCHAR2(3 BYTE),
  PAH_PROD_CODE       VARCHAR2(6 BYTE),
  PAH_CAT_TYPE        NUMBER(2),
  PAH_CUST_CATG       NUMBER(5),
  PAH_PAN_CODE        VARCHAR2(90 BYTE),
  PAH_MBR_NUMB        VARCHAR2(3 BYTE),
  PAH_CHANGE_SOURCE   VARCHAR2(3 BYTE),
  PAH_ACTION_TAKEN    VARCHAR2(6 BYTE),
  PAH_CHANGE_USER     NUMBER(5),
  PAH_CHANGE_DATE     DATE,
  PAH_LUPD_DATE       DATE,
  PAH_LUPD_USER       NUMBER(10),
  PAH_INS_DATE        DATE,
  PAH_INS_USER        NUMBER(10),
  PAH_EPAN_CODE       RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_ATTCHRULEGROUP_HIST ADD (
  CONSTRAINT FK_PCMS_ATTCHRULEGROUP_HIST 
 FOREIGN KEY (PAH_RULEGROUP_CODE) 
 REFERENCES VMSCMS.RULEGROUPING (RULEGROUPID))
/

