CREATE TABLE VMSCMS.PCMS_REQUISITION_TEMP
(
  REQUISITION_ID       NUMBER(19)               NOT NULL,
  REQUISITION_NO       VARCHAR2(30 BYTE)        NOT NULL,
  PRODUCT_CODE         VARCHAR2(20 BYTE)        NOT NULL,
  PRODUCT_DESCRIPTION  VARCHAR2(20 BYTE)        NOT NULL,
  CARD_TYPE            VARCHAR2(20 BYTE)        NOT NULL,
  CARD_DESCRIPTION     VARCHAR2(20 BYTE)        NOT NULL,
  AMOUNT               VARCHAR2(20 BYTE)        NOT NULL,
  LOC_TYPE             VARCHAR2(20 BYTE)        NOT NULL,
  LOC_CODE             VARCHAR2(20 BYTE)        NOT NULL,
  NO_OF_CARDS          NUMBER(10)               NOT NULL,
  IS_APPROVED          CHAR(1 BYTE),
  AMO_LUPD_DATE        DATE,
  AMO_INST_CODE        NUMBER(10),
  AMO_LUPD_USER        NUMBER(10),
  AMO_INS_DATE         DATE,
  AMO_INS_USER         NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


