CREATE TABLE VMSCMS.PCMS_PAYMENT_MASTER
(
  PIM_INST_CODE         NUMBER(3),
  PIM_APPLICATION_CODE  NUMBER(14),
  PIM_CUST_CODE         NUMBER(10),
  PIM_PAYMENT_MODE      VARCHAR2(10 BYTE),
  PIM_INSTRUMENT_NO     VARCHAR2(30 BYTE),
  PIM_AMOUNT            VARCHAR2(15 BYTE),
  PIM_INS_USER          NUMBER(5),
  PIM_INS_DATE          DATE,
  PIM_LUPD_USER         NUMBER(5),
  PIM_LUPD_DATE         DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


