CREATE TABLE VMSCMS.PCMS_CORP_PROD
(
  PCP_INST_CODE  NUMBER(5),
  PCP_CORP_CODE  VARCHAR2(4 BYTE),
  PCP_PROD_CODE  VARCHAR2(6 BYTE),
  PCP_CARD_TYPE  NUMBER(2),
  PCP_LUPD_USER  NUMBER(5),
  PCP_LUPD_DATE  DATE,
  PCP_INS_DATE   DATE,
  PCP_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_CORP_PROD ADD (
  CONSTRAINT PK_CORP_PROD
 PRIMARY KEY
 (PCP_INST_CODE, PCP_CORP_CODE, PCP_PROD_CODE, PCP_CARD_TYPE))
/

ALTER TABLE VMSCMS.PCMS_CORP_PROD ADD (
  CONSTRAINT FK_CORP_MAST 
 FOREIGN KEY (PCP_CORP_CODE) 
 REFERENCES VMSCMS.PCMS_CORPORATE_MASTER (PCM_ORGANIZATION_CODE),
  CONSTRAINT FK_PRODMAST_PRODCODE 
 FOREIGN KEY (PCP_INST_CODE, PCP_PROD_CODE) 
 REFERENCES VMSCMS.CMS_PROD_MAST (CPM_INST_CODE,CPM_PROD_CODE))
/

