CREATE TABLE VMSCMS.PCMS_ISSUE_CHARGE
(
  PIC_INST_CODE  NUMBER(3),
  PIC_ACCT_ID    NUMBER(10),
  PIC_PROD_AMT   VARCHAR2(10 BYTE),
  PIC_FEE_AMT    VARCHAR2(10 BYTE),
  PIC_FEE_CODE   NUMBER(3),
  PIC_LUPD_DATE  DATE,
  PIC_LUPD_USER  NUMBER(10),
  PIC_INS_DATE   DATE,
  PIC_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


