CREATE TABLE VMSCMS.PCMS_HOLD_CONDITIONS
(
  PHC_INST_CODE      NUMBER(5)                  NOT NULL,
  PHC_HOLDCOND_CODE  NUMBER(3)                  NOT NULL,
  PHC_HOLDCOND_DESC  VARCHAR2(200 BYTE),
  PHC_PARAM_AMOUNT   NUMBER(20,2),
  PHC_COND_TYPE      CHAR(1 BYTE),
  PHC_ENABLE_FLAG    CHAR(1 BYTE),
  PHC_CLASS_NAME     VARCHAR2(100 BYTE),
  PHC_REPORT_FLAG    CHAR(1 BYTE),
  PHC_NO_SWIPES      NUMBER(10),
  PHC_DEFINE_FLAG    CHAR(1 BYTE),
  PHC_MODIFIED_DATE  DATE,
  PHC_MODIFIED_USER  INTEGER,
  PHC_ABNORMAL_TIME  VARCHAR2(4 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_HOLD_CONDITIONS ADD (
  CONSTRAINT PK__HOLD_CONDITIONS1
 PRIMARY KEY
 (PHC_INST_CODE, PHC_HOLDCOND_CODE))
/

