CREATE TABLE VMSCMS.PCMS_RISK_MASTER
(
  PRM_INST_CODE         NUMBER(10),
  PRM_RISK_ID           NUMBER(10),
  PRM_RISK_DESCRIPTION  VARCHAR2(100 BYTE),
  PRM_INS_USER          NUMBER(10),
  PRM_INS_DATE          DATE,
  PRM_LUPD_USER         NUMBER(10),
  PRM_LUPD_DATE         DATE
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


