CREATE TABLE VMSCMS.PCMS_RISK_PRODUCT
(
  PRT_PROD_CODE       VARCHAR2(10 BYTE),
  PRT_CARD_TYPE       VARCHAR2(25 BYTE),
  PRT_RISK_ID         NUMBER(10),
  PRT_NO_TXN          NUMBER(10),
  PRT_TXN_AMT         NUMBER(10),
  PRT_EFFECTIVE_FROM  DATE,
  PRT_EFFECTIVE_TO    DATE,
  PRT_INS_USER        NUMBER(10),
  PRT_INS_DATE        DATE,
  PRT_LUPD_USER       NUMBER(10),
  PRT_LUPD_DATE       DATE,
  PRT_INST_CODE       NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_RISK_PRODUCT ADD (
  CONSTRAINT PK_PCMS_RISK_PRODUCT
 PRIMARY KEY
 (PRT_PROD_CODE, PRT_CARD_TYPE, PRT_RISK_ID, PRT_INST_CODE))
/

