CREATE TABLE VMSCMS.PCMS_PROD_RULEGROUP
(
  PPR_INST_CODE       NUMBER(3)                 NOT NULL,
  PPR_PROD_CODE       VARCHAR2(6 BYTE)          NOT NULL,
  PPR_RULEGROUP_CODE  VARCHAR2(4 BYTE)          NOT NULL,
  PPR_VALID_FROM      DATE                      NOT NULL,
  PPR_VALID_TO        DATE                      NOT NULL,
  PPR_INS_USER        NUMBER(5)                 NOT NULL,
  PPR_INS_DATE        DATE                      NOT NULL,
  PPR_LUPD_USER       NUMBER(5)                 NOT NULL,
  PPR_LUPD_DATE       DATE                      NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_PROD_RULEGROUP ADD (
  CONSTRAINT FK_PCMS_PROD_RULEGROUP 
 FOREIGN KEY (PPR_RULEGROUP_CODE) 
 REFERENCES VMSCMS.RULEGROUPING (RULEGROUPID))
/

