CREATE TABLE VMSCMS.PCMS_CORPORATE_RULEGROUP
(
  PCR_INST_CODE       NUMBER(3)                 NOT NULL,
  PCR_PROD_CODE       VARCHAR2(6 BYTE)          NOT NULL,
  PCR_CARD_TYPE       NUMBER(2)                 NOT NULL,
  PCR_RULEGROUP_CODE  VARCHAR2(4 BYTE)          NOT NULL,
  PCR_CORP_CODE       NUMBER(3)                 NOT NULL,
  PCR_VALID_FROM      DATE                      NOT NULL,
  PCR_VALID_TO        DATE                      NOT NULL,
  PCR_FLOW_SOURCE     VARCHAR2(3 BYTE)          NOT NULL,
  PCR_INS_USER        NUMBER(5)                 NOT NULL,
  PCR_INS_DATE        DATE                      NOT NULL,
  PCR_LUPD_USER       NUMBER(5)                 NOT NULL,
  PCR_LUPD_DATE       DATE                      NOT NULL
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.PCMS_CORPORATE_RULEGROUP ADD (
  CONSTRAINT FK_PCMS_CORPORATE_RULEGROUP 
 FOREIGN KEY (PCR_RULEGROUP_CODE) 
 REFERENCES VMSCMS.RULEGROUPING (RULEGROUPID))
/

