CREATE TABLE VMSCMS.PCMS_ERROR_LOG
(
  PCEL_INST_CODE    NUMBER(3),
  PCEL_FILE_NAME    VARCHAR2(35 BYTE),
  PCEL_PROCESS_ID   NUMBER(10),
  PCEL_SOURCE_NAME  VARCHAR2(30 BYTE),
  PCEL_ITEM_CODE    VARCHAR2(30 BYTE),
  PCEL_ERROR_MESG   VARCHAR2(500 BYTE)          NOT NULL,
  PCEL_PROB_ACTION  VARCHAR2(100 BYTE),
  PCEL_ROW_ID       VARCHAR2(5 BYTE),
  PCEL_ERROR_CNT    NUMBER(3),
  PCEL_LUPD_USER    NUMBER(5)                   NOT NULL,
  PCEL_LUPD_DATE    DATE                        NOT NULL,
  PCEL_SEQ#         NUMBER(20),
  PCE_INS_DATE      DATE,
  PCE_INS_USER      NUMBER(10)
)
TABLESPACE CMS_SML_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


