CREATE TABLE VMSCMS.PCMS_EMPLOYEE_MASTER_TEMP
(
  PEM_INST_CODE          NUMBER(3),
  PEM_ORGANIZATION_CODE  VARCHAR2(4 BYTE),
  PEM_EMP_CODE           VARCHAR2(10 BYTE),
  PEM_EMP_NAME           VARCHAR2(30 BYTE),
  PEM_UPD_USER           NUMBER(4),
  PEM_UPD_DATE           DATE,
  PEM_INS_USER           NUMBER(5),
  PEM_INS_DATE           DATE,
  PEM_EMP_ID             NUMBER(20),
  PEM_CUST_CODE          NUMBER(10),
  PEM_LUPD_DATE          DATE,
  PEM_LUPD_USER          NUMBER(10)
)
TABLESPACE CMS_MAST
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


