CREATE TABLE VMSCMS.PCMS_PROCESS_STAT
(
  PPS_INST_CODE       NUMBER(3),
  PPS_PROCESS_ID      NUMBER(5),
  PPS_LAST_RUN        DATE,
  PPS_LASTRUN_RESULT  VARCHAR2(1 BYTE),
  PPS_NEXT_RUN        DATE,
  PPS_INS_USER        NUMBER(5),
  PPS_INS_DATE        DATE,
  PPS_LUPD_USER       NUMBER(5),
  PPS_LUPD_DATE       DATE,
  PPS_STATUS          VARCHAR2(1 BYTE)          DEFAULT 'N',
  PPS_COMMENTS        VARCHAR2(50 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


