CREATE TABLE VMSCMS.PCMS_MARC_ACCT
(
  PMA_INST_CODE  NUMBER(3),
  PMA_ACCT_NO    VARCHAR2(20 BYTE),
  PMA_MCCODE     VARCHAR2(4 BYTE),
  PMA_INS_USER   NUMBER(5),
  PMA_INS_DATE   DATE,
  PMA_LUPD_USER  NUMBER(5),
  PMA_LUPD_DATE  DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


