CREATE TABLE VMSCMS.PNADATA
(
  BIN            VARCHAR2(6 BYTE),
  BRANCH         VARCHAR2(6 BYTE),
  HNI            VARCHAR2(1 BYTE),
  SEQ            VARCHAR2(5 BYTE),
  BIN_LUPD_DATE  DATE,
  BIN_INST_CODE  NUMBER(10),
  BIN_LUPD_USER  NUMBER(10),
  BIN_INS_DATE   DATE,
  BIN_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


