CREATE TABLE VMSCMS.PREPAID_TABLE_DTL
(
  PTD_TABLE_NAME          VARCHAR2(30 BYTE),
  PTD_RECORD_LENGTH_BYTE  NUMBER(9),
  PTD_REC_TOTSPACE_BYTE   NUMBER(9),
  PTD_NOOF_REC_1STYR      NUMBER(9),
  PTD_TOTSIZE_1STYR_INGB  NUMBER(9),
  PTD_TOTSIZE_2NDYR_INGB  NUMBER(9),
  PTD_TOTSIZE_3RDYR_INGB  NUMBER(9),
  PTD_INST_CODE           NUMBER(10),
  PTD_INS_DATE            DATE
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


