CREATE TABLE VMSCMS.PROCESS_AUDIT_LOG
(
  PAL_CARD_NO            VARCHAR2(90 BYTE),
  PAL_ACTIVITY_TYPE      VARCHAR2(50 BYTE),
  PAL_TRANSACTION_CODE   VARCHAR2(2 BYTE),
  PAL_DELV_CHNL          VARCHAR2(2 BYTE),
  PAL_TRAN_AMT           NUMBER,
  PAL_SOURCE             VARCHAR2(50 BYTE),
  PAL_INS_USER           NUMBER(5),
  PAL_INS_DATE           DATE,
  PAL_SUCCESS_FLAG       VARCHAR2(1 BYTE),
  PAL_PROCESS_MSG        VARCHAR2(300 BYTE),
  PAL_REASON_DESC        VARCHAR2(50 BYTE),
  PAL_REMARKS            VARCHAR2(100 BYTE),
  PAL_NEW_CARD           VARCHAR2(90 BYTE),
  PAL_SPPRT_TYPE         VARCHAR2(1 BYTE),
  PAL_INST_CODE          NUMBER(3),
  PAL_ATM_ONLINT_LIMIT   VARCHAR2(10 BYTE),
  PAL_ATM_OFFLINT_LIMIT  VARCHAR2(10 BYTE),
  PAL_POS_ONLINT_LIMIT   VARCHAR2(10 BYTE),
  PAL_POS_OFFLINT_LIMIT  VARCHAR2(10 BYTE),
  PAL_CARD_NO_ENCR       RAW(100),
  PAL_NEW_CARD_ENCR      RAW(100)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


