CREATE TABLE VMSCMS.REJ_PANS
(
  PAN            VARCHAR2(19 BYTE),
  PAN_LUPD_DATE  DATE,
  PAN_INST_CODE  NUMBER(10),
  PAN_LUPD_USER  NUMBER(10),
  PAN_INS_DATE   DATE,
  PAN_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


