CREATE TABLE VMSCMS.ROLL_PRXY_SHFL
(
  RPS_GPR_PAN         VARCHAR2(90 BYTE),
  RPS_GPROLD_PROXY    VARCHAR2(19 BYTE),
  RPS_GPRNEW_PROXY    VARCHAR2(19 BYTE),
  RPS_STATR_PAN       VARCHAR2(90 BYTE),
  RPS_STATROLD_PROXY  VARCHAR2(19 BYTE),
  RPS_STATRNEW_PROXY  VARCHAR2(19 BYTE),
  RPS_MSG             VARCHAR2(500 BYTE),
  DPS_FLAG            CHAR(1 BYTE)
)
TABLESPACE CMS_BKUP
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


