CREATE TABLE VMSCMS.RULEGEN
(
  RULEID                VARCHAR2(4 BYTE),
  RULEDESC              VARCHAR2(50 BYTE)       NOT NULL,
  RULETYPE              VARCHAR2(2 BYTE)        NOT NULL,
  AUTHTYPE              VARCHAR2(12 BYTE)       NOT NULL,
  RULEACTIVATIONSTATUS  VARCHAR2(2 BYTE)        NOT NULL,
  MCCGROUPID            VARCHAR2(4 BYTE),
  CCGROUPID             VARCHAR2(4 BYTE),
  USAGETYPE             VARCHAR2(12 BYTE),
  NOTRANSALLOWED        VARCHAR2(4 BYTE),
  TOTALAMOUNTLIMIT      VARCHAR2(12 BYTE),
  TRANSCODEGROUPID      VARCHAR2(4 BYTE),
  FROMTIME              VARCHAR2(5 BYTE),
  TOTIME                VARCHAR2(5 BYTE),
  AUT_LUPD_DATE         DATE,
  AUT_INST_CODE         NUMBER(10),
  AUT_LUPD_USER         NUMBER(10),
  AUT_INS_DATE          DATE,
  AUT_INS_USER          NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.RULEGEN ADD (
  CONSTRAINT PK_RULEGEN
 PRIMARY KEY
 (RULEID))
/

ALTER TABLE VMSCMS.RULEGEN ADD (
  CONSTRAINT RULETRANS_PK 
 FOREIGN KEY (TRANSCODEGROUPID) 
 REFERENCES VMSCMS.TRANSCODEGROUPING (TRANSCODEGROUPID),
  CONSTRAINT RULEGEN1_PK 
 FOREIGN KEY (MCCGROUPID) 
 REFERENCES VMSCMS.MCCODEGROUPING (MCCODEGROUPID),
  CONSTRAINT RULEGEN_PK 
 FOREIGN KEY (CCGROUPID) 
 REFERENCES VMSCMS.CURRENCYCODEGROUPING (CURRENCYCODEGROUPID))
/

