CREATE TABLE VMSCMS.RULECODE_GROUP
(
  RULEID         VARCHAR2(4 BYTE)               NOT NULL,
  RULEGROUPID    VARCHAR2(4 BYTE)               NOT NULL,
  RUL_LUPD_DATE  DATE,
  RUL_INST_CODE  NUMBER(10),
  RUL_LUPD_USER  NUMBER(10),
  RUL_INS_DATE   DATE,
  RUL_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.RULECODE_GROUP ADD (
  CONSTRAINT RULECODEGROUP
 PRIMARY KEY
 (RULEID, RULEGROUPID))
/

ALTER TABLE VMSCMS.RULECODE_GROUP ADD (
  CONSTRAINT RULECODE_PK 
 FOREIGN KEY (RULEID) 
 REFERENCES VMSCMS.RULE (RULEID),
  CONSTRAINT RULECODE1_PK 
 FOREIGN KEY (RULEGROUPID) 
 REFERENCES VMSCMS.RULEGROUPING (RULEGROUPID))
/

