CREATE TABLE VMSCMS.RULE
(
  RULEID              VARCHAR2(4 BYTE)          NOT NULL,
  RULEDESC            VARCHAR2(50 BYTE)         NOT NULL,
  RULETYPE            VARCHAR2(1 BYTE)          NOT NULL,
  AUTHTYPE            VARCHAR2(1 BYTE)          NOT NULL,
  MCCGROUPID          VARCHAR2(4 BYTE)          DEFAULT '-',
  CCGROUPID           VARCHAR2(4 BYTE)          DEFAULT '-',
  USAGETYPE           VARCHAR2(1 BYTE)          DEFAULT '-',
  NOTRANSALLOWED      VARCHAR2(4 BYTE)          DEFAULT '-',
  TOTALAMOUNTLIMIT    VARCHAR2(12 BYTE)         DEFAULT '-',
  TRANSCODEGROUPID    VARCHAR2(4 BYTE)          DEFAULT '-',
  FROMTIME            VARCHAR2(5 BYTE)          DEFAULT '-',
  TOTIME              VARCHAR2(5 BYTE)          DEFAULT '-',
  ACTIVATIONSTATUS    VARCHAR2(1 BYTE)          DEFAULT '-',
  DATEAPPLICABLE      VARCHAR2(12 BYTE)         DEFAULT 'N',
  FROMDATE            VARCHAR2(12 BYTE),
  TODATE              VARCHAR2(12 BYTE),
  ACT_LUPD_DATE       DATE,
  ACT_INST_CODE       NUMBER(10),
  ACT_LUPD_USER       NUMBER(10),
  ACT_INS_DATE        DATE,
  ACT_INS_USER        NUMBER(10),
  TRANSACTIONGROUPID  VARCHAR2(4 BYTE),
  COUNTRYGRPOUPID     VARCHAR2(4 BYTE),
  MERCHANTGROUPID     VARCHAR2(4 BYTE),
  PERMRULE_FLAG       VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.RULE ADD (
  CONSTRAINT PK_RULE
 PRIMARY KEY
 (RULEID))
/

ALTER TABLE VMSCMS.RULE ADD (
  CONSTRAINT RULECC_PK 
 FOREIGN KEY (CCGROUPID) 
 REFERENCES VMSCMS.CURRENCYCODEGROUPING (CURRENCYCODEGROUPID))
/

