CREATE TABLE VMSCMS.STOCK_STATUS
(
  LOC_TYPE_ID    NUMBER(19),
  ITEM_ID        NUMBER(19)                     DEFAULT '0',
  B_QUANTITY     NUMBER(19)                     DEFAULT '0',
  E_QUANTITY     NUMBER(19)                     DEFAULT '0',
  LOC_CODE_ID    NUMBER(19)                     DEFAULT '0',
  B_Q_LUPD_DATE  DATE,
  B_Q_INST_CODE  NUMBER(10),
  B_Q_LUPD_USER  NUMBER(10),
  B_Q_INS_DATE   DATE,
  B_Q_INS_USER   NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


