CREATE TABLE VMSCMS.TRANSCODE_GROUP
(
  TRANSCODE         VARCHAR2(4 BYTE)            NOT NULL,
  TRANSCODEGROUPID  VARCHAR2(4 BYTE)            NOT NULL,
  TRA_LUPD_DATE     DATE,
  TRA_INST_CODE     NUMBER(10),
  TRA_LUPD_USER     NUMBER(10),
  TRA_INS_DATE      DATE,
  TRA_INS_USER      NUMBER(10)
)
TABLESPACE CMS_BIG_TXN
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE VMSCMS.TRANSCODE_GROUP ADD (
  CONSTRAINT TRANSCODEGROUP
 PRIMARY KEY
 (TRANSCODE, TRANSCODEGROUPID))
/

ALTER TABLE VMSCMS.TRANSCODE_GROUP ADD (
  CONSTRAINT TRANSGROUP_PK 
 FOREIGN KEY (TRANSCODEGROUPID) 
 REFERENCES VMSCMS.TRANSCODEGROUPING (TRANSCODEGROUPID))
/

