CREATE TABLE vmscms.VMS_RULESET_MAST_DETAILS
(
	VSD_RULESET_ID NUMBER(9) NOT NULL ,
	VSD_RULEID NUMBER(9) NOT NULL,
	vsd_ins_user number not null,
	vsd_ins_date date not null,
	vsd_lupd_user number,
	vsd_lupd_date date,
	CONSTRAINT PK_RULESETDET_ID PRIMARY KEY (VSD_RULESET_ID,VSD_RULEID),
	CONSTRAINT FK_RULESETDET_RULESETMAST FOREIGN KEY (VSD_RULESET_ID)
	REFERENCES VMSCMS.VMS_RULESET_MAST (VRS_RULESET_ID),
	CONSTRAINT FK_RULESETDET_RULEMAST FOREIGN KEY (VSD_RULEID)
	REFERENCES VMSCMS.VMS_RULE_MAST (VRM_RULE_ID)
 ); 