CREATE
  TABLE vmscms.VMS_PRODCAT_DENO_MAST
  (
    VPD_INST_CODE   NUMBER(3,0) NOT NULL ENABLE,
    VPD_PROD_CODE   VARCHAR2(20) NOT NULL ENABLE,
    VPD_CARD_TYPE   NUMBER(3,0) NOT NULL ENABLE,
    VPD_PDEN_VAL    NUMBER(20,3) NOT NULL ENABLE,
	VPD_DENO_STATUS	NUMBER(1,0) NOT NULL ENABLE,
    VPD_INS_USER    NUMBER(5,0) NOT NULL ENABLE,
    VPD_INS_DATE DATE NOT NULL ENABLE,
    VPD_LUPD_USER NUMBER(5,0),
    VPD_LUPD_DATE DATE,
    CONSTRAINT FK_PROD_DENO_CATTYPE FOREIGN KEY (VPD_INST_CODE,
    VPD_PROD_CODE, VPD_CARD_TYPE) REFERENCES vmscms.
	CMS_PROD_CATTYPE (CPC_INST_CODE, CPC_PROD_CODE, CPC_CARD_TYPE));	