ALTER TABLE vmscms.VMS_TOKEN_INFO ADD (
VTI_CONTACTLESS_USAGE VARCHAR2(20),
VTI_CARD_ECOMM_USAGE VARCHAR2(20),
VTI_MOB_WALLET_ECOMM_USAGE VARCHAR2(20),
VTI_WALLET_IDENTIFIER VARCHAR2(20),
VTI_STORAGE_TECHNOLOGY VARCHAR2(20),
VTI_ACCT_NO VARCHAR2(20),
VTI_CUST_CODE NUMBER(10,0));

ALTER TABLE vmscms.VMS_TOKEN_INFO MODIFY (
VTI_TOKEN_PAN_REF_ID VARCHAR2(100),
VTI_TOKEN_REF_ID VARCHAR2(100),
VTI_TOKEN_DEVICE_NAME VARCHAR2(200));

