CREATE
  TABLE vmscms.VMS_GROUP_ACCESSID_MAST
  (
    VGA_GROUP_ID   VARCHAR2(20),
    VGA_GROUP_NAME VARCHAR2(20),
    VGA_INS_USER    NUMBER(5,0),
    VGA_INS_DATE DATE,
    VGA_LUPD_USER NUMBER(5,0),
    VGA_LUPD_DATE DATE
  );
  
ALTER TABLE VMSCMS.VMS_GROUP_ACCESSID_MAST ADD CONSTRAINT PK_GROUPACCESSID_MAST 
PRIMARY KEY (VGA_GROUP_ID,VGA_GROUP_NAME);