  CREATE TABLE vmscms.VMS_RULESET_MAST_DETAILS_HIST
   (	VRH_RULESET_ID NUMBER(9,0) NOT NULL , 
      VRH_RULEID NUMBER(9,0) NOT NULL , 
      VRH_INS_USER NUMBER(5,0) NOT NULL , 
      VRH_INS_DATE DATE NOT NULL , 
      VRH_LUPD_USER NUMBER(5,0), 
      VRH_LUPD_DATE DATE 
   ) ;