ALTER TABLE vmscms.VMS_PROD_CATTYPE_STAG ADD (
                    VPC_B2B_FLAG	VARCHAR2(20),
                    VPC_B2BCARD_STAT	VARCHAR2(20),
                    VPC_B2B_LMTPRFL	VARCHAR2(20),
                    VPC_B2B_ACTIVATION_CODE	VARCHAR2(20),
                    VPC_B2BFLNAME_FLAG	NUMBER(1));
					
ALTER TABLE vmscms.VMS_PROD_CATTYPE_STAG ADD (
VPC_INACTIVETOKEN_RETAINPERIOD NUMBER(7,0),
VPC_KYC_FLAG	VARCHAR2(20),
VPC_CVV2_VERIFICATION_FLAG	VARCHAR2(20),
VPC_EXPIRY_DATE_CHECK_FLAG	VARCHAR2(20),
VPC_ACCT_BALANCE_CHECK_FLAG	VARCHAR2(20),
VPC_ACCT_BAL_CHECK_TYPE VARCHAR2(20),
VPC_ACCT_BAL_CHECK_VALUE NUMBER(5,0),
VPC_REPLACEMENT_PROVISION_FLAG	VARCHAR2(20),
VPC_ISSU_PRODCONFIG_ID VARCHAR2(20),
VPC_CONSUMED_FLAG VARCHAR2(20),
VPC_CONSUMED_CARD_STAT VARCHAR2(20),
VPC_RENEW_REPLACE_OPTION VARCHAR2(20),
VPC_RENEW_REPLACE_PRODCODE VARCHAR2(20),
VPC_RENEW_REPLACE_CARDTYPE NUMBER(2,0));