alter TABLE VMSCMS.VMS_RULE_MAST drop CONSTRAINT CHECK_RULEMAST_ACTIONTYPE;

alter TABLE VMSCMS.VMS_RULE_MAST add 
CONSTRAINT CHECK_RULEMAST_ACTIONTYPE CHECK
 (VRM_ACTION_TYPE in ('DECLINE_IF_TRUE','DECLINE_IF_FALSE','CONDITIONAL_IF_FALSE','CONDITIONAL_IF_TRUE','NA')
 );