ALTER TABLE vmscms.VMS_TOKEN_STATUS_SYNC_DTLS ADD (VTS_TRAN_RRN 	VARCHAR2(50 BYTE),
VTS_RRN 	VARCHAR2(50 BYTE),
VTS_STAN	VARCHAR2(50 BYTE),
VTS_EXPRY_DATE VARCHAR2(100 BYTE),
VTS_TOKEN_PAN_REF_ID VARCHAR2(100 BYTE),
VTS_NEW_PAN	VARCHAR2(90 BYTE),
VTS_NEWPAN_ENCR RAW(300),VTS_NEWEXPRY_DATE VARCHAR2(100 BYTE),
VTS_ACCT_NO varchar2(20),VTS_CARD_STAT varchar2(10)
);


alter table VMSCMS.VMS_TOKEN_STATUS_SYNC_DTLS add 
VTS_TOKEN_STATUS_FLAG VARCHAR2(20 BYTE);
