CREATE
TABLE vmscms.VMS_PROD_GROUPACCESS_MAP
(
VPG_PROD_CODE	VARCHAR2(6),
VPG_CARD_TYPE	NUMBER(2,0),
VPG_PROD_GROUP_NAME	VARCHAR2(20),
VPG_INS_DATE	DATE,
VPG_INS_USER	NUMBER(5,0),
VPG_LUPD_DATE	DATE,
VPG_LUPD_USER	NUMBER(5,0)
);

ALTER TABLE VMSCMS.VMS_PROD_GROUPACCESS_MAP ADD CONSTRAINT PK_PROD_GROUPACCESS_MAP 
PRIMARY KEY (VPG_PROD_CODE,VPG_CARD_TYPE,VPG_PROD_GROUP_NAME);