 CREATE
  TABLE vmscms.VMS_PARTNER_ID_MAST
  (
    VPI_PARTNER_SNO   VARCHAR2(20),
    VPI_PARTNER_ID VARCHAR2(50),
    VPI_INS_USER    NUMBER(5,0),
    VPI_INS_DATE DATE,
    VPI_LUPD_USER NUMBER(5,0),
    VPI_LUPD_DATE DATE
  );
  
ALTER TABLE VMSCMS.VMS_PARTNER_ID_MAST ADD CONSTRAINT PK_PARTNERID_MAST 
PRIMARY KEY (VPI_PARTNER_SNO,VPI_PARTNER_ID);