CREATE TABLE vmscms.VMS_PACKAGEID_ATTRIBUTE
  (
    VPA_FIELD_KEY VARCHAR2(20 BYTE) NOT NULL,
    VPA_FIELD_NAME  VARCHAR2(50 BYTE) NOT NULL,
    VPA_FIELD_CNTRL  VARCHAR2(50 BYTE) NOT NULL,
    VPA_FIELD_EXP  VARCHAR2(100 BYTE) NOT NULL,
    VPA_FIELD_LENGTH   NUMBER(3,0) NOT NULL,
    VPA_FIELD_DEFAULT VARCHAR2(50 BYTE),
    VPA_FIELD_DATATYPE VARCHAR2(50 BYTE),
    VPA_FIELD_OPTIONDATA VARCHAR2(1000 BYTE)
);

ALTER TABLE vmscms.VMS_PACKAGEID_ATTRIBUTE ADD CONSTRAINT PK_PACKAGEID_ATTRIBUTE
PRIMARY KEY (VPA_FIELD_KEY);