CREATE TABLE VMSCMS.VMS_VERIF_CLASSES
(
  CVC_INST_CODE        NUMBER(3),
  CVC_VERIFY_CNAME     VARCHAR2(100 BYTE),
  CVC_DAO_CNAME        VARCHAR2(100 BYTE),
  CVC_DELIVERY_CHANEL  VARCHAR2(3 BYTE),
  CVC_TXN_CODE         VARCHAR2(2 BYTE),
  CVC_MSG_TYPE         VARCHAR2(10 BYTE),
  CVC_REVERSAL_CODE    NUMBER(3),
  CVC_INS_USER         NUMBER(5),
  CVC_INS_DATE         DATE,
  CVC_LUPD_USER        NUMBER(5),
  CVC_LUPD_DATE        DATE
)
TABLESPACE CMS_BKUP
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


