CREATE TABLE vmscms.VMS_TOKEN_RULE_RESPLOG(
VTR_PAN_CODE	varchar2(90),
VTR_PAN_CODE_ENCR	RAW(100),
VTR_TOKEN	VARCHAR2(20),
VTR_RRN	VARCHAR2(20),
VTR_WALLET_ID VARCHAR2(20),
VTR_DEVICE_ID VARCHAR2(50),
VTR_RULE_RESPONSE VARCHAR2(20),
VTR_INS_DATE	DATE,
VTR_LUPD_DATE	DATE,
constraint pk_pan_wallet_device_id primary key (VTR_PAN_CODE,VTR_WALLET_ID,VTR_DEVICE_ID));


