CREATE TABLE vmscms.VMS_PRODCAT_THRESHOLD
(
VPT_INST_CODE NUMBER(3,0),
VPT_PROD_CODE VARCHAR2(20),
VPT_CARD_TYPE VARCHAR2(20),
VPT_PROD_THRESHOLD NUMBER(25,0),
VPT_INS_USER NUMBER(5,0),
VPT_INS_DATE DATE,
VPT_LUPD_USER NUMBER(5,0),
VPT_LUPD_DATE DATE);

ALTER TABLE VMSCMS.VMS_PRODCAT_THRESHOLD ADD CONSTRAINT PK_PRODCAT_THRESHOLD 
PRIMARY KEY (VPT_INST_CODE,VPT_PROD_CODE,VPT_CARD_TYPE);