CREATE TABLE vmscms.VMS_WALLET_MAST
  (
    VWM_WALLET_ID   VARCHAR2(50),
    VWM_WALLET_NAME VARCHAR2(200),
    VWM_NETWORK_ID  VARCHAR2(50),
    VWM_INS_USER    NUMBER(5,0),
    VWM_INS_DATE DATE,
    VWM_LUPD_USER NUMBER(5,0),
    VWM_LUPD_DATE DATE
  );
  
  ALTER TABLE VMSCMS.VMS_WALLET_MAST ADD CONSTRAINT PK_WALLET_MAST 
	PRIMARY KEY (VWM_NETWORK_ID,VWM_WALLET_ID);