CREATE TABLE vmscms.VMS_RAN_PROGRAM_MERCHANT
(	
	VRP_PROGRAM_ID VARCHAR2(20) NOT NULL ,
	VRP_MERCHANT_ID  VARCHAR2(20) NOT NULL , 
	VRP_EFFECTIVE_DATE DATE NOT NULL , 
	VRP_EXPIRATION_DATE DATE NOT NULL , 
	VRP_UPDATE_TIMESTAMP TIMESTAMP NOT NULL , 
	VRP_INS_DATE DATE NOT NULL ,
	VRP_LUPD_DATE DATE,
	CONSTRAINT PK_RAN_PROGRAM_MERCHANT PRIMARY KEY (VRP_PROGRAM_ID,VRP_MERCHANT_ID)
);