  CREATE TABLE vmscms.VMS_RULE_MAST_DETAILS_HIST 
   (	VRH_RULE_ID NUMBER(9,0) NOT NULL , 
	VRH_RULE_DET_ID NUMBER(9,0) NOT NULL , 
	VRH_RULE_FILTER VARCHAR2(1000) NOT NULL , 
	VRH_INS_USER NUMBER(5,0) NOT NULL , 
	VRH_INS_DATE DATE NOT NULL , 
	VRH_LUPD_USER NUMBER(5,0), 
	VRH_LUPD_DATE DATE
   ) ;