CREATE TABLE vmscms.VMS_WALLET_ALERTMSG_CONFIG
  (
    VWA_PROD_CODE       VARCHAR2(20),
    VWA_CARD_TYPE       NUMBER(2,0),
    VWA_WALLET_ID       VARCHAR2(20),
    VWA_ALERT_MSG     VARCHAR2(2000),    
    VWA_SUBJECT_LINE    VARCHAR2(100),
    VWA_ALERT_ID        NUMBER(5,0),
    VWA_ALERT_LANG_ID   NUMBER(5,0),
    VWA_DEFALERT_LANG_FLAG VARCHAR2(20),
    VWA_INS_USER        NUMBER(5,0),
    VWA_INS_DATE DATE,
    VWA_LUPD_USER NUMBER(5,0),
    VWA_LUPD_DATE DATE
  );
    ALTER TABLE VMSCMS.VMS_WALLET_ALERTMSG_CONFIG ADD CONSTRAINT PK_WALLET_ALERT_CONFIG 
	PRIMARY KEY (VWA_PROD_CODE,VWA_CARD_TYPE,VWA_WALLET_ID,VWA_ALERT_ID,VWA_ALERT_LANG_ID);