CREATE TABLE vmscms.VMS_PACKAGEID_DETL 
  (
    VPD_PACKAGE_ID  VARCHAR2(20 BYTE) NOT NULL,
    VPD_FIELD_KEY   VARCHAR2(20 BYTE) NOT NULL,
    VPD_FIELD_VALUE VARCHAR2(100 BYTE),
    VPD_INS_DATE    DATE NOT NULL,
    VPD_INS_USER    NUMBER(5,0) NOT NULL,
    VPD_LUPD_DATE    DATE NOT NULL,
    VPD_LUPD_USER    NUMBER(5,0) NOT NULL   
);

ALTER TABLE vmscms.VMS_PACKAGEID_DETL ADD CONSTRAINT PK_PACKAGEID_DETL
PRIMARY KEY (VPD_PACKAGE_ID,VPD_FIELD_KEY);