CREATE TABLE vmscms.VMS_RULE_MAST_DETAILS
(	
	VRD_RULE_ID NUMBER(9) NOT NULL ,
	VRD_RULE_DET_ID  NUMBER(9) NOT NULL , 
	VRD_RULE_FILTER VARCHAR2(1000) NOT NULL , 
	VRD_INS_USER NUMBER(5) NOT NULL , 
	VRD_INS_DATE DATE NOT NULL , 
	VRD_LUPD_USER NUMBER(5), 
	VRD_LUPD_DATE DATE,
	CONSTRAINT PK_RULEDET_ID PRIMARY KEY (VRD_RULE_ID,VRD_RULE_DET_ID),
	CONSTRAINT FK_RULEMASTDET_RULEMAST FOREIGN KEY (VRD_RULE_ID)
	REFERENCES VMSCMS.VMS_RULE_MAST (VRM_RULE_ID) 
);