alter table VMSCMS.VMS_TOKEN_TRANSACTIONLOG
modify VTT_OTPCODE_EXPIRATION  varchar2(50);

ALTER TABLE vmscms.VMS_TOKEN_TRANSACTIONLOG MODIFY (
VTT_PAN_REFID VARCHAR2(100),
VTT_TOKEN_REF_ID varchar2(100),
VTT_DEVICE_NAME VARCHAR2(200));

ALTER TABLE vmscms.VMS_TOKEN_TRANSACTIONLOG ADD (
VTT_DELIVERY_CHANNEL VARCHAR2(20),
VTT_TXN_CODE VARCHAR2(20),
VTT_WALLET_ID VARCHAR2(20),
VTT_PRODUCT_CODE VARCHAR2(20), 
VTT_TOKEN_CARD_ACCEPTOR_IDCODE VARCHAR2(20),
VTT_REPLACEMENT_PAN VARCHAR2(20),
VTT_REPLACEMENT_PAN_EXPIRYDATE VARCHAR2(20),
VTT_WALLET_IDENTIFIER VARCHAR2(20),
VTT_STORAGE_TECHNOLOGY VARCHAR2(20),
VTT_CORRELATION_ID VARCHAR2(20),
VTT_PAYMENT_APPL_INSTANCE_ID VARCHAR2(100),
VTT_CONTACTLESS_USAGE VARCHAR2(20),
VTT_CARD_ECOMM_USAGE VARCHAR2(20),
VTT_MOB_WALLET_ECOMM_USAGE VARCHAR2(20),
VTT_FINAL_TOKEN_DECISION_REQID VARCHAR2(20),
VTT_FINAL_TOKENIZATION_DECIND VARCHAR2(20),
VTT_TCDATE_AND_TIME VARCHAR2(50),
VTT_NUMBEROF_ACT_ATTEMPTS VARCHAR2(20),
VTT_TOKENIZATION_REASONCODE VARCHAR2(20),
VTT_EVENT_REQUESTOR VARCHAR2(20),
VTT_ISSUER_PRODUCT_CONFID VARCHAR2(20),
VTT_TOKEN_EVENT_INDICATOR VARCHAR2(20),
VTT_TC_VERSION_NUMBER varchar2(100),
VTT_RULE_RESPONSE VARCHAR2(20)); 


ALTER TABLE vmscms.VMS_TOKEN_TRANSACTIONLOG ADD (
VTT_TRANSACTION_IDENTIFIER VARCHAR2(20),
VTT_ATC_VALUE VARCHAR2(20),
VTT_ATC_DISCREPANCY_VALUE VARCHAR2(20),
VTT_ATC_DISCREPANCY_ID VARCHAR2(20));