  CREATE TABLE VMSCMS.VMS_ORDER_LINEITEM
  (
    VOL_ORDER_ID     VARCHAR2(50 BYTE) NOT NULL ENABLE,
    VOL_LINE_ITEM_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
    VOL_DENOMINATION VARCHAR2(20 BYTE),
    VOL_EMBOSSEDLINE VARCHAR2(50 BYTE),
    VOL_PACKAGE_ID   VARCHAR2(20 BYTE),
    VOL_PRODUCT_ID   VARCHAR2(50 BYTE),
    VOL_OFFERCODE    VARCHAR2(20 BYTE),
    VOL_QUANTITY     NUMBER(2,0),
    VOL_ORDER_STATUS VARCHAR2(20 BYTE),
    VOL_INS_DATE DATE,
    VOL_ERROR_MSG      VARCHAR2(1000 BYTE),
    VOL_EMBOSSED_LINE1 VARCHAR2(50 BYTE),
    VOL_PARTNER_ID     VARCHAR2(50 BYTE),
	vol_tracking_no   VARCHAR2(50),
	vol_shipping_datetime  DATE
  );
  

  