CREATE TABLE VMSCMS.VMS_ISO_NETWORKID_FORCEPOST
  (
    VIN_INST_CODE  VARCHAR2(2),
    VIN_NETWORK_ID VARCHAR2(10),
    VIN_INS_DATE DATE,
    VIN_INS_USER VARCHAR2(5),
    VIN_LUPD_DATE DATE,
    VIN_LUPD_USER VARCHAR2(5)
  );