CREATE TABLE vmscms.VMS_PACKAGEID_MAST 
  (
    VPM_PACKAGE_ID  VARCHAR2(20 BYTE) NOT NULL,
    VPM_PACKAGE_DESC  VARCHAR2(50 BYTE) not null,
    VPM_REPLACEMENT_PACKAGE_ID VARCHAR2(20 BYTE) NOT NULL,
    VPM_VENDOR_ID   VARCHAR2(100 BYTE) NOT NULL,
    VPM_SHIP_METHODS VARCHAR2(100 BYTE) NOT NULL,
    VPM_INS_DATE    DATE NOT NULL,
    VPM_INS_USER    NUMBER(5,0) NOT NULL,
    VPM_LUPD_DATE    DATE NOT NULL,
    VPM_LUPD_USER    NUMBER(5,0) NOT NULL   
);

ALTER TABLE vmscms.VMS_PACKAGEID_MAST ADD CONSTRAINT PK_PACKAGEID_MAST
PRIMARY KEY (VPM_PACKAGE_ID);