CREATE TABLE vmscms.VMS_RAN_PROGRAM
(	
	VRP_PROGRAM_ID VARCHAR2(20) NOT NULL ,
	VRP_PROGRAM_NAME  VARCHAR2(50) NOT NULL , 
	VRP_PROGRAM_TYPE VARCHAR2(20) NOT NULL , 
	VRP_EFFECTIVE_DATE DATE NOT NULL , 
	VRP_EXPIRATION_DATE DATE NOT NULL , 
	VRP_UPDATE_TIMESTAMP TIMESTAMP NOT NULL , 
	VRP_INS_DATE DATE NOT NULL ,
	VRP_LUPD_DATE DATE,
	CONSTRAINT PK_RAN_PROGRAM PRIMARY KEY (VRP_PROGRAM_ID)
);