  CREATE TABLE VMSCMS.VMS_FSAPI_REQRESLOG
  (
    VFR_SEQ_NO     VARCHAR2(20 BYTE),
    VFR_TIME_TAKEN NUMBER(10,0),
    VFR_INS_DATE TIMESTAMP (6),
    VFR_SERVER_ID VARCHAR2(100 BYTE),
    VFR_RES_MSG CLOB,
    VFR_REQ_MSG CLOB,
	VFR_API_NAME varchar2(50),
	VFR_REQ_HEADER VARCHAR2(4000),
	VFR_RES_HEADER varchar2(4000)
  );