CREATE TABLE vmscms.VMS_FSAPI_SERIAL_ACTIVATION(
VFS_RRN VARCHAR2(20 BYTE) NOT NULL,
VFS_SERIAL_NUMBER  VARCHAR2(20 BYTE) NOT NULL,
VFS_ACTIVATION_CODE VARCHAR2(20 BYTE),
VFS_RESPONSE_STATUS VARCHAR2(500 BYTE),
VFS_INST_DATE DATE);