CREATE TABLE vmscms.VMS_STATE_RESTRICTION(
VSR_STATE_CODE VARCHAR2(20),
VSR_PROGRAM_TYPE VARCHAR2(20),
VSR_RULE_BASED VARCHAR2(20),
VSR_FEE_PERIOD NUMBER(3,0),
VSR_INS_USER	NUMBER(5,0),
VSR_INS_DATE	DATE,
VSR_LUPD_USER	NUMBER(5,0),
VSR_LUPD_DATE	DATE);

ALTER TABLE VMSCMS.VMS_STATE_RESTRICTION ADD CONSTRAINT PK_STATE_FEE_CONFIG 
PRIMARY KEY (VSR_STATE_CODE,VSR_PROGRAM_TYPE);