CREATE TABLE vmscms.VMS_FSAPI_TRANS_MAST(
VFT_CHANNEL_DESC	VARCHAR2(20 BYTE) NOT NULL,
VFT_REQUEST_TYPE	VARCHAR2(20 BYTE) NOT NULL,
VFT_CHANNEL_CODE	VARCHAR2(3 BYTE),
VFT_TRAN_CODE	VARCHAR2(3 BYTE),
VFT_INS_DATE	DATE,
VFT_INST_USER	NUMBER(1,0),
CONSTRAINT PK_VMS_FSAPI_TRANS_MAST PRIMARY KEY (VFT_CHANNEL_DESC,VFT_REQUEST_TYPE));