CREATE TABLE vmscms.VMS_PARAM_CONFIG_MAST(
VPC_PARAM_TYPE VARCHAR2(100),
VPC_PARAM_ID VARCHAR2(100),
VPC_PARAM_NAME VARCHAR2(200),
VPC_REMARKS VARCHAR2(200),
VPC_INS_USER    NUMBER(5,0),
VPC_INS_DATE DATE,
VPC_LUPD_USER NUMBER(5,0),
VPC_LUPD_DATE DATE);

ALTER TABLE VMSCMS.VMS_PARAM_CONFIG_MAST ADD CONSTRAINT PK_PARAM_CONFIG_MAST
PRIMARY KEY (VPC_PARAM_TYPE,VPC_PARAM_ID,VPC_PARAM_NAME);