CREATE TABLE vmscms.VMS_CVVPLUS_FSAPI
  (
    VCF_REQ_TYPE      VARCHAR2(50),
    VCF_HEADER_PARAM  VARCHAR2(1000),
    VCF_BODY_PARAM    VARCHAR2(4000),
    VCF_REQ_METHOD    VARCHAR2(200),
	VCF_TIMEOUT VARCHAR2(10),
	 VCF_URL VARCHAR2(500)
  );