ALTER TABLE vmscms.VMS_TOKEN_LIFECYCLE_LOG ADD 
(VTL_TOKEN_NEWPAN VARCHAR2(90),
VTL_TOKEN_NEWPAN_ENCR RAW(100),
VTL_PANREF_ID VARCHAR2(100 BYTE),
VTL_NEWEXPRY_DATE VARCHAR2(20),
VTL_TOKEN_REQ_REASON VARCHAR2(500)
);