CREATE TABLE VMSCMS.VMS_TRANSACTION_MAST
(
  CTM_INST_CODE           NUMBER(3),
  CTM_TRAN_CODE           VARCHAR2(2 BYTE),
  CTM_TRAN_DESC           VARCHAR2(50 BYTE),
  CTM_CREDIT_DEBIT_FLAG   VARCHAR2(2 BYTE),
  CTM_DELIVERY_CHANNEL    VARCHAR2(2 BYTE),
  CTM_OUTPUT_TYPE         VARCHAR2(1 BYTE),
  CTM_TRAN_TYPE           VARCHAR2(1 BYTE),
  CTM_SUPPORT_TYPE        VARCHAR2(1 BYTE),
  CTM_LUPD_DATE           DATE,
  CTM_LUPD_USER           NUMBER(10),
  CTM_INS_DATE            DATE,
  CTM_INS_USER            NUMBER(10),
  CTM_SUPPORT_CATG        VARCHAR2(1 BYTE),
  CTM_PREAUTH_FLAG        VARCHAR2(1 BYTE),
  CTM_AMNT_TRANSFER_FLAG  VARCHAR2(1 BYTE),
  CTM_LOGIN_TXN           VARCHAR2(1 BYTE),
  CTM_PRFL_FLAG           CHAR(1 BYTE),
  CTM_FEE_FLAG            VARCHAR2(1 BYTE)
)
TABLESPACE CMS_BKUP
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


