CREATE
  TABLE vmscms.VMS_GROUPID_PARTNERID_MAP
  (
	VGP_PARTNER_ID VARCHAR2(50),
    VGP_GROUP_ACCESS_NAME   VARCHAR2(20),    
    VGP_INS_USER    NUMBER(5,0),
    VGP_INS_DATE DATE,
    VGP_LUPD_USER NUMBER(5,0),
    VGP_LUPD_DATE DATE
  );
  
ALTER TABLE VMSCMS.VMS_GROUPID_PARTNERID_MAP ADD CONSTRAINT PK_GROUPID_PARTNERID_MAP 
PRIMARY KEY (VGP_PARTNER_ID,VGP_GROUP_ACCESS_NAME);