CREATE TABLE VMSCMS.VMS_TXN_PROPERTIES
(
  CTP_TXN_CODE                   VARCHAR2(2 BYTE),
  CTP_INST_CODE                  NUMBER(3),
  CTP_MSGBODY_PROP               VARCHAR2(100 BYTE),
  CTP_HEADER_PROP                VARCHAR2(100 BYTE),
  CTP_REVERSAL_CODE              NUMBER(3),
  CTP_MSG_TYPE                   VARCHAR2(10 BYTE),
  CTP_DELIVERY_CHANNEL           VARCHAR2(2 BYTE),
  CTP_VALIDATION_PROP            VARCHAR2(100 BYTE),
  CTP_HEADERPROP_VALIDATION      VARCHAR2(100 BYTE),
  CTP_NONMANDATORY_MSGBODY_PROP  VARCHAR2(100 BYTE),
  CTP_NONMANDATORY_VALIDATION    VARCHAR2(100 BYTE)
)
TABLESPACE CMS_BKUP
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


