CREATE TABLE vmscms.VMS_RULE_PARAM_OPERAT_MAPPING
(
	VRO_PARAM_ID VARCHAR2(50) NOT NULL ,
	VRO_OPERATOR_ID VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_OPERATMAP_ID PRIMARY KEY (VRO_PARAM_ID,VRO_OPERATOR_ID),
	CONSTRAINT FK_OPERATMAP_RULEPARAMETERS FOREIGN KEY (VRO_PARAM_ID)
	REFERENCES VMSCMS.VMS_RULE_PARAMETERS (VRP_PARAM_ID) ,
	CONSTRAINT FK_OPERATMAP_OPERATORMAST FOREIGN KEY (VRO_OPERATOR_ID)
	REFERENCES VMSCMS.VMS_OPERATOR_MAST (VOM_OPERATOR_ID) 
); 	