CREATE TABLE vmscms.VMS_FSAPI_PROXY_ACTIVATION(
VFP_RRN VARCHAR2(20 BYTE) NOT NULL,
VFP_PROXY_NUMBER  VARCHAR2(20 BYTE) NOT NULL,
VFP_ACTIVATION_CODE VARCHAR2(20 BYTE),
VFP_RESPONSE_STATUS VARCHAR2(500 BYTE),
VFP_INST_DATE DATE);