CREATE TABLE vmscms.vms_fee_mast_stag
(
   vfm_inst_code                 NUMBER (3) NOT NULL,
   vfm_feetype_code              NUMBER (5) NOT NULL,
   vfm_fee_code                  NUMBER (4) NOT NULL,
   vfm_fee_amt                   NUMBER (15, 2),
   vfm_fee_desc                  VARCHAR2 (100),
   vfm_delivery_channel          VARCHAR2 (2),
   vfm_tran_type                 VARCHAR2 (1),
   vfm_tran_code                 VARCHAR2 (2),
   vfm_tran_mode                 VARCHAR2 (1),
   vfm_consodium_code            NUMBER (3),
   vfm_partner_code              NUMBER (5),
   vfm_currency_code             VARCHAR2 (5),
   vfm_per_fees                  NUMBER (20, 2),
   vfm_min_fees                  NUMBER (20, 2),
   vfm_spprt_key                 VARCHAR2 (6),
   vfm_merc_code                 VARCHAR2 (4),
   vfm_date_assessment           VARCHAR2 (5),
   vfm_clawback_flag             VARCHAR2 (1),
   vfm_proration_flag            VARCHAR2 (1),
   vfm_duration                  VARCHAR2 (2),
   vfm_feeamnt_type              VARCHAR2 (2),
   vfm_free_txncnt               NUMBER (4) DEFAULT 0,
   vfm_intl_indicator            VARCHAR2 (1),
   vfm_approve_status            VARCHAR2 (1),
   vfm_pin_sign                  VARCHAR2 (1),
   vfm_normal_rvsl               VARCHAR2 (1),
   vfm_date_start                VARCHAR2 (2),
   vfm_feecap_flag               VARCHAR2 (1),
   vfm_max_limit                 NUMBER (5) DEFAULT 0,
   vfm_maxlmt_freq               VARCHAR2 (1),
   vfm_txnfree_amt               NUMBER (20, 3),
   vfm_cap_amt                   NUMBER (20, 2) DEFAULT '0',
   vfm_crfree_txncnt             NUMBER (4),
   vfm_clawback_count            NUMBER (3),
   vfm_clawback_type             VARCHAR2 (1) DEFAULT 'N',
   vfm_clawback_maxamt           NUMBER (20, 2) DEFAULT 0,
   vfm_assessed_days             NUMBER (3) DEFAULT 0,
   vfm_duration_change           DATE
);
