CREATE TABLE vmscms.VMS_RAN_FILE
(	
	VRF_INST_CODE	NUMBER(3,0),
	VRF_BATCH_ID VARCHAR2(20),
	VRF_FILE_NAME	VARCHAR2(100),
	VRF_FILE_CREATION_TIMESTAMP  TIMESTAMP,
	VRF_FILE_RECCOUNT	NUMBER(20,0),
	VRF_SUCCESS_RECCOUNT	NUMBER(20,0),
	VRF_FAIL_RECCOUNT	NUMBER(20,0),
	VRF_PROCESS_FLAG	CHAR(1) DEFAULT 'N',
	VRF_PROCESS_DETL	VARCHAR2(1000),
	VRF_INS_USER	NUMBER(5,0),
	VRF_INS_DATE	DATE,
	VRF_LUPD_USER	NUMBER(5,0),
	VRF_LUPD_DATE	DATE,
	CONSTRAINT PK_RAN_FILE PRIMARY KEY (VRF_BATCH_ID)
);

CREATE INDEX vmscms.IND_RAN_FILE_FILENAME ON vmscms.VMS_RAN_FILE(UPPER(VRF_FILE_NAME));