CREATE TABLE vmscms.VMS_SCORECARD_PRODCAT_MAPPING
(
VSP_INST_CODE NUMBER(3,0),
VSP_DELIVERY_CHANNEL VARCHAR2(20),
VSP_PROD_CODE VARCHAR2(20),
VSP_CARD_TYPE VARCHAR2(20),
VSP_SCORECARD_ID NUMBER(3,0), 
VSP_CIPCARD_STAT VARCHAR2(20),
VSP_AVQ_FLAG VARCHAR2(20),
VSP_INS_USER NUMBER(5,0),
VSP_INS_DATE DATE,
VSP_LUPD_USER NUMBER(5,0),
VSP_LUPD_DATE DATE);