CREATE
TABLE vmscms.VMS_FULFILLMENT_VENDOR_MAST
(
VFV_FVENDOR_ID   VARCHAR2(100),
VFV_FVENDOR_NAME VARCHAR2(200),
VFV_INS_USER    NUMBER(5,0),
VFV_INS_DATE DATE,
VFV_LUPD_USER NUMBER(5,0),
VFV_LUPD_DATE DATE,
VFV_IS_AUTOMATIC_SHIPPED VARCHAR2(20),
VFV_SHIPPED_TIME_DELAY NUMBER(3,0),
VFV_CCF_FILE_FORMAT VARCHAR2(100),
VFV_REPLACE_CCF_FILE_FORMAT VARCHAR2(100)
);

ALTER TABLE VMSCMS.VMS_FULFILLMENT_VENDOR_MAST ADD CONSTRAINT PK_FULFILLMENT_VENDOR_MAST 
PRIMARY KEY (VFV_FVENDOR_ID,VFV_FVENDOR_NAME);
