CREATE TABLE VMSCMS.VMS_CCFCONF_DTL
  (
    VCD_INST_CODE       NUMBER(3,0),
    VCD_DATA_SEQNO      NUMBER(5,0),
    VCD_DATA_TITLE      VARCHAR2(50 BYTE),
    VCD_DATA_DESC       VARCHAR2(100 BYTE),
    VCD_DATA_LENGTH     VARCHAR2(5 BYTE),
    VCD_DATA_ATTRTYPE   VARCHAR2(10 BYTE),
    VCD_DATA_VALUE      VARCHAR2(10 BYTE),
    VCD_DATA_FORMAT     VARCHAR2(10 BYTE),
    VCD_DATA_FILLER     VARCHAR2(10 BYTE),
    VCD_DATA_FILLERSIDE VARCHAR2(10 BYTE),
    VCD_INS_USER        NUMBER(5,0),
    VCD_INS_DATE DATE NOT NULL ENABLE,
    VCD_LUPD_USER NUMBER(5,0),
    VCD_LUPD_DATE DATE NOT NULL ENABLE,
    VCD_RECORD_TYPE    VARCHAR2(10 BYTE),
    VCD_VERSION_NAME   VARCHAR2(20 BYTE),
    VCD_VALUE_KEY      VARCHAR2(30 BYTE),
    VCD_FORMAT_TYPE    VARCHAR2(5 BYTE),
    VCD_POSSIBLE_VALUE VARCHAR2(50 BYTE),
    CONSTRAINT CHECK_RECORD_TYPE CHECK (VCD_RECORD_TYPE IN ('H','T','D')) ENABLE,
    CONSTRAINT PK_VMS_CCFCONF_DTL PRIMARY KEY (VCD_INST_CODE, VCD_DATA_SEQNO, VCD_VERSION_NAME, VCD_RECORD_TYPE)
  );

