CREATE TABLE vmscms.VMS_RULE_PARAM_TRANOBJ_MAPPING 
(
	VRT_PARAM_ID VARCHAR2(50) NOT NULL ,
	VRT_DELIVERY_CHANNEL VARCHAR2(2) NOT NULL,
	VRT_TRAN_CODE VARCHAR2(2) NOT NULL,   
	VRT_TRAN_OBJ_NAME VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_RULEPARAM_TRANMAP PRIMARY KEY (VRT_PARAM_ID,VRT_DELIVERY_CHANNEL,VRT_TRAN_CODE,VRT_TRAN_OBJ_NAME),
	CONSTRAINT FK_TRANOBJMAP_RULEPARAMETERS FOREIGN KEY (VRT_PARAM_ID)
	REFERENCES VMSCMS.VMS_RULE_PARAMETERS (VRP_PARAM_ID)  
);  	