CREATE OR REPLACE PACKAGE VMSCMS.PACK_GEN_VERIABLE
 AS

 TYPE TYPE_CUST_REC IS RECORD
 (
 p_cust_gendata   VARCHAR2(100));

 TYPE TYPE_CUST_REC_TAB_OLD IS TABLE OF TYPE_CUST_REC INDEX BY BINARY_INTEGER;
 TYPE TYPE_CUST_REC_TAB  AS VARRAY(10) OF  VARCHAR2(100);
 END;
/


