create or replace PACKAGE        vmscms.VMS_SPIL_VIRTUAL AS

   PROCEDURE SALE_ACTIVE_CODE_REQ(
    p_inst_code_in                 IN VARCHAR2,
    p_msg_typ_in                   IN VARCHAR2,
    p_rrn_in                       IN VARCHAR2,
    p_delivery_channel_in          IN VARCHAR2,
    p_term_id_in                   IN VARCHAR2,
    p_tran_code_in                 IN VARCHAR2,
    p_tran_mode_in                 IN VARCHAR2,
    p_business_date_in             IN VARCHAR2,
    p_business_time_in             IN VARCHAR2,
    p_curr_code_in                 IN VARCHAR2,
    p_reversal_code_in             IN VARCHAR2,
    p_prod_code_in                 IN VARCHAR2,
    p_card_type_in                 IN VARCHAR2,
    p_package_id_in                IN VARCHAR2,
    p_tran_amount_in               IN NUMBER,
    p_merchant_name_in             IN VARCHAR2,
    p_store_id_in                  IN VARCHAR2,
    p_store_addr1_in               IN VARCHAR2,
    p_store_addr2_in               IN VARCHAR2,
    p_store_city_in                IN VARCHAR2,
    p_store_state_in               IN VARCHAR2,
    p_postal_code_in               IN VARCHAR2,
    p_fee_amt_in                   IN VARCHAR2,
    p_upc_in                       IN VARCHAR2,
    p_mercrefnum_in                IN VARCHAR2,
    p_reqtimezone_in               IN VARCHAR2,
    p_localcountry_in              IN VARCHAR2,
    p_localcurrency_in             IN VARCHAR2,
    p_loclanguage_in               IN VARCHAR2,
    p_posentry_in                  IN VARCHAR2,
    p_poscond_in                   IN VARCHAR2,
    p_resp_msg_out                 OUT VARCHAR2,
    p_resp_code_out                OUT VARCHAR2,
    p_acct_balance_out             OUT NUMBER,
    p_auth_id_out                  OUT VARCHAR2,
    p_serial_no_out                OUT VARCHAR2,
    p_proxy_no_out                 OUT VARCHAR2,
    p_pan_number_out               OUT VARCHAR2,
    p_card_status_out              OUT VARCHAR2,
    p_merchant_id_in                IN VARCHAR2 DEFAULT NULL
    );

    PROCEDURE SALE_ACTIVE_CODE_REV(
    p_inst_code_in                 IN VARCHAR2,
    p_msg_typ_in                   IN VARCHAR2,
    p_rrn_in                       IN VARCHAR2,
    p_delivery_channel_in          IN VARCHAR2,
    p_term_id_in                   IN VARCHAR2,
    p_tran_code_in                 IN VARCHAR2,
    p_tran_mode_in                 IN VARCHAR2,
    p_business_date_in             IN VARCHAR2,
    p_business_time_in             IN VARCHAR2,
    p_curr_code_in                 IN VARCHAR2,
    p_reversal_code_in             IN VARCHAR2,
    p_prod_code_in                 IN VARCHAR2,
    p_card_type_in                 IN VARCHAR2,
    p_package_id_in                IN VARCHAR2,
    p_tran_amount_in               IN NUMBER,
    p_merchant_name_in             IN VARCHAR2,
    p_store_id_in                  IN VARCHAR2,
    p_store_addr1_in               IN VARCHAR2,
    p_store_addr2_in               IN VARCHAR2,
    p_store_city_in                IN VARCHAR2,
    p_store_state_in               IN VARCHAR2,
    p_postal_code_in               IN VARCHAR2,
    p_fee_amt_in                   IN VARCHAR2,
    p_upc_in                       IN VARCHAR2,
    p_mercrefnum_in                IN VARCHAR2,
    p_reqtimezone_in               IN VARCHAR2,
    p_localcountry_in              IN VARCHAR2,
    p_localcurrency_in             IN VARCHAR2,
    p_loclanguage_in               IN VARCHAR2,
    p_posentry_in                  IN VARCHAR2,
    p_poscond_in                   IN VARCHAR2,
    p_resp_msg_out                 OUT VARCHAR2,
    p_resp_code_out                OUT VARCHAR2,
    p_acct_balance_out             OUT NUMBER,
    p_auth_id_out                  OUT VARCHAR2,
    p_serial_no_out                OUT VARCHAR2,
    p_proxy_no_out                 OUT VARCHAR2,
    p_pan_number_out               OUT VARCHAR2,
    p_card_status_out              OUT VARCHAR2
    );

END VMS_SPIL_VIRTUAL;
/
show error