create or replace
PACKAGE vmscms.VMS_TRANSACTION IS 

PROCEDURE get_transaction_history (p_inst_code_in               IN   VARCHAR2,
                                   p_del_channel_in             IN   VARCHAR2,
                                   p_txn_code_in                IN   VARCHAR2,
                                   p_rrn_in                     IN   VARCHAR2,
                                   p_src_app_in                 IN   VARCHAR2,
                                   p_partner_id_in              IN   VARCHAR2,
                                   p_business_date_in           IN   VARCHAR2,
                                   p_business_time_in           IN   VARCHAR2,
                                   p_curr_code_in               IN   VARCHAR2,
                                   p_reversal_code_in           IN   VARCHAR2,
                                   p_msg_type_in                IN   VARCHAR2,
                                   p_ip_addr_in                 IN   VARCHAR2,
                                   p_ani_in                     IN   VARCHAR2,
                                   p_dni_in                     IN   VARCHAR2,
                                   p_dev_mob_no_in              IN   VARCHAR2,
                                   p_device_id_in               IN   VARCHAR2,
                                   p_uuid_in                    IN   VARCHAR2,
                                   p_osname_in                  IN   VARCHAR2,
                                   p_osversion_in               IN   VARCHAR2,
                                   p_gpscoordinates_in          IN   VARCHAR2,
                                   p_displayresolution_in       IN   VARCHAR2,
                                   p_physicalmemory_in          IN   VARCHAR2,
                                   p_appname_in                 IN   VARCHAR2,
                                   p_appversion_in              IN   VARCHAR2,
                                   p_sessionid_in               IN   VARCHAR2,
                                   p_devicecountry_in           IN   VARCHAR2,
                                   p_deviceregion_in            IN   VARCHAR2,
                                   p_ipcountry_in               IN   VARCHAR2,
                                   p_proxy_in                   IN   VARCHAR2,
                                   p_cust_id_in                 IN   VARCHAR2,
                                   p_pan_code_in                IN   VARCHAR2,
                                   p_start_date_in              IN   VARCHAR2,
                                   p_end_date_in                IN   VARCHAR2,
                                   p_account_type_in            IN   VARCHAR2,
                                   p_tran_filter_in             IN   VARCHAR2,
                                   p_no_of_records_in           IN   VARCHAR2,
                                   p_resp_code_out              OUT  VARCHAR2,
                                   p_resp_msg_out               OUT  VARCHAR2,
                                   p_transaction_out            OUT  SYS_REFCURSOR);
                                 
PROCEDURE get_transaction_history_v2 (p_inst_code_in            IN   VARCHAR2,
                                   p_del_channel_in             IN   VARCHAR2,
                                   p_txn_code_in                IN   VARCHAR2,
                                   p_rrn_in                     IN   VARCHAR2,
                                   p_src_app_in                 IN   VARCHAR2,
                                   p_partner_id_in              IN   VARCHAR2,
                                   p_business_date_in           IN   VARCHAR2,
                                   p_business_time_in           IN   VARCHAR2,
                                   p_curr_code_in               IN   VARCHAR2,
                                   p_reversal_code_in           IN   VARCHAR2,
                                   p_msg_type_in                IN   VARCHAR2,
                                   p_ip_addr_in                 IN   VARCHAR2,
                                   p_ani_in                     IN   VARCHAR2,
                                   p_dni_in                     IN   VARCHAR2,
                                   p_dev_mob_no_in              IN   VARCHAR2,
                                   p_device_id_in               IN   VARCHAR2,
                                   p_uuid_in                    IN   VARCHAR2,
                                   p_osname_in                  IN   VARCHAR2,
                                   p_osversion_in               IN   VARCHAR2,
                                   p_gpscoordinates_in          IN   VARCHAR2,
                                   p_displayresolution_in       IN   VARCHAR2,
                                   p_physicalmemory_in          IN   VARCHAR2,
                                   p_appname_in                 IN   VARCHAR2,
                                   p_appversion_in              IN   VARCHAR2,
                                   p_sessionid_in               IN   VARCHAR2,
                                   p_devicecountry_in           IN   VARCHAR2,
                                   p_deviceregion_in            IN   VARCHAR2,
                                   p_ipcountry_in               IN   VARCHAR2,
                                   p_proxy_in                   IN   VARCHAR2,
                                   p_cust_id_in                 IN   VARCHAR2,
                                   p_pan_code_in                IN   VARCHAR2,
                                   p_start_date_in              IN   VARCHAR2,
                                   p_end_date_in                IN   VARCHAR2,
                                   p_account_type_in            IN   VARCHAR2,
                                   p_tran_filter_in             IN   VARCHAR2,
                                   p_no_of_records_in           IN   VARCHAR2,
                                   p_pagenumber_in              IN   VARCHAR2,
                                   p_resp_code_out              OUT  VARCHAR2,
                                   p_resp_msg_out               OUT  VARCHAR2,
                                   p_total_records_out          OUT  VARCHAR2,
                                   p_total_debit_amount_out     OUT  VARCHAR2,
                                   p_total_credit_amount_out    OUT  VARCHAR2,
                                   p_total_pending_amount_out   OUT  VARCHAR2,
								   p_total_reload_amount_out    OUT  VARCHAR2,
                                   p_transaction_out            OUT  SYS_REFCURSOR
                                   );
								   

FUNCTION get_email_id			(   p_inst_code                 IN    VARCHAR2,
                                    p_customer_card_no_in       IN    VARCHAR2
                                )
    RETURN VARCHAR2;  								   
								   
								   
END VMS_TRANSACTION;
/
show error;