create or replace
PACKAGE               vmscms.VMSCOMMON AS
g_mbr_numb varchar2(5):='000';
PROCEDURE    TRFR_ALERTS (
   p_instcode_in            IN       NUMBER,
   p_fromcard_in            IN       VARCHAR2,
   p_tocard_in              IN       VARCHAR2,
   p_resp_code_out          OUT      VARCHAR2,
   p_errmsg_out             OUT      VARCHAR2
);

PROCEDURE    TXN_MAPPING (
   P_INSTCODE_IN            IN       NUMBER,
   P_FROMDEL_CHNL_IN        IN       VARCHAR2,
   P_TODEL_CHNL_IN          IN       VARCHAR2,
   P_FROMTXN_CODE_IN        IN       VARCHAR2,
   P_TO_TRAN_DESC_IN        IN       VARCHAR2,
   P_USERCODE_IN            IN       NUMBER,
   P_RESP_CODE_OUT          OUT      VARCHAR2,
   P_TO_TRAN_CODE_OUT       OUT       VARCHAR2,
   P_ERRMSG_OUT             OUT      VARCHAR2
);
function CHECK_OVERLAPS (P_EXISTING_SERIAL_IN    varchar2,
                            P_NEW_serial_IN         varchar2)
      RETURN VARCHAR2;

PROCEDURE get_transaction_details(p_inst_code_in          IN   NUMBER,
                                  p_delivery_channel_in   IN   VARCHAR2,
                                  p_tran_code_in          IN   VARCHAR2,
                                  p_cr_dr_flag_out        OUT  VARCHAR2,
                                  p_tran_type_out         OUT  VARCHAR2,
                                  p_tran_desc_out         OUT  VARCHAR2,
                                  p_prfl_flag_out         OUT  VARCHAR2,
                                  p_preauth_flag_out      OUT  VARCHAR2,
                                  p_login_txn_out         OUT  VARCHAR2,
                                  p_preauth_type_out      OUT  VARCHAR2,
                                  p_dup_rrn_check_out     OUT  VARCHAR2,
                                  p_resp_code_out         OUT  VARCHAR2,
                                  p_errmsg_out            OUT  VARCHAR2);

PROCEDURE validate_date_rrn( P_INST_CODE_IN        IN  NUMBER,
                             P_RRN_IN              IN  VARCHAR2,
                             P_TRANDATE_IN         IN  VARCHAR2,
                             P_TRANTIME_IN         IN  VARCHAR2,
                             P_DELIVERY_CHANNEL_IN IN  VARCHAR2,
                             P_ERRMSG_OUT          OUT VARCHAR2,
                             P_RESP_CODE_OUT       OUT VARCHAR2);


PROCEDURE   authorize_nonfinancial_txn (
   p_inst_code_in           IN       NUMBER,
   p_msg_type_in            IN       VARCHAR2,
   p_rrn_in                 IN       VARCHAR2,
   p_delivery_channel_in    IN       cms_delchannel_mast.cdm_channel_code%TYPE,
   p_txn_code_in            IN       cms_transaction_mast.ctm_tran_code%TYPE,
   p_txn_mode_in            IN       VARCHAR2,
   p_tran_date_in           IN       VARCHAR2,
   p_tran_time_in           IN       VARCHAR2,
   p_rvsl_code_in           IN       VARCHAR2,
   p_tran_type_in           IN       cms_transaction_mast.ctm_tran_type%TYPE,
   p_pan_code_in            IN       VARCHAR2,
   p_hash_pan_in            IN       cms_appl_pan.cap_pan_code%TYPE,
   p_encr_pan_in            IN       cms_appl_pan.cap_pan_code_encr%TYPE,
   p_acct_no_in             IN       cms_acct_mast.cam_acct_no%TYPE,
   p_card_stat_in           IN       cms_appl_pan.cap_card_stat%TYPE,
   p_expry_date_in          IN       cms_appl_pan.cap_expry_date%TYPE,
   p_prod_code_in           IN       cms_appl_pan.cap_prfl_code%TYPE,
   p_card_type_in           IN       cms_appl_pan.cap_card_type%TYPE,
   p_prfl_flag_in           IN       cms_transaction_mast.ctm_prfl_flag%TYPE,
   p_prfl_code_in           IN       cms_appl_pan.cap_prfl_code%TYPE,
   p_txn_type_in            IN       VARCHAR2,
   p_curr_code_in           IN       VARCHAR2,
   p_preauth_flag_in        IN       cms_transaction_mast.ctm_preauth_flag%TYPE,
   p_trans_desc_in          IN       cms_transaction_mast.ctm_tran_desc%TYPE,
   p_dr_cr_flag_in          IN       cms_transaction_mast.ctm_credit_debit_flag%TYPE,
   p_login_txn_in           IN       cms_transaction_mast.ctm_login_txn%TYPE,
   p_resp_code_out          OUT      VARCHAR2,
   p_res_msg_out            OUT      VARCHAR2,
   p_comb_hash_out          OUT      pkg_limits_check.type_hash,
   p_auth_id_out            OUT      transactionlog.auth_id%TYPE,
   p_fee_code_out           OUT      transactionlog.feecode%TYPE,
   p_fee_plan_out           OUT      transactionlog.fee_plan%TYPE,
   p_feeattach_type_out     OUT      transactionlog.feeattachtype%TYPE,
   p_tranfee_amt_out        OUT      transactionlog.tranfee_amt%TYPE,
   p_total_amt_out          OUT      transactionlog.total_amount%TYPE,
   p_preauth_type_out       OUT      cms_transaction_mast.ctm_preauth_type%TYPE
);

PROCEDURE authorize_financial_txn (
   p_inst_code_in           IN       NUMBER,
   p_msg_type_in            IN       VARCHAR2,
   p_rrn_in                 IN       VARCHAR2,
   p_delivery_channel_in    IN       VARCHAR2,
   p_terminal_id_in         IN       VARCHAR2,
   p_txn_code_in            IN       VARCHAR2,
   p_txn_mode_in            IN       VARCHAR2,
   p_tran_date_in           IN       VARCHAR2,
   p_tran_time_in           IN       VARCHAR2,
   p_card_no_in             IN       VARCHAR2,
   p_hash_pan_in            IN       cms_appl_pan.cap_pan_code%TYPE,
   p_encr_pan_in            IN       cms_appl_pan.cap_pan_code_encr%TYPE,
   p_card_status_in         IN       cms_appl_pan.cap_card_stat%TYPE,
   p_proxy_number_in        IN       cms_appl_pan.cap_proxy_number%TYPE,
   p_acct_no_in             IN       cms_acct_mast.cam_acct_no%TYPE,
   p_expry_date_in          IN       cms_appl_pan.cap_expry_date%TYPE,
   p_prod_code_in           IN       cms_appl_pan.cap_prfl_code%TYPE,
   p_card_type_in           IN       cms_appl_pan.cap_card_type%TYPE,
   p_prfl_flag_in           IN       cms_transaction_mast.ctm_prfl_flag%TYPE,
   p_prfl_code_in           IN       cms_appl_pan.cap_prfl_code%TYPE,
   p_txn_type_in            IN       VARCHAR2,
   p_curr_code_in           IN       VARCHAR2,
   p_preauth_flag_in        IN       cms_transaction_mast.ctm_preauth_flag%TYPE,
   p_trans_desc_in          IN       cms_transaction_mast.ctm_tran_desc%TYPE,
   p_dr_cr_flag_in          IN       cms_transaction_mast.ctm_credit_debit_flag%TYPE,
   p_login_txn_in           IN       cms_transaction_mast.ctm_login_txn%TYPE,
   p_amnt_tnfr_flag_in      IN       cms_transaction_mast.ctm_amnt_transfer_flag%TYPE,
    p_bank_code_in           IN       VARCHAR2,
   p_txn_amt_in             IN       NUMBER,
   p_merchant_name_in       IN       VARCHAR2,
   p_merchant_city_in       IN       VARCHAR2,
   p_mcc_code_in            IN       VARCHAR2,
   p_tip_amt_in             IN       VARCHAR2,
   p_to_acct_no_in          IN       VARCHAR2,
   p_atmname_loc_in         IN       VARCHAR2,
   p_mcccode_groupid_in     IN       VARCHAR2,
   p_currcode_groupid_in    IN       VARCHAR2,
   p_transcode_groupid_in   IN       VARCHAR2,
   p_rules_in               IN       VARCHAR2,
   p_preauth_date_in        IN       DATE,
   p_consodium_code_in      IN       VARCHAR2,
   p_partner_code_in        IN       VARCHAR2,
   p_stan_in                IN       VARCHAR2,
   p_rvsl_code_in           IN       VARCHAR2,
   p_fee_flag_in            IN       VARCHAR2,
   p_admin_flag_in          IN       VARCHAR2 ,
   p_ip_addr_in                IN       VARCHAR2,
   p_ani_in                    IN       VARCHAR2,
   p_dni_in                    IN       VARCHAR2,
   p_device_mob_no_in          IN       VARCHAR2,
   p_device_id_in              IN       VARCHAR2,
   p_uuid_in                   IN       VARCHAR2,
   p_os_name_in                IN       VARCHAR2,
   p_os_version_in             IN       VARCHAR2,
   p_gps_coordinates_in        IN       VARCHAR2,
   p_display_resolution_in     IN       VARCHAR2,
   p_physical_memory_in        IN       VARCHAR2,
   p_app_name_in               IN       VARCHAR2,
   p_app_version_in            IN       VARCHAR2,
   p_session_id_in             IN       VARCHAR2,
   p_device_country_in         IN       VARCHAR2,
   p_device_region_in          IN       VARCHAR2,
   p_comments_in          in varchar2,
   p_auth_id_out            OUT      VARCHAR2,
   p_resp_code_out          OUT      VARCHAR2,
   p_resp_msg_out           OUT      VARCHAR2
);


PROCEDURE CHECK_ORDER_STATUS(
    P_I_INST_CODE          IN NUMBER,
    p_I_delivery_channel   IN       VARCHAR2,
    p_I_tran_code          IN       VARCHAR2,
    p_I_hash_pan      IN       VARCHAR2,
    p_I_prod_code          IN       VARCHAR2,
    p_I_card_type          IN       VARCHAR2,
    P_I_CARD_STATUS     IN       VARCHAR2,
    P_I_MSGTYPE                 IN      VARCHAR2,
    P_O_STATUS_CHECK      OUT VARCHAR2,
    p_O_resp_code          OUT      VARCHAR2,
    p_O_resp_msg           OUT      VARCHAR2);

END VMSCOMMON;
/
SHOW ERROR;