create or replace
PACKAGE          VMSCMS.VMSTOKENIZATION IS

   -- Author  : Pankaj S.
   -- Created : 6/17/2016 2:00:00 PM
   -- Purpose : VISA Tokenization Service

   -- Public type declarations

   -- Public constant declarations

   -- Public variable declarations

   -- Public function and procedure declarations
PROCEDURE update_token_status(
    p_token_in     VARCHAR2,
    p_cardno_in    VARCHAR2,
    P_TOKEN_STATUS_in VARCHAR2,
    p_respmsg_out OUT VARCHAR2 );

PROCEDURE CHECK_ELIGIBILITY(
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_tran_amt_in                 in  	varchar2,
          p_curr_code_in                in  	varchar2,
          P_EXPRY_DATE_IN               IN  	VARCHAR2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_cntry_code_in               in  	varchar2,
          p_stan_in                     in  	varchar2,
          p_auth_id_out                 out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_resmsg_out                  out 	varchar2,
          P_ISSUERREF_ID_OUT            OUT   VARCHAR2,
          P_CARDART_ID_OUT              OUT   VARCHAR2,
          P_TANDC_ID_OUT                OUT   VARCHAR2,
          P_ACTION_CODE_OUT             OUT   VARCHAR2,
          p_error_code_out              OUT   VARCHAR2,
          p_resp_id_out                 OUT   VARCHAR2);



PROCEDURE  send_passcode_req (
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_token_in   		              in  	varchar2,
          p_tran_amt_in                 in  	varchar2,
          p_curr_code_in                in  	varchar2,
          p_expry_date_in               in  	varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_cntry_code_in               in  	varchar2,
          p_verify_method_in            in  	varchar2,
          p_auth_id_out                 out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resmsg_out                  out 	varchar2,
          p_cell_no_out                 out   varchar2,
          p_email_id_out                out   varchar2,
          p_verify_method_out           out  	varchar2,
          p_action_code_out             out  	varchar2,
          p_error_code_out              out  	varchar2,
          p_resp_id_out                 out  	varchar2
           );

PROCEDURE  CardholderVerification (
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_token_in   		              in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_token_type_in   		        in  	varchar2,
          p_token_status_in   		      in  	varchar2,
          p_token_assurance_level_in    in  	varchar2,
          p_token_requester_id_in   	  in  	varchar2,
          p_token_ref_id_in   		      in  	varchar2,
          p_token_expry_date_in         in  	varchar2,
          p_token_pan_ref_id_in         in  	varchar2,
          p_token_wpriskassessment_in   in  	varchar2,
          p_token_wpriskassess_ver_in in  	varchar2,
          p_token_wpdevice_score_in     in  	varchar2,
          p_token_wpaccount_score_in    in  	varchar2,
          p_token_wpreason_codes_in     in  	varchar2,
          p_token_wppan_source_in       in  	varchar2,
          p_token_wpacct_id_in          in  	varchar2,
          p_token_wpacct_email_in       in  	varchar2,
          p_token_device_type_in        in  	varchar2,
          p_token_device_langcode_in    in  	varchar2,
          p_token_device_id_in          in  	varchar2,
          p_token_device_no_in          in  	varchar2,
          p_token_device_name_in        in  	varchar2,
          p_token_device_loc_in         in  	varchar2,
          p_token_device_ip_in          in  	varchar2,
          p_token_device_secureeleid_in in  	varchar2,
          p_token_riskassess_score_in  in  	varchar2,
          p_token_provisioning_score_in in  	varchar2,
          p_curr_code_in                in    varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_stan_in                     in  	varchar2,
          P_NTW_SETTL_DATE              IN  	VARCHAR2,
          p_expry_date_in               in  	varchar2,          
          p_msg_reason_code_in          in    varchar2,
          p_contactless_usage_in        IN  	VARCHAR2,
          p_card_ecomm_usage_in         in  	varchar2,
          P_MOB_ECOMM_USAGE_IN_IN       IN  	VARCHAR2,
          p_wallet_identifier_in        IN  	VARCHAR2,
          p_storage_tech_in             IN  	VARCHAR2, 
          P_TOKEN_REQID13_IN            IN  	VARCHAR2,
          P_WP_REQID_IN                 IN  	VARCHAR2,
          P_WP_CONVID_IN                IN  	VARCHAR2,
          P_WALLET_ID_IN                IN  	VARCHAR2,
          P_TRAN_AMT_IN                 IN  	VARCHAR2,
          P_PAYMENT_APPPLNINSTANCEID_IN  in  	varchar2,
          p_auth_id_out                 out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resmsg_out                  out 	varchar2,
          p_action_code_out             out  	varchar2,
          p_error_code_out              out  	varchar2,
          p_de27response_out            out   varchar2,
          p_resp_id_out                 out   varchar2
   );

   PROCEDURE validate_pan_token(
        p_inst_code_in           IN   NUMBER,
        p_token_in               IN   VARCHAR2,
        P_CARDNO_IN              IN   VARCHAR2,
        p_delivery_channel_in    IN  VARCHAR2,
        p_response_id_out        OUT VARCHAR2,
        P_RESPMSG_OUT            OUT  VARCHAR2,
        p_token_staus_out        OUT VARCHAR2,
        p_reason_code_out        OUT VARCHAR2,
        p_token_reqid_out        OUT VARCHAR2,
        p_token_refid_out        OUT VARCHAR2);

  PROCEDURE  TokenServiceAdvice(
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_token_in   		              in  	varchar2,
          p_tran_amt_in                 in  	varchar2,
          p_curr_code_in                in  	varchar2,
          p_expry_date_in               in  	varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_cntry_code_in               in  	varchar2,
          p_response_code_in            in  	varchar2,
          p_stan_in                     in  	varchar2,
          p_ntw_settl_date              IN  	VARCHAR2,          
          P_ACTIVATION_RESULT           IN  	VARCHAR2,
          p_token_type_in   		        in  	varchar2,
          p_token_status_in   		      in  	varchar2,
          p_token_assurance_level_in    in  	varchar2,
          p_token_requester_id_in   	  in  	varchar2,
          p_token_ref_id_in   		      in  	varchar2,
          p_token_expry_date_in         in  	varchar2,
          p_token_pan_ref_id_in         in  	varchar2,
          p_token_wpriskassessment_in   in  	varchar2,
          p_token_wpriskassess_ver_in in  	varchar2,
          p_token_wpdevice_score_in     in  	varchar2,
          p_token_wpaccount_score_in    in  	varchar2,
          p_token_wpreason_codes_in     in  	varchar2,
          p_token_wppan_source_in       in  	varchar2,
          p_token_wpacct_id_in          in  	varchar2,
          p_token_wpacct_email_in       in  	varchar2,
          p_token_device_type_in        in  	varchar2,
          p_token_device_langcode_in    in  	varchar2,
          p_token_device_id_in          in  	varchar2,
          p_token_device_no_in          in  	varchar2,
          p_token_device_name_in        in  	varchar2,
          p_token_device_loc_in         in  	varchar2,
          p_token_device_ip_in          in  	varchar2,
          p_token_device_secureeleid_in in  	varchar2,
          P_TOKEN_RISKASSESS_SCORE_IN  IN  	VARCHAR2,
          P_TOKEN_PROVISIONING_SCORE_IN IN  	VARCHAR2,
          p_msg_reason_code_in          in    varchar2,
          p_contactless_usage_in        IN  	VARCHAR2,
          p_card_ecomm_usage_in         in  	varchar2,
          P_MOB_ECOMM_USAGE_IN_IN       IN  	VARCHAR2,
          p_wallet_identifier_in        IN  	VARCHAR2,
          p_storage_tech_in             IN  	VARCHAR2, 
          P_TOKEN_REQID13_IN            IN  	VARCHAR2,
          P_WP_REQID_IN                 IN  	VARCHAR2,
          P_WP_CONVID_IN                IN  	VARCHAR2,
          P_WALLET_ID_IN                IN  	VARCHAR2,
          P_PAYMENT_APPPLNINSTANCEID_IN  IN  	varchar2,
          p_auth_id_out                 out 	varchar2,
          p_resp_code_out               out 	varchar2,
          P_ISO_RESP_CODE_OUT           OUT 	VARCHAR2,
          p_resmsg_out                  out 	varchar2,
          P_ACTION_CODE_OUT             OUT  	VARCHAR2,
          p_error_code_out              out  	varchar2,
          P_TOKEN_ACT_FLAG_OUT           out   varchar2,
          p_resp_id_out                  out   varchar2
   );


     PROCEDURE  TokenCreateAdvice (
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_token_in   		              in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_token_type_in   		        in  	varchar2,
          p_token_status_in   		      in  	varchar2,
          p_token_assurance_level_in    in  	varchar2,
          p_token_requester_id_in   	  in  	varchar2,
          p_token_ref_id_in   		      in  	varchar2,
          p_token_expry_date_in         in  	varchar2,
          p_token_pan_ref_id_in         in  	varchar2,
          p_token_wpriskassessment_in   in  	varchar2,
          p_token_wpriskassess_ver_in in  	varchar2,
          p_token_wpdevice_score_in     in  	varchar2,
          p_token_wpaccount_score_in    in  	varchar2,
          p_token_wpreason_codes_in     in  	varchar2,
          p_token_wppan_source_in       in  	varchar2,
          p_token_wpacct_id_in          in  	varchar2,
          p_token_wpacct_email_in       in  	varchar2,
          p_token_device_type_in        in  	varchar2,
          p_token_device_langcode_in    in  	varchar2,
          p_token_device_id_in          in  	varchar2,
          p_token_device_no_in          in  	varchar2,
          p_token_device_name_in        in  	varchar2,
          p_token_device_loc_in         in  	varchar2,
          p_token_device_ip_in          in  	varchar2,
          p_token_device_secureeleid_in in  	varchar2,
          p_token_riskassess_score_in  in  	varchar2,
          p_token_provisioning_score_in in  	varchar2,
          p_curr_code_in                in    varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_stan_in                     in  	varchar2,
          P_NTW_SETTL_DATE              IN  	VARCHAR2,
          p_expry_date_in               in  	varchar2,          
          p_msg_reason_code_in          in    varchar2,
          p_contactless_usage_in        IN  	VARCHAR2,
          p_card_ecomm_usage_in         in  	varchar2,
          p_mob_ecomm_usage_in_in       IN  	VARCHAR2,
          p_wallet_identifier_in       IN  	VARCHAR2,
          p_storage_tech_in             IN  	VARCHAR2, 
          p_rule_response               IN  	VARCHAR2,
          p_auth_id_out                 out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_resmsg_out                  out 	VARCHAR2,
          p_de27response_out            out   varchar2
          ,p_token_reqid13_in         in  	varchar2 default null
          ,p_wp_reqid_in              in  	varchar2 default null
          ,p_wp_convid_in             in  	varchar2 default null
          ,P_WALLET_ID_IN             IN  	VARCHAR2 DEFAULT NULL
          ,P_TOKEN_ACT_FLAG_OUT           out   varchar2     
          ,p_resp_id_out                  out   varchar2
          );

PROCEDURE  Token_STIPAdvice(p_inst_code_in  in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_tran_amt_in                 in  	varchar2,
          p_curr_code_in                in  	varchar2,
          P_EXPRY_DATE_IN               IN  	VARCHAR2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_cntry_code_in               in  	varchar2,
          p_stan_in                     in  	varchar2,
          p_adj_resp_cod_in             in    varchar2,
          p_auth_id_out                 out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_resmsg_out                  out 	VARCHAR2,
          p_resp_id_out                 out 	varchar2);

PROCEDURE cleanup_suspend_tokens(
    p_job_id_in   IN NUMBER,
    p_respmsg_out OUT VARCHAR2 );    

PROCEDURE delete_sync_tokens(p_token_in     VARCHAR2, 
            p_cardno_in     VARCHAR2,
            p_newcard_in IN VARCHAR2,
            p_reasonCode_in IN VARCHAR2,
            p_acctno_in IN VARCHAR2,
            p_resp_code_in IN VARCHAR2,
            p_inst_code_in IN VARCHAR2,
            p_card_stat_in IN VARCHAR2,
            p_encr_pan_in IN VARCHAR2, 
            p_rrn_in  IN VARCHAR2,
            p_ccaflag_in        IN VARCHAR2 default 'Y' ,
            p_respmsg_out OUT VARCHAR2 );
    
PROCEDURE cardno_tokens_sync(
    p_cardno_in    VARCHAR2,
    p_respmsg_out OUT VARCHAR2 );
    
PROCEDURE TOKEN_STATUS_NOTIFY(
    P_CARDNO_IN       IN VARCHAR2,
    P_EXPRY_DATE_IN   IN VARCHAR2,
    P_CLOSEDCARDNO_IN IN VARCHAR2,
    P_NEWCARDNO_IN    IN VARCHAR2,
    P_RRN_IN          IN VARCHAR2,
    P_ACCT_NO_IN         IN VARCHAR2,
    p_prod_code_in    IN VARCHAR2,
    p_card_type_in    IN VARCHAR2,
    p_card_status_in  IN VARCHAR2,
    p_replaced_expry_date_in IN VARCHAR2,
    P_VALID_ACTION OUT VARCHAR2,
    P_REC_COUNT OUT NUMBER,
    P_RESPMSG_OUT OUT VARCHAR2);  
    
PROCEDURE  TokenCompleteNotification (
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_token_in   		              in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_token_type_in   		        in  	varchar2,
          p_token_status_in   		      in  	varchar2,
          p_token_assurance_level_in    in  	varchar2,
          p_token_requester_id_in   	  in  	varchar2,
          p_token_ref_id_in   		      in  	varchar2,
          p_token_expry_date_in         in  	varchar2,
          p_token_pan_ref_id_in         in  	varchar2,
          p_token_wpriskassessment_in   in  	varchar2,
          p_token_wpriskassess_ver_in in  	varchar2,
          p_token_wpdevice_score_in     in  	varchar2,
          p_token_wpaccount_score_in    in  	varchar2,
          p_token_wpreason_codes_in     in  	varchar2,
          p_token_wppan_source_in       in  	varchar2,
          p_token_wpacct_id_in          in  	varchar2,
          p_token_wpacct_email_in       in  	varchar2,
          p_token_device_type_in        in  	varchar2,
          p_token_device_langcode_in    in  	varchar2,
          p_token_device_id_in          in  	varchar2,
          p_token_device_no_in          in  	varchar2,
          p_token_device_name_in        in  	varchar2,
          p_token_device_loc_in         in  	varchar2,
          p_token_device_ip_in          in  	varchar2,
          p_token_device_secureeleid_in in  	varchar2,
          p_token_riskassess_score_in  in  	varchar2,
          p_token_provisioning_score_in in  	varchar2,
          p_curr_code_in                in    varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_stan_in                     in  	varchar2,
          P_NTW_SETTL_DATE              IN  	VARCHAR2,
          p_expry_date_in               IN  	VARCHAR2,          
          p_msg_reason_code_in          in    varchar2,
          p_contactless_usage_in        IN  	VARCHAR2,
          p_card_ecomm_usage_in         in  	varchar2,
          p_mob_ecomm_usage_in_in       IN  	VARCHAR2,
          p_wallet_identifier_in       IN  	VARCHAR2,
          p_storage_tech_in             IN  	VARCHAR2, 
          p_auth_id_out                 out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_resmsg_out                  out 	varchar2  
          ,p_token_reqid13_in         in  	varchar2 default null
          ,p_wp_reqid_in              in  	varchar2 default null
          ,p_wp_convid_in             in  	varchar2 default null
          ,p_wallet_id_in             in  	varchar2 default null
          ,p_correlation_id_in             in  	varchar2 default null
          ,p_payment_appplninstanceid_in     in  	varchar2 default null
          ,p_resp_id_out                 out   varchar2
          );    
          
PROCEDURE  TokenActivationNotification (
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_token_in   		              in  	varchar2,
          p_tran_amt_in                 in  	varchar2,
          p_curr_code_in                in  	varchar2,
          p_expry_date_in               in  	varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_cntry_code_in               IN  	VARCHAR2,
          p_verify_method_in            in  	varchar2,
          p_auth_id_out                 out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resmsg_out                  out 	VARCHAR2,
          p_cell_no_out                 out   VARCHAR2,
          p_email_id_out                out   VARCHAR2,
          p_verify_method_out           out  	varchar2,
          p_resp_id_out                 out  	varchar2);  
          
PROCEDURE  TokenEventNotification (
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_pan_code_in   		          in  	varchar2,          
          p_tran_amt_in                 in  	varchar2,
          p_curr_code_in                in  	varchar2,
          p_expry_date_in               in  	varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_cntry_code_in               IN  	VARCHAR2, 
          p_token_event_ind_in          IN  	VARCHAR2,  
          p_token_in                    in  	varchar2,
          p_token_type_in               IN  	VARCHAR2,
          p_token_status_in             IN  	VARCHAR2,
          p_token_assurance_level_in    in  	varchar2,
          p_token_requester_id_in       in  	varchar2,
          p_token_expry_date_in         in  	varchar2,
          p_token_device_type_in        in  	varchar2,
          p_token_device_langcode_in    in  	varchar2,
          p_token_device_id_in          in  	varchar2,
          p_token_device_no_in          in  	varchar2,
          p_token_device_name_in        in  	varchar2,
          p_token_device_loc_in         IN  	VARCHAR2,
          p_token_device_ip_in          IN  	VARCHAR2, 
          p_token_event_req_in          IN  	VARCHAR2,  
          p_auth_id_out                 out 	varchar2,
          p_resp_code_out               out 	VARCHAR2,
          p_iso_resp_code_out           out 	VARCHAR2,
          p_resmsg_out                  out 	varchar2,
          p_resp_id_out                 out 	varchar2 );    
          
PROCEDURE TOKEN_AUTHORISE_PRECHECK(
    P_INST_CODE_IN        IN VARCHAR2,
    P_DELIVERY_CHANNEL_IN IN VARCHAR2,
    P_TRAN_CODE_IN        IN VARCHAR2,
    P_TRAN_MODE_IN        IN VARCHAR2,
    P_MSG_TYPE_IN         IN VARCHAR2,
    P_TRAN_DATE_IN        IN VARCHAR2,
    P_TRAN_TIME_IN        IN VARCHAR2,
    P_CARD_NUMBER_IN      IN VARCHAR2,
    p_expry_date_in       in varchar2,
    p_token_in               in varchar2,
    p_correlationid_in               in varchar2,
    p_RRN_in               in varchar2,
    P_CVV2_FLAG_OUT       OUT VARCHAR2,
    p_rule_bypass         out varchar2,
    P_RETURN_CODE_OUT          OUT VARCHAR2,
    P_RESP_CODE_OUT       OUT VARCHAR2,
    p_resmsg_out          out varchar2
    );
    
 PROCEDURE TOKEN_LOG_RULE_RESPONSE(
    P_INST_CODE_IN     IN VARCHAR2,
    P_CARD_NUMBER_IN   IN VARCHAR2,
    P_TOKEN_REQUESTER_ID_IN    IN VARCHAR2,
    p_rule_response               IN  	VARCHAR2,
    p_rrn_in                      IN  	varchar2,
    p_token_in   		              IN  	varchar2,
    p_token_device_id_in    IN VARCHAR2,
    P_RESP_CODE_OUT OUT VARCHAR2,
    P_RESMSG_OUT OUT VARCHAR2 );   
    
    PROCEDURE LP_TOKEN_CREATE_UPDATE(
    P_TOKEN_IN                    IN VARCHAR2,
    P_HASH_PAN_IN                 IN VARCHAR2,
    P_TOKEN_TYPE_IN               IN VARCHAR2,
    P_RULE_RESPONSE               IN VARCHAR2,
    P_TOKEN_ASSURANCE_LEVEL_IN    IN VARCHAR2,
    P_TOKEN_REQUESTER_ID_IN       IN VARCHAR2,
    P_TOKEN_REF_ID_IN             IN VARCHAR2,
    P_TOKEN_EXPRY_DATE_IN         IN VARCHAR2,
    P_TOKEN_PAN_REF_ID_IN         IN VARCHAR2,
    P_TOKEN_WPPAN_SOURCE_IN       IN VARCHAR2,
    P_TOKEN_WPRISKASSESSMENT_IN   IN VARCHAR2,
    P_TOKEN_WPRISKASSESS_VER_IN   IN VARCHAR2,
    P_TOKEN_WPDEVICE_SCORE_IN     IN VARCHAR2,
    P_TOKEN_WPACCOUNT_SCORE_IN    IN VARCHAR2 ,
    P_TOKEN_WPREASON_CODES_IN     IN VARCHAR2,
    P_TOKEN_WPACCT_ID_IN          IN VARCHAR2,
    P_TOKEN_WPACCT_EMAIL_IN       IN VARCHAR2,
    P_TOKEN_DEVICE_TYPE_IN        IN VARCHAR2,
    P_TOKEN_DEVICE_LANGCODE_IN    IN VARCHAR2,
    P_TOKEN_DEVICE_ID_IN          IN VARCHAR2,
    P_TOKEN_DEVICE_NO_IN          IN VARCHAR2,
    P_TOKEN_DEVICE_NAME_IN        IN VARCHAR2,
    P_TOKEN_DEVICE_LOC_IN         IN VARCHAR2,
    P_TOKEN_DEVICE_IP_IN          IN VARCHAR2,
    P_TOKEN_DEVICE_SECUREELEID_IN IN VARCHAR2,
    P_WALLET_IDENTIFIER_IN        IN VARCHAR2,
    P_STORAGE_TECH_IN             IN VARCHAR2,
    P_TOKEN_RISKASSESS_SCORE_IN   IN VARCHAR2,
    P_TOKEN_PROVISIONING_SCORE_IN IN VARCHAR2,
    P_CONTACTLESS_USAGE_IN        IN VARCHAR2,
    P_CARD_ECOMM_USAGE_IN         IN VARCHAR2,
    P_MOB_ECOMM_USAGE_IN_IN       IN VARCHAR2,
    P_ACCT_NUMBER_IN              IN VARCHAR2,
    P_CUST_CODE_IN                IN VARCHAR2,
    P_INST_CODE_IN                IN VARCHAR2,
    P_TOKEN_REQID13_IN            IN VARCHAR2,
    P_WP_REQID_IN                 IN VARCHAR2,
    P_WP_CONVID_IN                IN VARCHAR2,
    P_WALLET_ID_IN                IN VARCHAR2 ,
    p_payment_appplninstanceid_in In VARCHAR2,
    p_de62_uid_in In VARCHAR2,
    P_RESP_CDE_OUT OUT VARCHAR2,
    P_RESP_MSG_OUT OUT VARCHAR2);
    
     PROCEDURE LP_GET_TOKEN_STATUS(
     P_TOKEN_IN IN VARCHAR2,
     P_HASHCARD_IN IN VARCHAR2,
     P_TOKEN_OLD_STATUS_IN IN VARCHAR2,
     P_TOKEN_STAT_OUT OUT VARCHAR2);
     
          PROCEDURE  AMEXTokenCreateAdvice (
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_token_in   		              in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_token_type_in   		        in  	varchar2,
          p_token_status_in   		      in  	varchar2,
          p_token_assurance_level_in    in  	varchar2,
          p_token_requester_id_in   	  in  	varchar2,
          p_token_ref_id_in   		      in  	varchar2,
          p_token_expry_date_in         in  	varchar2,
          p_token_pan_ref_id_in         in  	varchar2,
          p_token_wpriskassessment_in   in  	varchar2,
          p_token_wpriskassess_ver_in   in  	varchar2,
          p_token_wpdevice_score_in     in  	varchar2,
          p_token_wpaccount_score_in    in  	varchar2,
          p_token_wpreason_codes_in     in  	varchar2,
          p_token_wppan_source_in       in  	varchar2,
          p_token_wpacct_id_in          in  	varchar2,
          p_token_wpacct_email_in       in  	varchar2,
          p_token_device_type_in        in  	varchar2,
          p_token_device_langcode_in    in  	varchar2,
          p_token_device_id_in          in  	varchar2,
          p_token_device_no_in          in  	varchar2,
          p_token_device_name_in        in  	varchar2,
          p_token_device_loc_in         in  	varchar2,
          p_token_device_ip_in          in  	varchar2,
          p_token_device_secureeleid_in in  	varchar2,
          p_token_riskassess_score_in   in  	varchar2,
          p_token_provisioning_score_in in  	varchar2,
          p_curr_code_in                in    varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_stan_in                     in  	varchar2,
          P_NTW_SETTL_DATE              IN  	VARCHAR2,
          p_expry_date_in               in  	varchar2,
          p_msg_reason_code_in          in    varchar2,
          p_contactless_usage_in        IN  	VARCHAR2,
          p_card_ecomm_usage_in         in  	varchar2,
          p_mob_ecomm_usage_in_in       IN  	VARCHAR2,
          p_wallet_identifier_in        IN  	VARCHAR2,
          p_storage_tech_in             IN  	VARCHAR2,
          p_rule_response               IN  	VARCHAR2,
          p_token_reqid13_in            in  	varchar2,
          p_wp_reqid_in                 in  	varchar2,
          p_wp_convid_in                in  	varchar2,
          P_WALLET_ID_IN                IN  	VARCHAR2,
          P_ZIP_CODE_IN                 IN    VARCHAR2,
          P_ADDRVRIFY_FLAG_IN           IN    VARCHAR2,
          p_networkid_switch_IN         IN    VARCHAR2,
          P_cust_addr_IN            IN    VARCHAR2   DEFAULT NULL ,
          p_auth_id_out                 out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_resmsg_out                  out 	VARCHAR2,
          p_de27response_out            out   varchar2,
          P_TOKEN_ACT_FLAG_OUT          out   varchar2,
          P_ADDR_VERFY_RESPONSE_OUT     OUT   VARCHAR2,
          p_resp_id_out                 OUT   VARCHAR2
          );

    PROCEDURE AMEX_TOKEN_AUTHORISE_PRECHECK(
    P_INST_CODE_IN        IN VARCHAR2,
    P_DELIVERY_CHANNEL_IN IN VARCHAR2,
    P_TRAN_CODE_IN        IN VARCHAR2,
    P_TRAN_MODE_IN        IN VARCHAR2,
    P_MSG_TYPE_IN         IN VARCHAR2,
    P_TRAN_DATE_IN        IN VARCHAR2,
    P_TRAN_TIME_IN        IN VARCHAR2,
    P_CARD_NUMBER_IN      IN VARCHAR2,
    p_expry_date_in       in varchar2,
    p_token_in            in varchar2,
    p_correlationid_in    in varchar2,
    p_RRN_in              in varchar2,
    p_cvv2_flag_out       out varchar2,
    P_RULE_BYPASS         OUT VARCHAR2,
    p_resp_code_out       out varchar2,
    p_resmsg_out          out varchar2,
    P_RETURN_CODE_OUT     out varchar2,
	p_consumedstat_code_out  out varchar2); 
    
    PROCEDURE  AMEXTokenCompleteNotification (
          p_inst_code_in                in    number,
          p_msg_type_in                 in 	  varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_token_in   		              in  	varchar2,
          p_pan_code_in   		          in  	varchar2,
          p_token_type_in   		        in  	varchar2,
          p_token_status_in   		      in  	varchar2,
          p_token_assurance_level_in    in  	varchar2,
          p_token_requester_id_in   	  in  	varchar2,
          p_token_ref_id_in   		      in  	varchar2,
          p_token_expry_date_in         in  	varchar2,
          p_token_pan_ref_id_in         in  	varchar2,
          p_token_wpriskassessment_in   in  	varchar2,
          p_token_wpriskassess_ver_in   in  	varchar2,
          p_token_wpdevice_score_in     in  	varchar2,
          p_token_wpaccount_score_in    in  	varchar2,
          p_token_wpreason_codes_in     in  	varchar2,
          p_token_wppan_source_in       in  	varchar2,
          p_token_wpacct_id_in          in  	varchar2,
          p_token_wpacct_email_in       in  	varchar2,
          p_token_device_type_in        in  	varchar2,
          p_token_device_langcode_in    in  	varchar2,
          p_token_device_id_in          in  	varchar2,
          p_token_device_no_in          in  	varchar2,
          p_token_device_name_in        in  	varchar2,
          p_token_device_loc_in         in  	varchar2,
          p_token_device_ip_in          in  	varchar2,
          p_token_device_secureeleid_in in  	varchar2,
          p_token_riskassess_score_in   in  	varchar2,
          p_token_provisioning_score_in in  	varchar2,
          p_curr_code_in                in    varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_stan_in                     in  	varchar2,
          P_NTW_SETTL_DATE              IN  	VARCHAR2,
          p_expry_date_in               IN  	VARCHAR2,
          p_msg_reason_code_in          in    varchar2,
          p_contactless_usage_in        IN  	VARCHAR2,
          p_card_ecomm_usage_in         in  	varchar2,
          p_mob_ecomm_usage_in_in       IN  	VARCHAR2,
          p_wallet_identifier_in        IN  	VARCHAR2,
          p_storage_tech_in             IN  	VARCHAR2,
          p_token_reqid13_in            in  	varchar2,
          p_wp_reqid_in                 in  	varchar2,
          p_wp_convid_in                in  	varchar2,
          p_wallet_id_in                in  	varchar2,
          p_correlation_id_in           in  	varchar2,
          p_payment_appplninstanceid_in in  	varchar2,
          p_req_respcode                in    varchar2,
          p_rsncode_desc                in    varchar2,
          p_auth_id_out                 out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resp_code_out               out 	varchar2,
          p_resmsg_out                  out 	varchar2,
          p_resp_id_out                 OUT 	VARCHAR2
          );
          
 PROCEDURE AMEX_TOKEN_CREATE_UPDATE(
    P_TOKEN_IN                    IN VARCHAR2,
    P_HASH_PAN_IN                 IN VARCHAR2,
    P_TOKEN_TYPE_IN               IN VARCHAR2,
    P_RULE_RESPONSE               IN VARCHAR2,
    P_TOKEN_ASSURANCE_LEVEL_IN    IN VARCHAR2,
    P_TOKEN_REQUESTER_ID_IN       IN VARCHAR2,
    P_TOKEN_REF_ID_IN             IN VARCHAR2,
    P_TOKEN_EXPRY_DATE_IN         IN VARCHAR2,
    P_TOKEN_PAN_REF_ID_IN         IN VARCHAR2,
    P_TOKEN_WPPAN_SOURCE_IN       IN VARCHAR2,
    P_TOKEN_WPRISKASSESSMENT_IN   IN VARCHAR2,
    P_TOKEN_WPRISKASSESS_VER_IN   IN VARCHAR2,
    P_TOKEN_WPDEVICE_SCORE_IN     IN VARCHAR2,
    P_TOKEN_WPACCOUNT_SCORE_IN    IN VARCHAR2 ,
    P_TOKEN_WPREASON_CODES_IN     IN VARCHAR2,
    P_TOKEN_WPACCT_ID_IN          IN VARCHAR2,
    P_TOKEN_WPACCT_EMAIL_IN       IN VARCHAR2,
    P_TOKEN_DEVICE_TYPE_IN        IN VARCHAR2,
    P_TOKEN_DEVICE_LANGCODE_IN    IN VARCHAR2,
    P_TOKEN_DEVICE_ID_IN          IN VARCHAR2,
    P_TOKEN_DEVICE_NO_IN          IN VARCHAR2,
    P_TOKEN_DEVICE_NAME_IN        IN VARCHAR2,
    P_TOKEN_DEVICE_LOC_IN         IN VARCHAR2,
    P_TOKEN_DEVICE_IP_IN          IN VARCHAR2,
    P_TOKEN_DEVICE_SECUREELEID_IN IN VARCHAR2,
    P_WALLET_IDENTIFIER_IN        IN VARCHAR2,
    P_STORAGE_TECH_IN             IN VARCHAR2,
    P_TOKEN_RISKASSESS_SCORE_IN   IN VARCHAR2,
    P_TOKEN_PROVISIONING_SCORE_IN IN VARCHAR2,
    P_CONTACTLESS_USAGE_IN        IN VARCHAR2,
    P_CARD_ECOMM_USAGE_IN         IN VARCHAR2,
    P_MOB_ECOMM_USAGE_IN_IN       IN VARCHAR2,
    P_ACCT_NUMBER_IN              IN VARCHAR2,
    P_CUST_CODE_IN                IN VARCHAR2,
    P_INST_CODE_IN                IN VARCHAR2,
    P_TOKEN_REQID13_IN            IN VARCHAR2,
    P_WP_REQID_IN                 IN VARCHAR2,
    P_WP_CONVID_IN                IN VARCHAR2,
    P_WALLET_ID_IN                IN VARCHAR2,
    p_payment_appplninstanceid_in IN VARCHAR2,
    p_de62_uid_in                 IN VARCHAR2,
    p_token_stat_in               IN VARCHAR2,
    P_RESP_CDE_OUT                OUT VARCHAR2,
    P_resp_MSG_OUT                OUT VARCHAR2);
    
    PROCEDURE AVS_CHECK(
       P_INST_CODE_IN         IN    NUMBER,
       P_PROD_CODE_IN         IN    VARCHAR2,
       P_PROD_CATG_IN         IN    VARCHAR2,
       P_ZIP_CODE_IN          IN    VARCHAR2,
       P_ADDRVRIFY_FLAG_IN    IN    VARCHAR2,
       P_NETWORKID_SWITCH_IN  IN    VARCHAR2,
       P_CAP_CUST_CODE_IN     IN    VARCHAR2,
       P_CUST_ADDR_IN         IN    VARCHAR2,
       P_RESP_CODE_OUT        OUT   VARCHAR2,
       P_RESP_MSG_OUT         OUT   VARCHAR2,
       P_ADDR_VERFY_RESPONSE_OUT  OUT VARCHAR2);
	   
	      PROCEDURE AMEXTokenEventNotification(
    p_inst_code_in        IN NUMBER,
    p_msg_type_in         IN VARCHAR2,
    p_rrn_in              IN VARCHAR2,
    p_delivery_channel_in IN VARCHAR2,
    p_txn_code_in         IN VARCHAR2,
    p_txn_mode_in         IN VARCHAR2,
    p_tran_date_in        IN VARCHAR2,
    p_tran_time_in        IN VARCHAR2,
    p_tran_amt_in         IN VARCHAR2,
    p_rvsl_code_in        IN VARCHAR2,
    p_notify_type_in      IN VARCHAR2,
    p_tracking_id_in      IN VARCHAR2,
    p_pan_code_in         IN VARCHAR2,
    p_pan_seqno_in        IN VARCHAR2,
    p_token_in            IN VARCHAR2,
    p_token_refno_in      IN VARCHAR2,
    p_expry_date_in       IN VARCHAR2,
    p_effec_date_in       IN VARCHAR2,
    p_token_oldsts_in     IN VARCHAR2,
    p_device_id_in        IN VARCHAR2,
    p_wallet_id_in        IN VARCHAR2,
    p_visible_deviceid_in IN VARCHAR2,
    p_device_model_in     IN VARCHAR2,
    p_device_type_in      IN VARCHAR2,
    p_device_manu_in      IN VARCHAR2,
    p_reason_in           IN VARCHAR2,
    p_status_in           IN VARCHAR2,
    p_event_time_in       IN VARCHAR2,
    p_event_originator_in IN VARCHAR2,
    p_auth_id_out OUT VARCHAR2,
    p_resp_code_out OUT VARCHAR2,
    p_iso_resp_code_out OUT VARCHAR2,
    p_resmsg_out OUT VARCHAR2 );
	
	  Procedure  Tokenexpiryupdateadvice (
          p_inst_code_in                in      number,
          p_msg_type_in                 in 	    varchar2,
          p_rrn_in                      in  	varchar2,
          p_delivery_channel_in         in  	varchar2,
          p_txn_code_in                 in  	varchar2,
          p_txn_mode_in                 in  	varchar2,
          p_tran_date_in                in  	varchar2,
          p_tran_time_in                in  	varchar2,
          p_token_in   		            in  	varchar2,
          p_pan_code_in   		        in  	varchar2,
          p_token_type_in   		    in  	varchar2,
          p_token_expry_date_in   		in  	varchar2,   
          p_curr_code_in                in      varchar2,
          p_mbr_numb_in                 in  	varchar2,
          p_rvsl_code_in                in  	varchar2,
          p_stan_in                     in  	varchar2,
          p_ntw_settl_date              in  	varchar2,
          p_expry_date_in               IN  	VARCHAR2,          
          P_Req_Respcode                In      Varchar2,
          p_rsncode_desc                in      varchar2,
          p_auth_id_out                 out 	varchar2,
          p_iso_resp_code_out           out 	varchar2,
          p_resp_code_out               out 	varchar2,
          P_Resmsg_Out                  Out 	Varchar2,
          p_resp_id_out                 out 	varchar2 
          );
    
END VMSTOKENIZATION;
/
show error