create or replace
PACKAGE                                           vmscms.VMSVALIDATE
IS
   -- Created : 11/30/2017  12:40:00
   -- Purpose : VMSCMS Consolidated API related processes

   -- Public type declarations

   -- Public constant declarations

   -- Public variable declarations

   -- Public function and procedure declarations
   PROCEDURE authenticate (p_inst_code_in                 NUMBER,
                           p_delivery_chnl_in             VARCHAR2,
                           p_txn_code_in                  VARCHAR2,
                           p_rrn_in                       VARCHAR2,
                           p_cust_id_in                   VARCHAR2,
                           p_appl_id_in                   VARCHAR2,
                           p_partner_id_in                VARCHAR2,
                           p_tran_date_in                 VARCHAR2,
                           p_tran_time_in                 VARCHAR2,
                           p_curr_code_in                 VARCHAR2,
                           p_revrsl_code_in               VARCHAR2,
                           p_msg_type_in                  VARCHAR2,
                           p_ip_addr_in                   VARCHAR2,
                           p_ani_in                       VARCHAR2,
                           p_dni_in                       VARCHAR2,
                           p_device_mobno_in              VARCHAR2,
                           p_device_id_in                 VARCHAR2,
                           p_uuid_in                      VARCHAR2,
                           p_osname_in                    VARCHAR2,
                           p_osversion_in                 VARCHAR2,
                           p_gps_coordinates_in           VARCHAR2,
                           p_display_resolution_in        VARCHAR2,
                           p_physical_memory_in           VARCHAR2,
                           p_appname_in                   VARCHAR2,
                           p_appversion_in                VARCHAR2,
                           p_sessionid_in                 VARCHAR2,
                           p_device_country_in            VARCHAR2,
                           p_device_region_in             VARCHAR2,
                           p_ipcountry_in                 VARCHAR2,
                           p_proxy_flag_in                VARCHAR2,
                           p_pan_code_in                  VARCHAR2,
                           p_expry_date_in                VARCHAR2,
                           p_user_name_in                 VARCHAR2,
                           p_password_in                  VARCHAR2,
                           p_dob_in                       VARCHAR2,
                           p_phone_no_in                  VARCHAR2,
                           p_id_numbr_in                  VARCHAR2,
                           p_zip_code_in                  VARCHAR2,
                           p_resp_code_out            OUT VARCHAR2,
                           p_resp_msg_out             OUT VARCHAR2,
                           p_cust_id_out              OUT NUMBER,
                           p_loginAttempts_Left_out   OUT VARCHAR2,
                           p_custid_type_out          OUT VARCHAR2,
                           p_serial_num_out           OUT VARCHAR2,
                           p_card_stat_out            OUT VARCHAR2,
                           p_product_upc_out              OUT VARCHAR2,
                           p_initial_load_amount_out      OUT VARCHAR2,
                           p_replaced_card_out        OUT VARCHAR2,
                           p_order_channel_out        OUT VARCHAR2,
                           p_zip_code_out             OUT VARCHAR2,
                           p_isAuthorizedDevice_out   OUT VARCHAR2,
                           p_mobile_deliverymode_out  OUT VARCHAR2,
                           p_email_deliverymode_out   OUT VARCHAR2,
                           p_reason_code_out          OUT VARCHAR2,  --Added for VMS-6617 Changes
                           p_allowredemptions_out     OUT VARCHAR2, --Added for VMS-8677
                           p_transactions_out         OUT SYS_REFCURSOR);

    PROCEDURE validate_pin(p_inst_code_in             IN NUMBER,
                          p_delivery_channel_in      IN VARCHAR2,
                          p_txn_code_in              IN VARCHAR2,
                          p_rrn_in                   IN VARCHAR2,
                          p_cust_id_in               IN VARCHAR2,
                          p_partner_id_in            IN VARCHAR2,
                          p_trandate_in              IN  VARCHAR2,
                          p_trantime_in              IN  VARCHAR2,
                          p_curr_code_in             IN  VARCHAR2,
                          p_rvsl_code_in             IN  VARCHAR2,
                          p_msg_type_in              IN  VARCHAR2,
                          p_ip_addr_in               IN  VARCHAR2,
                          p_ani_in                   IN  VARCHAR2,
                          p_dni_in                   IN  VARCHAR2,
                          p_device_mob_no_in         IN  VARCHAR2,
                          p_device_id_in             IN  VARCHAR2,
                          p_pan_code_in              IN  VARCHAR2,
                          p_uuid_in                  IN  VARCHAR2,
                          p_os_name_in               IN  VARCHAR2,
                          p_os_version_in            IN  VARCHAR2,
                          p_gps_coordinates_in       IN  VARCHAR2,
                          p_display_resolution_in    IN  VARCHAR2,
                          p_physical_memory_in       IN  VARCHAR2,
                          p_app_name_in              IN  VARCHAR2,
                          p_app_version_in           IN  VARCHAR2,
                          p_session_id_in            IN  VARCHAR2,
                          p_device_country_in        IN  VARCHAR2,
                          p_device_region_in         IN  VARCHAR2,
                          p_ip_country_in            IN  VARCHAR2,
                          p_proxy_flag_in            IN  VARCHAR2,
                          p_resp_code_out            OUT VARCHAR2,
                          p_respmsg_out              OUT VARCHAR2
                          );

PROCEDURE        validate_security_questions (
             p_inst_code_in            IN       NUMBER,
             p_delivery_chnl_in        IN       VARCHAR2,
             p_txn_code_in             IN       VARCHAR2,
             p_rrn_in                  IN       VARCHAR2,
             p_appl_id_in              IN       VARCHAR2,
             p_partner_id_in           IN       VARCHAR2,
             p_tran_date_in            IN       VARCHAR2,
             p_tran_time_in            IN       VARCHAR2,
             p_curr_code_in            IN       VARCHAR2,
             p_revrsl_code_in          IN       VARCHAR2,
             p_msg_type_in             IN       VARCHAR2,
             p_user_name_in            IN       VARCHAR2,
             p_security_qus_in         IN       VARCHAR2,
             p_security_qus_ans_in     IN       VARCHAR2,
             p_ip_addr_in              IN       VARCHAR2,
             p_ani_in                  IN       VARCHAR2,
             p_dni_in                  IN       VARCHAR2,
             p_device_mobno_in         IN       VARCHAR2,
             p_device_id_in            IN       VARCHAR2,
             p_uuid_in                 IN       VARCHAR2,
             p_osname_in               IN       VARCHAR2,
             p_osversion_in            IN       VARCHAR2,
             p_gps_coordinates_in      IN       VARCHAR2,
             p_display_resolution_in   IN       VARCHAR2,
             p_physical_memory_in      IN       VARCHAR2,
             p_appname_in              IN       VARCHAR2,
             p_appversion_in           IN       VARCHAR2,
             p_sessionid_in            IN       VARCHAR2,
             p_device_country_in       IN       VARCHAR2,
             p_device_region_in        IN       VARCHAR2,
             p_ipcountry_in            IN       VARCHAR2,
             p_proxy_flag_in           IN       VARCHAR2,
             p_pan_code_in             IN       VARCHAR2,
             p_resp_code_out           OUT      VARCHAR2,
             p_resp_msg_out            OUT      VARCHAR2
          );

 PROCEDURE Validate_calllog_id   (p_inst_code_in             IN NUMBER,
                                 p_delivery_channel_in      IN VARCHAR2,
                                 p_txn_code_in              IN VARCHAR2,
                                 p_rrn_in                   IN VARCHAR2,
                                 p_cust_id_in               IN VARCHAR2,
                                 p_partner_id_in            IN VARCHAR2,
                                 p_trandate_in              IN  VARCHAR2,
                                 p_trantime_in              IN  VARCHAR2,
                                 p_curr_code_in             IN  VARCHAR2,
                                 p_rvsl_code_in             IN  VARCHAR2,
                                 p_msg_type_in              IN  VARCHAR2,
                                 p_ip_addr_in               IN  VARCHAR2,
                                 p_ani_in                   IN  VARCHAR2,
                                 p_dni_in                   IN  VARCHAR2,
                                 p_device_mob_no_in         IN  VARCHAR2,
                                 p_device_id_in             IN  VARCHAR2,
                                 p_pan_code_in              IN  VARCHAR2,
                                 p_uuid_in                  IN  VARCHAR2,
                                 p_os_name_in               IN  VARCHAR2,
                                 p_os_version_in            IN  VARCHAR2,
                                 p_gps_coordinates_in       IN  VARCHAR2,
                                 p_display_resolution_in    IN  VARCHAR2,
                                 p_physical_memory_in       IN  VARCHAR2,
                                 p_app_name_in              IN  VARCHAR2,
                                 p_app_version_in           IN  VARCHAR2,
                                 p_session_id_in            IN  VARCHAR2,
                                 p_device_country_in        IN  VARCHAR2,
                                 p_device_region_in         IN  VARCHAR2,
                                 p_ip_country_in            IN  VARCHAR2,
                                 p_proxy_flag_in            IN  VARCHAR2,
                                 p_call_logid_in            IN  VARCHAR2,
                                 p_resp_code_out            OUT VARCHAR2,
                                 p_respmsg_out              OUT VARCHAR2);

  PROCEDURE virtualcard_authenticate (p_inst_code_in                IN NUMBER,
                                       p_delivery_chnl_in            IN VARCHAR2,
                                       p_txn_code_in                 IN VARCHAR2,
                                       p_rrn_in                      IN VARCHAR2,
                                       p_cust_id_in                  IN VARCHAR2,
                                       p_partner_id_in               IN VARCHAR2,
                                       p_tran_date_in                IN VARCHAR2,
                                       p_tran_time_in                IN VARCHAR2,
                                       p_curr_code_in                IN VARCHAR2,
                                       p_revrsl_code_in              IN VARCHAR2,
                                       p_msg_type_in                 IN VARCHAR2,
                                       p_ip_addr_in                  IN VARCHAR2,
                                       p_ani_in                      IN VARCHAR2,
                                       p_dni_in                      IN VARCHAR2,
                                       p_device_mobno_in             IN VARCHAR2,
                                       p_device_id_in                IN VARCHAR2,
                                       p_uuid_in                     IN VARCHAR2,
                                       p_osname_in                   IN VARCHAR2,
                                       p_osversion_in                IN VARCHAR2,
                                       p_gps_coordinates_in          IN VARCHAR2,
                                       p_display_resolution_in       IN VARCHAR2,
                                       p_physical_memory_in          IN VARCHAR2,
                                       p_appname_in                  IN VARCHAR2,
                                       p_appversion_in               IN VARCHAR2,
                                       p_sessionid_in                IN VARCHAR2,
                                       p_device_country_in           IN VARCHAR2,
                                       p_device_region_in            IN VARCHAR2,
                                       p_ipcountry_in                IN VARCHAR2,
                                       p_proxy_flag_in               IN VARCHAR2,
                                       p_pan_code_in                 IN VARCHAR2,
                                       p_resp_code_out               OUT VARCHAR2,
                                       p_resp_msg_out                OUT VARCHAR2,
                                       p_cust_id_out                 OUT NUMBER,
                                       p_exp_date_out                OUT VARCHAR2,
                                       p_card_stat_out               OUT VARCHAR2,
                                       p_product_upc_out             OUT VARCHAR2,
                                       p_initial_load_amount_out     OUT VARCHAR2,
                                       p_zip_code_out                OUT VARCHAR2,
                                       p_status_out                  OUT VARCHAR2,
                                       p_reason_code_out          OUT VARCHAR2);  --Added for VMS-6617 Changes
  --SN:Added for VMS-6617 Changes                                     
  PROCEDURE updt_cardstat_hld2actv (p_inst_code_in  NUMBER,
                                    p_card_no_in    VARCHAR2,
                                    p_cardencr_in   VARCHAR2,
                                    p_acctno_in     VARCHAR2,
                                    p_rrn_in        VARCHAR2,
                                    p_auth_id_in    VARCHAR2,
                                    p_crdstat_in    VARCHAR2,
                                    p_resp_code_out OUT VARCHAR2,
                                    p_resp_msg_out  OUT VARCHAR2);        
  --EN:Added for VMS-6617 Changes                                                                         

END;
/
show error;